
package es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2025-02-04T13:37:58.616+01:00
 * Generated source version: 4.0.5
 *
 */
public final class ServeiTresoreriaPortType_ServeiTresoreriaPortTypePort_Client {

    private static final QName SERVICE_NAME = new QName("http://fcbarcelona.cat/servei/Finances/ServeiTresoreria/v01", "ServeiTresoreria");

    private ServeiTresoreriaPortType_ServeiTresoreriaPortTypePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServeiTresoreria.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServeiTresoreria ss = new ServeiTresoreria(wsdlURL, SERVICE_NAME);
        ServeiTresoreriaPortType port = ss.getServeiTresoreriaPortTypePort();

        {
        System.out.println("Invoking ajustCaixa...");
        es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.AjustCaixaInputType _ajustCaixa_input = null;
        try {
            es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.AjustCaixaOutputType _ajustCaixa__return = port.ajustCaixa(_ajustCaixa_input);
            System.out.println("ajustCaixa.result=" + _ajustCaixa__return);

        } catch (ServeiTresoreriaFault e) {
            System.out.println("Expected exception: serveiTresoreriaFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking altaDiposit...");
        es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.AltaDipositInputType _altaDiposit_input = null;
        try {
            es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.AltaDipositOutputType _altaDiposit__return = port.altaDiposit(_altaDiposit_input);
            System.out.println("altaDiposit.result=" + _altaDiposit__return);

        } catch (ServeiTresoreriaFault e) {
            System.out.println("Expected exception: serveiTresoreriaFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking liquidacionsParcials...");
        es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.LiquidacionsParcialsInputType _liquidacionsParcials_input = null;
        try {
            es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.LiquidacionsParcialsOutputType _liquidacionsParcials__return = port.liquidacionsParcials(_liquidacionsParcials_input);
            System.out.println("liquidacionsParcials.result=" + _liquidacionsParcials__return);

        } catch (ServeiTresoreriaFault e) {
            System.out.println("Expected exception: serveiTresoreriaFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking oberturaCaixa...");
        es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.OberturaCaixaInputType _oberturaCaixa_input = null;
        try {
            es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.OberturaCaixaOutputType _oberturaCaixa__return = port.oberturaCaixa(_oberturaCaixa_input);
            System.out.println("oberturaCaixa.result=" + _oberturaCaixa__return);

        } catch (ServeiTresoreriaFault e) {
            System.out.println("Expected exception: serveiTresoreriaFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking tancamentCaixa...");
        es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.TancamentCaixaInputType _tancamentCaixa_input = null;
        try {
            es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.TancamentCaixaOutputType _tancamentCaixa__return = port.tancamentCaixa(_tancamentCaixa_input);
            System.out.println("tancamentCaixa.result=" + _tancamentCaixa__return);

        } catch (ServeiTresoreriaFault e) {
            System.out.println("Expected exception: serveiTresoreriaFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking traspasCaixa...");
        es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.TraspasCaixaInputType _traspasCaixa_input = null;
        try {
            es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.TraspasCaixaOutputType _traspasCaixa__return = port.traspasCaixa(_traspasCaixa_input);
            System.out.println("traspasCaixa.result=" + _traspasCaixa__return);

        } catch (ServeiTresoreriaFault e) {
            System.out.println("Expected exception: serveiTresoreriaFault has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking cargaExtracteBancari...");
        es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.CargaExtracteBancariInputType _cargaExtracteBancari_input = null;
        try {
            es.onebox.fcb.datasources.peoplesoft.wsdl.tresoreria.CargaExtracteBancariOutputType _cargaExtracteBancari__return = port.cargaExtracteBancari(_cargaExtracteBancari_input);
            System.out.println("cargaExtracteBancari.result=" + _cargaExtracteBancari__return);

        } catch (ServeiTresoreriaFault e) {
            System.out.println("Expected exception: serveiTresoreriaFault has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
