package es.onebox.mgmt.entities.dto;

import java.io.Serializable;

public enum EventAction implements Serializable {

    ORDER_PURCHASE,
    ORDER_BOOKING,
    ORDER_REFUND,
    ORDER_UPDATE,
    ORDER_CANCEL,
    ORDER_PRINT,
    MEMBERORDER_PURCHASE,
    MEMBERORDER_UPDATE,
    PREORDER_ABANDONED,
    ITEM_PURCHASE,
    EVENT_CATALOG,
    SESSION_CATALOG,
    PROMOTION_UPDATE,
    CHANNEL_UPDATE,
    B2BBALANCE_UPDATE,
    ENTITY_FVZONE_UPDATE,
    ENTITY_FVZONE_CREATE,
    USER_FVZONE_CREATE,
    USER_FVZONE_REACTIVATE,
    USER_FVZONE_DEACTIVATE,
    PRODUCT_CATALOG,
    ITEM_TRANSFER;
}
