//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.channel;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clientField.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="clientField">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="SURNAME"/>
 *     &lt;enumeration value="EMAIL"/>
 *     &lt;enumeration value="GENDER"/>
 *     &lt;enumeration value="BIRTHDAY"/>
 *     &lt;enumeration value="COUNTRY"/>
 *     &lt;enumeration value="COUNTRY_SUBDIVISION"/>
 *     &lt;enumeration value="CITY"/>
 *     &lt;enumeration value="POSTAL_CODE"/>
 *     &lt;enumeration value="ADDRESS"/>
 *     &lt;enumeration value="PHONE_NUMBER"/>
 *     &lt;enumeration value="LANGUAGE"/>
 *     &lt;enumeration value="ID_CARD"/>
 *     &lt;enumeration value="DOC_TYPE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "clientField")
@XmlEnum
public enum ClientField {

    NAME,
    SURNAME,
    EMAIL,
    GENDER,
    BIRTHDAY,
    COUNTRY,
    COUNTRY_SUBDIVISION,
    CITY,
    POSTAL_CODE,
    ADDRESS,
    PHONE_NUMBER,
    LANGUAGE,
    ID_CARD,
    DOC_TYPE;

    public String value() {
        return name();
    }

    public static ClientField fromValue(String v) {
        return valueOf(v);
    }

}
