//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.channel;

import es.onebox.common.datasources.rest.dto.ns.purchase.order.OrderType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/channel}paymentDataField" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="orderType" type="{http://www.oneboxtm.es/ns/purchase/order}orderType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentDataField"
})
@XmlRootElement(name = "operationPaymentDataFields")
public class OperationPaymentDataFields
    implements Serializable
{

    @XmlElement(required = true)
    protected List<PaymentDataField> paymentDataField;
    @XmlAttribute(name = "orderType")
    protected OrderType orderType;

    /**
     * Gets the value of the paymentDataField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentDataField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentDataField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentDataField }
     * 
     * 
     */
    public List<PaymentDataField> getPaymentDataField() {
        if (paymentDataField == null) {
            paymentDataField = new ArrayList<PaymentDataField>();
        }
        return this.paymentDataField;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link OrderType }
     *     
     */
    public OrderType getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderType }
     *     
     */
    public void setOrderType(OrderType value) {
        this.orderType = value;
    }

    /**
     * Sets the value of the paymentDataField property.
     * 
     * @param paymentDataField
     *     allowed object is
     *     {@link PaymentDataField }
     *     
     */
    public void setPaymentDataField(List<PaymentDataField> paymentDataField) {
        this.paymentDataField = paymentDataField;
    }

}
