//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.attributes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/attributes}attribute-info"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/attributes}attribute-value" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idAttribute" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributeInfo",
    "attributeValue"
})
@XmlRootElement(name = "attribute-values")
public class AttributeValues
    implements Serializable
{

    @XmlElement(name = "attribute-info", required = true)
    protected AttributeInfo attributeInfo;
    @XmlElement(name = "attribute-value", required = true)
    protected List<AttributeValue> attributeValue;
    @XmlAttribute(name = "idAttribute")
    protected Integer idAttribute;
    @XmlAttribute(name = "description")
    protected String description;

    /**
     * Gets the value of the attributeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeInfo }
     *     
     */
    public AttributeInfo getAttributeInfo() {
        return attributeInfo;
    }

    /**
     * Sets the value of the attributeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeInfo }
     *     
     */
    public void setAttributeInfo(AttributeInfo value) {
        this.attributeInfo = value;
    }

    /**
     * Gets the value of the attributeValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeValue }
     * 
     * 
     */
    public List<AttributeValue> getAttributeValue() {
        if (attributeValue == null) {
            attributeValue = new ArrayList<AttributeValue>();
        }
        return this.attributeValue;
    }

    /**
     * Gets the value of the idAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdAttribute() {
        return idAttribute;
    }

    /**
     * Sets the value of the idAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdAttribute(Integer value) {
        this.idAttribute = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Sets the value of the attributeValue property.
     * 
     * @param attributeValue
     *     allowed object is
     *     {@link AttributeValue }
     *     
     */
    public void setAttributeValue(List<AttributeValue> attributeValue) {
        this.attributeValue = attributeValue;
    }

}
