/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
import { FormControlErrorsBase } from '@OneboxTM/feature-form-control-errors';

export class FormErrors extends FormControlErrorsBase {
    formControlErrors = FormControlErrors;
    errorsParameterMap = errorsParameterMap;
    prefix = 'FORMS.ERRORS.';
}

export enum FormControlErrors {
    default = 'INVALID_FIELD',
    required = 'REQUIRED_FIELD',
    atLeastOneRequired = 'AT_LEAST_ONE',
    atLeastOneInCollection = 'AT_LEAST_ONE_IN_COLLECTION',
    max = 'HIGHER_THAN',
    min = 'LOWER_THAN',
    maxlength = 'MAX_LENGTH_EXCEEDED',
    requiredLength = 'REQUIRED_LENGTH',
    invalidJson = 'INVALID_JSON',
    minlength = 'MIN_LENGTH',
    maxLengthWithoutHTML = 'MAX_LENGTH_EXCEEDED',
    richTextAreaMaxLength = 'MAX_LENGTH_EXCEEDED_WITH_FORMAT',
    email = 'INVALID_CHARACTERS',
    pattern = 'INVALID_CHARACTERS',
    notUniqueName = 'NAME_ALREADY_IN_USE',
    notSamePassword = 'NOT_SAME_PASSWORD',
    maxDecimalLength = 'MAX_DECIMAL_LENGTH',
    noDecimalsAllowed = 'NO_DECIMALS_ALLOWED',
    diffThanNumber = 'DIFF_THAN_NUMBER',
    noBlankSpaces = 'NO_BLANK_SPACES',
    taxIdAlreadyExists = 'TAX_ID_ALREADY_EXISTS',
    clientIdAlreadyExists = 'CLIENT_ID_ALREADY_EXISTS',
    duplicateValue = 'REPEATED_ELEMENT',
    greaterThanValidator = 'GREATER_THAN',
    range = 'NOT_IN_RANGE',
    rateConflict = 'RATE_CONFLICT',
    repeatedExternalDescription = 'REPEATED_EXTERNAL_DESCRIPTION',
    externalDescriptionNotFound = 'EXTERNAL_DESCRIPTION_NOT_FOUND',
    maxSelectedItems = 'MAX_SELECTED_ITEMS',
    activeAndDefaultRequired = 'REQUIRED_ACTIVE_AND_DEFAULT_FIELD',
    invalidLocation = 'INVALID_LOCATION',
    invalidFormat = 'INVALID_FORMAT',
    // PROMOTION LIMITS ERRORS:
    packsMinGTPurchaseMax = 'PACKS_MIN_GT_PURCHASE_MAX',
    packsMinGTPromotionMax = 'PACKS_MIN_GT_PROMOTION_MAX',
    packsMinGTSessionMax = 'PACKS_MIN_GT_SESSION_MAX',
    packsMinGTSessionUserMax = 'PACKS_MIN_GT_SESSION_USER_MAX',
    purchaseMinGTPromotion = 'PURCHASE_MIN_GT_PROMOTION_MAX',
    purchaseMinGTSession = 'PURCHASE_MIN_GT_SESSION_MAX',
    purchaseMinGTPurchaseMax = 'PURCHASE_MIN_GT_PURCHASE_MAX',
    purchaseMinGTSessionUserMax = 'PURCHASE_MIN_GT_SESSION_USER_MAX',
    purchaseMaxGTPromotion = 'PURCHASE_MAX_GT_PROMOTION_MAX',
    purchaseMaxGTSession = 'PURCHASE_MAX_GT_SESSION_MAX',
    purchaseMaxGTSessionUser = 'PURCHASE_MAX_GT_SESSION_USER_MAX',
    purchaseMinNotPurchaseMaxMultiple = 'PURCHASE_MIN_NOT_PURCHASE_MAX_MULTIPLE',
    packsMinNotPurchaseMaxMultiple = 'PACKS_MIN_NOT_PURCHASE_MAX_MULTIPLE',
    sessionUserMaxGTPromotion = 'SESSION_USER_MAX_GT_PROMOTION_MAX',
    sessionUserMaxGTSession = 'SESSION_USER_MAX_GT_SESSION_MAX',
    sessionUserMaxGTPurchase = 'SESSION_USER_MAX_GT_PURCHASE_MAX',
    purchaseMinNotSessionUserMaxMultiple = 'PURCHASE_MIN_NOT_SESSION_USER_MULTIPLE',
    packsMinNotSessionUserMaxMultiple = 'PACKS_MIN_NOT_SESSION_USER_MULTIPLE',
    purchaseMinNotPromotionMultiple = 'PURCHASE_MIN_NOT_PROMOTION_MAX_MULTIPLE',
    packsMinNotPromotionMultiple = 'PACKS_MIN_NOT_PROMOTION_MAX_MULTIPLE',
    sessionGTPromotion = 'SESSION_MAX_GT_PROMOTION_MAX',
    sessionGTSessionUser = 'SESSION_MAX_GT_SESSION_USER_MAX',
    purchaseMinNotSessionMultiple = 'PURCHASE_MIN_NOT_SESSION_MAX_MULTIPLE',
    packsMinNotSessionMultiple = 'PACKS_MIN_NOT_SESSION_MAX_MULTIPLE',
    sessionGTEventUser = 'SESSION_MAX_GT_EVENT_USER_MAX',
    purchaseMaxGTEventUser = 'PURCHASE_MAX_GT_EVENT_USER_MAX',
    purchaseMinGTEventUserMax = 'PURCHASE_MIN_GT_EVENT_USER_MAX',
    packsMinGTEventUserMax = 'PACKS_MIN_GT_EVENT_USER_MAX',
    sessionUserMaxGTEventUser = 'SESSION_USER_MAX_GT_EVENT_USER_MAX',
    eventUserMaxGTPromotion = 'EVENT_USER_MAX_GT_PROMOTION_MAX',
    purchaseMinNotEventUserMaxMultiple = 'PURCHASE_MIN_NOT_EVENT_USER_MULTIPLE',
    packsMinNotEventUserMaxMultiple = 'PACKS_MIN_NOT_EVENT_USER_MULTIPLE',
    // DATETIME
    startDateAfterEndDate = 'START_DATE_AFTER_THAN_END_DATE',
    releaseBeforeSeasonRelease = 'DATE_BEFORE_THAN_FEMALE',
    releaseAfterSaleStart = 'DATE_AFTER_THAN_MALE',
    saleStartBeforeRelease = 'DATE_BEFORE_THAN_FEMALE',
    saleStartAfterSaleEnd = 'DATE_AFTER_THAN_MALE',
    saleEndAfterSaleStart = 'DATE_AFTER_THAN_MALE',
    bookingStartAfterBookingEnd = 'DATE_BEFORE_THAN_FEMALE',
    bookingEndAfterBookingStart = 'DATE_AFTER_THAN_MALE',
    endDateBeforeStartDate = 'DATE_BEFORE_THAN_FEMALE',
    releaseDateAfterStartDate = 'DATE_AFTER_THAN_FEMALE',
    releaseDateAfterBookingStartDate = 'DATE_AFTER_THAN_MALE',
    releaseDateAfterSaleStartDate = 'DATE_AFTER_THAN_FEMALE',
    bookingStartDateBeforeReleaseDate = 'DATE_BEFORE_THAN_MALE',
    bookingStartDateAfterStartDate = 'DATE_AFTER_THAN_FEMALE',
    bookingStartDateAfterBookingEndDate = 'DATE_AFTER_THAN_MALE',
    bookingEndDateBeforeBookingStartDate = 'DATE_BEFORE_THAN_MALE',
    bookingEndDateAfterSaleEndDate = 'DATE_AFTER_THAN_MALE',
    saleStartDateBeforeReleaseDate = 'DATE_BEFORE_THAN_MALE',
    saleStartDateAfterStartDate = 'DATE_AFTER_THAN_FEMALE',
    saleStartDateAfterSaleEndDate = 'DATE_AFTER_THAN_MALE',
    saleEndDateBeforeSaleStartDate = 'DATE_BEFORE_THAN_MALE',
    saleEndDateBeforeBookingEndDate = 'DATE_BEFORE_THAN_MALE',
    releaseDateAfterSecondaryMarketSaleStartDate = 'DATE_BEFORE_THAN_MALE',
    secondaryMarketSaleStartDateBeforeReleaseDate = 'DATE_BEFORE_THAN_MALE',
    secondaryMarketSaleStartDateAfterStartDate = 'DATE_AFTER_THAN_FEMALE',
    secondaryMarketSaleStartDateAfterSecondaryMarketSaleEndDate = 'DATE_AFTER_THAN_MALE',
    secondaryMarketSaleEndDateBeforeSecondaryMarketSaleStartDate = 'DATE_BEFORE_THAN_MALE',
    secondaryMarketSaleEndDateBeforeBookingEndDate = 'DATE_BEFORE_THAN_MALE',
    presaleStartAfterPresaleEnd = 'PRESALES_START_AFTER_PRESALES_END',
    startAfterEnd = 'DATE_AFTER_THAN_MALE',
    endAfterStart = 'DATE_AFTER_THAN_MALE',
    channelPublishingDateAfterSameRenewalStartDate = 'DATE_AFTER_OR_SAME_THAN_FEMALE',
    channelPublishingDateAfterRenewalEndingDate = 'DATE_AFTER_OR_SAME_THAN_FEMALE',
    channelPublishingDateAfterSameChangeSeatsStartDate = 'DATE_AFTER_OR_SAME_THAN_FEMALE',
    channelPublishingDateAfterChangeSeatsEndingDate = 'DATE_AFTER_OR_SAME_THAN_FEMALE',
    channelPublishingDateAfterSameSalesStartDate = 'DATE_AFTER_OR_SAME_THAN_FEMALE',
    channelPublishingDateAfterSalesEndingDate = 'DATE_AFTER_THAN_FEMALE',
    renewalStartDateBeforeSameChannelPublishingDate = 'DATE_BEFORE_OR_SAME_THAN_FEMALE',
    renewalStartDateAfterRenewalEndingDate = 'DATE_AFTER_THAN_FEMALE',
    renewalEndingDateBeforeChannelPublishingDate = 'DATE_BEFORE_THAN_FEMALE',
    renewalEndingDateBeforeRenewalStartDate = 'DATE_BEFORE_THAN_FEMALE',
    changeSeatsStartDateBeforeSameChannelPublishingDate = 'DATE_BEFORE_OR_SAME_THAN_FEMALE',
    changeSeatsStartDateAfterChangeSeatsEndingDate = 'DATE_AFTER_THAN_FEMALE',
    changeSeatsEndingDateBeforeChannelPublishingDate = 'DATE_BEFORE_THAN_FEMALE',
    changeSeatsEndingDateBeforeChangeSeatsStartDate = 'DATE_BEFORE_THAN_FEMALE',
    salesStartDateBeforeSameChannelPublishingDate = 'DATE_BEFORE_OR_SAME_THAN_FEMALE',
    salesStartDateAfterSalesEndingDate = 'DATE_AFTER_THAN_FEMALE',
    salesEndingDateBeforeChannelPublishingDate = 'DATE_BEFORE_THAN_FEMALE',
    salesEndingDateBeforeSalesStartDate = 'DATE_BEFORE_THAN_FEMALE',
    dateIsFuture = 'DATE_IS_FUTURE',
    zoneDynamicPriceDateBeforeSalesStartDate = 'DATE_BEFORE_THAN_FEMALE',
    zoneDynamicPriceDateBeforeVenueTemplateNow = 'DATE_BEFORE_THAN_FEMALE',
    zoneDynamicPriceDateBeforeActiveZoneDynamicPriceDate = 'DATE_BEFORE_THAN_FEMALE',
    // CUSTOMERS
    customerDuplicatedEmail = 'CUSTOMER_DUPLICATED_EMAIL',
    customerAlreadyExists = 'CUSTOMER_ALREADY_EXISTS',
    customerDuplicatedMemberId = 'CUSTOMER_DUPLICATED_MEMBER_ID',
    // B2B:
    availableBalanceExceeded = 'B2B_CLIENT_BALANCE_LIMIT_EXCEEDED'
}

export const errorsParameterMap = {
    maxlength: { requiredLength: 'value' },
    minlength: { requiredLength: 'value' },
    requiredLength: { requiredLength: 'value' },
    max: { max: 'value' },
    min: { min: 'value' },
    maxLengthWithoutHTML: { requiredLength: 'value' },
    maxDecimalLength: { maxLength: 'value' },
    maxSelectedItems: 'value',
    richTextAreaMaxLength: { requiredLength: 'value' },
    greaterThanValidator: { moreThanMin: 'value' },
    diffThanNumber: 'value',
    startDateAfterEndDate: 'date',
    releaseBeforeSeasonRelease: 'date',
    releaseAfterSaleStart: 'date',
    saleStartBeforeRelease: 'date',
    saleStartAfterSaleEnd: 'date',
    saleEndAfterSaleStart: 'date',
    bookingStartAfterBookingEnd: 'date',
    bookingEndAfterBookingStart: 'date',
    endDateBeforeStartDate: 'date',
    releaseDateAfterStartDate: 'date',
    releaseDateAfterBookingStartDate: 'date',
    releaseDateAfterSaleStartDate: 'date',
    bookingStartDateBeforeReleaseDate: 'date',
    bookingStartDateAfterStartDate: 'date',
    bookingStartDateAfterBookingEndDate: 'date',
    bookingEndDateBeforeBookingStartDate: 'date',
    bookingEndDateAfterSaleEndDate: 'date',
    saleStartDateBeforeReleaseDate: 'date',
    saleStartDateAfterStartDate: 'date',
    saleStartDateAfterSaleEndDate: 'date',
    saleEndDateBeforeSaleStartDate: 'date',
    saleEndDateBeforeBookingEndDate: 'date',
    releaseDateAfterSecondaryMarketSaleStartDate: 'date',
    secondaryMarketSaleStartDateBeforeReleaseDate: 'date',
    secondaryMarketSaleStartDateAfterStartDate: 'date',
    secondaryMarketSaleStartDateAfterSecondaryMarketSaleEndDate: 'date',
    secondaryMarketSaleEndDateBeforeSecondaryMarketSaleStartDate: 'date',
    secondaryMarketSaleEndDateBeforeBookingEndDate: 'date',
    startAfterEnd: 'date',
    endAfterStart: 'date',
    channelPublishingDateAfterSameRenewalStartDate: 'date',
    channelPublishingDateAfterRenewalEndingDate: 'date',
    channelPublishingDateAfterSameSalesStartDate: 'date',
    channelPublishingDateAfterSalesEndingDate: 'date',
    channelPublishingDateAfterSameChangeSeatsStartDate: 'date',
    channelPublishingDateAfterChangeSeatsEndingDate: 'date',
    renewalStartDateBeforeSameChannelPublishingDate: 'date',
    renewalStartDateAfterRenewalEndingDate: 'date',
    renewalEndingDateBeforeChannelPublishingDate: 'date',
    renewalEndingDateBeforeRenewalStartDate: 'date',
    changeSeatsStartDateBeforeSameChannelPublishingDate: 'date',
    changeSeatsStartDateAfterChangeSeatsEndingDate: 'date',
    changeSeatsEndingDateBeforeChannelPublishingDate: 'date',
    changeSeatsEndingDateBeforeChangeSeatsStartDate: 'date',
    salesStartDateBeforeSameChannelPublishingDate: 'date',
    salesStartDateAfterSalesEndingDate: 'date',
    salesEndingDateBeforeChannelPublishingDate: 'date',
    salesEndingDateBeforeSalesStartDate: 'date',
    zoneDynamicPriceDateBeforeSalesStartDate: 'date',
    zoneDynamicPriceDateBeforeVenueTemplateNow: 'date',
    zoneDynamicPriceDateBeforeActiveZoneDynamicPriceDate: 'date'
};
