//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.taxonomy;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.taxonomy package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ParentCustomTaxonomy_QNAME = new QName("http://www.oneboxtm.es/ns/taxonomy", "parent-custom-taxonomy");
    private final static QName _CustomTaxonomy_QNAME = new QName("http://www.oneboxtm.es/ns/taxonomy", "custom-taxonomy");
    private final static QName _Taxonomy_QNAME = new QName("http://www.oneboxtm.es/ns/taxonomy", "taxonomy");
    private final static QName _ParentTaxonomy_QNAME = new QName("http://www.oneboxtm.es/ns/taxonomy", "parent-taxonomy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.taxonomy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChildTaxonomyType }
     * 
     */
    public ChildTaxonomyType createChildTaxonomyType() {
        return new ChildTaxonomyType();
    }

    /**
     * Create an instance of {@link CustomTaxonomyType }
     * 
     */
    public CustomTaxonomyType createCustomTaxonomyType() {
        return new CustomTaxonomyType();
    }

    /**
     * Create an instance of {@link ParentTaxonomyType }
     * 
     */
    public ParentTaxonomyType createParentTaxonomyType() {
        return new ParentTaxonomyType();
    }

    /**
     * Create an instance of {@link ParentCustomTaxonomyType }
     * 
     */
    public ParentCustomTaxonomyType createParentCustomTaxonomyType() {
        return new ParentCustomTaxonomyType();
    }

    /**
     * Create an instance of {@link TaxonomyType }
     * 
     */
    public TaxonomyType createTaxonomyType() {
        return new TaxonomyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentCustomTaxonomyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/taxonomy", name = "parent-custom-taxonomy")
    public JAXBElement<ParentCustomTaxonomyType> createParentCustomTaxonomy(ParentCustomTaxonomyType value) {
        return new JAXBElement<ParentCustomTaxonomyType>(_ParentCustomTaxonomy_QNAME, ParentCustomTaxonomyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomTaxonomyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/taxonomy", name = "custom-taxonomy")
    public JAXBElement<CustomTaxonomyType> createCustomTaxonomy(CustomTaxonomyType value) {
        return new JAXBElement<CustomTaxonomyType>(_CustomTaxonomy_QNAME, CustomTaxonomyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaxonomyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/taxonomy", name = "taxonomy")
    public JAXBElement<TaxonomyType> createTaxonomy(TaxonomyType value) {
        return new JAXBElement<TaxonomyType>(_Taxonomy_QNAME, TaxonomyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentTaxonomyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/taxonomy", name = "parent-taxonomy")
    public JAXBElement<ParentTaxonomyType> createParentTaxonomy(ParentTaxonomyType value) {
        return new JAXBElement<ParentTaxonomyType>(_ParentTaxonomy_QNAME, ParentTaxonomyType.class, null, value);
    }

}
