package es.onebox.mgmt.datasources.ms.event;

import es.onebox.core.exception.ErrorCode;
import es.onebox.mgmt.exception.ApiMgmtChannelsErrorCode;
import es.onebox.mgmt.exception.ApiMgmtErrorCode;
import es.onebox.mgmt.exception.ApiMgmtExportsErrorCode;
import es.onebox.mgmt.exception.ApiMgmtExternalEventErrorCode;
import es.onebox.mgmt.exception.ApiMgmtPassbookErrorCode;
import es.onebox.mgmt.exception.ApiMgmtSeasonTicketErrorCode;
import es.onebox.mgmt.exception.ApiMgmtSessionErrorCode;
import es.onebox.mgmt.exception.ApiMgmtTierErrorCode;
import org.springframework.http.HttpStatus;

import java.util.HashMap;
import java.util.Map;

public class MsEventMapping {

    protected static final String API_VERSION = "v1";
    protected static final String BASE_PATH = "/events-api/" + API_VERSION;
    protected static final int TIMEOUT = 60000;

    protected static final Map<String, ErrorCode> ERROR_CODES = new HashMap<>();

    protected static final String EVENT_ID = "/{eventId}";
    protected static final String EVENTS = "/events";
    protected static final String PRODUCTS = "/products";
    protected static final String PRESALES = "/presales";
    protected static final String PRESALE_ID = "/{presaleId}";
    protected static final String RATES = "/rates";
    protected static final String RATE_ID = "/{rateId}";
    protected static final String SESSIONS = "/sessions";
    protected static final String SESSION_ID = "/{sessionId}";
    protected static final String CHANNELS = "/channels";
    protected static final String CHANNEL_ID = "/{channelId}";
    protected static final String TICKET_CONTENTS = "/ticket-contents";
    protected static final String TICKET_TYPE_PASSBOOK = "/PASSBOOK";
    protected static final String TICKET_TYPE_PDF = "/PDF";

    protected static final String DELIVERY_POINTS = "/products-delivery-points";
    protected static final String PRODUCTS_DELIVERY_POINTS_RELATIONS = "/products/{productId}/delivery-points";
    protected static final String DELIVERY_POINT = "/{deliveryPointId}";
    protected static final String PRODUCTS_DELIVERY_POINT_ID = "/{deliveryPointId}";
    protected static final String PRODUCTS_LANGUAGES = "/products/{productId}/languages";
    protected static final String PRODUCTS_CHANNELS = "/products/{productId}/channels";
    protected static final String PRODUCT_CHANNEL = "/products/{productId}/channels/{channelId}";
    protected static final String PRODUCTS_DELIVERY = "/products/{productId}/delivery";
    protected static final String PRODUCTS_VARIANTS = "/products/{productId}/variants";
    protected static final String PRICES = "/prices";
    protected static final String PRODUCT_EVENTS = "/products/{productId}/events";
    protected static final String PRODUCT_EVENT_ID = "/products/{productId}/events/{eventId}";
    protected static final String PRODUCT_EVENT_PUBLISHING_SESSIONS = "/products/{productId}/events/{eventId}/publishing-sessions";
    protected static final String PRODUCT_EVENT_SESSIONS = "/products/{productId}/events/{eventId}/sessions";
    protected static final String PRODUCT_EVENT_SESSION = PRODUCT_EVENT_SESSIONS + SESSION_ID;
    protected static final String PRODUCT_CHANNEL_SESSIONS = "/products/{productId}/channels/{channelId}/sessions";
    protected static final String PRODUCT_ID = "/{productId}";
    protected static final String VARIANT_ID = "/{variantId}";
    protected static final String PRODUCTS_COMMUNICATION_ELEMENTS = "/products/{productId}/communication-elements";
    protected static final String PRODUCTS_ATTRIBUTES = "/products/{productId}/attributes";
    protected static final String PRODUCTS_ATTRIBUTE_VALUES = PRODUCTS_ATTRIBUTES + "/{attributeId}/values";
    protected static final String PRODUCTS_EVENTS_DELIVERY_POINTS = "/products/{productId}/events/{eventId}/delivery-points";
    protected static final String PRODUCTS_SESSIONS_DELIVERY_POINTS = "/products/{productId}/events/{eventId}/session-delivery-points";
    protected static final String PRODUCT_TICKET_TEMPLATES = "/product-ticket-templates";
    protected static final String ATTRIBUTE_CONTENTS_TEXT = "/products/{productId}/attributes/{attributeId}/channel-contents/texts";
    protected static final String VALUE_CONTENTS_TEXT = "/products/{productId}/attributes/{attributeId}/values/{valueId}/channel-contents/texts";
    protected static final String BULK_VALUE_CONTENTS_TEXT = "/products/{productId}/attributes/{attributeId}/values/channel-contents/texts";
    protected static final String TICKET_CONTENTS_TEXT = "/products/{productId}/ticket-contents/{languageCode}";
    protected static final String PRODUCT_TICKET_CONTENTS_IMAGE_PASSBOOK = PRODUCTS + PRODUCT_ID + TICKET_CONTENTS + TICKET_TYPE_PASSBOOK + "/images";
    protected static final String PRODUCT_TICKET_CONTENTS_IMAGE_PDF = PRODUCTS + PRODUCT_ID + TICKET_CONTENTS + TICKET_TYPE_PDF + "/images";
    protected static final String PRODUCT_TICKET_CONTENTS_TEXT_PASSBOOK = PRODUCTS + PRODUCT_ID + TICKET_CONTENTS + TICKET_TYPE_PASSBOOK + "/texts";
    protected static final String PRODUCT_TICKET_CONTENTS_TEXT_PDF = PRODUCTS + PRODUCT_ID + TICKET_CONTENTS + TICKET_TYPE_PDF + "/texts";

    protected static final String ATTRIBUTE_ID = "/{attributeId}";
    protected static final String VALUE_ID = "/{valueId}";
    protected static final String BULK = "/bulk";
    protected static final String VENUE_TEMPLATE_PRICES = EVENTS + "/{eventId}/venue-templates/{templateId}/prices";
    protected static final String COMMUNICATION_ELEMENTS = "/communication-elements";
    protected static final String EVENT_COMMUNICATION_ELEMENTS = EVENTS + EVENT_ID + COMMUNICATION_ELEMENTS;
    protected static final String EMAIL_COMMUNICATION_ELEMENTS = EVENTS + EVENT_ID + "/email-communication-elements";
    public static final String TICKET_COMMUNICATION_ELEMENTS_TYPE = "/ticket-communication-elements/{type}";
    protected static final String TICKET_COMMUNICATION_ELEMENTS = EVENTS + EVENT_ID + TICKET_COMMUNICATION_ELEMENTS_TYPE;
    protected static final String SESSION_COMMUNICATION_ELEMENTS = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + COMMUNICATION_ELEMENTS;
    protected static final String SESSION_COMMUNICATION_ELEMENTS_BULK = EVENTS + EVENT_ID + SESSIONS + COMMUNICATION_ELEMENTS;
    protected static final String LANGUAGES = "/languages";
    protected static final String SESSION_TICKET_COMMUNICATION_ELEMENTS = EVENTS + EVENT_ID + SESSIONS + SESSION_ID
            + TICKET_COMMUNICATION_ELEMENTS_TYPE;
    protected static final String SESSION_TICKET_COMMUNICATION_ELEMENTS_BULK = EVENTS + EVENT_ID + SESSIONS
            + TICKET_COMMUNICATION_ELEMENTS_TYPE;
    protected static final String SEASON_TICKETS = "/season-tickets";
    protected static final String SEASON_TICKET_ID = "/{seasonTicketId}";
    protected static final String SEASON_TICKET_PRICES = SEASON_TICKETS + SEASON_TICKET_ID + PRICES;
    protected static final String SEASON_TICKET_SESSIONS = SEASON_TICKETS + SEASON_TICKET_ID + SESSIONS;
    protected static final String SEASON_TICKET_SESSIONS_SESSION = SEASON_TICKET_SESSIONS + SESSION_ID;
    protected static final String SEASON_TICKET_RENEWAL_CANDIDATES = SEASON_TICKETS + SEASON_TICKET_ID + "/renewal-candidates";
    protected static final String RENEWALS = SEASON_TICKETS + "/renewals";
    protected static final String REPORT = RENEWALS + "/report";
    protected static final String SEASON_TICKET_RENEWALS = SEASON_TICKETS + SEASON_TICKET_ID + "/renewals";
    protected static final String SEASON_TICKET_RENEWAL_ENTITIES = SEASON_TICKETS + SEASON_TICKET_ID + "/renewal-entities";
    protected static final String SEASON_TICKET_CHANGE_SEATS = SEASON_TICKETS + SEASON_TICKET_ID + "/change-seats";
    protected static final String SEASON_TICKET_CHANGE_SEATS_PRICES = SEASON_TICKET_CHANGE_SEATS + PRICES;
    protected static final String SEASON_TICKET_LOYALTY_POINTS = SEASON_TICKETS + SEASON_TICKET_ID + "/loyalty-points";
    protected static final String SEASON_TICKET_RENEWAL_ID = SEASON_TICKET_RENEWALS + "/{renewalId}";
    protected static final String SEASON_TICKET_RENEWALS_PURGE = SEASON_TICKET_RENEWALS + "/purge";
    protected static final String SEASON_TICKET_RELEASE_SEAT = SEASON_TICKETS + SEASON_TICKET_ID + "/release-seat";
    protected static final String SEASON_TICKET_FORMS = SEASON_TICKETS + SEASON_TICKET_ID + "/forms/{formType}";
    protected static final String EVENT_CHANNELS = EVENTS + EVENT_ID + CHANNELS;
    protected static final String EVENT_CHANNEL = EVENT_CHANNELS + CHANNEL_ID;
    protected static final String SESSION_CHANNEL = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + CHANNELS + CHANNEL_ID;
    protected static final String SEASON_TICKET_STATUS = "/status";
    protected static final String SURCHARGES = "/surcharges";
    protected static final String TOURS = EVENTS + "/tours";
    protected static final String TOUR_ID = "/{tourId}";
    protected static final String TOUR_COMMUNICATION_ELEMENTS = TOURS + TOUR_ID + COMMUNICATION_ELEMENTS;
    protected static final String TIERS = "/tiers";
    protected static final String TICKET_TEMPLATES = "/ticket-templates";
    protected static final String TICKET_TEMPLATE_ID = "/{ticketTemplateId}";
    protected static final String TICKET_TEMPLATE_CLONE = TICKET_TEMPLATES + TICKET_TEMPLATE_ID + "/clone";
    protected static final String TICKET_TEMPLATE_DESIGNS = "/designs";
    protected static final String TICKET_TEMPLATE_COMMUNICATION_ELEMENTS = TICKET_TEMPLATES + TICKET_TEMPLATE_ID + COMMUNICATION_ELEMENTS;
    protected static final String TICKET_TEMPLATE_LITERALS = TICKET_TEMPLATES + TICKET_TEMPLATE_ID + "/literals";
    protected static final String PRODUCT_TICKET_TEMPLATE_LITERALS = PRODUCT_TICKET_TEMPLATES + TICKET_TEMPLATE_ID + "/literals";
    protected static final String TIER_ID = "/{tierId}";
    protected static final String VALIDATIONS = "/validations";
    protected static final String LIMIT = "/limit";
    protected static final String SALE_GROUPS = "/saleGroups";
    protected static final String SALE_GROUP_ID = "/{saleGroupId}";
    protected static final String COMM_ELEMENTS = COMMUNICATION_ELEMENTS;
    protected static final String SALE_CONSTRAINTS = "/sale-constraints";
    protected static final String REFUND_CONDITIONS = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + "/refund-conditions";
    protected static final String PRICE_TYPE_LIMIT = "/price-type-limit";
    protected static final String CART_LIMIT = "/cart-limit";
    protected static final String TICKET_COMMUNICATION_URL = "/languages/{language}/types/{tag}";
    protected static final String SEASON_TICKET_COMMUNICATION_ELEMENTS = SEASON_TICKETS + SEASON_TICKET_ID + COMMUNICATION_ELEMENTS;
    protected static final String SEASON_TICKET_EMAIL_COMMUNICATION_ELEMENTS = SEASON_TICKETS + SEASON_TICKET_ID
            + "/email-communication-elements";
    protected static final String SEASON_TICKET_TICKET_COMMUNICATION_ELEMENTS = SEASON_TICKETS + SEASON_TICKET_ID
            + TICKET_COMMUNICATION_ELEMENTS_TYPE;
    protected static final String PRICE_SIMULATION_EVENT_CHANNEL = "/price-engine/{saleRequestId}/simulation";
    protected static final String PRICE_SIMULATION_CHANNEL_EVENT = EVENT_CHANNEL + "/price-simulation";
    protected static final String PASSBOOK_TEMPLATE_CODE = "/passbookTemplateCode";
    protected static final String ATTENDANTS = "/attendants";
    protected static final String ATTENDANTS_SESSIONS = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + ATTENDANTS;
    protected static final String ATTENDANTS_EVENTS = EVENTS + EVENT_ID + ATTENDANTS;
    protected static final String ATTRIBUTES = "/attributes";
    protected static final String PRICE_TYPE = "/price-types";
    protected static final String PRICE_TYPE_ID = "/{priceTypeId}";
    protected static final String GET_PRICE_TYPE = EVENTS + EVENT_ID + PRICE_TYPE;
    protected static final String GET_SESSION_PRICE_TYPES = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + PRICE_TYPE;
    protected static final String PUT_PRICE_TYPE = GET_SESSION_PRICE_TYPES + PRICE_TYPE_ID;
    protected static final String GROUPS = "/groups";
    protected static final String LINKED_SESSIONS = "/linked-sessions";
    protected static final String GROUP_CONFIG = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + GROUPS;
    protected static final String EXTERNAL_BARCODE_CONFIG = EVENTS + EVENT_ID + "/external-barcode-config";
    protected static final String SESSION_EXTERNAL_BARCODE_CONFIG = SESSIONS + SESSION_ID + "/external-barcode-config";
    protected static final String PRICE_TYPE_RESTRICTION = "/venue-templates/{venueTemplateId}/price-types/{priceTypeId}/restrictions";
    protected static final String PRICE_TYPES = "/price-types";
    protected static final String SUBITEMS = "/subitems";
    protected static final String RESTRICTIONS = "/restrictions";
    protected static final String EXTERNAL_TYPES = "/external-types";
    protected static final String EXTERNAL_EVENTS = "/external-events";
    protected static final String EXTERNAL_EVENT_RATES = EXTERNAL_EVENTS + "/{internalId}/rates";

    protected static final String EVENT_CHANNEL_B2B = EVENT_CHANNEL + "/B2B";
    protected static final String EVENT_CHANNEL_B2B_ASSIGNATIONS = EVENT_CHANNEL_B2B + "/assignations";
    protected static final String RATES_GROUP = "/rates-group";
    protected static final String EXPORT_STATUS = "/exports/{exportId}/users/{userId}/status";
    protected static final String EVENT_B2B_PUBLISHING_CONFIG = EVENTS + EVENT_ID + CHANNELS + CHANNEL_ID + "/b2b/venue-templates/{templateId}/publishing-config";

    protected static final String AVET_SECTOR_RESTRICTIONS = "/events/{eventId}/avet-sector-restrictions";
    protected static final String AVET_SECTOR_RESTRICTION = "/events/{eventId}/avet-sector-restrictions/{restrictionId}";
    protected static final String TAGS = "/tags";
    protected static final String EVENT_TAGS = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + TAGS;
    protected static final String EVENT_TAGS_POSITION = EVENT_TAGS + "/{positionId}";
    protected static final String REPORT_PRICE_SIMULATION = PRICE_SIMULATION_EVENT_CHANNEL + "/report";
    protected static final String EVENT_SECONDARY_MARKET_CONFIG = "/secondary-market/events-config" + EVENT_ID;
    protected static final String SESSION_SECONDARY_MARKET_CONFIG = "/secondary-market/session-config" + SESSION_ID;
    protected static final String VALUES = "/values";

    protected static final String DYNAMIC_PRICE = EVENTS + EVENT_ID + SESSIONS + SESSION_ID + "/dynamic-prices";
    protected static final String DYNAMIC_PRICE_PRICE_ZONE = DYNAMIC_PRICE + "/price-zones/{idPriceZone}";
    protected static final String DYNAMIC_PRICE_ORDER_ID = DYNAMIC_PRICE_PRICE_ZONE + "/zone/{orderId}";
    protected static final String DYNAMIC_PRICE_PRICE_ZONE_RATES = DYNAMIC_PRICE_PRICE_ZONE + RATES;
    protected static final String EVENT_CUSTOMER_TYPES = EVENTS + EVENT_ID + "/customer-types";

    protected static final String CHANNEL_EVENT_COMMUNICATION_ELEMENTS = EVENT_CHANNEL + COMMUNICATION_ELEMENTS;
    protected static final String CHANNEL_SESSION_COMMUNICATION_ELEMENTS = SESSION_CHANNEL + COMMUNICATION_ELEMENTS;

    protected static final String PACKS = "/packs";
    protected static final String PACK = PACKS + "/{packId}";
    protected static final String PACK_ITEMS = PACK + "/items";
    protected static final String PACK_ITEM = PACK_ITEMS + "/{itemId}";
    protected static final String PACK_ITEM_PRICE_TYPES = PACK_ITEM + PRICE_TYPES;
    protected static final String PACK_ITEM_SUBITEMS = PACK_ITEM + SUBITEMS;
    protected static final String PACK_COMMUNICATION_ELEMENTS = PACK + COMMUNICATION_ELEMENTS;
    protected static final String PACK_TICKET_CONTENTS = PACK + TICKET_CONTENTS + "/{category}";
    protected static final String PACK_TICKET_CONTENTS_DELETE = PACK_TICKET_CONTENTS + "/languages/{language}/types/{type}";
    protected static final String POST_BOOKING_QUESTIONS = "/post-booking-questions";
    protected static final String EVENT_POST_BOOKING_QUESTIONS = EVENTS + EVENT_ID + POST_BOOKING_QUESTIONS;


    static {
        ERROR_CODES.put("500C0002", ApiMgmtErrorCode.GENERIC_ERROR);
        ERROR_CODES.put("400G0001", ApiMgmtErrorCode.BAD_REQUEST_PARAMETER);
        ERROR_CODES.put("404G0001", ApiMgmtErrorCode.NOT_FOUND);
        ERROR_CODES.put("ME0001", ApiMgmtErrorCode.EVENT_NOT_FOUND);
        ERROR_CODES.put("ME0002", ApiMgmtErrorCode.EVENT_CHANNEL_HAS_SALES);
        ERROR_CODES.put("ME0003", ApiMgmtErrorCode.FORBIDDEN_RESOURCE);
        ERROR_CODES.put("ME0006", ApiMgmtErrorCode.INVALID_LANG);
        ERROR_CODES.put("ME0007", ApiMgmtErrorCode.RATE_CONFLICT);
        ERROR_CODES.put("ME0008", ApiMgmtErrorCode.FORBIDDEN_EVENT_DELETE);
        ERROR_CODES.put("ME0009", ApiMgmtErrorCode.INVALID_NAME_FORMAT);
        ERROR_CODES.put("ME0010", ApiMgmtErrorCode.NAME_CONFLICT);
        ERROR_CODES.put("ME0011", ApiMgmtErrorCode.DEFAULT_LANG_REQUIRED);
        ERROR_CODES.put("ME0012", ApiMgmtErrorCode.FORBIDDEN_EVENT_UPDATE_STATUS);
        ERROR_CODES.put("ME0013", ApiMgmtErrorCode.FORBIDDEN_EVENT_FINISH);
        ERROR_CODES.put("ME0014", ApiMgmtErrorCode.INVALID_RATE);
        ERROR_CODES.put("ME0015", ApiMgmtErrorCode.INVALID_VENUE_TEMPLATE);
        ERROR_CODES.put("ME0016", ApiMgmtErrorCode.VENUE_TEMPLATE_PRICE_NOT_FOUND);
        ERROR_CODES.put("ME0017", ApiMgmtErrorCode.VENUE_TEMPLATE_PRICE_REQUIRED);
        ERROR_CODES.put("ME0020", ApiMgmtErrorCode.SEASON_LOCK);
        ERROR_CODES.put("ME0021", ApiMgmtErrorCode.VENUE_TEMPLATE_PRICE_EVENT_STATUS);
        ERROR_CODES.put("ME0022", ApiMgmtErrorCode.RATE_HAS_SESSIONS);
        ERROR_CODES.put("ME0023", ApiMgmtErrorCode.RATE_HAS_PROMOTIONS);
        ERROR_CODES.put("ME0024", ApiMgmtErrorCode.RATE_HAS_SALES);
        ERROR_CODES.put("ME0025", ApiMgmtErrorCode.SEASON_TICKET_INVALID_NAME_CONFLICT);
        ERROR_CODES.put("ME0026", ApiMgmtErrorCode.SEASON_TICKET_NOT_FOUND);
        ERROR_CODES.put("ME0027", ApiMgmtErrorCode.INVALID_SEASON_TICKET_ID);
        ERROR_CODES.put("ME0028", ApiMgmtErrorCode.EVENT_CHANNEL_NOT_FOUND);
        ERROR_CODES.put("ME0029", ApiMgmtErrorCode.EVENT_CHANNEL_EXISTS);
        ERROR_CODES.put("ME0030", ApiMgmtErrorCode.CHANNEL_NOT_FOUND);
        ERROR_CODES.put("ME0031", ApiMgmtChannelsErrorCode.CHANNEL_ID_INVALID);
        ERROR_CODES.put("ME0032", ApiMgmtErrorCode.SEASON_TICKET_INVALID_NUMBER_OF_SESSIONS);
        ERROR_CODES.put("ME0033", ApiMgmtErrorCode.INCONSISTENT_DATES);
        ERROR_CODES.put("ME0034", ApiMgmtErrorCode.INCONSISTENT_PUBLISHED_ONSALE_STATE);
        ERROR_CODES.put("ME0035", ApiMgmtErrorCode.FIELD_NOT_UPGRADEABLE);
        ERROR_CODES.put("ME0036", ApiMgmtErrorCode.REQUEST_NOT_PENDING);
        ERROR_CODES.put("ME0037", ApiMgmtErrorCode.USE_ALL_QUOTAS_MANDATORY);
        ERROR_CODES.put("ME0038", ApiMgmtErrorCode.QUOTAS_MANDATORY);
        ERROR_CODES.put("ME0039", ApiMgmtErrorCode.SETTINGS_MANDATORY);
        ERROR_CODES.put("ME0040", ApiMgmtErrorCode.USE_EVENT_DATES_MANDATORY);
        ERROR_CODES.put("ME0041", ApiMgmtErrorCode.EVENT_CHANNEL_SETTINGS_DATES_MANDATORY);
        ERROR_CODES.put("ME0042", ApiMgmtErrorCode.START_GREATER_END_DATE);
        ERROR_CODES.put("ME0043", ApiMgmtErrorCode.INVALID_QUOTAS);
        ERROR_CODES.put("ME0044", ApiMgmtErrorCode.ID_RATES_NOT_COHERENT);
        ERROR_CODES.put("ME0045", ApiMgmtErrorCode.INVALID_DESCRIPTION_LENGTH);
        ERROR_CODES.put("ME0046", ApiMgmtErrorCode.SECONDARY_MARKET_NOT_ALLOWED_FOR_EVENT);
        ERROR_CODES.put("SECONDARY_MARKET_NOT_ALLOWED_BY_ENTITY", ApiMgmtErrorCode.SECONDARY_MARKET_NOT_ALLOWED_BY_ENTITY);
        ERROR_CODES.put("SECONDARY_MARKET_NOT_SUPPORTED", ApiMgmtErrorCode.SECONDARY_MARKET_NOT_SUPPORTED);
        ERROR_CODES.put("EVENT_TYPE_DOES_NOT_SUPPORT_SECONDARY_MARKET", ApiMgmtErrorCode.EVENT_TYPE_DOES_NOT_SUPPORT_SECONDARY_MARKET);

        ERROR_CODES.put("ME0048", ApiMgmtErrorCode.SEASON_TICKET_MAX_BUYING_LIMIT_RANGE);
        ERROR_CODES.put("ME0049", ApiMgmtErrorCode.TYPE_MANDATORY);
        ERROR_CODES.put("ME0050", ApiMgmtErrorCode.SURCHARGE_TYPE_DUPLICATED);
        ERROR_CODES.put("ME0051", ApiMgmtErrorCode.SURCHARGE_TYPE_NOT_SUPPORTED);
        ERROR_CODES.put("ME0052", ApiMgmtErrorCode.AT_LEAST_ONE_RANGE);
        ERROR_CODES.put("ME0053", ApiMgmtErrorCode.SURCHARGE_FROM_RANGE_MANDATORY);
        ERROR_CODES.put("ME0054", ApiMgmtErrorCode.FIXED_OR_PERCENTAGE_MANDATORY);
        ERROR_CODES.put("ME0055", ApiMgmtErrorCode.SURCHARGE_TYPE_DUPLICATED);
        ERROR_CODES.put("ME0056", ApiMgmtErrorCode.SURCHARGE_FROM_RANGE_ZERO_MANDANTORY);
        ERROR_CODES.put("ME0057", ApiMgmtErrorCode.MIN_SURCHARGE_GREATER_THAN_MAX);
        ERROR_CODES.put("ME0075", ApiMgmtErrorCode.WHEN_LIMIT_ENABLED_IS_MANDATORY);
        ERROR_CODES.put("ME0076", ApiMgmtErrorCode.WHEN_LIMIT_ENABLED_MIN_LOWER_THAN_MAX);
        ERROR_CODES.put("ME0077", ApiMgmtErrorCode.SEASON_TICKET_IN_CREATION);
        ERROR_CODES.put("ME0078", ApiMgmtErrorCode.INVALID_SEASON_TICKET_HAS_SALES);
        ERROR_CODES.put("ME0079", ApiMgmtErrorCode.EVENT_AVET_CONFIG_MANDATORY);
        ERROR_CODES.put("ME0080", ApiMgmtErrorCode.EVENT_AVET_COMPETITION_MANDATORY);
        ERROR_CODES.put("ME0081", ApiMgmtErrorCode.TOUR_NOT_FOUND);
        ERROR_CODES.put("ME0086", ApiMgmtErrorCode.TICKET_TEMPLATE_NOT_FOUND);
        ERROR_CODES.put("ME0087", ApiMgmtErrorCode.TICKET_TEMPLATE_MODEL_NOT_FOUND);
        ERROR_CODES.put("ME0088", ApiMgmtErrorCode.TICKET_TEMPLATE_NOT_REMOVABLE);
        ERROR_CODES.put("ME0089", ApiMgmtErrorCode.TICKET_TEMPLATE_INVALID_DEFAULT_LANGUAGE);
        ERROR_CODES.put("ME0094", ApiMgmtErrorCode.TICKET_TEMPLATE_LITERAL_NOT_FOUND);
        ERROR_CODES.put("TICKET_TEMPLATE_FORMAT_NOT_AVAILABLE", ApiMgmtErrorCode.TICKET_TEMPLATE_FORMAT_NOT_AVAILABLE);
        ERROR_CODES.put("ME0098", ApiMgmtErrorCode.EVENT_ALREADY_HAS_SESSION_PACKS);
        ERROR_CODES.put("ME0100", ApiMgmtErrorCode.SEASON_TICKET_WITH_BOOKED_SEAT_REGISTRY_CHANGE);
        ERROR_CODES.put("ME0103", ApiMgmtErrorCode.SEASON_TICKET_INVALID_RENEWAL_DATES);
        ERROR_CODES.put("ME0104", ApiMgmtErrorCode.SEASON_TICKET_RENEWAL_IS_NOT_ALLOWED);
        ERROR_CODES.put("ME0105", ApiMgmtErrorCode.SEASON_TICKET_RENEWAL_FIELDS_NOT_INFORMED);
        ERROR_CODES.put("ME0106", ApiMgmtErrorCode.SEASON_TICKET_RENEWAL_PUBLISHING_NOT_ENABLED);
        ERROR_CODES.put("ME0107", ApiMgmtErrorCode.SEASON_TICKET_RENEWAL_PUBLISHING_DATES);
        ERROR_CODES.put("ME0108", ApiMgmtSeasonTicketErrorCode.RENEWALS_SEATS_NOT_AVAILABLE);
        ERROR_CODES.put("ME0109", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_DIFFERENT_VENUES);
        ERROR_CODES.put("ME0110", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_DIFFERENT_ENTITY);
        ERROR_CODES.put("ME0111", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_ON_SALE);
        ERROR_CODES.put("ME0112", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_DIFFERENT_MEMBER_MANDATORY);
        ERROR_CODES.put("ME0113", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_SAME_SEASON_TICKETS);
        ERROR_CODES.put("ME0114", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_NOT_READY);
        ERROR_CODES.put("ME0115", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_IN_PROGRESS);
        ERROR_CODES.put("ME0116", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_NO_PRODUCTS_TO_RENEWAL);
        ERROR_CODES.put("ME0117", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_NOT_FOUND);
        ERROR_CODES.put("ME0118", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_DELETE_RENEWED_NOT_ALLOWED);
        ERROR_CODES.put("ME0119", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RENEWAL_DELETE_NOT_ALLOWED);
        ERROR_CODES.put("ME0120", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_RATE_USED_ON_RENEWAL);
        ERROR_CODES.put("SEASON_TICKET_CHANGE_SEAT_IS_NOT_ALLOWED", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_CHANGE_SEAT_IS_NOT_ALLOWED);
        ERROR_CODES.put("SEASON_TICKET_CHANGE_SEAT_FIELDS_NOT_INFORMED", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_CHANGE_SEAT_FIELDS_NOT_INFORMED);
        ERROR_CODES.put("SEASON_TICKET_CHANGE_SEAT_PUBLISHING_NOT_ENABLED", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_CHANGE_SEAT_PUBLISHING_NOT_ENABLED);
        ERROR_CODES.put("SEASON_TICKET_CHANGE_SEAT_PUBLISHING_DATES", ApiMgmtSeasonTicketErrorCode.SEASON_TICKET_CHANGE_SEAT_PUBLISHING_DATES);
        ERROR_CODES.put("ME0121", ApiMgmtErrorCode.UPDATE_EVENT_EXTERNAL_BARCODE_CONFIG_WITH_ACTIVE_SESSIONS);
        ERROR_CODES.put("ME0122", ApiMgmtErrorCode.UPDATE_EVENT_EXTERNAL_BARCODE_WITH_SALES);
        ERROR_CODES.put("ME0125", ApiMgmtErrorCode.RATE_NOT_FOUND);
        ERROR_CODES.put("ME0126", ApiMgmtErrorCode.EVENT_IS_NOT_AVET);
        ERROR_CODES.put("ME0127", ApiMgmtErrorCode.REPEATED_EXTERNAL_DESCRIPTION);
        ERROR_CODES.put("ME0128", ApiMgmtErrorCode.EXTERNAL_DESCRIPTION_NOT_FOUND);
        ERROR_CODES.put("ME0129", ApiMgmtErrorCode.WRONG_EXTERNAL_DESCRIPTION);
        ERROR_CODES.put("ME0130", ApiMgmtErrorCode.NOT_MODIFIABLE_DEFAULT_RATE);
        ERROR_CODES.put("ME0131", ApiMgmtErrorCode.PRICE_LIST_VOID_IN_AVET);
        ERROR_CODES.put("500C0005", ApiMgmtErrorCode.PERSISTENCE_ERROR);
        ERROR_CODES.put("COMMUNICATION_ELEMENT_BULK_UPDATE_LOCKED", ApiMgmtErrorCode.GENERIC_ERROR);
        ERROR_CODES.put("INVALID_ACTIVITY_SALE_GROUPS", ApiMgmtErrorCode.INVALID_ACTIVITY_QUOTAS);
        ERROR_CODES.put("EVENT_GROUP_NOT_ALLOWED", ApiMgmtErrorCode.EVENT_GROUP_NOT_ALLOWED);
        ERROR_CODES.put("EVENT_INVALID_GROUP_CHANGE", ApiMgmtErrorCode.INVALID_GROUP_CHANGE);
        ERROR_CODES.put("EVENT_CHANNEL_CURRENCY_NOT_MATCH", ApiMgmtErrorCode.EVENT_CHANNEL_CURRENCY_NOT_MATCH);
        ERROR_CODES.put("SESSION_PRESALE_NOT_FOUND", ApiMgmtErrorCode.SESSION_PRESALE_NOT_FOUND);
        ERROR_CODES.put("INVALID_SESSION_PRESALE_UPDATE_REQUEST", ApiMgmtErrorCode.INVALID_SESSION_PRESALE_UPDATE_REQUEST);
        ERROR_CODES.put("INVALID_SESSION_PRESALE_CREATE_REQUEST", ApiMgmtErrorCode.INVALID_SESSION_PRESALE_CREATE_REQUEST);
        ERROR_CODES.put("INVALID_SESSION_PRESALE_DATES_REQUIRED", ApiMgmtErrorCode.INVALID_SESSION_PRESALE_DATES_REQUIRED);
        ERROR_CODES.put("INVALID_SESSION_PRESALE_DATES_END_BEFORE_START", ApiMgmtErrorCode.INVALID_SESSION_PRESALE_DATES_END_BEFORE_START);
        // TIERS
        ERROR_CODES.put("TIER_NAME_MANDATORY", ApiMgmtTierErrorCode.TIER_NAME_MANDATORY);
        ERROR_CODES.put("TIER_NAME_MAX_LENGTH", ApiMgmtTierErrorCode.TIER_NAME_MAX_LENGTH);
        ERROR_CODES.put("TIER_NAME_UNIQUE", ApiMgmtTierErrorCode.TIER_NAME_UNIQUE);
        ERROR_CODES.put("TIER_PRICE_MANDATORY", ApiMgmtTierErrorCode.TIER_PRICE_MANDATORY);
        ERROR_CODES.put("TIER_PRICE_TYPE_MANDATORY", ApiMgmtTierErrorCode.TIER_PRICE_TYPE_MANDATORY);
        ERROR_CODES.put("TIER_PRICE_TYPE_BELONG_TO_EVENT", ApiMgmtTierErrorCode.TIER_PRICE_TYPE_BELONG_TO_EVENT);
        ERROR_CODES.put("TIER_START_DATE_MANDATORY", ApiMgmtTierErrorCode.TIER_START_DATE_MANDATORY);
        ERROR_CODES.put("EVENT_CANNOT_USE_TIER", ApiMgmtTierErrorCode.EVENT_CANNOT_USE_TIER);
        ERROR_CODES.put("TIER_START_DATE_AFTER_EVENT", ApiMgmtTierErrorCode.TIER_START_DATE_AFTER_EVENT);
        ERROR_CODES.put("TIER_DATA_MANDATORY", ApiMgmtTierErrorCode.TIER_DATA_MANDATORY);
        ERROR_CODES.put("DEACTIVATE_TIERS_WITH_TIERS_CREATED", ApiMgmtTierErrorCode.DEACTIVATE_TIERS);
        ERROR_CODES.put("USE_TIERS_WITH_RATES", ApiMgmtTierErrorCode.USE_TIERS_WITH_RATES);
        ERROR_CODES.put("CHANGE_TIERS_WITH_SESSIONS", ApiMgmtTierErrorCode.CHANGE_TIERS_WITH_SESSIONS);
        ERROR_CODES.put("TIER_START_DATE_ALREADY_EXISTS", ApiMgmtTierErrorCode.TIER_START_DATE_ALREADY_EXISTS);
        ERROR_CODES.put("USE_TIERS_WITH_GRAPHIC_VENUE_TEMPLATE", ApiMgmtTierErrorCode.TIERS_NOT_ALLOW_GRAPHICAL_VENUE);
        ERROR_CODES.put("TIER_NOT_FOUND", ApiMgmtTierErrorCode.TIERS_NOT_FOUND);
        ERROR_CODES.put("TIER_ID_MANDATORY", ApiMgmtTierErrorCode.TIER_ID_MANDATORY);
        ERROR_CODES.put("TIER_PRICE_POSITIVE", ApiMgmtTierErrorCode.TIER_PRICE_POSITIVE);
        ERROR_CODES.put("NO_ON_SALE_TIER_FOR_ENTIRE_EVENT_LIFESPAN", ApiMgmtTierErrorCode.NO_ON_SALE_TIER_FOR_ENTIRE_EVENT_LIFESPAN);
        ERROR_CODES.put("INVALID_TIER_DATES", ApiMgmtTierErrorCode.INVALID_TIER_DATES);
        ERROR_CODES.put("EVENT_DATES_NEEDED_TO_ACTIVATE_TIERED_EVENT", ApiMgmtTierErrorCode.EVENT_DATES_NEEDED_TO_ACTIVATE_TIERED_EVENT);
        ERROR_CODES.put("LIMIT_NEGATIVE", ApiMgmtTierErrorCode.LIMIT_NEGATIVE);
        ERROR_CODES.put("LIMIT_BELOW_ZERO", ApiMgmtTierErrorCode.LIMIT_BELOW_ZERO);
        ERROR_CODES.put("INVALID_SALE_GROUP_LIMIT", ApiMgmtTierErrorCode.INVALID_QUOTA_LIMIT);
        ERROR_CODES.put("SALEGROUP_ID_MANDATORY", ApiMgmtTierErrorCode.QUOTA_ID_MANDATORY);
        ERROR_CODES.put("SALEGROUP_NOT_FOUND", ApiMgmtTierErrorCode.QUOTA_NOT_FOUND);
        ERROR_CODES.put("SALEGROUP_TEMPLATE_NOT_MATCHING_TIER_TEMPLATE", ApiMgmtTierErrorCode.QUOTA_TEMPLATE_NOT_MATCHING_TIER_TEMPLATE);
        ERROR_CODES.put("SALE_GROUP_TIER_NOT_FOUND", ApiMgmtTierErrorCode.TIER_QUOTA_NOT_FOUND);
        ERROR_CODES.put("TIER_SALE_GROUP_ALREADY_EXISTS", ApiMgmtTierErrorCode.TIER_QUOTA_ALREADY_EXISTS);
        ERROR_CODES.put("STOCK_CONDITION_WITHOUT_LIMIT", ApiMgmtTierErrorCode.STOCK_CONDITION_WITHOUT_LIMIT);
        ERROR_CODES.put("TIER_LIMIT_REACHED", ApiMgmtTierErrorCode.TIER_LIMIT_REACHED);
        ERROR_CODES.put("TIER_SALE_GROUP_LIMIT_REACHED", ApiMgmtTierErrorCode.TIER_QUOTA_LIMIT_REACHED);
        ERROR_CODES.put("TIER_TRANSLATION_MANDATORY", ApiMgmtTierErrorCode.TIER_TRANSLATION_MANDATORY);
        ERROR_CODES.put("INVALID_COMM_ELEM_VALUE", ApiMgmtTierErrorCode.INVALID_COMM_ELEM_VALUE);
        ERROR_CODES.put("INVALID_COMM_ELEM_LANG", ApiMgmtTierErrorCode.INVALID_COMM_ELEM_LANG);
        // SESSIONS
        ERROR_CODES.put("404ME001", ApiMgmtSessionErrorCode.SESSION_NOT_FOUND);
        ERROR_CODES.put("400ME001", ApiMgmtSessionErrorCode.SESSION_NOT_MATCH_EVENT);
        ERROR_CODES.put("ME0019", ApiMgmtSessionErrorCode.SESSION_WITH_BOOKED_SEAT);
        ERROR_CODES.put("ME0047", ApiMgmtSessionErrorCode.INVALID_SESSION_SPACE);
        ERROR_CODES.put("ME0058", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_START_REQUIRED);
        ERROR_CODES.put("ME0095", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_END_BEFORE_START);
        ERROR_CODES.put("ME0059", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_RELEASE_REQUIRED);
        ERROR_CODES.put("ME0060", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_RELEASE_AFTER_START);
        ERROR_CODES.put("ME0061", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_RELEASE_AFTER_BOOKING_START);
        ERROR_CODES.put("ME0062", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_RELEASE_AFTER_SALES_START);
        ERROR_CODES.put("ME0063", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_SALES_START_REQUIRED);
        ERROR_CODES.put("ME0064", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_SALES_START_BEFORE_RELEASE);
        ERROR_CODES.put("ME0065", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_SALES_START_AFTER_START);
        ERROR_CODES.put("ME0066", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_SALES_START_NOT_BEFORE_SALES_END);
        ERROR_CODES.put("ME0067", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_SALES_END_REQUIRED);
        ERROR_CODES.put("ME0068", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_SALES_END_BEFORE_BOOKING_END);
        ERROR_CODES.put("ME0069", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_BOOKING_START_REQUIRED);
        ERROR_CODES.put("ME0070", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_BOOKING_START_BEFORE_RELEASE);
        ERROR_CODES.put("ME0071", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_BOOKING_START_NOT_BEFORE_BOOKING_END);
        ERROR_CODES.put("ME0072", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_BOOKING_END_REQUIRED);
        ERROR_CODES.put("ME0073", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_BOOKING_END_AFTER_SALES_END);
        ERROR_CODES.put("ME0074", ApiMgmtSessionErrorCode.INVALID_SESSION_DATES_BOOKING_END_CONFLICT_EVENT_LIMIT);
        ERROR_CODES.put("ME0082", ApiMgmtSessionErrorCode.INVALID_SESSION_TAX);
        ERROR_CODES.put("ME0090", ApiMgmtSessionErrorCode.SALE_TYPE_MANDATORY);
        ERROR_CODES.put("ME0091", ApiMgmtSessionErrorCode.SALE_TYPE_GROUP_FORBIDDEN);
        ERROR_CODES.put("ME0092", ApiMgmtSessionErrorCode.SESSION_CLONE_GENERATION_STATUS);
        ERROR_CODES.put("ME0093", ApiMgmtSessionErrorCode.SESSION_CLONE_SESSION_PACK);
        ERROR_CODES.put("ME0096", ApiMgmtSessionErrorCode.SESSION_CREATE_SESSION_PACK_STATUS);
        ERROR_CODES.put("ME0097", ApiMgmtSessionErrorCode.SESSION_CREATE_PACK_BLOCKING_REASON);
        ERROR_CODES.put("ME0099", ApiMgmtSessionErrorCode.SESSION_PACK_BULK_UPDATE_FORBIDDEN);
        ERROR_CODES.put("ME0101", ApiMgmtPassbookErrorCode.PASSBOOK_TEMPLATE_NOT_FOUND);
        ERROR_CODES.put("MES0001", ApiMgmtSessionErrorCode.PRICE_TYPE_NOT_IN_SESSION);
        ERROR_CODES.put("MES0002", ApiMgmtSessionErrorCode.INVALID_MAX_PRICE_TYPE_LIMIT);
        ERROR_CODES.put("MES0003", ApiMgmtSessionErrorCode.INVALID_MIN_PRICE_TYPE_LIMIT);
        ERROR_CODES.put("MES0004", ApiMgmtSessionErrorCode.MAX_SMALLER_THAN_MIN);
        ERROR_CODES.put("MES0005", ApiMgmtSessionErrorCode.MAX_GREATER_THAN_SESSION_CART_LIMIT);
        ERROR_CODES.put("MES0006", ApiMgmtSessionErrorCode.INVALID_CART_LIMIT);
        ERROR_CODES.put("MES0007", ApiMgmtSessionErrorCode.DUPLICATED_PRICE_TYPE_LIMIT);
        ERROR_CODES.put("MES0008", ApiMgmtSessionErrorCode.INVALID_SALES_TYPE);
        ERROR_CODES.put("MES0009", ApiMgmtSessionErrorCode.INVALID_SESSION_CLIENT_CONFIGURATION);
        ERROR_CODES.put("PE0001", ApiMgmtErrorCode.SALE_REQUEST_NOT_FOUND);
        ERROR_CODES.put("PE0002", ApiMgmtErrorCode.SALE_REQUEST_NOT_FOUND);
        ERROR_CODES.put("VENUES_WITH_DIFFERENT_OLSON_ID", ApiMgmtSessionErrorCode.VENUES_WITH_DIFFERENT_OLSON_ID);
        ERROR_CODES.put("GATE_ID_INVALID", ApiMgmtSessionErrorCode.GATE_ID_INVALID);
        ERROR_CODES.put("ACTIVITY_SESSION_MANDATORY", ApiMgmtSessionErrorCode.ACTIVITY_SESSION_MANDATORY);
        ERROR_CODES.put("EVENT_SESSION_PACKS_NOT_ALLOWED", ApiMgmtSessionErrorCode.EVENT_SESSION_PACKS_NOT_ALLOWED);
        ERROR_CODES.put("ATTRIBUTE_INVALID_VALUE", ApiMgmtSessionErrorCode.ATTRIBUTE_INVALID_VALUE);
        ERROR_CODES.put("ATTRIBUTE_INVALID_ID", ApiMgmtSessionErrorCode.ATTRIBUTE_INVALID_ID);
        ERROR_CODES.put("PRODUCER_ID_NOT_VALID", ApiMgmtSessionErrorCode.PRODUCER_ID_NOT_VALID);
        ERROR_CODES.put("PRODUCER_ID_DO_NOT_EXIST", ApiMgmtSessionErrorCode.PRODUCER_ID_DO_NOT_EXIST);
        ERROR_CODES.put("PRODUCER_ID_MANDATORY", ApiMgmtSessionErrorCode.PRODUCER_ID_MANDATORY);
        ERROR_CODES.put("SESSION_INVALID_STATUS_FOR_INVOICE_MODIFICATION", ApiMgmtSessionErrorCode.SESSION_INVALID_STATUS_FOR_INVOICE_MODIFICATION);
        ERROR_CODES.put("INVOICE_PREFIX_ID_MANDATORY", ApiMgmtSessionErrorCode.INVOICE_PREFIX_ID_MANDATORY);
        ERROR_CODES.put("INVOICE_PREFIX_NOT_FOUND", ApiMgmtSessionErrorCode.INVOICE_PREFIX_NOT_FOUND);
        ERROR_CODES.put("QUEUE_ALIAS_MANDATORY", ApiMgmtSessionErrorCode.QUEUE_ALIAS_MANDATORY);
        ERROR_CODES.put("EMPTY_COUNTRY_FILTER_LIST", ApiMgmtSessionErrorCode.EMPTY_COUNTRY_FILTER_LIST);
        ERROR_CODES.put("SUBSCRIPTION_LIST_ID_NOT_FOUND", ApiMgmtSessionErrorCode.SUBSCRIPTION_LIST_ID_NOT_FOUND);
        ERROR_CODES.put("ATTENDANT_CONFIG_AUTOFILL_NOT_ALLOWED", ApiMgmtSessionErrorCode.ATTENDANT_CONFIG_AUTOFILL_NOT_ALLOWED);
        ERROR_CODES.put("GROUPS_ACTIVITY_SESSION", ApiMgmtSessionErrorCode.GROUPS_ACTIVITY_SESSION);
        ERROR_CODES.put("SESSION_CREATE_PACK_ALLOW_PARTIAL_REFUND", ApiMgmtSessionErrorCode.SESSION_CREATE_PACK_ALLOW_PARTIAL_REFUND);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_NOT_FOUND", ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_NOT_FOUND);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_SESSIONS",
                ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_SESSIONS);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_PRICETYPES",
                ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_PRICETYPES);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_RATES", ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_RATES);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_PERCENTAGE",
                ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_PERCENTAGE);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_TOTAL_PERCENTAGE",
                ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_TOTAL_PERCENTAGE);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_QUOTA", ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_QUOTA);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_SEAT_STATUS",
                ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_SEAT_STATUS);
        ERROR_CODES.put("SESSION_REFUND_CONDITIONS_INVALID_BLOCKING_REASON",
                ApiMgmtSessionErrorCode.SESSION_PACK_REFUND_CONDITIONS_INVALID_BLOCKING_REASON);
        ERROR_CODES.put("ME0123", ApiMgmtSessionErrorCode.UPDATE_SESSION_EXTERNAL_BARCODE_WITH_SALES);

        ERROR_CODES.put("REQUIRED_PRICE_TYPE_MANDATORY", ApiMgmtSessionErrorCode.REQUIRED_PRICE_TYPE_MANDATORY);
        ERROR_CODES.put("PRICE_TYPE_NOT_FOUND", ApiMgmtErrorCode.PRICE_TYPE_NOT_FOUND);
        ERROR_CODES.put("PRICE_TYPE_RESTRICTION_NOT_FOUND", ApiMgmtErrorCode.PRICE_TYPE_RESTRICTION_NOT_FOUND);
        ERROR_CODES.put("RATE_RESTRICTIONS_NOT_FOUND", ApiMgmtErrorCode.RATE_RESTRICTIONS_NOT_FOUND);
        ERROR_CODES.put("INVALID_RATE_RESTRICTIONS", ApiMgmtErrorCode.INVALID_RATE_RESTRICTIONS);
        ERROR_CODES.put("RATE_EXTERNAL_TYPE_REQUIRED", ApiMgmtErrorCode.RATE_EXTERNAL_TYPE_REQUIRED);
        ERROR_CODES.put("TICKET_NUMBER_EXCLUSION_INPUT", ApiMgmtSessionErrorCode.TICKET_NUMBER_EXCLUSION_INPUT);
        ERROR_CODES.put("CIRCULAR_PRICE_TYPE_RESTRICTION", ApiMgmtSessionErrorCode.CIRCULAR_PRICE_TYPE_RESTRICTION);
        ERROR_CODES.put("GRAPHIC_TEMPLATE_OPERATION", ApiMgmtErrorCode.GRAPHIC_TEMPLATE_OPERATION);
        ERROR_CODES.put("OPERATION_NOT_ALLOWED_ON_GRAPHIC_TEMPLATE", ApiMgmtSessionErrorCode.OPERATION_NOT_ALLOWED_ON_GRAPHIC_TEMPLATE);
        ERROR_CODES.put("INVOICE_PREFIX_ALREADY_EXIST", ApiMgmtErrorCode.INVOICE_PREFIX_ALREADY_EXIST);
        ERROR_CODES.put("PRODUCER_SIMPLIFIED_INVOICE_FLAG", ApiMgmtErrorCode.PRODUCER_SIMPLIFIED_INVOICE_FLAG);
        ERROR_CODES.put("INVOICE_PREFIX_ALLOWED_CHARACTERS", ApiMgmtErrorCode.INVOICE_PREFIX_ALLOWED_CHARACTERS);
        ERROR_CODES.put("INVOICE_PREFIX_CANNOT_BE_MODIFIED", ApiMgmtErrorCode.INVOICE_PREFIX_CANNOT_BE_MODIFIED);
        ERROR_CODES.put("SIMPLIFIED_INVOICES_CANNOT_BE_USED", ApiMgmtErrorCode.SIMPLIFIED_INVOICES_CANNOT_BE_USED);
        ERROR_CODES.put("ME0124", ApiMgmtExternalEventErrorCode.EXTERNAL_EVENT_NOT_FOUND);
        ERROR_CODES.put("SESSION_EXTERNAL_BARCODES_MUST_BE_CONFIGURED", ApiMgmtSessionErrorCode.SESSION_EXTERNAL_BARCODES_MUST_BE_CONFIGURED);
        ERROR_CODES.put("NO_OBJECT_UNDER_S3_PATH", ApiMgmtErrorCode.NO_OBJECT_UNDER_S3_PATH);
        ERROR_CODES.put("EVENT_ACCOMMODATIONS_CONFIG_NOT_PROPERLY_ENABLED", ApiMgmtErrorCode.EVENT_ACCOMMODATIONS_CONFIG_NOT_PROPERLY_ENABLED);
        ERROR_CODES.put("ACCOMMODATIONS_CONFIG_NOT_ENABLED_BY_ENTITY", ApiMgmtErrorCode.ACCOMMODATIONS_CONFIG_NOT_ENABLED_BY_ENTITY);
        ERROR_CODES.put("ACCOMMODATIONS_VENDOR_NOT_ALLOWED_BY_ENTITY", ApiMgmtErrorCode.ACCOMMODATIONS_VENDOR_NOT_ALLOWED_BY_ENTITY);
        ERROR_CODES.put("CONFIG_NOT_FOUND", ApiMgmtErrorCode.CONFIG_NOT_FOUND);
        ERROR_CODES.put("INVALID_SESSION_DATE_CHANGE_SEAT_CONFIG", ApiMgmtErrorCode.INVALID_SESSION_DATE_CHANGE_SEAT_CONFIG);

        ERROR_CODES.put("EXPORT_WITH_TOO_MANY_RECORDS", ApiMgmtExportsErrorCode.EXPORT_WITH_TOO_MANY_RECORDS);
        ERROR_CODES.put("S3_FILE_NOT_UPLOADED", ApiMgmtExportsErrorCode.S3_FILE_NOT_UPLOADED);
        ERROR_CODES.put("AMQP_PUSH_EXCEPTION", ApiMgmtExportsErrorCode.AMQP_PUSH_EXCEPTION);
        ERROR_CODES.put("EXPORT_STATUS_NOT_FOUND", ApiMgmtExportsErrorCode.EXPORT_STATUS_NOT_FOUND);
        ERROR_CODES.put("SMART_BOOKING_NOT_ALLOWED", ApiMgmtErrorCode.SMART_BOOKING_NOT_ALLOWED);
        ERROR_CODES.put("INVALID_ENTITY_TAX", ApiMgmtErrorCode.INVALID_ENTITY_TAX);
        ERROR_CODES.put("TAX_NOT_UPDATABLE_ON_PRODUCT", ApiMgmtErrorCode.TAX_NOT_UPDATABLE_ON_PRODUCT);
        //PRODUCTS
        ERROR_CODES.put("PRODUCT_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_EVENT_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_EVENT_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_EVENT_SESSION_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_EVENT_SESSION_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_EVENT_SESSION_INVALID_SELECTION_TYPE", ApiMgmtErrorCode.PRODUCT_EVENT_SESSION_INVALID_SELECTION_TYPE);
        ERROR_CODES.put("PRODUCT_EVENT_SESSION_INVALID_TYPE_OR_STOCK_TYPE", ApiMgmtErrorCode.PRODUCT_EVENT_SESSION_INVALID_TYPE_OR_STOCK_TYPE);
        ERROR_CODES.put("PRODUCT_EVENT_SESSION_BAD_REQUEST_STOCK_MANDATORY", ApiMgmtErrorCode.PRODUCT_EVENT_SESSION_BAD_REQUEST_STOCK_MANDATORY);
        ERROR_CODES.put("PRODUCT_EVENT_STATE_NOT_VALID", ApiMgmtErrorCode.PRODUCT_EVENT_STATE_NOT_VALID);
        ERROR_CODES.put("PRODUCT_EVENT_ALREADY_EXISTS", ApiMgmtErrorCode.PRODUCT_EVENT_ALREADY_EXISTS);
        ERROR_CODES.put("PRODUCT_VARIANT_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_VARIANT_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_DELIVERY_POINT_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_DELIVERY_POINT_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_DELIVERY_NOT_UPDATABLE", ApiMgmtErrorCode.PRODUCT_DELIVERY_NOT_UPDATABLE);
        ERROR_CODES.put("PRODUCT_DELIVERY_POINT_RELATION_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_DELIVERY_POINT_RELATION_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_DELIVERY_TYPE_REQUIRED", ApiMgmtErrorCode.PRODUCT_DELIVERY_TYPE_REQUIRED);
        ERROR_CODES.put("PRODUCT_DELIVERY_PERIOD_REQUIRED", ApiMgmtErrorCode.PRODUCT_DELIVERY_PERIOD_REQUIRED);
        ERROR_CODES.put("MORE_THAN_ONE_VARIANT", ApiMgmtErrorCode.ILLEGAL_VARIANT_AMOUNT);
        ERROR_CODES.put("PRODUCT_LANGUAGES_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_LANGUAGES_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_CHANNEL_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_CHANNEL_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_CHANNELS_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_CHANNELS_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_ATTRIBUTE_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_ATTRIBUTE_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_ATTRIBUTE_NAME_DUPLICATED", ApiMgmtErrorCode.PRODUCT_ATTRIBUTE_NAME_DUPLICATED);
        ERROR_CODES.put("PRODUCT_EVENT_NOT_RELATED", ApiMgmtErrorCode.PRODUCT_EVENT_NOT_RELATED);
        ERROR_CODES.put("MAX_ATTRIBUTES_REACHED", ApiMgmtErrorCode.MAX_ATTRIBUTES_REACHED);
        ERROR_CODES.put("PRODUCT_COMMUNICATIONS_ELEMENTS_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_COMMUNICATIONS_ELEMENTS_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_VARIANT_PRICE_AND_STOCK_NOT_UPDATABLE", ApiMgmtErrorCode.PRODUCT_VARIANT_PRICE_AND_STOCK_NOT_UPDATABLE);
        ERROR_CODES.put("EVENT_ALREADY_EXISTS", ApiMgmtErrorCode.EVENT_ALREADY_EXISTS);
        ERROR_CODES.put("ST_EVENT_ALREADY_EXISTS", ApiMgmtErrorCode.ST_EVENT_ALREADY_EXISTS);
        ERROR_CODES.put("PRODUCT_CANNOT_BE_ACTIVATED", ApiMgmtErrorCode.PRODUCT_CANNOT_BE_ACTIVATED);
        ERROR_CODES.put("SESSIONS_NOT_FOUND_OR_INVALID_SESSION_STATE", ApiMgmtErrorCode.SESSIONS_NOT_FOUND_OR_INVALID_SESSION_STATE);
        ERROR_CODES.put("PRODUCT_TAX_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_TAX_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_SURCHARGE_TAX_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_SURCHARGE_TAX_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_EVENT_DELIVERY_POINT_DEFAULT_REQUIRED", ApiMgmtErrorCode.PRODUCT_EVENT_DELIVERY_POINT_DEFAULT_REQUIRED);
        ERROR_CODES.put("PRODUCT_LANGUAGE_DEFAULT_REQUIRED", ApiMgmtErrorCode.PRODUCT_LANGUAGE_DEFAULT_REQUIRED);
        ERROR_CODES.put("PRODUCT_EVENTS_REQUIRED", ApiMgmtErrorCode.PRODUCT_EVENTS_REQUIRED);
        ERROR_CODES.put("PRODUCT_SESSIONS_REQUIRED", ApiMgmtErrorCode.PRODUCT_SESSIONS_REQUIRED);
        ERROR_CODES.put("PRODUCT_VARIANT_PRICE_REQUIRED", ApiMgmtErrorCode.PRODUCT_VARIANT_PRICE_REQUIRED);
        ERROR_CODES.put("PRODUCT_VARIANT_NOT_ENOUGH_STOCK", ApiMgmtErrorCode.PRODUCT_VARIANT_NOT_ENOUGH_STOCK);
        ERROR_CODES.put("PRODUCT_NAME_ALREADY_IN_USE", ApiMgmtErrorCode.PRODUCT_NAME_ALREADY_IN_USE);
        ERROR_CODES.put("PRODUCT_CHANNEL_ALREADY_EXISTS", ApiMgmtErrorCode.PRODUCT_CHANNEL_ALREADY_EXISTS);
        ERROR_CODES.put("PRODUCT_CHANNEL_NOT_FROM_ENTITY", ApiMgmtErrorCode.PRODUCT_CHANNEL_NOT_FROM_ENTITY);
        ERROR_CODES.put("PRODUCT_CHANNEL_INVALID_TYPE", ApiMgmtErrorCode.PRODUCT_CHANNEL_INVALID_TYPE);
        ERROR_CODES.put("PRODUCT_CHANNEL_INVALID_OPTIONS", ApiMgmtErrorCode.PRODUCT_CHANNEL_INVALID_OPTIONS);
        ERROR_CODES.put("DELIVERY_POINT_NAME_ALREADY_IN_USE", ApiMgmtErrorCode.DELIVERY_POINT_NAME_ALREADY_IN_USE);
        ERROR_CODES.put("POSITION_MUST_BE_POSITIVE", ApiMgmtErrorCode.POSITION_MUST_BE_POSITIVE);
        ERROR_CODES.put("PRODUCT_HAS_SALES", ApiMgmtErrorCode.PRODUCT_HAS_SALES);
        ERROR_CODES.put("PRODUCT_INVALID_TYPE_FOR_SESSION_BOUNDED", ApiMgmtErrorCode.PRODUCT_INVALID_TYPE_FOR_SESSION_BOUNDED);
        ERROR_CODES.put("PRODUCT_TYPE_NOT_ALLOWED", ApiMgmtErrorCode.PRODUCT_TYPE_NOT_ALLOWED);
        ERROR_CODES.put("PRODUCT_STOCK_TYPE_NOT_ALLOWED", ApiMgmtErrorCode.PRODUCT_STOCK_TYPE_NOT_ALLOWED);
        ERROR_CODES.put("PRODUCT_MISSING_ACTIVE_VARIANT", ApiMgmtErrorCode.PRODUCT_MISSING_ACTIVE_VARIANT);

        ERROR_CODES.put("DUPLICATE_AVET_SECTOR_RESTRICTION_NAME", ApiMgmtErrorCode.DUPLICATE_AVET_SECTOR_RESTRICTION_NAME);
        ERROR_CODES.put("DUPLICATE_AVET_SECTOR_RESTRICTION_SID", ApiMgmtErrorCode.DUPLICATE_AVET_SECTOR_RESTRICTION_SID);
        ERROR_CODES.put("AVET_SECTOR_RESTRICTION_NOT_FOUND", ApiMgmtErrorCode.AVET_SECTOR_RESTRICTION_NOT_FOUND);
        ERROR_CODES.put("EVENT_WHITELABEL_UI_SETTINGS_CONFLICT", ApiMgmtErrorCode.EVENT_WHITELABEL_UI_SETTINGS_CONFLICT);
        ERROR_CODES.put("SESSION_TAG_NOT_FOUND", ApiMgmtErrorCode.SESSION_TAG_NOT_FOUND);
        ERROR_CODES.put("EVENT_TAG_LANGUAGE_NOT_FOUND", ApiMgmtErrorCode.EVENT_TAG_LANGUAGE_NOT_FOUND);
        ERROR_CODES.put("INVALID_SECONDARY_MARKET_CONFIG", ApiMgmtErrorCode.INVALID_SECONDARY_MARKET_CONFIG);
        ERROR_CODES.put("NULL_SECONDARY_MARKET_VALUES", ApiMgmtErrorCode.NULL_SECONDARY_MARKET_VALUES);
        ERROR_CODES.put("NEGATIVE_SECONDARY_MARKET_VALUES", ApiMgmtErrorCode.NEGATIVE_SECONDARY_MARKET_VALUES);
        ERROR_CODES.put("INVALID_SECONDARY_MARKET_RANGE", ApiMgmtErrorCode.INVALID_SECONDARY_MARKET_RANGE);
        ERROR_CODES.put("PRODUCT_ATTRIBUTE_VALUE_NAME_DUPLICATED", ApiMgmtErrorCode.PRODUCT_ATTRIBUTE_VALUE_NAME_DUPLICATED);
        ERROR_CODES.put("SESSION_SECONDARY_MARKET_ENABLE_REQUIRED", ApiMgmtErrorCode.SESSION_SECONDARY_MARKET_ENABLE_REQUIRED);
        ERROR_CODES.put("SESSION_SECONDARY_MARKET_START_DATE_REQUIRED", ApiMgmtErrorCode.SESSION_SECONDARY_MARKET_START_DATE_REQUIRED);
        ERROR_CODES.put("SESSION_SECONDARY_MARKET_END_DATE_REQUIRED", ApiMgmtErrorCode.SESSION_SECONDARY_MARKET_END_DATE_REQUIRED);
        ERROR_CODES.put("SECONDARY_MARKET_START_DATE_AFTER_END_DATE", ApiMgmtErrorCode.SECONDARY_MARKET_START_DATE_AFTER_END_DATE);
        ERROR_CODES.put("PRODUCT_VARIANT_STATE_INVALID", ApiMgmtErrorCode.PRODUCT_VARIANT_STATE_INVALID);
        ERROR_CODES.put("PRODUCT_VARIANT_PRODUCT_TYPE_INVALID", ApiMgmtErrorCode.PRODUCT_VARIANT_PRODUCT_TYPE_INVALID);
        ERROR_CODES.put("PRODUCT_VARIANT_NUMBER_ATTRIBUTES_INVALID", ApiMgmtErrorCode.PRODUCT_VARIANT_NUMBER_ATTRIBUTES_INVALID);
        ERROR_CODES.put("PRODUCT_VARIANT_MINIMUM_VALUES_INVALID", ApiMgmtErrorCode.PRODUCT_VARIANT_MINIMUM_VALUES_INVALID);
        ERROR_CODES.put("PRODUCT_VARIANT_STATUS_NOT_UPDATABLE", ApiMgmtErrorCode.PRODUCT_VARIANT_STATUS_NOT_UPDATABLE);
        ERROR_CODES.put("PRODUCT_VARIANT_FILTER_INVALID", ApiMgmtErrorCode.PRODUCT_VARIANT_FILTER_INVALID);
        ERROR_CODES.put("INVALID_CUSTOMER_TYPE", ApiMgmtErrorCode.INVALID_CUSTOMER_TYPE);
        ERROR_CODES.put("INVALID_CUSTOMER_LIMITS", ApiMgmtErrorCode.INVALID_CUSTOMER_LIMITS);
        ERROR_CODES.put("DYNAMIC_PRICE_ZONE_NOT_FOUND", ApiMgmtErrorCode.DYNAMIC_PRICE_ZONE_NOT_FOUND);
        ERROR_CODES.put("MISSING_DATE", ApiMgmtErrorCode.MISSING_DATE);
        ERROR_CODES.put("MISSING_CAPACITY", ApiMgmtErrorCode.MISSING_CAPACITY);
        ERROR_CODES.put("DATE_BEFORE_CREATION", ApiMgmtErrorCode.DATE_BEFORE_CREATION);
        ERROR_CODES.put("DATE_BEFORE_SALE_START", ApiMgmtErrorCode.DATE_BEFORE_SALE_START);
        ERROR_CODES.put("MISSING_NAME", ApiMgmtErrorCode.MISSING_NAME);
        ERROR_CODES.put("MISSING_CONDITION_TYPE", ApiMgmtErrorCode.MISSING_CONDITION_TYPE);
        ERROR_CODES.put("MISSING_ORDER", ApiMgmtErrorCode.MISSING_ORDER);
        ERROR_CODES.put("MISSING_RATES", ApiMgmtErrorCode.MISSING_RATES);
        ERROR_CODES.put("CAPACITY_LESS_THAN_PREVIOUS", ApiMgmtErrorCode.CAPACITY_LESS_THAN_PREVIOUS);
        ERROR_CODES.put("DYNAMIC_PRICE_NOT_FOUND", ApiMgmtErrorCode.DYNAMIC_PRICE_NOT_FOUND);
        ERROR_CODES.put("CANNOT_DELETE_ACTIVE_DYNAMIC_PRICE", ApiMgmtErrorCode.CANNOT_DELETE_ACTIVE_DYNAMIC_PRICE);
        ERROR_CODES.put("CANNOT_DELETE_PASS_DYNAMIC_PRICE", ApiMgmtErrorCode.CANNOT_DELETE_PASS_DYNAMIC_PRICE);
        ERROR_CODES.put("INVALID_ORDER_SEQUENCE", ApiMgmtErrorCode.INVALID_ORDER_SEQUENCE);
        ERROR_CODES.put("CANNOT_UPDATE_DYNAMIC_PRICE_FOR_ACTIVE_SESSION", ApiMgmtErrorCode.CANNOT_UPDATE_DYNAMIC_PRICE_FOR_ACTIVE_SESSION);
        ERROR_CODES.put("CANNOT_ACTIVATED_DYNAMIC_PRICE_IF_TIERED_PRICING_ACTIVE", ApiMgmtErrorCode.CANNOT_ACTIVATED_DYNAMIC_PRICE_IF_TIERED_PRICING_ACTIVE);
        ERROR_CODES.put("DATE_LESS_THAN_PREVIOUS", ApiMgmtErrorCode.DATE_LESS_THAN_PREVIOUS);
        ERROR_CODES.put("CUSTOMER_TYPE_NOT_FOUND_IN_EVENT", ApiMgmtErrorCode.CUSTOMER_TYPE_NOT_FOUND_IN_EVENT);
        ERROR_CODES.put("INVALID_EVENT_CHANGE_SEAT_EXPIRY_TIME_UNIT", ApiMgmtErrorCode.INVALID_EVENT_CHANGE_SEAT_EXPIRY_TIME_UNIT);
        ERROR_CODES.put("CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_THIS_TYPE_EVENT", ApiMgmtErrorCode.CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_THIS_TYPE_EVENT);
        ERROR_CODES.put("GROUPS_INCOMPATIBLE_WITH_DYNAMIC_PRICES", ApiMgmtErrorCode.GROUPS_INCOMPATIBLE_WITH_DYNAMIC_PRICES);
        ERROR_CODES.put("CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_ACTIVITY_WITH_GROUPS", ApiMgmtErrorCode.CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_ACTIVITY_WITH_GROUPS);
        ERROR_CODES.put("DYNAMIC_PRICES_REQUIRE_V4_CHANNEL", ApiMgmtErrorCode.DYNAMIC_PRICES_REQUIRE_V4_CHANNEL);
        ERROR_CODES.put("EVENT_TAX_MODE_NOT_ALLOWED", ApiMgmtErrorCode.EVENT_TAX_MODE_NOT_ALLOWED);
        ERROR_CODES.put("TAX_MODE_NOT_UPDATABLE_ON_PRODUCT", ApiMgmtErrorCode.TAX_MODE_NOT_UPDATABLE_ON_PRODUCT);
        ERROR_CODES.put("INVALID_PRODUCT_TAX_MODE", ApiMgmtErrorCode.INVALID_PRODUCT_TAX_MODE);
        ERROR_CODES.put("INVALID_EVENT_TAX_MODE", ApiMgmtErrorCode.INVALID_EVENT_TAX_MODE);
        ERROR_CODES.put("EVENT_UPDATE_TAX_MODE_INVALID_EVENT_STATUS", ApiMgmtErrorCode.EVENT_UPDATE_TAX_MODE_INVALID_EVENT_STATUS);
        ERROR_CODES.put("PRODUCT_UPDATE_TAX_MODE_INVALID_PRODUCT_STATUS", ApiMgmtErrorCode.PRODUCT_UPDATE_TAX_MODE_INVALID_PRODUCT_STATUS);
        ERROR_CODES.put("INVALID_LANGUAGE_CODE", ApiMgmtErrorCode.INVALID_LANGUAGE_CODE);
        ERROR_CODES.put("EMPTY_TRANSFER_TICKET_SESSION_LIST", ApiMgmtErrorCode.EMPTY_TRANSFER_TICKET_SESSION_LIST);
        ERROR_CODES.put("INVALID_TRANSFER_TICKET_SESSION_LIST", ApiMgmtErrorCode.INVALID_TRANSFER_TICKET_SESSION_LIST);
        ERROR_CODES.put("ENTITY_COMMUNICATIONS_ELEMENTS_NOT_FOUND", ApiMgmtErrorCode.ENTITY_COMMUNICATIONS_ELEMENTS_NOT_FOUND);
        ERROR_CODES.put("ENTITY_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND", ApiMgmtErrorCode.ENTITY_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND);
        ERROR_CODES.put("INVALID_VALIDATION_RULE_FOR_FIELD_TYPE", ApiMgmtErrorCode.INVALID_VALIDATION_RULE_FOR_FIELD_TYPE);

        //PACKS
        ERROR_CODES.put("PACK_NOT_FOUND", ApiMgmtChannelsErrorCode.PACK_NOT_FOUND);
        ERROR_CODES.put("INVALID_PACK_CONFIG", ApiMgmtChannelsErrorCode.INVALID_PACK_CONFIG);
        ERROR_CODES.put("PACK_RATE_NOT_FOUND", ApiMgmtChannelsErrorCode.PACK_RATE_NOT_FOUND);
        ERROR_CODES.put("PACK_CANNOT_BE_ENABLED_EVENT_HAS_NO_PUBLISHED_SESSIONS", ApiMgmtChannelsErrorCode.PACK_CANNOT_BE_ENABLED_EVENT_HAS_NO_PUBLISHED_SESSIONS);
        ERROR_CODES.put("PACK_ITEM_MUST_HAVE_A_CHANNEL_CURRENCY", ApiMgmtChannelsErrorCode.PACK_ITEM_MUST_HAVE_A_CHANNEL_CURRENCY);
        ERROR_CODES.put("PACK_ITEMS_MUST_HAVE_SAME_CURRENCY", ApiMgmtChannelsErrorCode.PACK_ITEMS_MUST_HAVE_SAME_CURRENCY);
        ERROR_CODES.put("PACK_CANNOT_BE_ENABLED_PRODUCT_IS_NOT_ACTIVE", ApiMgmtChannelsErrorCode.PACK_CANNOT_BE_ENABLED_PRODUCT_IS_NOT_ACTIVE);
        ERROR_CODES.put("PACK_CANNOT_BE_ENABLED_PRODUCT_WITHOUT_STOCK", ApiMgmtChannelsErrorCode.PACK_CANNOT_BE_ENABLED_PRODUCT_WITHOUT_STOCK);
        ERROR_CODES.put("PACK_CANNOT_BE_ENABLED_PRODUCT_IS_NOT_RELATED", ApiMgmtChannelsErrorCode.PACK_CANNOT_BE_ENABLED_PRODUCT_IS_NOT_RELATED);
        ERROR_CODES.put("PACK_ITEM_NOT_FOUND", ApiMgmtChannelsErrorCode.CHANNEL_PACK_ITEM_NOT_FOUND);
        ERROR_CODES.put("PACK_STATUS_INVALID", ApiMgmtChannelsErrorCode.PACK_STATUS_INVALID);
        ERROR_CODES.put("CHANNEL_PACK_RELATIONSHIP_INCONSISTENT", ApiMgmtChannelsErrorCode.CHANNEL_PACK_RELATIONSHIP_INCONSISTENT);
        ERROR_CODES.put("PACK_SALE_REQUEST_ALREADY_EXISTS", ApiMgmtChannelsErrorCode.PACK_SALE_REQUEST_ALREADY_EXISTS);
        ERROR_CODES.put("PACK_ITEM_PRICE_TYPES_INVALID_MAPPING", ApiMgmtSessionErrorCode.INVALID_TARGET_PRICE_TYPE_ID);
        ERROR_CODES.put("PACK_ITEM_SUBSETS_NOT_FOUND", ApiMgmtChannelsErrorCode.PACK_ITEM_SUBSET_NOT_FOUND);
        ERROR_CODES.put("PACK_ITEM_INVALID_FOR_SUBSETS", ApiMgmtChannelsErrorCode.PACK_ITEM_INVALID_FOR_SUBSETS);

        ERROR_CODES.put("BAD_REQUEST_PARAMETER", ApiMgmtErrorCode.BAD_REQUEST_PARAMETER);
        ERROR_CODES.put("QUESTION_NOT_FOUND", ApiMgmtErrorCode.QUESTION_NOT_FOUND);

		ERROR_CODES.put("PRODUCT_TICKET_TEMPLATE_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_TICKET_TEMPLATE_NOT_FOUND);
		ERROR_CODES.put("PRODUCT_TICKET_MODEL_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_TICKET_MODEL_NOT_FOUND);
		ERROR_CODES.put("PRODUCT_TICKET_TEMPLATE_NAME_ALREADY_SET",
				ApiMgmtErrorCode.PRODUCT_TICKET_TEMPLATE_NAME_ALREADY_SET);
		ERROR_CODES.put("SESSION_LIMIT_NOT_ALLOWED", ApiMgmtErrorCode.SESSION_LIMIT_NOT_ALLOWED);
        ERROR_CODES.put("PRODUCT_TICKET_LANGUAGE_LITERALS_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_TICKET_LANGUAGE_LITERALS_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_TICKET_DEFAULT_LITERALS_NOT_FOUND", ApiMgmtErrorCode.PRODUCT_TICKET_DEFAULT_LITERALS_NOT_FOUND);
        ERROR_CODES.put("RATE_EDITING_BLOCKED", ApiMgmtSessionErrorCode.RATE_EDITING_BLOCKED);
    }
}
