//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.user;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/user}entities"/>
 *         &lt;element name="corporateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fiscalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="supportsActivities" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="operatorShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.oneboxtm.es/user}channels" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/user}pointsOfSales" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/user}entityProfiles" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entities",
    "corporateName",
    "fiscalCode",
    "logo",
    "supportsActivities",
    "operatorShortName",
    "channels",
    "pointsOfSales",
    "entityProfiles"
})
@XmlRootElement(name = "entity")
public class Entity
    implements Serializable
{

    @XmlElement(required = true)
    protected Entities entities;
    @XmlElement(required = true)
    protected String corporateName;
    @XmlElement(required = true)
    protected String fiscalCode;
    @XmlElement(required = true)
    protected String logo;
    protected boolean supportsActivities;
    @XmlElement(required = true)
    protected String operatorShortName;
    protected Channels channels;
    protected PointsOfSales pointsOfSales;
    protected EntityProfiles entityProfiles;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link Entities }
     *     
     */
    public Entities getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entities }
     *     
     */
    public void setEntities(Entities value) {
        this.entities = value;
    }

    /**
     * Gets the value of the corporateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporateName() {
        return corporateName;
    }

    /**
     * Sets the value of the corporateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporateName(String value) {
        this.corporateName = value;
    }

    /**
     * Gets the value of the fiscalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiscalCode() {
        return fiscalCode;
    }

    /**
     * Sets the value of the fiscalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiscalCode(String value) {
        this.fiscalCode = value;
    }

    /**
     * Gets the value of the logo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogo() {
        return logo;
    }

    /**
     * Sets the value of the logo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogo(String value) {
        this.logo = value;
    }

    /**
     * Gets the value of the supportsActivities property.
     * 
     */
    public boolean isSupportsActivities() {
        return supportsActivities;
    }

    /**
     * Sets the value of the supportsActivities property.
     * 
     */
    public void setSupportsActivities(boolean value) {
        this.supportsActivities = value;
    }

    /**
     * Gets the value of the operatorShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorShortName() {
        return operatorShortName;
    }

    /**
     * Sets the value of the operatorShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorShortName(String value) {
        this.operatorShortName = value;
    }

    /**
     * Gets the value of the channels property.
     * 
     * @return
     *     possible object is
     *     {@link Channels }
     *     
     */
    public Channels getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channels }
     *     
     */
    public void setChannels(Channels value) {
        this.channels = value;
    }

    /**
     * Gets the value of the pointsOfSales property.
     * 
     * @return
     *     possible object is
     *     {@link PointsOfSales }
     *     
     */
    public PointsOfSales getPointsOfSales() {
        return pointsOfSales;
    }

    /**
     * Sets the value of the pointsOfSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointsOfSales }
     *     
     */
    public void setPointsOfSales(PointsOfSales value) {
        this.pointsOfSales = value;
    }

    /**
     * Gets the value of the entityProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link EntityProfiles }
     *     
     */
    public EntityProfiles getEntityProfiles() {
        return entityProfiles;
    }

    /**
     * Sets the value of the entityProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityProfiles }
     *     
     */
    public void setEntityProfiles(EntityProfiles value) {
        this.entityProfiles = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
