//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.user;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entityProfile" type="{http://www.oneboxtm.es/user}entityProfile" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityProfile"
})
@XmlRootElement(name = "entityProfiles")
public class EntityProfiles
    implements Serializable
{

    protected List<EntityProfile> entityProfile;

    /**
     * Gets the value of the entityProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityProfile }
     * 
     * 
     */
    public List<EntityProfile> getEntityProfile() {
        if (entityProfile == null) {
            entityProfile = new ArrayList<EntityProfile>();
        }
        return this.entityProfile;
    }

    /**
     * Sets the value of the entityProfile property.
     * 
     * @param entityProfile
     *     allowed object is
     *     {@link EntityProfile }
     *     
     */
    public void setEntityProfile(List<EntityProfile> entityProfile) {
        this.entityProfile = entityProfile;
    }

}
