export const defaultTicketTemplateLiterals = {
    warningDialogMessage: 'TICKET_TEMPLATE.UPDATE_DEFAULT_TPL_WARNING_MESSAGE',
    warningDialogTitle: 'TITLES.TICKET_TEMPLATE.UPDATE_DEFAULT_TPL_WARNING',
    successMessageRemove: 'TICKET_TEMPLATE.REMOVE_DEFAULT_TPL_SUCCESS_MESSAGE',
    successMessageUpdate: 'TICKET_TEMPLATE.UPDATE_DEFAULT_TPL_SUCCESS_MESSAGE',
    tooltipDisabledReason: 'TICKET_TEMPLATE.UPDATE_DEFAULT_TPL_DISABLED_TOOLTIP',
    tooltipInfo: 'TICKET_TEMPLATE.UPDATE_DEFAULT_TPL_TOOLTIP'
};
