post:
  x-internal: true
  summary: Upsert product delivery points relation
  description: Upsert product delivery points relation
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      description: The Product ID
      schema:
        type: integer
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/upsert-products-delivery-point-relation.yml
  responses:
    '201':
      description: Product delivery point relation has been created successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

get:
  x-internal: true
  summary: Search product delivery point relations
  description: Search product delivery point relations
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      description: The Product ID
      schema:
        type: integer
      required: true
    - in: query
      name: limit
      description: The pagination limit
      schema:
        type: integer
      required: false
    - in: query
      name: offset
      description: The pagination offset
      schema:
        type: integer
      required: false
  responses:
    '200':
      description: Search a list of product delivery point relations
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-delivery-point-relations.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
