get:
  x-internal: true
  summary: Get product event delivery points
  description: Get product event delivery points
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
  responses:
    '200':
      description: Get list of product event delivery points
      content:
        application/json:
          schema:
            additionalProperties: false
            $ref: ../../models/products/product-event-delivery-points.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  x-internal: true
  summary: Update product event delivery points
  description: Update product event delivery points
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: Event ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/update-product-event-delivery-points.yml
  responses:
    '200':
      description: Product event delivery points has been updated successfully
      content:
        application/json:
          schema:
            additionalProperties: false
            $ref: ../../models/products/product-event-delivery-points.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

