post:
  x-internal: true
  summary: Create product
  description: Creates a new product in status INACTIVE and returns it's id
  security:
    - OAuth2: [ 'ROLE_EVN_MGR', 'ROLE_OPR_MGR' ]
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - entity_id
            - producer_id
            - name
            - stock_type
            - product_type
          properties:
            entity_id:
              type: integer
              description: Entity ID
            producer_id:
              type: integer
              description: Producer ID
            name:
              type: string
              description: Product name
            stock_type:
              $ref: '../../models/products/product-stock-type.yml'
            product_type:
              type: string
              description: Product type name
              enum:
                - SIMPLE
                - VARIANT
            currency_code:
              type: string
              description: Product currency code
  responses:
    '201':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            required:
              - id
            properties:
              id:
                type: integer
                format: int64
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

get:
  x-internal: true
  summary: Search Products
  description: Search Products
  security:
    - OAuth2: [ 'ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS' ]
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: query
      name: entity_id
      description: The Product entity
      schema:
        type: integer
      required: false
    - in: query
      name: q
      description: Filter by name
      schema:
        type: string
      required: false
    - in: query
      name: stock_type
      description: The Product stock type
      schema:
        type: array
        items:
          $ref: '../../models/products/product-stock-type.yml'
      required: false
    - in: query
      name: product_type
      description: The Product type
      schema:
        type: array
        items:
          type: string
          enum:
            - SIMPLE
            - VARIANT
      required: false
    - in: query
      name: product_state
      description: The Product state
      schema:
        type: array
        items:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
      required: false
    - in: query
      name: currency_code
      description: The product currency code
      schema:
        type: string
      required: false
    - in: query
      name: event_ids
      description: The events related with the product
      schema:
        type: string
      required: false
    - in: query
      name: event_session_selection_type
      description: The session selection type for an event related with the product
      schema:
        type: array
        items:
          type: string
          enum:
            - ALL
            - RESTRICTED
      required: false
    - in: query
      name: session_ids
      description: The sessions related with the product
      schema:
        type: string
      required: false
    - in: query
      name: limit
      description: The pagination limit
      schema:
        type: integer
      required: false
    - in: query
      name: offset
      description: The pagination offset
      schema:
        type: integer
      required: false
    - in: query
      name: sort
      description: Sorting by name with format field:[asc|desc]. For example 'name:asc'
      schema:
        type: string
      required: false
  responses:
    '200':
      description: Search a list of product delivery points
      content:
        application/json:
          schema:
            $ref: ../../models/products/products.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
