get:
   x-internal: true
   summary: Get product promotion
   description: ''
   security:
     - OAuth2: ['ROLE_CNL_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
   tags:
   - Product Promotions
   parameters:
   -  in: header
      name: Authorization
      description: Bearer Token
      schema:
         type: string
      required: true
   -  in: path
      name: productId
      schema:
         type: integer
         format: int64
      required: true
      description: Product ID
   -  in: path
      name: promotionId
      schema:
         type: integer
         format: int64
      required: true
      description: Promotion ID
   responses:
      '200':
         description: 'Successful response'
         content:
            application/json:
               schema:
                  $ref: ../../models/products/product-promotion.yml
      '400':
         description: Bad request
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '401':
         description: Unauthorized
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error-auth.yml
      '403':
         description: Forbidden
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '404':
         description: Not found
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '500':
         description: Internal server error
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
put:
   x-internal: true
   summary: Update product promotion
   description: ''
   security:
     - OAuth2: ['ROLE_CNL_MGR', 'ROLE_OPR_MGR']
   tags:
   - Product Promotions
   parameters:
   -  in: header
      name: Authorization
      description: Bearer Token
      schema:
         type: string
      required: true
   -  in: path
      name: productId
      schema:
         type: integer
         format: int64
      required: true
      description: Product ID
   -  in: path
      name: promotionId
      schema:
         type: integer
         format: int64
      required: true
      description: Promotion ID
   requestBody:
      required: true
      content:
         application/json:
            schema:
               $ref: ../../models/products/product-promotion-update.yml
   responses:
      '204':
         description: Event promotion update succesfully.
      '400':
         description: Bad request
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '401':
         description: Unauthorized
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error-auth.yml
      '403':
         description: Forbidden
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '404':
         description: Not found
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '500':
         description: Internal server error
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
delete:
   x-internal: true
   summary: Delete promotion
   description: ''
   security:
     - OAuth2: ['ROLE_CNL_MGR', 'ROLE_OPR_MGR']
   tags:
   - Product Promotions
   parameters:
   -  in: header
      name: Authorization
      description: Bearer Token
      schema:
         type: string
      required: true
   -  in: path
      name: productId
      schema:
         type: integer
         format: int64
      required: true
      description: Product ID
   -  in: path
      name: promotionId
      schema:
         type: integer
         format: int64
      required: true
      description: Promotion ID
   responses:
      '204':
         description: Promotion deleted
      '400':
         description: bad request
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '401':
         description: invalid token
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error-auth.yml
      '403':
         description: unauthorized
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
      '500':
         description: Internal server error
         content:
            application/json:
               schema:
                  $ref: ../../models/common/error.yml
