get:
  x-internal: true
  summary: Get Product delivery detail by product ID
  description: Get product delivery detail by product id
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
  responses:
    '200':
      description: Product delivery information
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-delivery.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  x-internal: true
  summary: Update product delivery detail
  description: Update product delivery detail
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/product-delivery.yml
  responses:
    '200':
      description: Product channels has been updated successfully
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            required:
              - delivery_type
              - start_time_unit
              - start_time_value
              - end_time_unit
              - end_time_value
            properties:
              delivery_type:
                type: string
                enum:
                  - SESSION
                  - PURCHASE
                description: Product delivery type
              start_time_unit:
                type: string
                enum:
                  - MINUTES
                  - HOURS
                  - DAYS
                  - WEEKS
                  - MONTHS
                description: Delivery start time unit
              start_time_value:
                type: integer
                description: Delivery start time value
              end_time_unit:
                type: string
                enum:
                  - MINUTES
                  - HOURS
                  - DAYS
                  - WEEKS
                  - MONTHS
                description: Delivery end time unit
              end_time_value:
                type: integer
                description: Delivery end time value
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

