get:
  x-internal: true
  summary: Get Product event sessions
  description: Get product event sessions overrides
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: path
      name: eventId
      schema:
        type: integer
      required: true
      description: Event ID
    - in: query
      name: start_date
      description: Filter sessions for start_date with date-time format. Optional operators could be used as prefix of value with ':' separator (url encoded as ``%3A``). Supported operators are ``eq``, ``ne``, ``gt``, ``gte``, ``lt``, ``lte``
      example: eq:2019-01-01T08:00:00Z
      style: form
      schema:
        type: array
        items:
          type: string
    - in: query
      name: has_override
      schema:
        type: boolean
      description: Filter sessions with any applied override
    - in: query
      name: q
      description: Free search for sessions by name
      schema:
        type: string
    - in: query
      name: limit
      schema:
        type: integer
      description: Limit (default 50, max 1000)
    - in: query
      name: offset
      schema:
        type: integer
      description: Offset (default 0)
  responses:
    '200':
      description: Get list of product event sessions
      content:
        application/json:
          schema:
            additionalProperties: false
            type: object
            properties:
              metadata:
                $ref: ../../models/common/metadata.yml
              data:
                $ref: ../../models/products/product-session.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
