get:
  x-internal: true
  summary: Get product surcharges
  description: Get all surcharges of a product
  security:
    - OAuth2:
        - 'ROLE_EVN_MGR'
        - 'ROLE_OPR_MGR'
        - 'ROLE_ENT_ANS'
        - 'ROLE_OPR_ANS'
  tags:
    - Product surcharges
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: query
      name: type
      description: Type of surcharge
      schema:
        $ref: '../../models/surcharges/product-surcharge-type.yml'
  responses:
    '200':
      description: Get product surcharges
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                type:
                  $ref: '../../models/surcharges/product-surcharge-type.yml'
                ranges:
                  type: array
                  description: There must be a range with a from value of 0
                  items:
                    $ref: '../../models/surcharges/surcharge-get.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  x-internal: true
  summary: Set product surcharges
  description: Replace product surcharges if they exist previously or create it if not
  security:
    - OAuth2:
        - 'ROLE_EVN_MGR'
        - 'ROLE_OPR_MGR'
  tags:
    - Product surcharges
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            required:
              - type
              - ranges
            properties:
              type:
                $ref: '../../models/surcharges/product-surcharge-type.yml'
              ranges:
                type: array
                description: There must be a range with a from value of 0
                items:
                  $ref: '../../models/surcharges/surcharge-post.yml'
  responses:
    '204':
      description: Surcharge added successfully.
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '409':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml