get:
  x-internal: true
  summary: Get product ticket contents
  description: 'Obtain a list of key/value pair for product literals'
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
    - in: path
      name: language
      schema:
        type: string
      required: true
      description: Language ID
  responses:
    '200':
      description: 'Successful response'
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-attribute-text-contents.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  x-internal: true
  summary: Create or update a product literals ticket content
  description: 'Create or update a list of key/value pair product literals'
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - Products
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
    - in: path
      name: language
      schema:
        type: string
      required: true
      description: Language ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/product-attribute-text-contents.yml
  responses:
    '204':
      description: Text content created or updated
    '400':
      description: bad request
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '401':
      description: invalid token
      content:
        application/json:
          schema:
            $ref: '../../models/common/error-auth.yml'
    '403':
      description: unauthorized
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'

    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
