//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.cashregister;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/cashregister}cashRegisterPayment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cashRegisterPayment"
})
@XmlRootElement(name = "cashRegisterPayments")
public class CashRegisterPayments
    implements Serializable
{

    protected List<CashRegisterPayment> cashRegisterPayment;

    /**
     * Gets the value of the cashRegisterPayment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashRegisterPayment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashRegisterPayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashRegisterPayment }
     * 
     * 
     */
    public List<CashRegisterPayment> getCashRegisterPayment() {
        if (cashRegisterPayment == null) {
            cashRegisterPayment = new ArrayList<CashRegisterPayment>();
        }
        return this.cashRegisterPayment;
    }

    /**
     * Sets the value of the cashRegisterPayment property.
     * 
     * @param cashRegisterPayment
     *     allowed object is
     *     {@link CashRegisterPayment }
     *     
     */
    public void setCashRegisterPayment(List<CashRegisterPayment> cashRegisterPayment) {
        this.cashRegisterPayment = cashRegisterPayment;
    }

}
