//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.cashregister;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.cashregister package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.cashregister
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CashRegisterSummary }
     * 
     */
    public CashRegisterSummary createCashRegisterSummary() {
        return new CashRegisterSummary();
    }

    /**
     * Create an instance of {@link LineCashRegisterSummary }
     * 
     */
    public LineCashRegisterSummary createLineCashRegisterSummary() {
        return new LineCashRegisterSummary();
    }

    /**
     * Create an instance of {@link CashRegisterMethod }
     * 
     */
    public CashRegisterMethod createCashRegisterMethod() {
        return new CashRegisterMethod();
    }

    /**
     * Create an instance of {@link CashSummaryZpl }
     * 
     */
    public CashSummaryZpl createCashSummaryZpl() {
        return new CashSummaryZpl();
    }

    /**
     * Create an instance of {@link CashRegisterPayment }
     * 
     */
    public CashRegisterPayment createCashRegisterPayment() {
        return new CashRegisterPayment();
    }

    /**
     * Create an instance of {@link CashRegisterPayments }
     * 
     */
    public CashRegisterPayments createCashRegisterPayments() {
        return new CashRegisterPayments();
    }

    /**
     * Create an instance of {@link CashSummaryPDF }
     * 
     */
    public CashSummaryPDF createCashSummaryPDF() {
        return new CashSummaryPDF();
    }

}
