//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.venuebridge;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for Aforo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Aforo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoTemporada" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codigoAforo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Aforo", propOrder = {
    "codigoTemporada",
    "codigoAforo"
})
public class Aforo
    implements Serializable
{

    protected int codigoTemporada;
    protected int codigoAforo;

    /**
     * Gets the value of the codigoTemporada property.
     * 
     */
    public int getCodigoTemporada() {
        return codigoTemporada;
    }

    /**
     * Sets the value of the codigoTemporada property.
     * 
     */
    public void setCodigoTemporada(int value) {
        this.codigoTemporada = value;
    }

    /**
     * Gets the value of the codigoAforo property.
     * 
     */
    public int getCodigoAforo() {
        return codigoAforo;
    }

    /**
     * Sets the value of the codigoAforo property.
     * 
     */
    public void setCodigoAforo(int value) {
        this.codigoAforo = value;
    }

}
