//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.venuebridge;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creditCardType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="creditCardType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MASTERCARD"/>
 *     &lt;enumeration value="VISA"/>
 *     &lt;enumeration value="VISA_ELECTRON"/>
 *     &lt;enumeration value="AMERICAN_EXPRESS"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "creditCardType")
@XmlEnum
public enum CreditCardType {

    MASTERCARD,
    VISA,
    VISA_ELECTRON,
    AMERICAN_EXPRESS,
    OTHER;

    public String value() {
        return name();
    }

    public static CreditCardType fromValue(String v) {
        return valueOf(v);
    }

}
