//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.venuebridge;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for DatosLocalidad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosLocalidad">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoBarras" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoCliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoPrecio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="importeLocalidad" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="codigoAcceso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoPuerta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoBoca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jornadaPartido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoZona" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="filaAsiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numAsiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idExterno" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="listaParametros" type="{http://www.oneboxtm.es/ns/venuebridge}ParametroOperacion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="codigoUsuario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoUsuario" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosLocalidad", propOrder = {
    "codigoBarras",
    "tipoCliente",
    "codigoPrecio",
    "importeLocalidad",
    "codigoAcceso",
    "codigoPuerta",
    "codigoBoca",
    "jornadaPartido",
    "codigoZona",
    "filaAsiento",
    "numAsiento",
    "idExterno",
    "listaParametros",
    "codigoUsuario",
    "tipoUsuario"
})
public class DatosLocalidad
    implements Serializable
{

    @XmlElement(required = true)
    protected String codigoBarras;
    @XmlElement(required = true)
    protected String tipoCliente;
    protected int codigoPrecio;
    protected float importeLocalidad;
    @XmlElement(required = true)
    protected String codigoAcceso;
    @XmlElement(required = true)
    protected String codigoPuerta;
    @XmlElement(required = true)
    protected String codigoBoca;
    @XmlElement(required = true)
    protected String jornadaPartido;
    protected int codigoZona;
    @XmlElement(required = true)
    protected String filaAsiento;
    @XmlElement(required = true)
    protected String numAsiento;
    protected int idExterno;
    protected List<ParametroOperacion> listaParametros;
    @XmlElement(required = true)
    protected String codigoUsuario;
    protected byte tipoUsuario;

    /**
     * Gets the value of the codigoBarras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoBarras() {
        return codigoBarras;
    }

    /**
     * Sets the value of the codigoBarras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoBarras(String value) {
        this.codigoBarras = value;
    }

    /**
     * Gets the value of the tipoCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCliente() {
        return tipoCliente;
    }

    /**
     * Sets the value of the tipoCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCliente(String value) {
        this.tipoCliente = value;
    }

    /**
     * Gets the value of the codigoPrecio property.
     * 
     */
    public int getCodigoPrecio() {
        return codigoPrecio;
    }

    /**
     * Sets the value of the codigoPrecio property.
     * 
     */
    public void setCodigoPrecio(int value) {
        this.codigoPrecio = value;
    }

    /**
     * Gets the value of the importeLocalidad property.
     * 
     */
    public float getImporteLocalidad() {
        return importeLocalidad;
    }

    /**
     * Sets the value of the importeLocalidad property.
     * 
     */
    public void setImporteLocalidad(float value) {
        this.importeLocalidad = value;
    }

    /**
     * Gets the value of the codigoAcceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoAcceso() {
        return codigoAcceso;
    }

    /**
     * Sets the value of the codigoAcceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoAcceso(String value) {
        this.codigoAcceso = value;
    }

    /**
     * Gets the value of the codigoPuerta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoPuerta() {
        return codigoPuerta;
    }

    /**
     * Sets the value of the codigoPuerta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoPuerta(String value) {
        this.codigoPuerta = value;
    }

    /**
     * Gets the value of the codigoBoca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoBoca() {
        return codigoBoca;
    }

    /**
     * Sets the value of the codigoBoca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoBoca(String value) {
        this.codigoBoca = value;
    }

    /**
     * Gets the value of the jornadaPartido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJornadaPartido() {
        return jornadaPartido;
    }

    /**
     * Sets the value of the jornadaPartido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJornadaPartido(String value) {
        this.jornadaPartido = value;
    }

    /**
     * Gets the value of the codigoZona property.
     * 
     */
    public int getCodigoZona() {
        return codigoZona;
    }

    /**
     * Sets the value of the codigoZona property.
     * 
     */
    public void setCodigoZona(int value) {
        this.codigoZona = value;
    }

    /**
     * Gets the value of the filaAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilaAsiento() {
        return filaAsiento;
    }

    /**
     * Sets the value of the filaAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilaAsiento(String value) {
        this.filaAsiento = value;
    }

    /**
     * Gets the value of the numAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumAsiento() {
        return numAsiento;
    }

    /**
     * Sets the value of the numAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumAsiento(String value) {
        this.numAsiento = value;
    }

    /**
     * Gets the value of the idExterno property.
     * 
     */
    public int getIdExterno() {
        return idExterno;
    }

    /**
     * Sets the value of the idExterno property.
     * 
     */
    public void setIdExterno(int value) {
        this.idExterno = value;
    }

    /**
     * Gets the value of the listaParametros property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaParametros property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaParametros().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParametroOperacion }
     * 
     * 
     */
    public List<ParametroOperacion> getListaParametros() {
        if (listaParametros == null) {
            listaParametros = new ArrayList<ParametroOperacion>();
        }
        return this.listaParametros;
    }

    /**
     * Gets the value of the codigoUsuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoUsuario() {
        return codigoUsuario;
    }

    /**
     * Sets the value of the codigoUsuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoUsuario(String value) {
        this.codigoUsuario = value;
    }

    /**
     * Gets the value of the tipoUsuario property.
     * 
     */
    public byte getTipoUsuario() {
        return tipoUsuario;
    }

    /**
     * Sets the value of the tipoUsuario property.
     * 
     */
    public void setTipoUsuario(byte value) {
        this.tipoUsuario = value;
    }

    /**
     * Sets the value of the listaParametros property.
     * 
     * @param listaParametros
     *     allowed object is
     *     {@link ParametroOperacion }
     *     
     */
    public void setListaParametros(List<ParametroOperacion> listaParametros) {
        this.listaParametros = listaParametros;
    }

}
