//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.venuebridge;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="retorno" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="estat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcioEstat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "retorno",
    "estat",
    "descripcioEstat",
    "valor"
})
@XmlRootElement(name = "ImprimirEntradasResponse")
public class ImprimirEntradasResponse
    implements Serializable
{

    protected int retorno;
    @XmlElement(required = true)
    protected String estat;
    @XmlElement(required = true)
    protected String descripcioEstat;
    @XmlElement(required = true)
    protected String valor;

    /**
     * Gets the value of the retorno property.
     * 
     */
    public int getRetorno() {
        return retorno;
    }

    /**
     * Sets the value of the retorno property.
     * 
     */
    public void setRetorno(int value) {
        this.retorno = value;
    }

    /**
     * Gets the value of the estat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstat() {
        return estat;
    }

    /**
     * Sets the value of the estat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstat(String value) {
        this.estat = value;
    }

    /**
     * Gets the value of the descripcioEstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcioEstat() {
        return descripcioEstat;
    }

    /**
     * Sets the value of the descripcioEstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcioEstat(String value) {
        this.descripcioEstat = value;
    }

    /**
     * Gets the value of the valor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValor() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValor(String value) {
        this.valor = value;
    }

}
