//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.venuebridge;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoClub" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="deportes" type="{http://www.oneboxtm.es/ns/venuebridge}Deporte" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoClub",
    "deportes"
})
@XmlRootElement(name = "InformacionEventosClub")
public class InformacionEventosClub
    implements Serializable
{

    protected int codigoClub;
    @XmlElement(required = true)
    protected List<Deporte> deportes;

    /**
     * Gets the value of the codigoClub property.
     * 
     */
    public int getCodigoClub() {
        return codigoClub;
    }

    /**
     * Sets the value of the codigoClub property.
     * 
     */
    public void setCodigoClub(int value) {
        this.codigoClub = value;
    }

    /**
     * Gets the value of the deportes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deportes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeportes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Deporte }
     * 
     * 
     */
    public List<Deporte> getDeportes() {
        if (deportes == null) {
            deportes = new ArrayList<Deporte>();
        }
        return this.deportes;
    }

    /**
     * Sets the value of the deportes property.
     * 
     * @param deportes
     *     allowed object is
     *     {@link Deporte }
     *     
     */
    public void setDeportes(List<Deporte> deportes) {
        this.deportes = deportes;
    }

}
