//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.venuebridge;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoZona" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fila" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numeroAsiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="listaPartidos" type="{http://www.oneboxtm.es/ns/venuebridge}PartidoAsientoLibre" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigoZona",
    "fila",
    "numeroAsiento",
    "listaPartidos"
})
@XmlRootElement(name = "PartidosAsientoLibre")
public class PartidosAsientoLibre
    implements Serializable
{

    protected int codigoZona;
    @XmlElement(required = true)
    protected String fila;
    @XmlElement(required = true)
    protected String numeroAsiento;
    protected List<PartidoAsientoLibre> listaPartidos;

    /**
     * Gets the value of the codigoZona property.
     * 
     */
    public int getCodigoZona() {
        return codigoZona;
    }

    /**
     * Sets the value of the codigoZona property.
     * 
     */
    public void setCodigoZona(int value) {
        this.codigoZona = value;
    }

    /**
     * Gets the value of the fila property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFila() {
        return fila;
    }

    /**
     * Sets the value of the fila property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFila(String value) {
        this.fila = value;
    }

    /**
     * Gets the value of the numeroAsiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroAsiento() {
        return numeroAsiento;
    }

    /**
     * Sets the value of the numeroAsiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroAsiento(String value) {
        this.numeroAsiento = value;
    }

    /**
     * Gets the value of the listaPartidos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaPartidos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaPartidos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartidoAsientoLibre }
     * 
     * 
     */
    public List<PartidoAsientoLibre> getListaPartidos() {
        if (listaPartidos == null) {
            listaPartidos = new ArrayList<PartidoAsientoLibre>();
        }
        return this.listaPartidos;
    }

    /**
     * Sets the value of the listaPartidos property.
     * 
     * @param listaPartidos
     *     allowed object is
     *     {@link PartidoAsientoLibre }
     *     
     */
    public void setListaPartidos(List<PartidoAsientoLibre> listaPartidos) {
        this.listaPartidos = listaPartidos;
    }

}
