//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.venuebridge;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.math.BigDecimal;


/**
 * <p>Java class for PartidoAsientoLibre complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartidoAsientoLibre">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoPartido" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="activo" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="estado" type="{http://www.oneboxtm.es/ns/venuebridge}PartidoALType"/>
 *         &lt;element name="fechaEstado" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="importeRecaudado" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="competicion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoCompeticion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nombrePartido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fechaPartido" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="definitiva" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="jornada" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoTemporada" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codigoAforo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartidoAsientoLibre", propOrder = {
    "codigoPartido",
    "activo",
    "estado",
    "fechaEstado",
    "importeRecaudado",
    "competicion",
    "codigoCompeticion",
    "nombrePartido",
    "fechaPartido",
    "definitiva",
    "jornada",
    "codigoTemporada",
    "codigoAforo"
})
public class PartidoAsientoLibre
    implements Serializable
{

    protected int codigoPartido;
    protected boolean activo;
    @XmlElement(required = true)
    protected PartidoALType estado;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEstado;
    @XmlElement(required = true)
    protected BigDecimal importeRecaudado;
    @XmlElement(required = true)
    protected String competicion;
    protected int codigoCompeticion;
    @XmlElement(required = true)
    protected String nombrePartido;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaPartido;
    protected boolean definitiva;
    @XmlElement(required = true)
    protected String jornada;
    protected int codigoTemporada;
    protected int codigoAforo;

    /**
     * Gets the value of the codigoPartido property.
     * 
     */
    public int getCodigoPartido() {
        return codigoPartido;
    }

    /**
     * Sets the value of the codigoPartido property.
     * 
     */
    public void setCodigoPartido(int value) {
        this.codigoPartido = value;
    }

    /**
     * Gets the value of the activo property.
     * 
     */
    public boolean isActivo() {
        return activo;
    }

    /**
     * Sets the value of the activo property.
     * 
     */
    public void setActivo(boolean value) {
        this.activo = value;
    }

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link PartidoALType }
     *     
     */
    public PartidoALType getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartidoALType }
     *     
     */
    public void setEstado(PartidoALType value) {
        this.estado = value;
    }

    /**
     * Gets the value of the fechaEstado property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEstado() {
        return fechaEstado;
    }

    /**
     * Sets the value of the fechaEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEstado(XMLGregorianCalendar value) {
        this.fechaEstado = value;
    }

    /**
     * Gets the value of the importeRecaudado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImporteRecaudado() {
        return importeRecaudado;
    }

    /**
     * Sets the value of the importeRecaudado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImporteRecaudado(BigDecimal value) {
        this.importeRecaudado = value;
    }

    /**
     * Gets the value of the competicion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompeticion() {
        return competicion;
    }

    /**
     * Sets the value of the competicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompeticion(String value) {
        this.competicion = value;
    }

    /**
     * Gets the value of the codigoCompeticion property.
     * 
     */
    public int getCodigoCompeticion() {
        return codigoCompeticion;
    }

    /**
     * Sets the value of the codigoCompeticion property.
     * 
     */
    public void setCodigoCompeticion(int value) {
        this.codigoCompeticion = value;
    }

    /**
     * Gets the value of the nombrePartido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrePartido() {
        return nombrePartido;
    }

    /**
     * Sets the value of the nombrePartido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrePartido(String value) {
        this.nombrePartido = value;
    }

    /**
     * Gets the value of the fechaPartido property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaPartido() {
        return fechaPartido;
    }

    /**
     * Sets the value of the fechaPartido property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaPartido(XMLGregorianCalendar value) {
        this.fechaPartido = value;
    }

    /**
     * Gets the value of the definitiva property.
     * 
     */
    public boolean isDefinitiva() {
        return definitiva;
    }

    /**
     * Sets the value of the definitiva property.
     * 
     */
    public void setDefinitiva(boolean value) {
        this.definitiva = value;
    }

    /**
     * Gets the value of the jornada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJornada() {
        return jornada;
    }

    /**
     * Sets the value of the jornada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJornada(String value) {
        this.jornada = value;
    }

    /**
     * Gets the value of the codigoTemporada property.
     * 
     */
    public int getCodigoTemporada() {
        return codigoTemporada;
    }

    /**
     * Sets the value of the codigoTemporada property.
     * 
     */
    public void setCodigoTemporada(int value) {
        this.codigoTemporada = value;
    }

    /**
     * Gets the value of the codigoAforo property.
     * 
     */
    public int getCodigoAforo() {
        return codigoAforo;
    }

    /**
     * Sets the value of the codigoAforo property.
     * 
     */
    public void setCodigoAforo(int value) {
        this.codigoAforo = value;
    }

}
