additionalProperties: false
type: object
properties:
  product_id:
    type: integer
    format: int64
  entity:
    $ref: ../common/idname.yml
  producer:
    $ref: ../common/idname.yml
  tax:
    $ref: ../common/idname.yml
  surcharge_tax:
    $ref: ../common/idname.yml
  name:
    type: string
  product_type:
    type: string
    enum:
      - SIMPLE
      - VARIANT
  stock_type:
    $ref: ../../models/products/product-stock-type.yml
  product_state:
    type: string
    enum:
      - DELETED
      - ACTIVE
      - INACTIVE
  currency_code:
    type: string
  create_date:
    type: string
    format: date-time
  update_date:
    type: string
    format: date-time
  ui_settings:
    $ref: ../../models/products/product-ui-settings.yml
  settings:
    $ref: ../products/product-settings.yml
  has_sales:
    type: boolean