post:
  summary: create product variants
  description: Creates product variants with the combination between product attribute and their values
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Product ID'
  responses:
    '201':
      description: A JSON array of product variants id and names
      content:
        application/json:
          schema:
            $ref: '../../models/products/product-variants-created.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

get:
  x-internal: true
  summary: Get product variants
  description: Retrieves all product variants
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
    - in: query
      name: q
      description: Filter by name
      schema:
        type: string
      required: false
    - in: query
      name: limit
      description: The pagination limit
      schema:
        type: integer
      required: false
    - in: query
      name: offset
      description: The pagination offset
      schema:
        type: integer
      required: false
    - in: query
      name: status
      description: The Product variant status
      schema:
        type: array
        items:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
    - in: query
      name: ids
      schema:
        type: array
        items:
          type: number
        format: int64
      description: The product variant ids
    - in: query
      name: stock
      description: Product variants with or without stock (1 or 0)
      schema:
        type: number
  responses:
    '200':
      description: A list of product variants
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-variants.yml

    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
