get:
  summary: Get product variant
  description: Get a product variant
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
    - in: path
      name: variantId
      schema:
        type: integer
        format: int64
      required: true
      description: Variant ID
  responses:
    '200':
      description: 'Product variant details'
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-variant.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
put:
  summary: Update product variant
  description: Update a product variant
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
    - in: path
      name: variantId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/update-product-variants.yml
  responses:
    '204':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
