get:
  x-internal: true
  summary: Get product attributes by product ID
  description: Get product attributes by product id
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
  responses:
    '200':
      description: Get list of product attributes
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-attributes.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
post:
  x-internal: true
  summary: Create product attribute
  description: Create a new product attribute
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: Product ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/create-product-attribute.yml
  responses:
    '201':
      description: Product attribute has been created successfully
      content:
        application/json:
          schema:
            additionalProperties: false
            type: object
            properties:
              id:
                type: integer
                format: int64
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
