put:
  summary: Update product event session
  description: Update product event session stock for simple product with stock type ```SESSION_BOUNDED```
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Product ID'
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Event ID'
    - in: path
      name: sessionId
      schema:
        type: integer
        format: int64
      required: true
      description: Session ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/update-product-session.yml
  responses:
    '204':
      description: 'Successful response'
    '400':
      description: 'Bad request'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '404':
      description: 'Not found'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '409':
      description: 'Conflict'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '500':
      description: 'Internal server error'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'