get:
  summary: Returns a product channels list
  description: ''
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
  responses:
    '200':
      description: A JSON with product channels information
      content:
        application/json:
          schema:
            $ref: '../../models/products/products-channels.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  summary: Create product channels
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            channelIds:
              type: array
              items:
                type: integer
  responses:
    '201':
      description: Saved successfully
      content:
        application/json:
          schema:
            $ref: '../../models/products/products-channels-create-response.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

