get:
  summary: Returns a product channel sessions list
  description: ''
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: path
      name: channelId
      schema:
        type: integer
      required: true
      description: Channel ID
    - in: query
      name: offset
      schema:
        type: integer
    - in: query
      name: limit
      schema:
        type: integer
      description: Default 50. Maximum 1000.
    - in: query
      name: status
      schema:
        $ref: '../../models/sessions/session-status.yml'
      description: session state array
  responses:
    '200':
      description: A JSON with product channels information
      content:
        application/json:
          schema:
            $ref: '../../models/products/product-channel-sessions.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
