get:
  summary: Returns a list of product delivery points relations
  description: ''
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: path
      name: deliveryPointId
      schema:
        type: integer
      required: true
      description: Product delivery point relation ID
  responses:
    '200':
      description: A JSON with a product delivery points relation
      content:
        application/json:
          schema:
            $ref: '../../models/products/product-delivery-points-relations.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

