get:
  summary: 'Get product event sessions'
  description: 'Retrieve the sessions scope and configuration.'
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Product ID'
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Event ID'
    - in: query
      name: startDate
      description: Filter sessions for startDate with date-time format. Optional operators could be used as prefix of value with ':' separator (url encoded as ``%3A``). Supported operators are ``eq``, ``ne``, ``gt``, ``gte``, ``lt``, ``lte``
      example: eq:2019-01-01T08:00:00Z
      style: form
      schema:
        type: array
        items:
          type: string
    - in: query
      name: freeSearch
      description: Free search for sessions by name
      schema:
        type: string
    - in: query
      name: limit
      schema:
        type: integer
      description: Limit (default 50, max 1000)
    - in: query
      name: offset
      schema:
        type: integer
      description: Offset (default 0)
  responses:
    '200':
      description: Get list of product event sessions
      content:
        application/json:
          schema:
            $ref: ../../models/products/product-session.yml
    '400':
      description: 'Bad request'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '412':
      description: 'Precondition failed'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '404':
      description: 'Not found'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '500':
      description: 'Internal server error'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'

put:
  summary: 'Update product event sessions'
  description: 'Update the sessions scope and configuration.'
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Product ID'
    - in: path
      name: eventId
      schema:
        type: integer
        format: int64
      required: true
      description: 'Event ID'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../models/products/update-product-sessions.yml
  responses:
    '204':
      description: 'Successful response'
    '400':
      description: 'Bad request'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '404':
      description: 'Not found'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '500':
      description: 'Internal server error'
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'