put:
  summary: Update a product channel
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: path
      name: channelId
      schema:
        type: integer
      required: true
      description: Channel ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            checkoutSuggestionEnabled:
              type: boolean
            standaloneEnabled:
              type: boolean
  responses:
    '204':
      description: Product channel updated successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
delete:
  summary: Delete a product channel
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: path
      name: channelId
      schema:
        type: integer
      required: true
      description: Channel ID
  responses:
    '204':
      description: Deleted successfully
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
