get:
  summary: Returns a product events list
  description: ''
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
    - in: query
      name: eventIds
      schema:
        type: array
        items:
          type: integer
    - in: query
      name: sessionSelectionType
      schema:
        type: string
        enum:
          - ALL
          - RESTRICTED
    - in: query
      name: status
      schema:
        type: string
        enum:
          - ACTIVE
          - INACTIVE
          - DELETED
  responses:
    '200':
      description: A JSON with product events information
      content:
        application/json:
          schema:
            $ref: '../../models/products/product-events.yml'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

put:
  summary: Update product events
  tags:
    - Products
  parameters:
    - in: path
      name: productId
      schema:
        type: integer
      required: true
      description: Product ID
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            eventIds:
              type: array
              items:
                $ref: ../../models/products/update-product-event.yml
  responses:
    '204':
      description: Saved successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
