//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.venue;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/venue}link-price-zones"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/venue}link-sector" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="refId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetViewId" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="targetViewName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetViewVip" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "linkPriceZones",
    "linkSector"
})
@XmlRootElement(name = "link")
public class Link
    implements Serializable
{

    @XmlElement(name = "link-price-zones", required = true)
    protected LinkPriceZones linkPriceZones;
    @XmlElement(name = "link-sector", required = true)
    protected List<LinkSector> linkSector;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "refId", required = true)
    protected String refId;
    @XmlAttribute(name = "targetViewId", required = true)
    protected BigInteger targetViewId;
    @XmlAttribute(name = "targetViewName")
    protected String targetViewName;
    @XmlAttribute(name = "targetViewVip", required = true)
    protected boolean targetViewVip;

    /**
     * Gets the value of the linkPriceZones property.
     * 
     * @return
     *     possible object is
     *     {@link LinkPriceZones }
     *     
     */
    public LinkPriceZones getLinkPriceZones() {
        return linkPriceZones;
    }

    /**
     * Sets the value of the linkPriceZones property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkPriceZones }
     *     
     */
    public void setLinkPriceZones(LinkPriceZones value) {
        this.linkPriceZones = value;
    }

    /**
     * Gets the value of the linkSector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkSector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkSector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkSector }
     * 
     * 
     */
    public List<LinkSector> getLinkSector() {
        if (linkSector == null) {
            linkSector = new ArrayList<LinkSector>();
        }
        return this.linkSector;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the targetViewId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTargetViewId() {
        return targetViewId;
    }

    /**
     * Sets the value of the targetViewId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTargetViewId(BigInteger value) {
        this.targetViewId = value;
    }

    /**
     * Gets the value of the targetViewName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetViewName() {
        return targetViewName;
    }

    /**
     * Sets the value of the targetViewName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetViewName(String value) {
        this.targetViewName = value;
    }

    /**
     * Gets the value of the targetViewVip property.
     * 
     */
    public boolean isTargetViewVip() {
        return targetViewVip;
    }

    /**
     * Sets the value of the targetViewVip property.
     * 
     */
    public void setTargetViewVip(boolean value) {
        this.targetViewVip = value;
    }

    /**
     * Sets the value of the linkSector property.
     * 
     * @param linkSector
     *     allowed object is
     *     {@link LinkSector }
     *     
     */
    public void setLinkSector(List<LinkSector> linkSector) {
        this.linkSector = linkSector;
    }

}
