//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.venue;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.data_query.venue package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.data_query.venue
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Venue }
     * 
     */
    public Venue createVenue() {
        return new Venue();
    }

    /**
     * Create an instance of {@link Space }
     * 
     */
    public Space createSpace() {
        return new Space();
    }

    /**
     * Create an instance of {@link Sector }
     * 
     */
    public Sector createSector() {
        return new Sector();
    }

    /**
     * Create an instance of {@link SeatMap }
     * 
     */
    public SeatMap createSeatMap() {
        return new SeatMap();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link LinkPriceZones }
     * 
     */
    public LinkPriceZones createLinkPriceZones() {
        return new LinkPriceZones();
    }

    /**
     * Create an instance of {@link LinkSector }
     * 
     */
    public LinkSector createLinkSector() {
        return new LinkSector();
    }

    /**
     * Create an instance of {@link PriceZones }
     * 
     */
    public PriceZones createPriceZones() {
        return new PriceZones();
    }

    /**
     * Create an instance of {@link PriceZone }
     * 
     */
    public PriceZone createPriceZone() {
        return new PriceZone();
    }

    /**
     * Create an instance of {@link MatrixInfo }
     * 
     */
    public MatrixInfo createMatrixInfo() {
        return new MatrixInfo();
    }

    /**
     * Create an instance of {@link ExternalLink }
     * 
     */
    public ExternalLink createExternalLink() {
        return new ExternalLink();
    }

    /**
     * Create an instance of {@link CompleteMapStatus }
     * 
     */
    public CompleteMapStatus createCompleteMapStatus() {
        return new CompleteMapStatus();
    }

    /**
     * Create an instance of {@link ViewStatus }
     * 
     */
    public ViewStatus createViewStatus() {
        return new ViewStatus();
    }

    /**
     * Create an instance of {@link DayTypes }
     * 
     */
    public DayTypes createDayTypes() {
        return new DayTypes();
    }

    /**
     * Create an instance of {@link DayType }
     * 
     */
    public DayType createDayType() {
        return new DayType();
    }

    /**
     * Create an instance of {@link MapStatus }
     * 
     */
    public MapStatus createMapStatus() {
        return new MapStatus();
    }

    /**
     * Create an instance of {@link MatrixStatus }
     * 
     */
    public MatrixStatus createMatrixStatus() {
        return new MatrixStatus();
    }

    /**
     * Create an instance of {@link SeatExtendedStatus }
     * 
     */
    public SeatExtendedStatus createSeatExtendedStatus() {
        return new SeatExtendedStatus();
    }

    /**
     * Create an instance of {@link OrderInfo }
     * 
     */
    public OrderInfo createOrderInfo() {
        return new OrderInfo();
    }

    /**
     * Create an instance of {@link Calendar }
     * 
     */
    public Calendar createCalendar() {
        return new Calendar();
    }

    /**
     * Create an instance of {@link CalendarDays }
     * 
     */
    public CalendarDays createCalendarDays() {
        return new CalendarDays();
    }

    /**
     * Create an instance of {@link CalendarDay }
     * 
     */
    public CalendarDay createCalendarDay() {
        return new CalendarDay();
    }

    /**
     * Create an instance of {@link MatrixView }
     * 
     */
    public MatrixView createMatrixView() {
        return new MatrixView();
    }

    /**
     * Create an instance of {@link SeatsExtendedStatus }
     * 
     */
    public SeatsExtendedStatus createSeatsExtendedStatus() {
        return new SeatsExtendedStatus();
    }

    /**
     * Create an instance of {@link NameAndIdentifier }
     * 
     */
    public NameAndIdentifier createNameAndIdentifier() {
        return new NameAndIdentifier();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

}
