//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.venue;

import es.onebox.common.datasources.rest.dto.ns.customer.CustomerType;
import es.onebox.common.datasources.rest.dto.ns.purchase.order.OrderType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;


/**
 * <p>Java class for orderInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/customer}customer"/>
 *         &lt;element name="orderType" type="{http://www.oneboxtm.es/ns/purchase/order}orderType"/>
 *         &lt;element name="purchaseDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="channel" type="{http://www.oneboxtm.es/ns/data-query/venue}nameAndIdentifier"/>
 *         &lt;element name="entityChannel" type="{http://www.oneboxtm.es/ns/data-query/venue}nameAndIdentifier"/>
 *         &lt;element name="terminal" type="{http://www.oneboxtm.es/ns/data-query/venue}nameAndIdentifier"/>
 *         &lt;element name="pointSale" type="{http://www.oneboxtm.es/ns/data-query/venue}nameAndIdentifier"/>
 *         &lt;element name="sellerUser" type="{http://www.oneboxtm.es/ns/data-query/venue}user"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderInfo", propOrder = {
    "orderCode",
    "customer",
    "orderType",
    "purchaseDate",
    "channel",
    "entityChannel",
    "terminal",
    "pointSale",
    "sellerUser"
})
public class OrderInfo
    implements Serializable
{

    @XmlElement(required = true)
    protected String orderCode;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/customer", required = true)
    protected CustomerType customer;
    @XmlElement(required = true)
    protected OrderType orderType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar purchaseDate;
    @XmlElement(required = true)
    protected NameAndIdentifier channel;
    @XmlElement(required = true)
    protected NameAndIdentifier entityChannel;
    @XmlElement(required = true)
    protected NameAndIdentifier terminal;
    @XmlElement(required = true)
    protected NameAndIdentifier pointSale;
    @XmlElement(required = true)
    protected User sellerUser;

    /**
     * Gets the value of the orderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * Sets the value of the orderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderCode(String value) {
        this.orderCode = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     */
    public void setCustomer(CustomerType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link OrderType }
     *     
     */
    public OrderType getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderType }
     *     
     */
    public void setOrderType(OrderType value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurchaseDate(XMLGregorianCalendar value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link NameAndIdentifier }
     *     
     */
    public NameAndIdentifier getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameAndIdentifier }
     *     
     */
    public void setChannel(NameAndIdentifier value) {
        this.channel = value;
    }

    /**
     * Gets the value of the entityChannel property.
     * 
     * @return
     *     possible object is
     *     {@link NameAndIdentifier }
     *     
     */
    public NameAndIdentifier getEntityChannel() {
        return entityChannel;
    }

    /**
     * Sets the value of the entityChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameAndIdentifier }
     *     
     */
    public void setEntityChannel(NameAndIdentifier value) {
        this.entityChannel = value;
    }

    /**
     * Gets the value of the terminal property.
     * 
     * @return
     *     possible object is
     *     {@link NameAndIdentifier }
     *     
     */
    public NameAndIdentifier getTerminal() {
        return terminal;
    }

    /**
     * Sets the value of the terminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameAndIdentifier }
     *     
     */
    public void setTerminal(NameAndIdentifier value) {
        this.terminal = value;
    }

    /**
     * Gets the value of the pointSale property.
     * 
     * @return
     *     possible object is
     *     {@link NameAndIdentifier }
     *     
     */
    public NameAndIdentifier getPointSale() {
        return pointSale;
    }

    /**
     * Sets the value of the pointSale property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameAndIdentifier }
     *     
     */
    public void setPointSale(NameAndIdentifier value) {
        this.pointSale = value;
    }

    /**
     * Gets the value of the sellerUser property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getSellerUser() {
        return sellerUser;
    }

    /**
     * Sets the value of the sellerUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setSellerUser(User value) {
        this.sellerUser = value;
    }

}
