//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.venue;

import es.onebox.common.datasources.rest.dto.ns.data_query.places.NotNumberedAreas;
import es.onebox.common.datasources.rest.dto.ns.data_query.places.Seats;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/places}seats" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/places}notNumberedAreas" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seats",
    "notNumberedAreas"
})
@XmlRootElement(name = "price-zone")
public class PriceZone
    implements Serializable
{

    @XmlElement(namespace = "http://www.oneboxtm.es/ns/data-query/places")
    protected Seats seats;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/data-query/places")
    protected NotNumberedAreas notNumberedAreas;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the seats property.
     * 
     * @return
     *     possible object is
     *     {@link Seats }
     *     
     */
    public Seats getSeats() {
        return seats;
    }

    /**
     * Sets the value of the seats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Seats }
     *     
     */
    public void setSeats(Seats value) {
        this.seats = value;
    }

    /**
     * Gets the value of the notNumberedAreas property.
     * 
     * @return
     *     possible object is
     *     {@link NotNumberedAreas }
     *     
     */
    public NotNumberedAreas getNotNumberedAreas() {
        return notNumberedAreas;
    }

    /**
     * Sets the value of the notNumberedAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotNumberedAreas }
     *     
     */
    public void setNotNumberedAreas(NotNumberedAreas value) {
        this.notNumberedAreas = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
