//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.venue;

import es.onebox.common.datasources.rest.dto.ns.availability.PriceZonesStatus;
import es.onebox.common.datasources.rest.dto.ns.availability.Status;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/availability}status"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/availability}price-zones-status"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/venue}sector" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "priceZonesStatus",
    "sector"
})
@XmlRootElement(name = "viewStatus")
public class ViewStatus
    implements Serializable
{

    @XmlElement(namespace = "http://www.oneboxtm.es/ns/availability", required = true)
    protected Status status;
    @XmlElement(name = "price-zones-status", namespace = "http://www.oneboxtm.es/ns/availability", required = true)
    protected PriceZonesStatus priceZonesStatus;
    @XmlElement(required = true)
    protected List<Sector> sector;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the priceZonesStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PriceZonesStatus }
     *     
     */
    public PriceZonesStatus getPriceZonesStatus() {
        return priceZonesStatus;
    }

    /**
     * Sets the value of the priceZonesStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceZonesStatus }
     *     
     */
    public void setPriceZonesStatus(PriceZonesStatus value) {
        this.priceZonesStatus = value;
    }

    /**
     * Gets the value of the sector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sector }
     * 
     * 
     */
    public List<Sector> getSector() {
        if (sector == null) {
            sector = new ArrayList<Sector>();
        }
        return this.sector;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Sets the value of the sector property.
     * 
     * @param sector
     *     allowed object is
     *     {@link Sector }
     *     
     */
    public void setSector(List<Sector> sector) {
        this.sector = sector;
    }

}
