//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.session;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.data_query.session package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.data_query.session
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SessionsSearchInfo }
     * 
     */
    public SessionsSearchInfo createSessionsSearchInfo() {
        return new SessionsSearchInfo();
    }

    /**
     * Create an instance of {@link SessionSearchInfo }
     * 
     */
    public SessionSearchInfo createSessionSearchInfo() {
        return new SessionSearchInfo();
    }

    /**
     * Create an instance of {@link SessionBaseType }
     * 
     */
    public SessionBaseType createSessionBaseType() {
        return new SessionBaseType();
    }

    /**
     * Create an instance of {@link SeasonSessionInfo }
     * 
     */
    public SeasonSessionInfo createSeasonSessionInfo() {
        return new SeasonSessionInfo();
    }

    /**
     * Create an instance of {@link BlockingReasons }
     * 
     */
    public BlockingReasons createBlockingReasons() {
        return new BlockingReasons();
    }

    /**
     * Create an instance of {@link BlockingReason }
     * 
     */
    public BlockingReason createBlockingReason() {
        return new BlockingReason();
    }

    /**
     * Create an instance of {@link VisitorGroupConfig }
     * 
     */
    public VisitorGroupConfig createVisitorGroupConfig() {
        return new VisitorGroupConfig();
    }

    /**
     * Create an instance of {@link SessionRates }
     * 
     */
    public SessionRates createSessionRates() {
        return new SessionRates();
    }

    /**
     * Create an instance of {@link SessionRate }
     * 
     */
    public SessionRate createSessionRate() {
        return new SessionRate();
    }

    /**
     * Create an instance of {@link SessionMinPrice }
     * 
     */
    public SessionMinPrice createSessionMinPrice() {
        return new SessionMinPrice();
    }

    /**
     * Create an instance of {@link SessionMaxPrice }
     * 
     */
    public SessionMaxPrice createSessionMaxPrice() {
        return new SessionMaxPrice();
    }

    /**
     * Create an instance of {@link SessionsInfo }
     * 
     */
    public SessionsInfo createSessionsInfo() {
        return new SessionsInfo();
    }

    /**
     * Create an instance of {@link SessionInfo }
     * 
     */
    public SessionInfo createSessionInfo() {
        return new SessionInfo();
    }

    /**
     * Create an instance of {@link PromotionsDiscounts }
     * 
     */
    public PromotionsDiscounts createPromotionsDiscounts() {
        return new PromotionsDiscounts();
    }

    /**
     * Create an instance of {@link SessionProperties }
     * 
     */
    public SessionProperties createSessionProperties() {
        return new SessionProperties();
    }

    /**
     * Create an instance of {@link SessionViewMappings }
     * 
     */
    public SessionViewMappings createSessionViewMappings() {
        return new SessionViewMappings();
    }

    /**
     * Create an instance of {@link ViewMappingItem }
     * 
     */
    public ViewMappingItem createViewMappingItem() {
        return new ViewMappingItem();
    }

    /**
     * Create an instance of {@link SessionBasicInfo }
     * 
     */
    public SessionBasicInfo createSessionBasicInfo() {
        return new SessionBasicInfo();
    }

    /**
     * Create an instance of {@link SessionPresalesStatus }
     * 
     */
    public SessionPresalesStatus createSessionPresalesStatus() {
        return new SessionPresalesStatus();
    }

    /**
     * Create an instance of {@link SessionsBasicInfo }
     * 
     */
    public SessionsBasicInfo createSessionsBasicInfo() {
        return new SessionsBasicInfo();
    }

}
