//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.08.05 at 12:32:19 PM CEST
//


package es.onebox.common.datasources.rest.dto.ns.data_query.session;

import es.onebox.common.datasources.rest.dto.ns.availability.AvailabilityInfo;
import es.onebox.common.datasources.rest.dto.ns.availability.VisitorGroupAvailability;
import es.onebox.common.datasources.rest.dto.ns.communication.CommunicationElements;
import es.onebox.common.datasources.rest.dto.ns.communication.Image;
import es.onebox.common.datasources.rest.dto.ns.data_query.prices.ActivityTicketTypesAvailability;
import es.onebox.common.datasources.rest.dto.ns.data_query.prices.PriceZonesAvailability;
import es.onebox.common.datasources.rest.dto.ns.data_query.venue.Sector;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.oneboxtm.es/ns/data-query/session}sessionBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isGraphicVenue" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="nonGraphicImage" type="{http://www.oneboxtm.es/ns/communication}image"/&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/session}sessionMinPrice" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/session}sessionMaxPrice" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.oneboxtm.es/ns/data-query/prices}price-zones-availability" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.oneboxtm.es/ns/data-query/prices}activity-ticket-types-availability" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/availability}availability-info" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/communication}communication-elements" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/session}promotions-discounts" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/venue}sector" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/session}session-properties"/&gt;
 *         &lt;element ref="{http://www.oneboxtm.es/ns/availability}visitorGroupAvailability"/&gt;
 *         &lt;element name="mandatoryLogin" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ticketingPartit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "isGraphicVenue",
        "nonGraphicImage",
        "sessionMinPrice",
        "sessionMaxPrice",
        "priceZonesAvailability",
        "activityTicketTypesAvailability",
        "availabilityInfo",
        "communicationElements",
        "promotionsDiscounts",
        "sector",
        "sessionProperties",
        "visitorGroupAvailability",
        "mandatoryLogin",
        "ticketingPartit"
})
@XmlRootElement(name = "session-info")
public class SessionInfo
        extends SessionBaseType
        implements Serializable
{

    protected boolean isGraphicVenue;
    @XmlElement(required = true)
    protected Image nonGraphicImage;
    protected SessionMinPrice sessionMinPrice;
    protected SessionMaxPrice sessionMaxPrice;
    @XmlElement(name = "price-zones-availability", namespace = "http://www.oneboxtm.es/ns/data-query/prices")
    protected PriceZonesAvailability priceZonesAvailability;
    @XmlElement(name = "activity-ticket-types-availability", namespace = "http://www.oneboxtm.es/ns/data-query/prices")
    protected ActivityTicketTypesAvailability activityTicketTypesAvailability;
    @XmlElement(name = "availability-info", namespace = "http://www.oneboxtm.es/ns/availability")
    protected AvailabilityInfo availabilityInfo;
    @XmlElement(name = "communication-elements", namespace = "http://www.oneboxtm.es/ns/communication")
    protected CommunicationElements communicationElements;
    @XmlElement(name = "promotions-discounts")
    protected PromotionsDiscounts promotionsDiscounts;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/data-query/venue", required = true)
    protected List<Sector> sector;
    @XmlElement(name = "session-properties", required = true)
    protected SessionProperties sessionProperties;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/availability", required = true)
    protected VisitorGroupAvailability visitorGroupAvailability;
    protected boolean mandatoryLogin;
    @XmlElement(required = true)
    protected String ticketingPartit;

    /**
     * Gets the value of the isGraphicVenue property.
     *
     */
    public boolean isIsGraphicVenue() {
        return isGraphicVenue;
    }

    /**
     * Sets the value of the isGraphicVenue property.
     *
     */
    public void setIsGraphicVenue(boolean value) {
        this.isGraphicVenue = value;
    }

    /**
     * Gets the value of the nonGraphicImage property.
     *
     * @return
     *     possible object is
     *     {@link Image }
     *
     */
    public Image getNonGraphicImage() {
        return nonGraphicImage;
    }

    /**
     * Sets the value of the nonGraphicImage property.
     *
     * @param value
     *     allowed object is
     *     {@link Image }
     *
     */
    public void setNonGraphicImage(Image value) {
        this.nonGraphicImage = value;
    }

    /**
     * Gets the value of the sessionMinPrice property.
     *
     * @return
     *     possible object is
     *     {@link SessionMinPrice }
     *
     */
    public SessionMinPrice getSessionMinPrice() {
        return sessionMinPrice;
    }

    /**
     * Sets the value of the sessionMinPrice property.
     *
     * @param value
     *     allowed object is
     *     {@link SessionMinPrice }
     *
     */
    public void setSessionMinPrice(SessionMinPrice value) {
        this.sessionMinPrice = value;
    }

    /**
     * Gets the value of the sessionMaxPrice property.
     *
     * @return
     *     possible object is
     *     {@link SessionMaxPrice }
     *
     */
    public SessionMaxPrice getSessionMaxPrice() {
        return sessionMaxPrice;
    }

    /**
     * Sets the value of the sessionMaxPrice property.
     *
     * @param value
     *     allowed object is
     *     {@link SessionMaxPrice }
     *
     */
    public void setSessionMaxPrice(SessionMaxPrice value) {
        this.sessionMaxPrice = value;
    }

    /**
     * Gets the value of the priceZonesAvailability property.
     *
     * @return
     *     possible object is
     *     {@link PriceZonesAvailability }
     *
     */
    public PriceZonesAvailability getPriceZonesAvailability() {
        return priceZonesAvailability;
    }

    /**
     * Sets the value of the priceZonesAvailability property.
     *
     * @param value
     *     allowed object is
     *     {@link PriceZonesAvailability }
     *
     */
    public void setPriceZonesAvailability(PriceZonesAvailability value) {
        this.priceZonesAvailability = value;
    }

    /**
     * Gets the value of the activityTicketTypesAvailability property.
     *
     * @return
     *     possible object is
     *     {@link ActivityTicketTypesAvailability }
     *
     */
    public ActivityTicketTypesAvailability getActivityTicketTypesAvailability() {
        return activityTicketTypesAvailability;
    }

    /**
     * Sets the value of the activityTicketTypesAvailability property.
     *
     * @param value
     *     allowed object is
     *     {@link ActivityTicketTypesAvailability }
     *
     */
    public void setActivityTicketTypesAvailability(ActivityTicketTypesAvailability value) {
        this.activityTicketTypesAvailability = value;
    }

    /**
     * Gets the value of the availabilityInfo property.
     *
     * @return
     *     possible object is
     *     {@link AvailabilityInfo }
     *
     */
    public AvailabilityInfo getAvailabilityInfo() {
        return availabilityInfo;
    }

    /**
     * Sets the value of the availabilityInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link AvailabilityInfo }
     *
     */
    public void setAvailabilityInfo(AvailabilityInfo value) {
        this.availabilityInfo = value;
    }

    /**
     * Gets the value of the communicationElements property.
     *
     * @return
     *     possible object is
     *     {@link CommunicationElements }
     *
     */
    public CommunicationElements getCommunicationElements() {
        return communicationElements;
    }

    /**
     * Sets the value of the communicationElements property.
     *
     * @param value
     *     allowed object is
     *     {@link CommunicationElements }
     *
     */
    public void setCommunicationElements(CommunicationElements value) {
        this.communicationElements = value;
    }

    /**
     * Gets the value of the promotionsDiscounts property.
     *
     * @return
     *     possible object is
     *     {@link PromotionsDiscounts }
     *
     */
    public PromotionsDiscounts getPromotionsDiscounts() {
        return promotionsDiscounts;
    }

    /**
     * Sets the value of the promotionsDiscounts property.
     *
     * @param value
     *     allowed object is
     *     {@link PromotionsDiscounts }
     *
     */
    public void setPromotionsDiscounts(PromotionsDiscounts value) {
        this.promotionsDiscounts = value;
    }

    /**
     * Gets the value of the sector property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sector property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSector().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sector }
     *
     *
     */
    public List<Sector> getSector() {
        if (sector == null) {
            sector = new ArrayList<Sector>();
        }
        return this.sector;
    }

    /**
     * Gets the value of the sessionProperties property.
     *
     * @return
     *     possible object is
     *     {@link SessionProperties }
     *
     */
    public SessionProperties getSessionProperties() {
        return sessionProperties;
    }

    /**
     * Sets the value of the sessionProperties property.
     *
     * @param value
     *     allowed object is
     *     {@link SessionProperties }
     *
     */
    public void setSessionProperties(SessionProperties value) {
        this.sessionProperties = value;
    }

    /**
     * Gets the value of the visitorGroupAvailability property.
     *
     * @return
     *     possible object is
     *     {@link VisitorGroupAvailability }
     *
     */
    public VisitorGroupAvailability getVisitorGroupAvailability() {
        return visitorGroupAvailability;
    }

    /**
     * Sets the value of the visitorGroupAvailability property.
     *
     * @param value
     *     allowed object is
     *     {@link VisitorGroupAvailability }
     *
     */
    public void setVisitorGroupAvailability(VisitorGroupAvailability value) {
        this.visitorGroupAvailability = value;
    }

    /**
     * Gets the value of the mandatoryLogin property.
     *
     */
    public boolean isMandatoryLogin() {
        return mandatoryLogin;
    }

    /**
     * Sets the value of the mandatoryLogin property.
     *
     */
    public void setMandatoryLogin(boolean value) {
        this.mandatoryLogin = value;
    }

    /**
     * Gets the value of the ticketingPartit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTicketingPartit() {
        return ticketingPartit;
    }

    /**
     * Sets the value of the ticketingPartit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTicketingPartit(String value) {
        this.ticketingPartit = value;
    }

    /**
     * Sets the value of the sector property.
     *
     * @param sector
     *     allowed object is
     *     {@link Sector }
     *
     */
    public void setSector(List<Sector> sector) {
        this.sector = sector;
    }

}
