//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.session;

import es.onebox.common.datasources.rest.dto.ns.availability.AvailabilityInfo;
import es.onebox.common.datasources.rest.dto.ns.availability.VisitorGroupAvailability;
import es.onebox.common.datasources.rest.dto.ns.data_query.prices.ActivityTicketTypesAvailability;
import es.onebox.common.datasources.rest.dto.ns.data_query.prices.PriceZonesAvailability;
import es.onebox.common.datasources.rest.dto.ns.data_query.venue.Sector;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oneboxtm.es/ns/data-query/session}sessionBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/availability}availability-info" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/session}sessionMinPrice" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/session}sessionMaxPrice" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.oneboxtm.es/ns/data-query/prices}price-zones-availability" minOccurs="0"/>
 *           &lt;element ref="{http://www.oneboxtm.es/ns/data-query/prices}activity-ticket-types-availability" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/venue}sector" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/availability}visitorGroupAvailability" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "availabilityInfo",
    "sessionMinPrice",
    "sessionMaxPrice",
    "priceZonesAvailability",
    "activityTicketTypesAvailability",
    "sector",
    "visitorGroupAvailability"
})
@XmlRootElement(name = "session-search-info")
public class SessionSearchInfo
    extends SessionBaseType
    implements Serializable
{

    @XmlElement(name = "availability-info", namespace = "http://www.oneboxtm.es/ns/availability")
    protected AvailabilityInfo availabilityInfo;
    protected SessionMinPrice sessionMinPrice;
    protected SessionMaxPrice sessionMaxPrice;
    @XmlElement(name = "price-zones-availability", namespace = "http://www.oneboxtm.es/ns/data-query/prices")
    protected PriceZonesAvailability priceZonesAvailability;
    @XmlElement(name = "activity-ticket-types-availability", namespace = "http://www.oneboxtm.es/ns/data-query/prices")
    protected ActivityTicketTypesAvailability activityTicketTypesAvailability;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/data-query/venue", required = true)
    protected List<Sector> sector;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/availability")
    protected VisitorGroupAvailability visitorGroupAvailability;

    /**
     * Gets the value of the availabilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityInfo }
     *     
     */
    public AvailabilityInfo getAvailabilityInfo() {
        return availabilityInfo;
    }

    /**
     * Sets the value of the availabilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityInfo }
     *     
     */
    public void setAvailabilityInfo(AvailabilityInfo value) {
        this.availabilityInfo = value;
    }

    /**
     * Gets the value of the sessionMinPrice property.
     * 
     * @return
     *     possible object is
     *     {@link SessionMinPrice }
     *     
     */
    public SessionMinPrice getSessionMinPrice() {
        return sessionMinPrice;
    }

    /**
     * Sets the value of the sessionMinPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionMinPrice }
     *     
     */
    public void setSessionMinPrice(SessionMinPrice value) {
        this.sessionMinPrice = value;
    }

    /**
     * Gets the value of the sessionMaxPrice property.
     * 
     * @return
     *     possible object is
     *     {@link SessionMaxPrice }
     *     
     */
    public SessionMaxPrice getSessionMaxPrice() {
        return sessionMaxPrice;
    }

    /**
     * Sets the value of the sessionMaxPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionMaxPrice }
     *     
     */
    public void setSessionMaxPrice(SessionMaxPrice value) {
        this.sessionMaxPrice = value;
    }

    /**
     * Gets the value of the priceZonesAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link PriceZonesAvailability }
     *     
     */
    public PriceZonesAvailability getPriceZonesAvailability() {
        return priceZonesAvailability;
    }

    /**
     * Sets the value of the priceZonesAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceZonesAvailability }
     *     
     */
    public void setPriceZonesAvailability(PriceZonesAvailability value) {
        this.priceZonesAvailability = value;
    }

    /**
     * Gets the value of the activityTicketTypesAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link ActivityTicketTypesAvailability }
     *     
     */
    public ActivityTicketTypesAvailability getActivityTicketTypesAvailability() {
        return activityTicketTypesAvailability;
    }

    /**
     * Sets the value of the activityTicketTypesAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivityTicketTypesAvailability }
     *     
     */
    public void setActivityTicketTypesAvailability(ActivityTicketTypesAvailability value) {
        this.activityTicketTypesAvailability = value;
    }

    /**
     * Gets the value of the sector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sector }
     * 
     * 
     */
    public List<Sector> getSector() {
        if (sector == null) {
            sector = new ArrayList<Sector>();
        }
        return this.sector;
    }

    /**
     * Gets the value of the visitorGroupAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link VisitorGroupAvailability }
     *     
     */
    public VisitorGroupAvailability getVisitorGroupAvailability() {
        return visitorGroupAvailability;
    }

    /**
     * Sets the value of the visitorGroupAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisitorGroupAvailability }
     *     
     */
    public void setVisitorGroupAvailability(VisitorGroupAvailability value) {
        this.visitorGroupAvailability = value;
    }

    /**
     * Sets the value of the sector property.
     * 
     * @param sector
     *     allowed object is
     *     {@link Sector }
     *     
     */
    public void setSector(List<Sector> sector) {
        this.sector = sector;
    }

}
