
package es.onebox.fcb.datasources.peoplesoft.wsdl.factures;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2025-02-04T13:37:57.454+01:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "faultServeisFCB", targetNamespace = "http://fcbarcelona.cat/esquema/Fault/v01")
public class FacturesFault extends Exception {

    private es.onebox.fcb.datasources.peoplesoft.wsdl.factures.FaultServeisFCBType faultInfo;

    public FacturesFault() {
        super();
    }

    public FacturesFault(String message) {
        super(message);
    }

    public FacturesFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FacturesFault(String message, es.onebox.fcb.datasources.peoplesoft.wsdl.factures.FaultServeisFCBType faultServeisFCB) {
        super(message);
        this.faultInfo = faultServeisFCB;
    }

    public FacturesFault(String message, es.onebox.fcb.datasources.peoplesoft.wsdl.factures.FaultServeisFCBType faultServeisFCB, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultServeisFCB;
    }

    public es.onebox.fcb.datasources.peoplesoft.wsdl.factures.FaultServeisFCBType getFaultInfo() {
        return this.faultInfo;
    }
}
