type: object
additionalProperties:
  oneOf:
    - type: string
    - type: object
  description: Product ticket template literals
example:
  key1: 'Some literal value in given lang'
  key2: 'Some other literal value'
