//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.platformclient;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.platformclient package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.platformclient
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlatformClientType }
     * 
     */
    public PlatformClientType createPlatformClientType() {
        return new PlatformClientType();
    }

    /**
     * Create an instance of {@link ClientConditionsType }
     * 
     */
    public ClientConditionsType createClientConditionsType() {
        return new ClientConditionsType();
    }

    /**
     * Create an instance of {@link ClientDiscountType }
     * 
     */
    public ClientDiscountType createClientDiscountType() {
        return new ClientDiscountType();
    }

    /**
     * Create an instance of {@link ClientB2BType }
     * 
     */
    public ClientB2BType createClientB2BType() {
        return new ClientB2BType();
    }

    /**
     * Create an instance of {@link ClientB2BBranchType }
     * 
     */
    public ClientB2BBranchType createClientB2BBranchType() {
        return new ClientB2BBranchType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link ClientCommissionType }
     * 
     */
    public ClientCommissionType createClientCommissionType() {
        return new ClientCommissionType();
    }

}
