package es.onebox.event.seasontickets.dto;

public enum SeasonTicketSessionValidationReason {

    SEASON_TICKET_GENERATION_STATUS_NOT_VALID,
    SESSION_TYPE_INVALID,
    DIFFERENT_ENTITY_IDS,
    DIFFERENT_VENUE_IDS,
    EVENT_OR_SESSION_STATUS_NOT_VALID,
    ORIGIN_SESSION_NOT_LINKABLE_SEATS,
    ONE_SECTOR_MIN_NOT_FOUND_IN_TARGET,
    ONE_LINKABLE_SEAT_NOT_FOUND_IN_TARGET,
    AT_LEAST_ONE_SEAT_IS_NOT_FOUND_IN_TARGET_SESSION,
    SEASON_TICKET_SESSION_ALREADY_ASSIGNED,
    SEASON_TICKET_SESSION_RESTRICTED,
    SESSION_VENUE_NOT_GRAPHIC,
    ONE_NNZ_MIN_NOT_FOUND_IN_TARGET
}
