//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.products;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.data_query.products package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.data_query.products
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PromotionsDiscounts }
     * 
     */
    public PromotionsDiscounts createPromotionsDiscounts() {
        return new PromotionsDiscounts();
    }

    /**
     * Create an instance of {@link ProductVariant }
     * 
     */
    public ProductVariant createProductVariant() {
        return new ProductVariant();
    }

    /**
     * Create an instance of {@link VariantAttributes }
     * 
     */
    public VariantAttributes createVariantAttributes() {
        return new VariantAttributes();
    }

    /**
     * Create an instance of {@link VariantAttribute }
     * 
     */
    public VariantAttribute createVariantAttribute() {
        return new VariantAttribute();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link CatalogInfo }
     * 
     */
    public CatalogInfo createCatalogInfo() {
        return new CatalogInfo();
    }

    /**
     * Create an instance of {@link ProductInfo }
     * 
     */
    public ProductInfo createProductInfo() {
        return new ProductInfo();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link ProductImage }
     * 
     */
    public ProductImage createProductImage() {
        return new ProductImage();
    }

    /**
     * Create an instance of {@link ProductsInfo }
     * 
     */
    public ProductsInfo createProductsInfo() {
        return new ProductsInfo();
    }

}
