//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.input_data.shopping.cart;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="idValue" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *         &lt;element name="user-input-value" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attribute name="idAttribute" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idValue",
    "userInputValue"
})
@XmlRootElement(name = "attribute-value")
public class AttributeValue
    implements Serializable
{

    @XmlElement(type = Integer.class)
    protected List<Integer> idValue;
    @XmlElement(name = "user-input-value")
    protected List<Object> userInputValue;
    @XmlAttribute(name = "idAttribute")
    protected Integer idAttribute;

    /**
     * Gets the value of the idValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getIdValue() {
        if (idValue == null) {
            idValue = new ArrayList<Integer>();
        }
        return this.idValue;
    }

    /**
     * Gets the value of the userInputValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userInputValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserInputValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getUserInputValue() {
        if (userInputValue == null) {
            userInputValue = new ArrayList<Object>();
        }
        return this.userInputValue;
    }

    /**
     * Gets the value of the idAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdAttribute() {
        return idAttribute;
    }

    /**
     * Sets the value of the idAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdAttribute(Integer value) {
        this.idAttribute = value;
    }

    /**
     * Sets the value of the idValue property.
     * 
     * @param idValue
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdValue(List<Integer> idValue) {
        this.idValue = idValue;
    }

    /**
     * Sets the value of the userInputValue property.
     * 
     * @param userInputValue
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUserInputValue(List<Object> userInputValue) {
        this.userInputValue = userInputValue;
    }

}
