//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.16 at 08:50:55 AM CET 
//


package es.onebox.common.datasources.rest.dto.ns.input_data.shopping.cart;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="salesType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PERCENTAGE"/&gt;
 *     &lt;enumeration value="FIXED"/&gt;
 *     &lt;enumeration value="NO_DISCOUNT"/&gt;
 *     &lt;enumeration value="UNDEFINED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "salesType")
@XmlEnum
public enum SalesType {

    PERCENTAGE,
    FIXED,
    NO_DISCOUNT,
    UNDEFINED;

    public String value() {
        return name();
    }

    public static SalesType fromValue(String v) {
        return valueOf(v);
    }

}
