//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.skidatawhitelist;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.oneboxtm.es/ns/skidatawhitelist}Header"/>
 *         &lt;element name="WhitelistRecord" type="{http://www.oneboxtm.es/ns/skidatawhitelist}WhiteListRecord" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "whitelistRecord"
})
@XmlRootElement(name = "TSData")
public class TSData
    implements Serializable
{

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "WhitelistRecord", required = true)
    protected List<WhiteListRecord> whitelistRecord;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the whitelistRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the whitelistRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWhitelistRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WhiteListRecord }
     * 
     * 
     */
    public List<WhiteListRecord> getWhitelistRecord() {
        if (whitelistRecord == null) {
            whitelistRecord = new ArrayList<WhiteListRecord>();
        }
        return this.whitelistRecord;
    }

    /**
     * Sets the value of the whitelistRecord property.
     * 
     * @param whitelistRecord
     *     allowed object is
     *     {@link WhiteListRecord }
     *     
     */
    public void setWhitelistRecord(List<WhiteListRecord> whitelistRecord) {
        this.whitelistRecord = whitelistRecord;
    }

}
