//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.prices;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/prices}price-zone-availability" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "priceZoneAvailability"
})
@XmlRootElement(name = "price-zones-availability")
public class PriceZonesAvailability
    implements Serializable
{

    @XmlElement(name = "price-zone-availability", required = true)
    protected List<PriceZoneAvailability> priceZoneAvailability;

    /**
     * Gets the value of the priceZoneAvailability property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priceZoneAvailability property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriceZoneAvailability().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriceZoneAvailability }
     * 
     * 
     */
    public List<PriceZoneAvailability> getPriceZoneAvailability() {
        if (priceZoneAvailability == null) {
            priceZoneAvailability = new ArrayList<PriceZoneAvailability>();
        }
        return this.priceZoneAvailability;
    }

    /**
     * Sets the value of the priceZoneAvailability property.
     * 
     * @param priceZoneAvailability
     *     allowed object is
     *     {@link PriceZoneAvailability }
     *     
     */
    public void setPriceZoneAvailability(List<PriceZoneAvailability> priceZoneAvailability) {
        this.priceZoneAvailability = priceZoneAvailability;
    }

}
