type: object
required:
  - productId
  - eventId
  - deliveryPointId
  - isDefault
properties:
  productId:
    type: integer
    description: Product  ID
  eventId:
    type: integer
    description: Event ID
  deliveryPointId:
    type: string
    description: Delivery point code
  isDefault:
    type: boolean
    description: Language default flag
