type: object
properties:
  productId:
    type: integer
    format: int64
  entity:
    $ref: ../common/idname.yml
  producer:
    $ref: ../common/idname.yml
  name:
    type: string
  productType:
    type: string
    enum:
      - SIMPLE
      - VARIANT
  stock_type:
    type: string
    enum:
      - BOUNDED
      - UNBOUNDED
  productState:
    type: string
    enum:
      - DELETED
      - ACTIVE
      - INACTIVE
  currencyId:
    type: string
  createDate:
    type: string
    format: date-time
  updateDate:
    type: string
    format: date-time
  tax:
    $ref: ../common/idname.yml
  surchargeTax:
    $ref: ../common/idname.yml
  hideDeliveryPoint:
    type: boolean
  hideDeliveryDateTime:
    type: boolean
  category:
    type: object
    properties:
      id:
        type: integer
      description:
        type: string
      code:
        type: string
  customCategory:
    type: object
    properties:
      id:
        type: integer
      description:
        type: string
      code:
        type: string