type: object
properties:
  type:
    type: string
    enum:
      - NAME
      - DELIVERY_DETAIL
    description: Communication element type
  language:
    type: string
    description: Text language code
  value:
    type: string
    description: Communication element value