type: object
required:
  - session
  - dates
properties:
  id:
    type: string
    description: Session ID
  name:
    type: string
    description: Session name
  useCustomStock:
    type: boolean
    description: Use stock value defined in generic config or use a custom. Only for simple product with stock type ```SESSION_BOUNDED```
  isSmartBooking:
    type: boolean
  stock:
    type: integer
    description: Stock defined for this session. Only for simple product with stock type ```SESSION_BOUNDED``` and ```useCustomStock``` is ```TRUE```
  dates:
    type: object
    properties:
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
