type: object
required:
  - product
  - event
  - allEvents
properties:
  product:
    $ref: ../common/idname.yml
    description: Product
  event:
    $ref: ../common/idname.yml
    description: Event
  sessionsSelectionType:
    type: string
    enum:
      - ALL
      - RESTRICTED
    description: Sessions selection type