type: object
required:
  - productId
  - sessionId
  - deliveryPointId
  - isDefault
properties:
  productId:
    type: integer
    description: Product  ID
  eventId:
    type: integer
    description: Session ID
  deliveryPointId:
    type: string
    description: Delivery point code
  isDefault:
    type: boolean
    description: Language default flag
