type: object
properties:
  tagId:
    type: integer
    description: Tag ID
  position:
    type: integer
    description: Image position
  id:
    type: integer
    description: Image ID
  tag:
    type: string
    description: Image tag
  language:
    type: string
    description: Image language
  type:
    type: string
    enum:
      - LANDSCAPE
  value:
    type: string
    description: Image path
  imageBinary:
    type: string
    description: Image content
  altText:
    type: string
    description: Image alternative text
