type: object
properties:
  type:
    type: string
    enum:
      - BODY
      - THUMBNAIL
    description: Image type
  language:
    type: string
    description: Image language code
  value:
    type: string
    description: Image path