additionalProperties: false
type: object
required:
  - attributeId
  - name
  - position
properties:
  attributeId:
    type: integer
  name:
    type: string
  position:
    type: integer
    minimum: 0
