type: object
properties:
  id:
    type: string
    description: Session ID
  name:
    type: string
    description: Session name
  status:
    $ref: ../sessions/session-status.yml
  dates:
    type: object
    properties:
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
      channelPublication:
        type: string
        format: date-time
