type: object
required:
  - session
  - dates
properties:
  id:
    type: string
    description: Session ID
  name:
    type: string
    description: Session name
  dates:
    type: object
    properties:
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
