additionalProperties: false
type: object
required:
  - valueId
  - attributeId
  - name
  - position
properties:
  valueId:
    type: integer
  attributeId:
    type: integer
  name:
    type: string
  position:
    type: integer
