type: object
required:
  - id
  - product
  - productDeliveryPoint
properties:
  id:
    type: integer
    description: Product delivery type
  product:
    $ref: ../common/idname.yml
    description: Product
  deliveryPoint:
    $ref: ../common/idname.yml
    description: Delivery point
