type: object
required:
 - deliveryType
properties:
  deliveryType:
    type: string
    enum:
      - SESSION
      - PURCHASE
      - FIXED_DATES
    description: Product delivery type
  startTimeUnit:
    type: string
    enum:
      - MINUTES
      - HOURS
      - DAYS
      - WEEKS
      - MONTHS
    description: Delivery start time unit
  startTimeValue:
    type: integer
    description: Delivery start time value
  endTimeUnit:
    type: string
    enum:
      - MINUTES
      - HOURS
      - DAYS
      - WEEKS
      - MONTHS
    description: Delivery end  time unit
  endTimeValue:
    type: integer
    description: Delivery end time value
  deliveryDateFrom:
    format: date-time
    type: string
    description: Delivery fixed start date if delivery type is fixed
  deliveryDateTo:
    format: date-time
    type: string
    description: Delivery fixed end date if delivery type is fixed
