type: object
properties:
  productId:
    type: integer
    description: Product  ID
  languageId:
    type: integer
    description: Language ID
  code:
    type: string
    description: Language code
  isDefault:
    type: boolean
    description: Language default flag
