type: object
properties:
  id:
    type: integer
  product:
    $ref: ../common/idname.yml
  name:
    type: string
  sku:
    type: string
  stock:
    type: integer
  price:
    type: number
  createDate:
    type: string
  updateDate:
    type: string
  variantOption1:
    $ref: ../common/idname.yml
  variantOption2:
    $ref: ../common/idname.yml
  variantValue1:
    $ref: ../common/idname.yml
  variantValue2:
    $ref: ../common/idname.yml
  status:
    type: string
