//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.whitelist;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SeatId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeatBarcode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeatGate" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SeatStatus" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SeatLastUpdatedTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeatPromotion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeatDiscount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeatSection" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeatRow" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeatSeat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Seat")
public class Seat
    implements Serializable
{

    @XmlAttribute(name = "SeatId")
    protected String seatId;
    @XmlAttribute(name = "SeatBarcode")
    protected String seatBarcode;
    @XmlAttribute(name = "SeatGate")
    protected BigInteger seatGate;
    @XmlAttribute(name = "SeatStatus")
    protected BigInteger seatStatus;
    @XmlAttribute(name = "SeatLastUpdatedTime")
    protected String seatLastUpdatedTime;
    @XmlAttribute(name = "SeatPromotion")
    protected String seatPromotion;
    @XmlAttribute(name = "SeatDiscount")
    protected String seatDiscount;
    @XmlAttribute(name = "SeatSection")
    protected String seatSection;
    @XmlAttribute(name = "SeatRow")
    protected String seatRow;
    @XmlAttribute(name = "SeatSeat")
    protected String seatSeat;

    /**
     * Gets the value of the seatId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatId() {
        return seatId;
    }

    /**
     * Sets the value of the seatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatId(String value) {
        this.seatId = value;
    }

    /**
     * Gets the value of the seatBarcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatBarcode() {
        return seatBarcode;
    }

    /**
     * Sets the value of the seatBarcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatBarcode(String value) {
        this.seatBarcode = value;
    }

    /**
     * Gets the value of the seatGate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeatGate() {
        return seatGate;
    }

    /**
     * Sets the value of the seatGate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeatGate(BigInteger value) {
        this.seatGate = value;
    }

    /**
     * Gets the value of the seatStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeatStatus() {
        return seatStatus;
    }

    /**
     * Sets the value of the seatStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeatStatus(BigInteger value) {
        this.seatStatus = value;
    }

    /**
     * Gets the value of the seatLastUpdatedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatLastUpdatedTime() {
        return seatLastUpdatedTime;
    }

    /**
     * Sets the value of the seatLastUpdatedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatLastUpdatedTime(String value) {
        this.seatLastUpdatedTime = value;
    }

    /**
     * Gets the value of the seatPromotion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatPromotion() {
        return seatPromotion;
    }

    /**
     * Sets the value of the seatPromotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatPromotion(String value) {
        this.seatPromotion = value;
    }

    /**
     * Gets the value of the seatDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatDiscount() {
        return seatDiscount;
    }

    /**
     * Sets the value of the seatDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatDiscount(String value) {
        this.seatDiscount = value;
    }

    /**
     * Gets the value of the seatSection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatSection() {
        return seatSection;
    }

    /**
     * Sets the value of the seatSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatSection(String value) {
        this.seatSection = value;
    }

    /**
     * Gets the value of the seatRow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatRow() {
        return seatRow;
    }

    /**
     * Sets the value of the seatRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatRow(String value) {
        this.seatRow = value;
    }

    /**
     * Gets the value of the seatSeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatSeat() {
        return seatSeat;
    }

    /**
     * Sets the value of the seatSeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatSeat(String value) {
        this.seatSeat = value;
    }

}
