//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.whitelist;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ValidationInit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ValidationEnd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ValidationRange")
public class ValidationRange
    implements Serializable
{

    @XmlAttribute(name = "ValidationInit")
    protected String validationInit;
    @XmlAttribute(name = "ValidationEnd")
    protected String validationEnd;

    /**
     * Gets the value of the validationInit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationInit() {
        return validationInit;
    }

    /**
     * Sets the value of the validationInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationInit(String value) {
        this.validationInit = value;
    }

    /**
     * Gets the value of the validationEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationEnd() {
        return validationEnd;
    }

    /**
     * Sets the value of the validationEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationEnd(String value) {
        this.validationEnd = value;
    }

}
