//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.event;

import es.onebox.common.datasources.rest.dto.ns.data_query.session.SessionsSearchInfo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oneboxtm.es/ns/data-query/event}eventBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/session}sessions-search-info" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/event}eventMinPrice" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/event}eventMaxPrice" minOccurs="0"/>
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionsSearchInfo",
    "eventMinPrice",
    "eventMaxPrice",
    "position"
})
@XmlRootElement(name = "event-search-info")
public class EventSearchInfo
    extends EventBaseType
    implements Serializable
{

    @XmlElement(name = "sessions-search-info", namespace = "http://www.oneboxtm.es/ns/data-query/session")
    protected SessionsSearchInfo sessionsSearchInfo;
    protected EventMinPrice eventMinPrice;
    protected EventMaxPrice eventMaxPrice;
    protected Integer position;

    /**
     * Gets the value of the sessionsSearchInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SessionsSearchInfo }
     *     
     */
    public SessionsSearchInfo getSessionsSearchInfo() {
        return sessionsSearchInfo;
    }

    /**
     * Sets the value of the sessionsSearchInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionsSearchInfo }
     *     
     */
    public void setSessionsSearchInfo(SessionsSearchInfo value) {
        this.sessionsSearchInfo = value;
    }

    /**
     * Gets the value of the eventMinPrice property.
     * 
     * @return
     *     possible object is
     *     {@link EventMinPrice }
     *     
     */
    public EventMinPrice getEventMinPrice() {
        return eventMinPrice;
    }

    /**
     * Sets the value of the eventMinPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventMinPrice }
     *     
     */
    public void setEventMinPrice(EventMinPrice value) {
        this.eventMinPrice = value;
    }

    /**
     * Gets the value of the eventMaxPrice property.
     * 
     * @return
     *     possible object is
     *     {@link EventMaxPrice }
     *     
     */
    public EventMaxPrice getEventMaxPrice() {
        return eventMaxPrice;
    }

    /**
     * Sets the value of the eventMaxPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventMaxPrice }
     *     
     */
    public void setEventMaxPrice(EventMaxPrice value) {
        this.eventMaxPrice = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPosition(Integer value) {
        this.position = value;
    }

}
