//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.event;

import es.onebox.common.datasources.rest.dto.ns.attributes.AttributeValues;
import es.onebox.common.datasources.rest.dto.ns.commissions.Commission;
import es.onebox.common.datasources.rest.dto.ns.communication.CommunicationElements;
import es.onebox.common.datasources.rest.dto.ns.dates.Dates;
import es.onebox.common.datasources.rest.dto.ns.languages.LanguagesType;
import es.onebox.common.datasources.rest.dto.ns.passbook.PassbookPreferences;
import es.onebox.common.datasources.rest.dto.ns.taxonomy.ChildTaxonomyType;
import es.onebox.common.datasources.rest.dto.ns.taxonomy.CustomTaxonomyType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for eventBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="internalName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="externalReferenceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subtitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shortDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="longDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="additionalEventData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/communication}communication-elements" minOccurs="0"/>
 *         &lt;element name="taxonomy" type="{http://www.oneboxtm.es/ns/taxonomy}childTaxonomyType" minOccurs="0"/>
 *         &lt;element name="custom-taxonomy" type="{http://www.oneboxtm.es/ns/taxonomy}customTaxonomyType" minOccurs="0"/>
 *         &lt;element name="promoter-custom-taxonomy" type="{http://www.oneboxtm.es/ns/taxonomy}customTaxonomyType" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/languages}languages" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/dates}dates" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/event}entidad" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/event}promotor" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/event}tour" minOccurs="0"/>
 *         &lt;element name="severalVenues" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="severalLocations" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="supraEvent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="giftTicket" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="nominal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="eventType" type="{http://www.oneboxtm.es/ns/data-query/event}eventType"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/attributes}attribute-values" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/passbook}passbookPreferences"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/event}clientEventDiscount" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/commissions}commission" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventBaseType", propOrder = {
    "internalName",
    "externalReferenceCode",
    "title",
    "subtitle",
    "shortDescription",
    "longDescription",
    "additionalEventData",
    "duration",
    "communicationElements",
    "taxonomy",
    "customTaxonomy",
    "promoterCustomTaxonomy",
    "languages",
    "dates",
    "entidad",
    "promotor",
    "tour",
    "severalVenues",
    "severalLocations",
    "supraEvent",
    "giftTicket",
    "nominal",
    "eventType",
    "attributeValues",
    "passbookPreferences",
    "clientEventDiscount",
    "commission"
})
@XmlSeeAlso({
    EventCatalogInfo.class,
    EventSessionInfo.class,
    EventInfo.class,
    EventBasicInfo.class,
    EventSearchInfo.class
})
public class EventBaseType
    implements Serializable
{

    @XmlElement(required = true)
    protected String internalName;
    @XmlElement(required = true)
    protected String externalReferenceCode;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String subtitle;
    @XmlElement(required = true)
    protected String shortDescription;
    @XmlElement(required = true)
    protected String longDescription;
    @XmlElement(required = true)
    protected String additionalEventData;
    @XmlElement(required = true)
    protected String duration;
    @XmlElement(name = "communication-elements", namespace = "http://www.oneboxtm.es/ns/communication")
    protected CommunicationElements communicationElements;
    protected ChildTaxonomyType taxonomy;
    @XmlElement(name = "custom-taxonomy")
    protected CustomTaxonomyType customTaxonomy;
    @XmlElement(name = "promoter-custom-taxonomy")
    protected CustomTaxonomyType promoterCustomTaxonomy;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/languages")
    protected LanguagesType languages;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/dates")
    protected Dates dates;
    protected Entidad entidad;
    protected Promotor promotor;
    protected Tour tour;
    protected boolean severalVenues;
    protected boolean severalLocations;
    protected boolean supraEvent;
    protected boolean giftTicket;
    protected boolean nominal;
    @XmlElement(required = true)
    protected EventType eventType;
    @XmlElement(name = "attribute-values", namespace = "http://www.oneboxtm.es/ns/attributes")
    protected List<AttributeValues> attributeValues;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/passbook", required = true)
    protected PassbookPreferences passbookPreferences;
    protected ClientEventDiscount clientEventDiscount;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/commissions")
    protected List<Commission> commission;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;

    /**
     * Gets the value of the internalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalName() {
        return internalName;
    }

    /**
     * Sets the value of the internalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalName(String value) {
        this.internalName = value;
    }

    /**
     * Gets the value of the externalReferenceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalReferenceCode() {
        return externalReferenceCode;
    }

    /**
     * Sets the value of the externalReferenceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalReferenceCode(String value) {
        this.externalReferenceCode = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the subtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * Sets the value of the subtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtitle(String value) {
        this.subtitle = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortDescription(String value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the longDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * Sets the value of the longDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongDescription(String value) {
        this.longDescription = value;
    }

    /**
     * Gets the value of the additionalEventData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalEventData() {
        return additionalEventData;
    }

    /**
     * Sets the value of the additionalEventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalEventData(String value) {
        this.additionalEventData = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the communicationElements property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationElements }
     *     
     */
    public CommunicationElements getCommunicationElements() {
        return communicationElements;
    }

    /**
     * Sets the value of the communicationElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationElements }
     *     
     */
    public void setCommunicationElements(CommunicationElements value) {
        this.communicationElements = value;
    }

    /**
     * Gets the value of the taxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link ChildTaxonomyType }
     *     
     */
    public ChildTaxonomyType getTaxonomy() {
        return taxonomy;
    }

    /**
     * Sets the value of the taxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildTaxonomyType }
     *     
     */
    public void setTaxonomy(ChildTaxonomyType value) {
        this.taxonomy = value;
    }

    /**
     * Gets the value of the customTaxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link CustomTaxonomyType }
     *     
     */
    public CustomTaxonomyType getCustomTaxonomy() {
        return customTaxonomy;
    }

    /**
     * Sets the value of the customTaxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomTaxonomyType }
     *     
     */
    public void setCustomTaxonomy(CustomTaxonomyType value) {
        this.customTaxonomy = value;
    }

    /**
     * Gets the value of the promoterCustomTaxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link CustomTaxonomyType }
     *     
     */
    public CustomTaxonomyType getPromoterCustomTaxonomy() {
        return promoterCustomTaxonomy;
    }

    /**
     * Sets the value of the promoterCustomTaxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomTaxonomyType }
     *     
     */
    public void setPromoterCustomTaxonomy(CustomTaxonomyType value) {
        this.promoterCustomTaxonomy = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link LanguagesType }
     *     
     */
    public LanguagesType getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguagesType }
     *     
     */
    public void setLanguages(LanguagesType value) {
        this.languages = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link Dates }
     *     
     */
    public Dates getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dates }
     *     
     */
    public void setDates(Dates value) {
        this.dates = value;
    }

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link Entidad }
     *     
     */
    public Entidad getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entidad }
     *     
     */
    public void setEntidad(Entidad value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the promotor property.
     * 
     * @return
     *     possible object is
     *     {@link Promotor }
     *     
     */
    public Promotor getPromotor() {
        return promotor;
    }

    /**
     * Sets the value of the promotor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Promotor }
     *     
     */
    public void setPromotor(Promotor value) {
        this.promotor = value;
    }

    /**
     * Gets the value of the tour property.
     * 
     * @return
     *     possible object is
     *     {@link Tour }
     *     
     */
    public Tour getTour() {
        return tour;
    }

    /**
     * Sets the value of the tour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tour }
     *     
     */
    public void setTour(Tour value) {
        this.tour = value;
    }

    /**
     * Gets the value of the severalVenues property.
     * 
     */
    public boolean isSeveralVenues() {
        return severalVenues;
    }

    /**
     * Sets the value of the severalVenues property.
     * 
     */
    public void setSeveralVenues(boolean value) {
        this.severalVenues = value;
    }

    /**
     * Gets the value of the severalLocations property.
     * 
     */
    public boolean isSeveralLocations() {
        return severalLocations;
    }

    /**
     * Sets the value of the severalLocations property.
     * 
     */
    public void setSeveralLocations(boolean value) {
        this.severalLocations = value;
    }

    /**
     * Gets the value of the supraEvent property.
     * 
     */
    public boolean isSupraEvent() {
        return supraEvent;
    }

    /**
     * Sets the value of the supraEvent property.
     * 
     */
    public void setSupraEvent(boolean value) {
        this.supraEvent = value;
    }

    /**
     * Gets the value of the giftTicket property.
     * 
     */
    public boolean isGiftTicket() {
        return giftTicket;
    }

    /**
     * Sets the value of the giftTicket property.
     * 
     */
    public void setGiftTicket(boolean value) {
        this.giftTicket = value;
    }

    /**
     * Gets the value of the nominal property.
     * 
     */
    public boolean isNominal() {
        return nominal;
    }

    /**
     * Sets the value of the nominal property.
     * 
     */
    public void setNominal(boolean value) {
        this.nominal = value;
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setEventType(EventType value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the attributeValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeValues }
     * 
     * 
     */
    public List<AttributeValues> getAttributeValues() {
        if (attributeValues == null) {
            attributeValues = new ArrayList<AttributeValues>();
        }
        return this.attributeValues;
    }

    /**
     * Gets the value of the passbookPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link PassbookPreferences }
     *     
     */
    public PassbookPreferences getPassbookPreferences() {
        return passbookPreferences;
    }

    /**
     * Sets the value of the passbookPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassbookPreferences }
     *     
     */
    public void setPassbookPreferences(PassbookPreferences value) {
        this.passbookPreferences = value;
    }

    /**
     * Gets the value of the clientEventDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link ClientEventDiscount }
     *     
     */
    public ClientEventDiscount getClientEventDiscount() {
        return clientEventDiscount;
    }

    /**
     * Sets the value of the clientEventDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientEventDiscount }
     *     
     */
    public void setClientEventDiscount(ClientEventDiscount value) {
        this.clientEventDiscount = value;
    }

    /**
     * Gets the value of the commission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Commission }
     * 
     * 
     */
    public List<Commission> getCommission() {
        if (commission == null) {
            commission = new ArrayList<Commission>();
        }
        return this.commission;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Sets the value of the attributeValues property.
     * 
     * @param attributeValues
     *     allowed object is
     *     {@link AttributeValues }
     *     
     */
    public void setAttributeValues(List<AttributeValues> attributeValues) {
        this.attributeValues = attributeValues;
    }

    /**
     * Sets the value of the commission property.
     * 
     * @param commission
     *     allowed object is
     *     {@link Commission }
     *     
     */
    public void setCommission(List<Commission> commission) {
        this.commission = commission;
    }

}
