//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.event;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.data_query.event package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.data_query.event
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TicketInfo }
     * 
     */
    public TicketInfo createTicketInfo() {
        return new TicketInfo();
    }

    /**
     * Create an instance of {@link Promotor }
     * 
     */
    public Promotor createPromotor() {
        return new Promotor();
    }

    /**
     * Create an instance of {@link ClientEventDiscount }
     * 
     */
    public ClientEventDiscount createClientEventDiscount() {
        return new ClientEventDiscount();
    }

    /**
     * Create an instance of {@link EventsSearch }
     * 
     */
    public EventsSearch createEventsSearch() {
        return new EventsSearch();
    }

    /**
     * Create an instance of {@link EventSearchInfo }
     * 
     */
    public EventSearchInfo createEventSearchInfo() {
        return new EventSearchInfo();
    }

    /**
     * Create an instance of {@link EventBaseType }
     * 
     */
    public EventBaseType createEventBaseType() {
        return new EventBaseType();
    }

    /**
     * Create an instance of {@link Entidad }
     * 
     */
    public Entidad createEntidad() {
        return new Entidad();
    }

    /**
     * Create an instance of {@link Tour }
     * 
     */
    public Tour createTour() {
        return new Tour();
    }

    /**
     * Create an instance of {@link EventBasicInfo }
     * 
     */
    public EventBasicInfo createEventBasicInfo() {
        return new EventBasicInfo();
    }

    /**
     * Create an instance of {@link EventMinPrice }
     * 
     */
    public EventMinPrice createEventMinPrice() {
        return new EventMinPrice();
    }

    /**
     * Create an instance of {@link EventMaxPrice }
     * 
     */
    public EventMaxPrice createEventMaxPrice() {
        return new EventMaxPrice();
    }

    /**
     * Create an instance of {@link EventField }
     * 
     */
    public EventField createEventField() {
        return new EventField();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link EventInfo }
     * 
     */
    public EventInfo createEventInfo() {
        return new EventInfo();
    }

    /**
     * Create an instance of {@link EventSessionInfo }
     * 
     */
    public EventSessionInfo createEventSessionInfo() {
        return new EventSessionInfo();
    }

    /**
     * Create an instance of {@link EventCatalogInfo }
     * 
     */
    public EventCatalogInfo createEventCatalogInfo() {
        return new EventCatalogInfo();
    }

    /**
     * Create an instance of {@link EventsCatalog }
     * 
     */
    public EventsCatalog createEventsCatalog() {
        return new EventsCatalog();
    }

}
