additionalProperties: false
type: object
properties:
  id:
    type: number
    format: int64
  name:
    type: string
  status:
    $ref: ../promotions/promotion-status.yml
  type:
    $ref: product-promotion-type.yml
  discount:
    $ref: product-promotion-discount.yml
  activator:
    $ref: product-promotion-activator.yml
