type: array
items:
  type: object
  required:
    - id
    - name
    - dates
  properties:
    id:
      type: integer
      format: int64
      description: Session ID
    name:
      type: string
      description: Session name
    use_custom_stock:
      type: boolean
      description: Use stock value defined in generic config or use a custom. Only for simple product with stock type ```SESSION_BOUNDED```  (Deprecated)
    smart_booking:
      type: object
      properties:
        type:
          type: string
          enum:
            - SEAT_SELECTION
            - SMART_BOOKING
    stock:
      type: integer
      description: Stock defined for this session. Only for simple product with stock type ```use_custom_stock``` and ```useCustomStock``` is ```TRUE``` (Deprecated)
    variants:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            description: Variant ID
          use_custom_stock:
            type: boolean
            description: Use stock value defined in generic config or use a custom.
          stock:
            type: integer
            description: Stock override defined for this session
          use_custom_price:
            type: boolean
            description: Use price value defined in generic config or use a custom.
          price:
            type: number
            description: Price override defined for this session
    dates:
      type: object
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
