additionalProperties: false
type: object
required:
  - id
  - product
  - delivery_point
properties:
  id:
    type: integer
  product:
    $ref: ../common/idname.yml
  delivery_point:
    $ref: ../common/idname.yml
