additionalProperties: false
type: object
required:
  - value_id
  - attribute_id
  - name
  - position
properties:
  value_id:
    type: integer
  attribute_id:
    type: integer
  name:
    type: string
  position:
    type: integer
