additionalProperties: false
type: object
required:
  - product
  - event
  - delivery_point
  - is_default
properties:
  product:
    $ref: ../common/idname.yml
    description: Product
  event:
    $ref: ../common/idname.yml
    description: Event
  delivery_point:
    $ref: ../common/idname.yml
    description: Delivery point
  is_default:
    type: boolean
    description: Language default flag