additionalProperties: false
type: object
properties:
  type:
    type: string
    enum:
      - BODY
    description: Image type
  language:
    type: string
    description: Language code
  image_url:
    type: string
    description: Image url