additionalProperties: false
type: object
properties:
  id:
    type: integer
  product:
    $ref: ../common/idname.yml
  name:
    type: string
  sku:
    type: string
  stock:
    type: integer
  price:
    type: number
  create_date:
    type: string
  update_date:
    type: string
  variant_option_1:
    $ref: ../common/idname.yml
  variant_option_2:
    $ref: ../common/idname.yml
  variant_value_1:
    $ref: ../common/idname.yml
  variant_value_2:
    $ref: ../common/idname.yml
  status:
    type: string
