additionalProperties: false
type: object
required:
  - delivery_type
properties:
  delivery_type:
    type: string
    enum:
      - SESSION
      - PURCHASE
      - FIXED_DATES
    description: Product delivery type
  start_time_unit:
    type: string
    enum:
      - MINUTES
      - HOURS
      - DAYS
      - WEEKS
      - MONTHS
    description: Delivery start time unit
  start_time_value:
    type: integer
    description: Delivery start time value
  end_time_unit:
    type: string
    enum:
      - MINUTES
      - HOURS
      - DAYS
      - WEEKS
      - MONTHS
    description: Delivery end time unit
  end_time_value:
    type: integer
    description: Delivery end time value
  delivery_date_from:
    format: date-time
    type: string
    description: Delivery fixed start date if delivery type is fixed
  delivery_date_to:
    format: date-time
    type: string
    description: Delivery fixed end date if delivery type is fixed
