type: object
required:
  - product
  - event
  - status
  - sessions_selection_type
properties:
  product:
    $ref: ../common/idname.yml
  event:
    $ref: ./product-events-data.yml
  status:
    type: string
    enum:
      - ACTIVE
      - INACTIVE
    description: Product event status
  sessions_selection_type:
    type: string
    enum:
      - ALL
      - RESTRICTED
    description: Sessions selection type
