additionalProperties: false
type: object
properties:
  product_id:
    type: integer
    description: Product ID
  language_id:
    type: integer
    description: Language ID
  code:
    type: string
    description: Language code
  is_default:
    type: boolean
    description: Language default flag