additionalProperties: false
type: object
properties:
  type:
    type: string
    enum:
      - NAME
      - DELIVERY_DETAIL
    description: Ticket content type
  language:
    type: string
    description: Language code
  value:
    type: string
    description: Ticket content value
