additionalProperties: false
type: object
properties:
  type:
    type: string
    enum:
      - PRODUCT_NAME
      - DESCRIPTION
      - NOTES
      - DELIVERY_DETAIL
    description: Communication element type
  language:
    type: string
    description: Language code
  language_id:
    type: string
    description: Language ID
  value:
    type: string
    description: Communication element value
