additionalProperties: false
type: object
required:
  - id
  - name
  - is_default
properties:
  id:
    type: integer
    description: Delivery point ID
  name:
    type: string
    description: Delivery point name
  is_default:
    type: boolean
    description: Delivery point default flag
