additionalProperties: false
type: object
properties:
  id:
    type: number
    description: Session ID
  name:
    type: string
    description: Session name
  link:
    type: string
    description: URL to the products of the sessions in Channels
    example: https://tickets.oneboxtds.net/channelname/select/123456789/products?hl=es-ES
  enabled:
    type: boolean