additionalProperties: false
type: object
required:
  - id
  - type
  - format
properties:
  id:
    type: integer
    description: Ticket template ID
  type:
    $ref: ./ticket-template-type.yml
  format:
    $ref: ./ticket-template-format.yml

