additionalProperties: false
type: object
required:
  - id
  - name
  - type
  - validation_method
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  type:
    $ref: ../collectives/status.yml
  validation_method:
    $ref: ../collectives/validation-method.yml