type: object
required:
  - product
  - channel
properties:
  product:
    $ref: ../common/idname.yml
    description: Product
  channel:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      entity:
        type: object
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
          logo:
            type: string
            description: URL or base64 of the channel entity logo
  checkout_suggestion_enabled:
    type: boolean
  standalone_enabled:
    type: boolean
  sale_request_status:
    type: string
    enum:
      - REJECTED
      - PENDING
      - ACCEPTED
      - PENDING_REQUEST
  languages:
    type: object
    properties:
      default:
        type: string
      selected:
        type: array
        items:
          type: string
