additionalProperties: false
type: object
properties:
  type:
    type: string
    enum:
      - LANDSCAPE
    description: Image type
  language:
    type: string
    description: Language code
  image:
    type: string
    description: Image content
  image_url:
    type: string
    description: image url
  position:
    type: integer
    description: Image position
  alt_text:
    type: string
    description: image alternative text
