additionalProperties: false
type: object
properties:
  id:
    type: integer
  entity:
    $ref: ../common/idname.yml
  producer:
    $ref: ../common/idname.yml
  tax:
    $ref: ../common/idname.yml
  product_id:
    type: integer
  product_type:
    type: string
    enum:
      - SIMPLE
      - VARIANT
  name:
    type: string
  product_state:
    type: string
    enum:
      - ACTIVE
      - INACTIVE
  create_date:
    type: string
    format: date-time
  update_date:
    type: string
    format: date-time
  stock_type:
    type: string
    enum:
      - BOUNDED
      - UNBOUNDED
  currency_code:
    type: string
  ticket_template_id:
    type: integer
  ui_settings:
    $ref: product-ui-settings.yml
  settings:
    type: object
    properties:
      tax_mode:
        type: string
        enum:
          - INCLUDED
          - ON_TOP
