 type: array
 items:
   type: object
   required:
      - valueId
      - key
      - value
      - language
   properties:
      valueId:
         type: integer
         format: int64
      key:
         type: string
         enum:
            - VALUE_NAME
      value:
         type: string
      language:
         type: string
