additionalProperties: false
type: object
required:
  - attribute_id
  - name
  - position
properties:
  attribute_id:
    type: integer
  name:
    type: string
  position:
    type: integer
    minimum: 0
