 type: array
 items:
   type: object
   required:
      - key
      - value
      - language
   properties: 
      key:
         type: string
         enum:
            - VALUE_NAME
      value:
         type: string
      language:
         type: string
