type: object
description: Full product-channel configuration and current status
properties:
  product:
    $ref: ../common/idname.yml
  channel:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      entity:
        type: object
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
          logo:
            type: string
            description: URL or base64 of the channel entity logo
      type:
        type: string
        enum:
          - EXTERNAL
          - WEB
          - BOX_OFFICE
          - WEB_BOX_OFFICE
          - WEB_SUBSCRIBERS
          - WEB_B2B
          - MEMBERS
  checkout_suggestion_enabled:
    type: boolean
    description: Whether checkout suggestion is enabled
  standalone_enabled:
    type: boolean
    description: Whether standalone mode is enabled
  sale_request_status:
    type: string
    enum:
      - REJECTED
      - PENDING
      - ACCEPTED
      - PENDING_REQUEST
  languages:
    type: object
    properties:
      default:
        type: string
      selected:
        type: array
        items:
          type: string
