//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.widgetdescriptor;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Attribute" type="{http://www.oneboxtm.es/ns/widgetdescriptor}Attribute" maxOccurs="unbounded"/>
 *         &lt;element name="RemoteEndPoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ScopeVar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ConsumerFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProviderFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attribute",
    "remoteEndPoint",
    "scopeVar",
    "consumerFile",
    "providerFile"
})
@XmlRootElement(name = "WidgetDescriptor")
public class WidgetDescriptor
    implements Serializable
{

    @XmlElement(name = "Attribute", required = true)
    protected List<Attribute> attribute;
    @XmlElement(name = "RemoteEndPoint", required = true)
    protected String remoteEndPoint;
    @XmlElement(name = "ScopeVar", required = true)
    protected String scopeVar;
    @XmlElement(name = "ConsumerFile", required = true)
    protected String consumerFile;
    @XmlElement(name = "ProviderFile", required = true)
    protected String providerFile;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    public List<Attribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<Attribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the remoteEndPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteEndPoint() {
        return remoteEndPoint;
    }

    /**
     * Sets the value of the remoteEndPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteEndPoint(String value) {
        this.remoteEndPoint = value;
    }

    /**
     * Gets the value of the scopeVar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScopeVar() {
        return scopeVar;
    }

    /**
     * Sets the value of the scopeVar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScopeVar(String value) {
        this.scopeVar = value;
    }

    /**
     * Gets the value of the consumerFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerFile() {
        return consumerFile;
    }

    /**
     * Sets the value of the consumerFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerFile(String value) {
        this.consumerFile = value;
    }

    /**
     * Gets the value of the providerFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderFile() {
        return providerFile;
    }

    /**
     * Sets the value of the providerFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderFile(String value) {
        this.providerFile = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Sets the value of the attribute property.
     * 
     * @param attribute
     *     allowed object is
     *     {@link Attribute }
     *     
     */
    public void setAttribute(List<Attribute> attribute) {
        this.attribute = attribute;
    }

}
