//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.sales;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for groupValidationMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="groupValidationMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PROMOTIONAL_CODE"/>
 *     &lt;enumeration value="USER"/>
 *     &lt;enumeration value="USER_PASSWORD"/>
 *     &lt;enumeration value="CREDIT_CARD"/>
 *     &lt;enumeration value="GIFT_TICKET"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "groupValidationMethodType")
@XmlEnum
public enum GroupValidationMethodType {

    PROMOTIONAL_CODE,
    USER,
    USER_PASSWORD,
    CREDIT_CARD,
    GIFT_TICKET;

    public String value() {
        return name();
    }

    public static GroupValidationMethodType fromValue(String v) {
        return valueOf(v);
    }

}
