//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.data_query.occupation;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/occupation}filter-venue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/data-query/occupation}filter-event" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name",
    "filterVenue",
    "filterEvent"
})
@XmlRootElement(name = "filter-space")
public class FilterSpace
    implements Serializable
{

    protected Integer id;
    protected String name;
    @XmlElement(name = "filter-venue")
    protected List<FilterVenue> filterVenue;
    @XmlElement(name = "filter-event")
    protected List<FilterEvent> filterEvent;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the filterVenue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterVenue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterVenue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterVenue }
     * 
     * 
     */
    public List<FilterVenue> getFilterVenue() {
        if (filterVenue == null) {
            filterVenue = new ArrayList<FilterVenue>();
        }
        return this.filterVenue;
    }

    /**
     * Gets the value of the filterEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterEvent }
     * 
     * 
     */
    public List<FilterEvent> getFilterEvent() {
        if (filterEvent == null) {
            filterEvent = new ArrayList<FilterEvent>();
        }
        return this.filterEvent;
    }

    /**
     * Sets the value of the filterVenue property.
     * 
     * @param filterVenue
     *     allowed object is
     *     {@link FilterVenue }
     *     
     */
    public void setFilterVenue(List<FilterVenue> filterVenue) {
        this.filterVenue = filterVenue;
    }

    /**
     * Sets the value of the filterEvent property.
     * 
     * @param filterEvent
     *     allowed object is
     *     {@link FilterEvent }
     *     
     */
    public void setFilterEvent(List<FilterEvent> filterEvent) {
        this.filterEvent = filterEvent;
    }

}
