package es.onebox.fcb.datasources.peoplesoft.wsdl.clients;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 4.0.5
 * 2025-02-04T13:37:55.898+01:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "Clients",
                  wsdlLocation = "https://user:pass@serveis.fcbarcelona.cat/service/extern/vendes/clientsPortType/v01?wsdl",
                  targetNamespace = "http://fcbarcelona.cat/servei/Vendes/Clients/v01")
public class Clients extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://fcbarcelona.cat/servei/Vendes/Clients/v01", "Clients");
    public static final QName ClientsSOAP = new QName("http://fcbarcelona.cat/servei/Vendes/Clients/v01", "ClientsSOAP");
    static {
        URL url = null;
        try {
            url = URI.create("https://user:pass@serveis.fcbarcelona.cat/service/extern/vendes/clientsPortType/v01?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Clients.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://user:pass@serveis.fcbarcelona.cat/service/extern/vendes/clientsPortType/v01?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Clients(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Clients(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Clients() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Clients(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Clients(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Clients(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ClientsPortType
     */
    @WebEndpoint(name = "ClientsSOAP")
    public ClientsPortType getClientsSOAP() {
        return super.getPort(ClientsSOAP, ClientsPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientsPortType
     */
    @WebEndpoint(name = "ClientsSOAP")
    public ClientsPortType getClientsSOAP(WebServiceFeature... features) {
        return super.getPort(ClientsSOAP, ClientsPortType.class, features);
    }

}
