additionalProperties: false
type: object
required:
  - id
  - name
  - entity
  - model
  - defaultLanguage
  - selectedLanguageIds
properties:
  id:
    type: number
    format: int64
  name:
    type: string
  entity:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
  model:
    $ref: product-ticket-template-model.yml
  defaultLanguage:
    type: integer
    format: int64
    description: ID of the default language for this template
    nullable: true
  selectedLanguageIds:
    type: array
    items:
      type: integer
      format: int64
    description: List of selected language IDs for this template
    nullable: true

