additionalProperties: false
type: object
required:
  - id
  - name
  - description
  - type
  - target
  - file_name
properties:
  id:
    type: integer
  name:
    type: string
  description:
    type: string
  type:
    $ref: product-ticket-model-type.yml
  target:
    $ref: product-ticket-model-target.yml
  file_name:
    type: string
