additionalProperties: false
type: object
required:
  - id
  - name
  - entity
  - model
properties:
  id:
    type: number
    format: int64
  name:
    type: string
  entity:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
  model:
    $ref: product-ticket-template-model.yml

