package es.onebox.mgmt.datasources.ms.promotion;

import es.onebox.core.exception.ErrorCode;
import es.onebox.mgmt.exception.ApiMgmtPromotionErrorCode;

import java.util.HashMap;
import java.util.Map;

public class MsPromotionMapping {

    protected static final int TIMEOUT = 60000;

    protected static final String API_VERSION = "v1";
    protected static final String BASE_PATH = "/ms-promotion-api/" + API_VERSION;

    protected static final String EVENT_PROMOTIONS = "/events/{eventId}/promotions";
    protected static final String EVENT_PROMOTIONS_CLONE = "/events/{eventId}/promotions/clone";
    protected static final String EVENT_PROMOTION = "/events/{eventId}/promotions/{promotionId}";
    protected static final String EVENT_PROMOTION_CHANNELS = EVENT_PROMOTION + "/channels";
    protected static final String EVENT_PROMOTION_SESSIONS = EVENT_PROMOTION + "/sessions";
    protected static final String EVENT_PROMOTION_PRICE_TYPES = EVENT_PROMOTION + "/price-types";
    protected static final String EVENT_PROMOTION_RATES = EVENT_PROMOTION + "/rates";
    protected static final String EVENT_PROMOTION_PACKS = EVENT_PROMOTION + "/packs";
    protected static final String EVENT_PROMOTIONS_RESET_PROMOTION_DISCOUNT_CONFIG = EVENT_PROMOTIONS + "/reset-promotion-discount-config";

    protected static final String CHANNEL_PROMOTIONS = "/channels/{channelId}/promotions";
    protected static final String CHANNEL_PROMOTION = "/channels/{channelId}/promotions/{promotionId}";
    protected static final String CHANNEL_PROMOTION_EVENTS = CHANNEL_PROMOTION + "/events";
    protected static final String CHANNEL_PROMOTION_SESSIONS = CHANNEL_PROMOTION + "/sessions";
    protected static final String CHANNEL_PROMOTION_PRICE_TYPES = CHANNEL_PROMOTION + "/price-types";
    protected static final String CHANNEL_PROMOTION_COMMUNICATION_ELEMENTS = CHANNEL_PROMOTION + "/communication-elements";

    protected static final String PRODUCT_PROMOTIONS = "/products/{productId}/promotions";
    protected static final String PRODUCT_PROMOTION = "/products/{productId}/promotions/{promotionId}";

    protected static final String EVENT_COMMUNICATION_ELEMENTS = EVENT_PROMOTION + "/communication-elements";

    protected static final Map<String, ErrorCode> ERROR_CODES = new HashMap<>();

    static {
        ERROR_CODES.put("COLLECTIVE_SELF_MANAGEMENT_LIMIT_REQUIRED", ApiMgmtPromotionErrorCode.COLLECTIVE_VALIDATION_LIMIT_REQUIRED);
        ERROR_CODES.put("INVALID_PARAM", ApiMgmtPromotionErrorCode.BAD_REQUEST_PARAMETER);
        ERROR_CODES.put("EVENT_PROMOTION_NOT_FOUND", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_NOT_FOUND);
        ERROR_CODES.put("EVENT_PROMOTION_NAME_MANDATORY", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_NAME_MANDATORY);
        ERROR_CODES.put("EVENT_PROMOTION_NAME_INVALID", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_NAME);
        ERROR_CODES.put("EVENT_PROMOTION_TYPE_MANDATORY", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_TYPE_MANDATORY);
        ERROR_CODES.put("EVENT_PROMOTION_NAME_EXISTS", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_USED_NAME);
        ERROR_CODES.put("EVENT_PROMOTION_AUTOMATIC_TYPE_BAD_REQUEST", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_AUTOMATIC_TYPE_BAD_REQUEST);
        ERROR_CODES.put("EVENT_PROMOTION_NON_AUTOMATIC_TYPE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_NON_AUTOMATIC_TYPE_INVALID_PARAMS);
        ERROR_CODES.put("EVENT_PROMOTION_AUTOMATIC_TYPE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_AUTOMATIC_TYPE_INVALID_PARAMS);
        ERROR_CODES.put("EVENT_PROMOTION_INVALID_VALUE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_VALUE);
        ERROR_CODES.put("EVENT_PROMOTION_INVALID_DISCOUNT_TYPE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_DISCOUNT_TYPE);
        ERROR_CODES.put("EVENT_PROMOTION_PRICE_TYPES_ASSIGNMENT_NOT_MODIFIABLE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_PRICE_TYPES_ASSIGNMENT_NOT_MODIFIABLE);
        ERROR_CODES.put("EVENT_PROMOTION_PACK_INVALID_PACK_IDS", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_PACK_INVALID_PACK_IDS);
        ERROR_CODES.put("SESSION_NOT_FOUND", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_SESSION_ID);
        ERROR_CODES.put("PRICE_TYPE_NOT_FOUND", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_PRICE_TYPE_ID);
        ERROR_CODES.put("RATE_NOT_FOUND", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_RATE_ID);
        ERROR_CODES.put("EVENT_CHANNEL_RELATIONSHIP_NOT_EXIST", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_CHANNEL_ID);
        ERROR_CODES.put("ENABLE_EVENT_PROMOTION_INVALID_CHANNELS_ASSIGNMENT",
                ApiMgmtPromotionErrorCode.ENABLE_EVENT_PROMOTION_INVALID_CHANNELS_ASSIGNMENT);
        ERROR_CODES.put("ENABLE_EVENT_PROMOTION_INVALID_SESSIONS_ASSIGNMENT",
                ApiMgmtPromotionErrorCode.ENABLE_EVENT_PROMOTION_INVALID_SESSIONS_ASSIGNMENT);
        ERROR_CODES.put("ENABLE_EVENT_PROMOTION_INVALID_PRICE_TYPES_ASSIGNMENT",
                ApiMgmtPromotionErrorCode.ENABLE_EVENT_PROMOTION_INVALID_PRICE_TYPES_ASSIGNMENT);
        ERROR_CODES.put("ENABLE_EVENT_PROMOTION_INVALID_RATES_ASSIGNMENT",
                ApiMgmtPromotionErrorCode.ENABLE_EVENT_PROMOTION_INVALID_RATES_ASSIGNMENT);
        ERROR_CODES.put("ENABLE_EVENT_PROMOTION_INVALID_DISCOUNT", ApiMgmtPromotionErrorCode.ENABLE_EVENT_PROMOTION_INVALID_DISCOUNT);
        ERROR_CODES.put("ENABLE_EVENT_PROMOTION_INVALID_VALIDITY_PERIOD",
                ApiMgmtPromotionErrorCode.ENABLE_EVENT_PROMOTION_INVALID_VALIDITY_PERIOD);
        ERROR_CODES.put("EVENT_PROMOTION_INVALID_DISCOUNT_VALUE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_DISCOUNT_VALUE);
        ERROR_CODES.put("ENTITY_PROMOTION_NOT_FOUND", ApiMgmtPromotionErrorCode.ENTITY_PROMOTION_NOT_FOUND);
        ERROR_CODES.put("ENABLE_EVENT_PROMOTION_REQUIRED_CONTENTS", ApiMgmtPromotionErrorCode.ENABLE_EVENT_PROMOTION_INVALID_CONTENTS);

        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_SESSION_GREATER_THAN_PROMOTION",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_SESSION_GREATER_THAN_PROMOTION);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MAX_PURCHASE_GREATER_THAN_PROMOTION",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MAX_PURCHASE_GREATER_THAN_PROMOTION);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MAX_PURCHASE_GREATER_THAN_SESSION",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MAX_PURCHASE_GREATER_THAN_SESSION);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MIN_PURCHASE_GREATER_THAN_PROMOTION",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MIN_PURCHASE_GREATER_THAN_PROMOTION);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MIN_PURCHASE_GREATER_THAN_SESSION",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MIN_PURCHASE_GREATER_THAN_SESSION);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MIN_PURCHASE_GREATER_THAN_MAX_PURCHASE",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MIN_PURCHASE_GREATER_THAN_MAX_PURCHASE);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_GROUPS_GREATER_THAN_MAX_PURCHASE",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_GROUPS_GREATER_THAN_MAX_PURCHASE);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MIN_PURCHASE_NOT_PROMOTION_MULTIPLE",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MIN_PURCHASE_NOT_PROMOTION_MULTIPLE);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MIN_PURCHASE_NOT_SESSION_MULTIPLE",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MIN_PURCHASE_NOT_SESSION_MULTIPLE);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_MIN_PURCHASE_NOT_PURCHASE_MULTIPLE",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_MIN_PURCHASE_NOT_PURCHASE_MULTIPLE);
        ERROR_CODES.put("EVENT_PROMOTION_LIMITS_INVALID_STATE",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMITS_INVALID_STATE);
        ERROR_CODES.put("EVENT_PROMOTION_COLLECTIVE_INVALID", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_COLLECTIVE_INVALID);
        ERROR_CODES.put("COLLECTIVE_ID_INVALID", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_INVALID_COLLECTIVE_ID);
        ERROR_CODES.put("MISSING_COLLECTIVE_ID", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_REQUIRED_COLLECTIVE_ID);
        ERROR_CODES.put("COLLECTIVE_MUST_VALIDATE_IN_OFFICE_BOX", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_COLLECTIVE_INVALID_STATE);
        ERROR_CODES.put("PROMOTION_CAN_NOT_BE_RESTRICTIVE_SALE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_CAN_NOT_BE_RESTRICTIVE_SALE);
        ERROR_CODES.put("SHOPPING_CART_COLLECTIVE_NOT_COMPATIBLE_WITH_PROMOTIONS",
                ApiMgmtPromotionErrorCode.SHOPPING_CART_COLLECTIVE_NOT_COMPATIBLE_WITH_PROMOTIONS);
        ERROR_CODES.put("COLLECTIVE_SELF_MANAGEMENT_NOT_ALLOWED", ApiMgmtPromotionErrorCode.COLLECTIVE_SELF_MANAGEMENT_NOT_ALLOWED);
        ERROR_CODES.put("CHANNEL_PROMOTION_BAD_REQUEST", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_BAD_REQUEST);
        ERROR_CODES.put("CHANNEL_PROMOTION_NOT_FOUND", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_NOT_FOUND);
        ERROR_CODES.put("CHANNEL_PROMOTION_NAME_EXISTS", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_NAME_EXISTS);
        ERROR_CODES.put("CHANNEL_PROMOTION_COLLECTIVE_TYPE", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_COLLECTIVE_TYPE);
        ERROR_CODES.put("CHANNEL_PROMOTION_AUTOMATIC_TYPE", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_AUTOMATIC_TYPE);
        ERROR_CODES.put("CHANNEL_PROMOTION_INVALID_DISCOUNT", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_INVALID_DISCOUNT);
        ERROR_CODES.put("CHANNEL_PROMOTION_INVALID_MIN_AMOUNT_LIMIT", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_INVALID_MIN_AMOUNT_LIMIT);
        ERROR_CODES.put("CHANNEL_PROMOTION_INVALID_DATES", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_INVALID_DATES);
        ERROR_CODES.put("CHANNEL_PROMOTION_TYPE_MANDATORY", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_TYPE_MANDATORY);
        ERROR_CODES.put("CHANNEL_PROMOTION_AMOUNT_MANDATORY", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_AMOUNT_MANDATORY);
        ERROR_CODES.put("CHANNEL_PROMOTION_BAD_CONFIG_PACKS_SESSIONS",
                ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_BAD_CONFIG_PACKS_SESSIONS);
        ERROR_CODES.put("CHANNEL_PROMOTION_INVALID_PRICE_TYPE", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_INVALID_PRICE_TYPE);
        ERROR_CODES.put("CHANNEL_NOT_FOUND", ApiMgmtPromotionErrorCode.CHANNEL_NOT_FOUND);
        ERROR_CODES.put("CHANNEL_PROMOTION_COLLECTIVE_TYPE_INVALID", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_COLLECTIVE_TYPE_INVALID);
        ERROR_CODES.put("ENABLE_CHANNEL_PROMOTION_INVALID_EVENTS_ASSIGNMENT",
                ApiMgmtPromotionErrorCode.ENABLE_CHANNEL_PROMOTION_INVALID_EVENTS_ASSIGNMENT);
        ERROR_CODES.put("ENABLE_CHANNEL_PROMOTION_INVALID_SESSIONS_ASSIGNMENT",
                ApiMgmtPromotionErrorCode.ENABLE_CHANNEL_PROMOTION_INVALID_SESSIONS_ASSIGNMENT);
        ERROR_CODES.put("ENABLE_CHANNEL_PROMOTION_INVALID_DISCOUNT", ApiMgmtPromotionErrorCode.ENABLE_CHANNEL_PROMOTION_INVALID_DISCOUNT);
        ERROR_CODES.put("ENABLE_CHANNEL_PROMOTION_INVALID_VALIDITY_PERIOD",
                ApiMgmtPromotionErrorCode.ENABLE_CHANNEL_PROMOTION_INVALID_VALIDITY_PERIOD);
        ERROR_CODES.put("ENABLE_CHANNEL_PROMOTION_REQUIRED_CONTENTS", ApiMgmtPromotionErrorCode.ENABLE_CHANNEL_PROMOTION_REQUIRED_CONTENTS);
        ERROR_CODES.put("CHANNEL_RELATIONSHIP_NOT_EXIST", ApiMgmtPromotionErrorCode.PROMOTION_CHANNEL_RELATIONSHIP_NOT_SUPPORTED);
        ERROR_CODES.put("EVENT_NOT_FOUND_OR_INVALID_EVENT_STATE", ApiMgmtPromotionErrorCode.EVENT_NOT_FOUND_OR_INVALID_EVENT_STATE);
        ERROR_CODES.put("SESSION_NOT_FOUND_OR_INVALID_SESSION_STATE", ApiMgmtPromotionErrorCode.SESSION_NOT_FOUND_OR_INVALID_SESSION_STATE);
        ERROR_CODES.put("EVENT_SESSION_CONFLICT", ApiMgmtPromotionErrorCode.EVENT_SESSION_CONFLICT);
        ERROR_CODES.put("EVENT_PROMOTION_PRESALE_NOT_MODIFIABLE_PARAM",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_PRESALE_NOT_MODIFIABLE_PARAM);
        ERROR_CODES.put("EVENT_PROMOTION_ENABLE_DUPLICATE_PRESALE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_ENABLE_DUPLICATE_PRESALE);
        ERROR_CODES.put("EVENT_PROMOTION_CHANNEL_ASSIGNMENT_NOT_SUPPORTED",
                ApiMgmtPromotionErrorCode.EVENT_PROMOTION_CHANNEL_ASSIGNMENT_NOT_SUPPORTED);
        ERROR_CODES.put("EVENT_PROMOTION_COLLECTIVE_REQUIRED_FOR_PRESALE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_COLLECTIVE_REQUIRED_FOR_PRESALE);
        ERROR_CODES.put("RESTRICTIVE_SALE_MANDATORY_FOR_PRESALE_PROMOTION", ApiMgmtPromotionErrorCode.RESTRICTIVE_SALE_MANDATORY_FOR_PRESALE_PROMOTION);
        ERROR_CODES.put("PRESALE_PROMO_ON_AVET_EVENT", ApiMgmtPromotionErrorCode.PRESALE_PROMO_ON_AVET_EVENT);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_PURCHASE_MAX_NOT_TICKET_GROUP_MIN_MULTIPLE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_PURCHASE_MAX_NOT_TICKET_GROUP_MIN_MULTIPLE);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_PROMOTION_MAX_NOT_TICKET_GROUP_MIN_MULTIPLE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_PROMOTION_MAX_NOT_TICKET_GROUP_MIN_MULTIPLE);
        ERROR_CODES.put("EVENT_PROMOTION_LIMIT_SESSION_MAX_NOT_TICKET_GROUP_MIN_MULTIPLE", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_LIMIT_SESSION_MAX_NOT_TICKET_GROUP_MIN_MULTIPLE);
        ERROR_CODES.put("EVENT_PROMOTION_BASE_PRICE_RANGES_NOT_VALID", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_BASE_PRICE_RANGES_NOT_VALID);
        ERROR_CODES.put("EVENT_PROMOTION_BASE_PRICE_VALUE_NOT_VALID", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_BASE_PRICE_VALUE_NOT_VALID);
        ERROR_CODES.put("SESSION_COLLECTIVE_LIMIT_REQUIRES_COLLECTIVE_EXTERNAL_INTERNAL", ApiMgmtPromotionErrorCode.SESSION_COLLECTIVE_LIMIT_REQUIRES_COLLECTIVE_EXTERNAL_INTERNAL);
        ERROR_CODES.put("SESSION_COLLECTIVE_LIMIT_INCOMPATIBLE_AUTOMATIC", ApiMgmtPromotionErrorCode.SESSION_COLLECTIVE_LIMIT_INCOMPATIBLE_AUTOMATIC);
        ERROR_CODES.put("EVENT_PROMOTION_BAD_REQUEST", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_BAD_REQUEST);
        ERROR_CODES.put("ENTITY_PROMOTION_TEMPLATE_NOT_ACCESIBLE", ApiMgmtPromotionErrorCode.ENTITY_PROMOTION_TEMPLATE_NOT_ACCESIBLE);
        ERROR_CODES.put("ENTITY_PROMOTION_TEMPLATE_NAME_EXISTS", ApiMgmtPromotionErrorCode.ENTITY_PROMOTION_TEMPLATE_NAME_EXISTS);
        ERROR_CODES.put("CHANNEL_PROMOTION_NOT_AVAILABLE", ApiMgmtPromotionErrorCode.CHANNEL_PROMOTION_NOT_AVAILABLE);
        ERROR_CODES.put("ENTITY_NOT_FOUND", ApiMgmtPromotionErrorCode.ENTITY_NOT_FOUND);
        ERROR_CODES.put("EVENT_PROMOTION_CURRENCY_NOT_MATCH", ApiMgmtPromotionErrorCode.EVENT_PROMOTION_CURRENCY_NOT_MATCH);
        ERROR_CODES.put("PRODUCT_PROMOTION_NOT_FOUND", ApiMgmtPromotionErrorCode.PRODUCT_PROMOTION_NOT_FOUND);
        ERROR_CODES.put("PRODUCT_PROMOTION_BAD_REQUEST", ApiMgmtPromotionErrorCode.PRODUCT_PROMOTION_BAD_REQUEST);
        ERROR_CODES.put("PRODUCT_PROMOTION_ACTIVATOR_NOT_SUPPORTED", ApiMgmtPromotionErrorCode.PRODUCT_PROMOTION_ACTIVATOR_NOT_SUPPORTED);
        ERROR_CODES.put("ENTITY_SECONDARY_MARKET_NOT_ACTIVE", ApiMgmtPromotionErrorCode.ENTITY_SECONDARY_MARKET_NOT_ACTIVE);
        ERROR_CODES.put("MISSING_RATES_IN_PROMOTION_CONDITIONS", ApiMgmtPromotionErrorCode.MISSING_RATES_IN_PROMOTION_CONDITIONS);
        ERROR_CODES.put("INVALID_RATES_IN_PROMOTION_CONDITIONS", ApiMgmtPromotionErrorCode.INVALID_RATES_IN_PROMOTION_CONDITIONS);
        ERROR_CODES.put("INVALID_CUSTOMER_TYPES_IN_PROMOTION_CONDITIONS", ApiMgmtPromotionErrorCode.INVALID_CUSTOMER_TYPES_IN_PROMOTION_CONDITIONS);
        ERROR_CODES.put("CUSTOMER_TYPE_NOT_FOUND_IN_ENTITY", ApiMgmtPromotionErrorCode.CUSTOMER_TYPE_NOT_FOUND_IN_ENTITY);
        ERROR_CODES.put("DUPLICATED_RATES_IN_PROMOTION_CONDITIONS", ApiMgmtPromotionErrorCode.DUPLICATED_RATES_IN_PROMOTION_CONDITIONS);
        ERROR_CODES.put("DUPLICATED_CUSTOMER_TYPES_IN_PROMOTION_CONDITIONS", ApiMgmtPromotionErrorCode.DUPLICATED_CUSTOMER_TYPES_IN_PROMOTION_CONDITIONS);

    }

}