//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.sales.data;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for EventTickets complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventTickets">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idEvent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tickets" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventTickets", propOrder = {
    "idEvent",
    "tickets"
})
public class EventTickets
    implements Serializable
{

    protected int idEvent;
    protected int tickets;

    /**
     * Gets the value of the idEvent property.
     * 
     */
    public int getIdEvent() {
        return idEvent;
    }

    /**
     * Sets the value of the idEvent property.
     * 
     */
    public void setIdEvent(int value) {
        this.idEvent = value;
    }

    /**
     * Gets the value of the tickets property.
     * 
     */
    public int getTickets() {
        return tickets;
    }

    /**
     * Sets the value of the tickets property.
     * 
     */
    public void setTickets(int value) {
        this.tickets = value;
    }

}
