//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.sales.data;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.sales.data package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SearchFilter_QNAME = new QName("http://www.oneboxtm.es/ns/sales/data", "searchFilter");
    private final static QName _ItemFilter_QNAME = new QName("http://www.oneboxtm.es/ns/sales/data", "itemFilter");
    private final static QName _Order_QNAME = new QName("http://www.oneboxtm.es/ns/sales/data", "Order");
    private final static QName _Paginate_QNAME = new QName("http://www.oneboxtm.es/ns/sales/data", "Paginate");
    private final static QName _SummaryField_QNAME = new QName("http://www.oneboxtm.es/ns/sales/data", "summaryField");
    private final static QName _FieldValue_QNAME = new QName("http://www.oneboxtm.es/ns/sales/data", "fieldValue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.sales.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link OperationsResult }
     * 
     */
    public OperationsResult createOperationsResult() {
        return new OperationsResult();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link ItemFilter }
     * 
     */
    public ItemFilter createItemFilter() {
        return new ItemFilter();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link SearchFilter }
     * 
     */
    public SearchFilter createSearchFilter() {
        return new SearchFilter();
    }

    /**
     * Create an instance of {@link Paginate }
     * 
     */
    public Paginate createPaginate() {
        return new Paginate();
    }

    /**
     * Create an instance of {@link SummaryField }
     * 
     */
    public SummaryField createSummaryField() {
        return new SummaryField();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link AttributeValues }
     * 
     */
    public AttributeValues createAttributeValues() {
        return new AttributeValues();
    }

    /**
     * Create an instance of {@link OperationProfile }
     * 
     */
    public OperationProfile createOperationProfile() {
        return new OperationProfile();
    }

    /**
     * Create an instance of {@link EventTickets }
     * 
     */
    public EventTickets createEventTickets() {
        return new EventTickets();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/sales/data", name = "searchFilter")
    public JAXBElement<SearchFilter> createSearchFilter(SearchFilter value) {
        return new JAXBElement<SearchFilter>(_SearchFilter_QNAME, SearchFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/sales/data", name = "itemFilter")
    public JAXBElement<ItemFilter> createItemFilter(ItemFilter value) {
        return new JAXBElement<ItemFilter>(_ItemFilter_QNAME, ItemFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/sales/data", name = "Order")
    public JAXBElement<Order> createOrder(Order value) {
        return new JAXBElement<Order>(_Order_QNAME, Order.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Paginate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/sales/data", name = "Paginate")
    public JAXBElement<Paginate> createPaginate(Paginate value) {
        return new JAXBElement<Paginate>(_Paginate_QNAME, Paginate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SummaryField }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/sales/data", name = "summaryField")
    public JAXBElement<SummaryField> createSummaryField(SummaryField value) {
        return new JAXBElement<SummaryField>(_SummaryField_QNAME, SummaryField.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.oneboxtm.es/ns/sales/data", name = "fieldValue")
    public JAXBElement<FieldValue> createFieldValue(FieldValue value) {
        return new JAXBElement<FieldValue>(_FieldValue_QNAME, FieldValue.class, null, value);
    }

}
