additionalProperties: false
type: object
required:
  - id
  - status
  - date
  - channel
  - product
properties:
  id:
    type: integer
    format: int64
  status:
    $ref: sale-request-status.yml
  date:
    type: string
    format: date-time
  languages:
    type: object
    required:
      - default
      - selected
    properties:
      default:
        type: string
        description: Language code
      selected:
        type: array
        items:
          type: string
          description: Language code
  channel:
    $ref: channel-sale-request-detail.yml
  product:
    $ref: product-sale-request-detail.yml