additionalProperties: false
type: object
properties:
  product_id:
    type: integer
    format: int64
  product_name:
    type: string
  product_type:
    type: string
    enum:
      - SIMPLE
      - VARIANT
  entity:
    $ref: ../../common/idname.yml
  contact_person:
    type: object
    properties:
      name:
        type: string
      surname:
        type: string
      email:
        type: string
        format: email
      phone:
        type: string
  currency_code:
    type: string
    description: ISO 4217 currency code of the user entity
    example: EUR
