package es.onebox.mgmt.seasontickets.enums;

public enum SeasonTicketLinkSeatReasonDTO {
    SEAT_SOLD_IN_SEASON_TICKET,
    SEAT_SOLD_IN_INDIVIDUAL_SESSION,
    SEAT_ALREADY_LINKED,
    SEAT_ALREADY_NOT_LINKED,
    SEAT_NOT_COMPATIBLE,
    SEAT_BLOCKED_IN_INDIVIDUAL_SESSION,
    SEAT_NOT_AVAILABLE_IN_INDIVIDUAL_SESSION,
    SEAT_KILLED_IN_INDIVIDUAL_SESSION
}
