package es.onebox.mgmt.exception;

import es.onebox.core.exception.ErrorCode;
import org.springframework.http.HttpStatus;

import java.util.stream.Stream;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.CONFLICT;
import static org.springframework.http.HttpStatus.GATEWAY_TIMEOUT;
import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.http.HttpStatus.PRECONDITION_FAILED;

public enum ApiMgmtErrorCode implements FormattableErrorCode {

    GENERIC_ERROR(INTERNAL_SERVER_ERROR, "Generic error, something really wrong happened"),
    PERSISTENCE_ERROR(INTERNAL_SERVER_ERROR, "Error persisting data"),
    NOT_FOUND(HttpStatus.NOT_FOUND, "Item not found"),
    UNSUPPORTED_OPERATION(CONFLICT, "Operation not supported"),
    BAD_REQUEST_PARAMETER(BAD_REQUEST, "Some parameters are incorrect or invalid", true),
    FIX_OR_PERCENTAGE_ERROR(BAD_REQUEST, "Must choose percentage or fixed rate"),
    CONFIGURATION_NOT_FOUND(HttpStatus.NOT_FOUND, "Configuration not found"),
    TIMEOUT(GATEWAY_TIMEOUT, "The request could not be completed"),
    FORBIDDEN_RESOURCE(HttpStatus.FORBIDDEN, "Denied for permissions. The user does not have required role"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "Invalid credentials"),
    UNAUTHORIZED_ACCESS(HttpStatus.UNAUTHORIZED, "%s"),
    AUTH_OPERATOR_NOT_FOUND(HttpStatus.FORBIDDEN, "Operator not found"),
    OPERATOR_MANDATORY(BAD_REQUEST, "Operator cannot be null"),
    AUTH_OPERATOR_INACTIVE(HttpStatus.FORBIDDEN, "Operator is inactive"),
    AUTH_ENTITY_NOT_FOUND(HttpStatus.FORBIDDEN, "Entity not found"),
    AUTH_ENTITY_INACTIVE(HttpStatus.FORBIDDEN, "Entity is inactive"),
    COMMUNICATION_ERROR(HttpStatus.GATEWAY_TIMEOUT, "Error in the communication with AVET"),
    AVET_DATA_INCONSISTENCY(HttpStatus.CONFLICT, "AVET data inconsistency"),
    AVET_CAPACITY_NOT_ALLOWED(PRECONDITION_FAILED, "AVET capacity is not allowed by the club"),
    AVET_CAPACITY_NOT_ENABLED(PRECONDITION_FAILED, "AVET capacity is not enabled"),
    AVET_CAPACITY_NOT_LOADED(PRECONDITION_FAILED, "AVET capacity is not loaded"),
    EXTERNAL_CAPACITY_IN_USE_BY_EVENT(PRECONDITION_FAILED, "External capacity is being used in an event"),
    EXTERNAL_CAPACITY_IN_USE_BY_VENUE_TEMPLATE(PRECONDITION_FAILED, "External capacity is being used in a venue template"),
    CHANNEL_STRUCTURE_INVALID_VALUE(BAD_REQUEST, "There ara invalid values in the field: %s"),
    TOO_MANY_RESULTS(CONFLICT, "There are more than 1 item for filtered request"),
    NOT_IMPLEMENTED(HttpStatus.NOT_IMPLEMENTED, "Operation not implemented"),
    INVALID_PARAM_FORMAT(HttpStatus.BAD_REQUEST, "Invalid '%s' format: '%s'"),
    REQUEST_RESOURCE_CONFLICT(HttpStatus.CONFLICT, "The request could not be completed due to a conflict with the current state of the target resource."),

    VENUE_TEMPLATE_NOT_MATCH_EVENT(BAD_REQUEST, "Venue template not from this event"),
    VENUE_TEMPLATE_ITEM_NOT_MATCH(BAD_REQUEST, "Item is not from this venue template"),
    VENUE_TEMPLATE_WRONG_EXPORT_TYPE(BAD_REQUEST, "Incorrect venue template export type"),
    VENUE_TEMPLATE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Venue template already exists for the indicated entity and inventory"),
    ST_VENUE_TEMPLATE_ID_MANDATORY(HttpStatus.CONFLICT, "Season ticket venue template id must be specified in additionalConfig"),
    EVENT_ALREADY_EXISTS(HttpStatus.CONFLICT, "Event already exists for the indicated entity"),
    ACTIVITY_ALREADY_EXISTS(HttpStatus.CONFLICT, "Activity already exists for the indicated entity"),
    ST_EVENT_ALREADY_EXISTS(HttpStatus.CONFLICT, "Season ticket event already exists for the indicated entity"),
    EVENT_CHANNEL_CURRENCY_NOT_MATCH(CONFLICT, "Event currency not match with channel currencies"),
    CURRENCY_NOT_MATCH_OPERATOR(CONFLICT, "currency not match with operator currencies"),
    CURRENCY_NOT_MATCH_EVENT(CONFLICT, "currency not match with event currencies"),
    CURRENCY_DEFAULT_EXCHANGE_REQUIRED(CONFLICT, "Currency default exchange is required"),
    SESSION_ALREADY_EXISTS(HttpStatus.CONFLICT, "Session already exists for the indicated entity"),
    SESSION_ALREADY_STARTED(PRECONDITION_FAILED, "Session already started"),
    INVENTORY_ID_MANDATORY(HttpStatus.CONFLICT, "Inventory id must be specified in additionalConfig"),
    ST_INVENTORY_ID_MANDATORY(HttpStatus.CONFLICT, "Season ticket inventory id must be specified in additionalConfig"),
    EXTERNAL_SESSION_ID_MANDATORY(HttpStatus.CONFLICT, "External session id must be specified in additionalConfig"),
    EXTERNAL_SESSION_NOT_RELATED_TO_EXTERNAL_EVENT(HttpStatus.CONFLICT, "External session is not related to external event"),
    VENUE_TEMPLATE_MAPPING_NOT_FOUND(HttpStatus.CONFLICT, "Venue template mapping wasn't found"),
    EVENT_MAPPING_NOT_FOUND(HttpStatus.CONFLICT, "Event mapping wasn't found"),
    SEAT_MAPPING_CONFLICT(HttpStatus.CONFLICT, "Conflict while retrieving external seat mapping"),
    EXPORT_STATUS_NOT_FOUND(HttpStatus.NOT_FOUND, "Export status not found for provided ID"),
    AMQP_PUSH_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, "Unable to send message to the queue"),
    EXPORT_UPLOAD_EXCEPTION(HttpStatus.NOT_FOUND, "Error uploading report to S3"),
    INVALID_EXPORT_TYPE(BAD_REQUEST, "Export type is not correct"),
    INVALID_VENUE_TEMPLATE_TYPE_FOR_EXPORT(BAD_REQUEST, "Venue template type is not correct for export"),

    ENTITY_ID_MANDATORY(BAD_REQUEST, "Entity ID is mandatory"),
    ENTITY_NOT_FOUND(HttpStatus.NOT_FOUND, "Entity not found"),
    OPERATOR_NOT_FOUND(HttpStatus.NOT_FOUND, "Operator not found"),
    OPERATOR_TAX_NOT_FOUND(HttpStatus.NOT_FOUND, "Tax not found"),
    ENTITY_INACTIVE(CONFLICT, "Entity is inactive"),
    INVALID_ENTITY_ID(CONFLICT, "Entity id is invalid"),
    INVALID_OPERATOR_ID(CONFLICT, "Operator id is invalid"),
    OPERATOR_FILTER_NOT_ALLOWED(CONFLICT, "Only Super Operator can filter by operator"),
    ENTITY_ADMIN_TYPES_CONFLICT(CONFLICT, "Entity admin only can be ENTITY_ADMIN type"),
    ENTITY_ADMIN_MANDATORY_MANAGED(CONFLICT, "Entity admin must manage at least one entity"),
    ENTITY_IS_NOT_ENTITY_ADMIN(CONFLICT, "Entity must be entity Admin"),
    PRODUCER_NOT_FOUND(HttpStatus.NOT_FOUND, "Producer not found"),
    INVALID_SALE_REQUEST_STATUS_TRANSITION(HttpStatus.NOT_FOUND, "Invalid sale request status transition"),
    SIMPLIFIED_INVOICE_CAN_NOT_BE_DISABLED(BAD_REQUEST, "Simplified invoice can not be disabled"),
    NIF_MODIFICATION_DISABLED(BAD_REQUEST, "Nif modification is disabled"),
    CHANNEL_ID_MANDATORY(HttpStatus.BAD_REQUEST, "Channel ID is mandatory"),
    CHANNEL_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel not found"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "User not found"),
    USER_NOT_MODIFIABLE(CONFLICT, "User parameter not modifiable"),
    ROLE_NOT_FOUND(HttpStatus.NOT_FOUND, "Role not found"),
    INVALID_ROLE(HttpStatus.BAD_REQUEST, "Invalid Role"),
    INVALID_OB_SECTOR(HttpStatus.BAD_REQUEST, "Invalid Onebox sector id"),
    CALENDAR_NOT_FOUND(HttpStatus.NOT_FOUND, "Calendar not found"),
    ATTRIBUTE_NOT_FOUND(HttpStatus.NOT_FOUND, "Attribute not found"),
    EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Event not found"),
    SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "Session not found"),
    EVENT_CURRENCY_NOT_MATCH_OPERATOR(BAD_REQUEST, "Event Currency not match with operator currencies"),
    VOUCHER_CURRENCY_NOT_MATCH_OPERATOR(BAD_REQUEST, "Voucher Currency not match with operator currencies"),
    INVALID_VOUCHER_GROUP(BAD_REQUEST, "Invalid voucher group"),
    EVENT_UPDATE_EVENT_CURRENCY_IS_PUBLISHED(BAD_REQUEST, "Event Currency Can´t change if event is published"),
    EVENT_UPDATE_EVENT_CURRENCY_HAS_SALES(BAD_REQUEST, "Event Currency Can´t change if event has sales"),
    EVENT_IS_NOT_AVET(HttpStatus.NOT_FOUND, "Event is not AVET"),
    EVENT_IS_NOT_SGA(HttpStatus.NOT_FOUND, "Event is not SGA"),
    REPEATED_EXTERNAL_DESCRIPTION(HttpStatus.CONFLICT, "In event external description cannot be repeated"),
    ENTITY_IS_NOT_AVET(HttpStatus.NOT_FOUND, "Entity is not AVET"),
    SALE_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "Sale request not found"),
    INVALID_EVENT_ID(BAD_REQUEST, "Event id is invalid"),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "Category not found"),
    VENUE_TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Venue template not found"),
    VENUE_TEMPLATE_IS_NOT_AVET(BAD_REQUEST, "Venue template is not AVET"),
    VENUE_TEMPLATE_VIEW_NOT_FOUND(HttpStatus.NOT_FOUND, "Venue template container not found"),
    VENUE_TEMPLATE_PRICE_NOT_FOUND(HttpStatus.NOT_FOUND, "Venue template price not found"),
    VENUE_TEMPLATE_PRICE_REQUIRED(BAD_REQUEST, "Venue template price ticket type is required"),
    VENUE_TEMPLATE_SECTOR_NOT_FOUND(HttpStatus.NOT_FOUND, "Venue template sector not found"),
    VENUE_TEMPLATE_NNZONE_NOT_FOUND(HttpStatus.NOT_FOUND, "Venue template not numbered zone not found"),
    VENUE_TEMPLATE_CREATION_FORBIDDEN(HttpStatus.FORBIDDEN, "Venue template creation forbidden"),
    VENUE_TEMPLATE_NAME_CONFLICT(HttpStatus.FORBIDDEN, "Venue template name already in use"),
    TOUR_NOT_FOUND(HttpStatus.NOT_FOUND, "Tour not found"),
    TICKET_TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Ticket template not found"),
    TICKET_TEMPLATE_MODEL_NOT_FOUND(HttpStatus.NOT_FOUND, "Ticket template model not found"),
    TICKET_TEMPLATE_NOT_REMOVABLE(HttpStatus.FORBIDDEN, "Default ticket template not removable"),
    TICKET_TEMPLATE_INVALID_DEFAULT_LANGUAGE(HttpStatus.PRECONDITION_FAILED, "Ticket template language config not valid"),
    TICKET_TEMPLATE_LITERAL_NOT_FOUND(HttpStatus.NOT_FOUND, "Ticket template literal not found"),
    TICKET_TEMPLATE_FORMAT_NOT_AVAILABLE(HttpStatus.PRECONDITION_FAILED, "Ticket template format not available"),
    TICKET_REPORT_NOT_GENERATED(HttpStatus.INTERNAL_SERVER_ERROR, "Error while filling report"),

    SHORTNAME_CONFLICT(CONFLICT, "Shortname already in use"),
    NAME_CONFLICT(CONFLICT, "Name already in use"),
    EMAIL_CONFLICT(CONFLICT, "Email already in use"),
    USERNAME_CONFLICT(CONFLICT, "Username already in use"),
    CLUBCODE_CONFLICT(CONFLICT, "Avet club code not found or already in use"),
    RATE_CONFLICT(CONFLICT, "Rate conflict"),
    EXTERNAL_DESCRIPTION_NOT_FOUND(CONFLICT, "External description not found"),
    NOT_MODIFIABLE_DEFAULT_RATE(CONFLICT, "Rate not modifiable"),
    PRICE_LIST_VOID_IN_AVET(CONFLICT, "Does not exist avet prices in AVET"),
    BARCODES_NOT_UPDATED(CONFLICT, "Cannot update barcodes"),
    REQUEST_CONFLICT(CONFLICT, "The request is not ok"),
    SEASON_SESSION_EXCEPTION(CONFLICT, "Session belongs to a Season"),
    VENUE_TEMPLATE_INVALID_TAGS(CONFLICT, "Tag with invalid id for the venue template"),
    VENUE_TEMPLATE_INVALID_STATUS(CONFLICT, "You cannot change the status"),
    SEASON_TICKET_CURRENCY_NOT_MATCH_OPERATOR(BAD_REQUEST, "Season ticket currency not match with operator currencies"),
    CURRENCY_MANDATORY(BAD_REQUEST, "Currency mandatory"),
    SEASON_TICKET_UPDATE_CURRENCY_IS_PUBLISHED(BAD_REQUEST, "Season ticket currency can´t change if event is published"),
    SEASON_TICKET_INVALID_NAME_CONFLICT(CONFLICT, "Season ticket name already exists for entity"),
    SEASON_TICKET_NOT_FOUND(HttpStatus.NOT_FOUND, "Season ticket not found"),
    SEASON_TICKET_INVALID_STATUS(HttpStatus.BAD_REQUEST, "Invalid season ticket status"),
    SEASON_TICKET_INVALID_INVENTORY_PROVIDER(HttpStatus.BAD_REQUEST, "Invalid inventory provider for intended operation"),
    INVALID_SEASON_TICKET_ID(BAD_REQUEST, "Season ticket id is invalid"),
    INVALID_SEASON_TICKET_HAS_SALES(CONFLICT, "Season ticket cannot be deleted because it has booked seats"),
    SALES_PERIOD_NOT_COHERENT(CONFLICT, "Sales period is not coherent"),
    SEASON_TICKET_MAX_BUYING_LIMIT_RANGE(BAD_REQUEST, "Season ticket max buying limit out of range"),
    SEASON_TICKET_IN_CREATION(CONFLICT, "The operation cannot be done until the season ticket is ready"),
    SEASON_TICKET_WITH_BOOKED_SEAT(CONFLICT, "Season ticket with any booked seat"),
    SEASON_TICKET_WITH_BOOKED_SEAT_REGISTRY_CHANGE(CONFLICT, "Season ticket with any booked seat can't change registry policy"),
    SEASON_TICKET_INVALID_RENEWAL_DATES(CONFLICT, "Season ticket renewal dates are invalid"),
    SEASON_TICKET_RENEWAL_IS_NOT_ALLOWED(CONFLICT, "Season ticket renewal is not allowed"),
    SEASON_TICKET_RENEWAL_FIELDS_NOT_INFORMED(CONFLICT, "Season ticket renewal has fields not informed"),
    SEASON_TICKET_RENEWAL_PUBLISHING_NOT_ENABLED(CONFLICT, "Season ticket renewal can't be enabled until publishing is not enabled"),
    SEASON_TICKET_RENEWAL_PUBLISHING_DATES(CONFLICT, "Season ticket renewal dates can't be before publishing date"),
    SEASON_TICKET_INVALID_CHANGE_SEAT_DATES(CONFLICT, "Season ticket change seat dates are invalid"),
    SEASON_TICKET_INVALID_CHANGE_SEAT_MAX_VALUE(CONFLICT, "Season ticket maximum change seat value is invalid"),
    SEASON_TICKET_CHANGE_SEAT_IS_NOT_ALLOWED(CONFLICT, "Season ticket change seat is not allowed"),
    SEASON_TICKET_CHANGE_SEAT_FIELDS_NOT_INFORMED(CONFLICT, "Season ticket change seat has fields not informed"),
    SEASON_TICKET_CHANGE_SEAT_PUBLISHING_NOT_ENABLED(CONFLICT, "Season ticket change seat can't be enabled until publishing is not enabled"),
    SEASON_TICKET_CHANGE_SEAT_PUBLISHING_DATES(CONFLICT, "Season ticket change seat dates can't be before publishing date"),
    SEASON_TICKET_INVALID_NUMBER_OF_SESSIONS(CONFLICT, "Season ticket must have only one session"),
    SEASON_TICKET_RELEASE_SEAT_INVALID_PERCENTAGES(CONFLICT, "The percentage for customers must be between 0 and 100"),
    SEASON_TICKET_RELEASE_SEAT_INVALID_DELAY_TIMES(CONFLICT, "Release and recover delay times must be positive integers"),
    SEASON_TICKET_TRANSFER_SEAT_INVALID_MIN_DELAY_TIMES(CONFLICT, "The minimum transfer delay times must be positive integers and greater than the maximum"),
    SEASON_TICKET_RELEASE_SEAT_INVALID_MIN_DELAY_TIMES(CONFLICT, "The minimum release delay times must be positive integers and greater than the maximum"),
    SEASON_TICKET_RELEASE_SEAT_INVALID_MAX_EARNINGS(CONFLICT, "The maximum percentage for customers must be between 0 and 100"),
    SEASON_TICKET_RELEASE_SEAT_INVALID_EXCLUDED_SESSION(CONFLICT, "Excluded sessions are not valid"),
    SEASON_TICKET_RELEASE_SEAT_NOT_ALLOWED(PRECONDITION_FAILED, "Release seat is not allowed for this season ticket or session"),
    SEASON_TICKET_RELEASE_SEAT_OUT_OF_TERM(PRECONDITION_FAILED, "Session start is too close for release or recover seat"),
    SEASON_TICKET_RELEASE_SEAT_INVALID_MAX_RELEASES(PRECONDITION_FAILED, "The maximum total number of seat releases must be a positive integer"),
    INCONSISTENT_DATES(CONFLICT, "The introduced date(s) are not coherent"),
    INCONSISTENT_PUBLISHED_ONSALE_STATE(CONFLICT, "Sales cannot be enabled while the season ticket is not published"),
    FIELD_NOT_UPGRADEABLE(CONFLICT, "One of the fields cannot be updated"),
    INVALID_VENUE_SPACE(CONFLICT, "Invalid venue space"),
    SEASON_TICKET_INVITATION_SURCHARGE_INVALID(BAD_REQUEST, "INVITATION surcharge type is invalid for Season Tickets"),
    SEASON_TICKET_SURCHARGE_INVALID_STATUS(BAD_REQUEST, "Season Ticket surcharges cannot be updated with Season Ticket status not SET_UP or PENDING_PUBLICATION"),
    VALIDATE_TICKET_EXCEPTION(INTERNAL_SERVER_ERROR, "Error validating tickets"),
    SESSION_PRESALE_NOT_FOUND(HttpStatus.NOT_FOUND, "Session presale not found"),
    INVALID_SESSION_PRESALE_CREATE_REQUEST(HttpStatus.BAD_REQUEST, "Invalid session presale create request"),
    INVALID_SESSION_PRESALE_UPDATE_REQUEST(HttpStatus.BAD_REQUEST, "Invalid session presale update request"),
    INVALID_SESSION_PRESALE_DATES_REQUIRED(HttpStatus.BAD_REQUEST, "Session presale update request missing dates"),
    INVALID_SESSION_PRESALE_DATES_END_BEFORE_START(HttpStatus.BAD_REQUEST, "Session presale update request invalid dates"),
    EXTERNAL_PRESALE_ID_MANDATORY(HttpStatus.BAD_REQUEST, "External presale id must be specified in additionalConfig"),
    EXTERNAL_PRESALE_ID_ALREADY_EXISTS(BAD_REQUEST, "External presale id already exists for the indicated session"),
    EXTERNAL_PRESALE_NOT_FOUND(HttpStatus.NOT_FOUND, "External presale not found"),
    CUSTOMER_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, "Customer type not found"),

    INVALID_NAME_FORMAT(HttpStatus.PRECONDITION_FAILED, "Name has invalid format, size or reserved characters"),
    INVALID_FILENAME_NO_EXTENSION(BAD_REQUEST, "Filename has no file extension"),
    INVALID_FILENAME_HAS_SEPARATOR(HttpStatus.BAD_REQUEST, "Filename has separator"),
    INVALID_LANG(HttpStatus.PRECONDITION_FAILED, "Any selected language is not valid in the platform"),
    INVALID_RATE(HttpStatus.PRECONDITION_FAILED, "Invalid rates configuration"),
    INVALID_VENUE_TEMPLATE(HttpStatus.PRECONDITION_FAILED, "Invalid VenueTemplate for current event or session"),
    NOT_AVAILABLE_LANG(HttpStatus.PRECONDITION_FAILED, "Any selected language is not available for item"),
    DEFAULT_LANG_REQUIRED(HttpStatus.PRECONDITION_FAILED, "One default language must be defined from selected"),
    VENUE_TEMPLATE_INVALID_TYPE(BAD_REQUEST, "Venue template type is invalid"),
    VENUE_TEMPLATE_HAS_SESSION(HttpStatus.PRECONDITION_FAILED, "Venue template item cant be deleted because it has linked sessions"),
    VENUE_TEMPLATE_NNZONE_HAS_SESSION(HttpStatus.PRECONDITION_FAILED, "Not numbered zone cant be created because Venue template already has linked sessions"),
    VENUE_TEMPLATE_SECTOR_HAS_SESSIONS(HttpStatus.PRECONDITION_FAILED, "Sector cant be created because Venue template already has linked sessions"),
    VENUE_TEMPLATE_PRICE_EVENT_STATUS(HttpStatus.PRECONDITION_FAILED, "Venue template prices cannot be updated with event status not IN_PROGRAMMING, PLANNED or READY"),

    USERS_LIMIT_EXCEEDED(HttpStatus.FORBIDDEN, "Limit of users for entity exceeded"),
    USERS_DELETE_CONFLICT(HttpStatus.FORBIDDEN, "Last MGR role user of entity cant be deleted"),
    FORBIDDEN_ROLE_CHANGE(HttpStatus.FORBIDDEN, "Denied, user can't change its own roles"),
    FORBIDDEN_EVENT_DELETE(HttpStatus.FORBIDDEN, "Event cant be deleted when already have sales"),
    FORBIDDEN_EVENT_UPDATE_STATUS(HttpStatus.FORBIDDEN, "Event status cant change while there are pending seat generation"),
    FORBIDDEN_EVENT_FINISH(HttpStatus.FORBIDDEN, "Event status cant change to finished with alive sessions"),
    VENUE_TEMPLATE_SESSIONS_DELETE(HttpStatus.FORBIDDEN, "VenueTemplate with active sessions cant be deleted"),
    VENUE_TEMPLATE_AVET_DELETE(HttpStatus.FORBIDDEN, "VenueTemplate of AVET type can't be deleted"),
    VENUE_TEMPLATE_TAG_DEFAULT_DELETE(HttpStatus.FORBIDDEN, "Venue template tag default cant be deleted"),
    VENUE_TEMPLATE_TAG_SALES_DELETE(HttpStatus.FORBIDDEN, "Venue template tag with sales cant be deleted"),
    VENUE_TEMPLATE_SECTOR_DEFAULT_DELETE(HttpStatus.FORBIDDEN, "Venue template sector default cant be deleted"),
    VENUE_TEMPLATE_NOT_APPLICABLE_TO_GRAPHIC(HttpStatus.PRECONDITION_FAILED, "Cannot applicable to graphic templates"),
    VENUE_TEMPLATE_CLONE_AVET_NOT_ALLOWED(HttpStatus.CONFLICT, "AVET venue templates can't be cloned"),
    VENUE_TEMPLATE_PRICE_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, "Venue template price type not found"),
    VENUE_TEMPLATE_PRICE_TYPE_CREATE_AVET_NOT_ALLOWED(HttpStatus.FORBIDDEN, "PriceType of AVET venue template can't be created"),
    VENUE_TEMPLATE_PRICE_TYPE_DELETE_AVET_NOT_ALLOWED(HttpStatus.FORBIDDEN, "PriceType of AVET venue template can't be deleted"),
    VENUE_TEMPLATE_TAG_PRICE_TYPE_UPDATE_AVET_NOT_ALLOWED(HttpStatus.FORBIDDEN, "PriceType tag of AVET venue template can't be modified"),
    VENUE_TEMPLATE_PRICE_TYPE_EVENT_NOT_AVET_FOR_RATE_GROUP_FILTER(PRECONDITION_FAILED, "Filter rate_group_id is only for AVET event."),
    RATE_HAS_SESSIONS(HttpStatus.FORBIDDEN, "Rate cant be deleted with assigned sessions"),
    RATE_HAS_PROMOTIONS(HttpStatus.FORBIDDEN, "Rate cant be deleted with assigned promotions"),
    RATE_HAS_SALES(HttpStatus.FORBIDDEN, "Rate cant be deleted when already have sales"),
    ENTITY_NOT_SUPPORT_MULTI_PRODUCER(HttpStatus.FORBIDDEN, "Entity does not allows multiple producers"),
    DEFAULT_PRODUCER_STATUS_CANNOT_BE_CHANGED(HttpStatus.FORBIDDEN, "Default producer status must be active"),
    DEFAULT_PRODUCER_CANNOT_BE_CHANGED(HttpStatus.FORBIDDEN, "The entity must have a default producer"),
    INVOICE_PROVIDER_ALREADY_REQUESTED(HttpStatus.CONFLICT, "This invoice provider has been already requested"),
    PRODUCER_NAME_DUPLICATED(HttpStatus.CONFLICT, "Producer name already exist"),
    EVENT_ALREADY_HAS_SESSION_PACKS(HttpStatus.FORBIDDEN, "Event pack type cant be changed with existing session packs"),
    SEASON_LOCK(CONFLICT, "Season session lock"),

    CHANNEL_ID_INVALID(BAD_REQUEST, "Channel id is invalid"),
    ENTITY_CANNOT_CREATE_B2B_CHANNEL(BAD_REQUEST, "Entity cannot create channel of type B2B"),
    ENTITY_CANNOT_CREATE_AVET_EVENTS(BAD_REQUEST, "Entity cannot create AVET events"),
    ENTITY_CANNOT_CREATE_ACTIVITY_EVENTS(BAD_REQUEST, "Entity cannot create activity events"),
    AT_LEAST_ONE_RANGE(BAD_REQUEST, "At least one range should be informed"),
    SURCHARGE_TYPE_NOT_ALLOWED_AT_ENTITY_LEVEL(BAD_REQUEST, "Allowed entity surcharge types are GENERIC and SECONDARY_MARKET"),
    SURCHARGE_FROM_RANGE_MANDATORY(BAD_REQUEST, "From range is mandatory"),
    SURCHARGE_RANGE_MANDATORY(BAD_REQUEST, "Range is mandatory"),
    COMMISSION_FROM_RANGE_MANDATORY(BAD_REQUEST, "From range is mandatory"),
    SURCHARGE_FROM_RANGE_DUPLICATED(BAD_REQUEST, "From range should be unique"),
    MEMBER_CONFIG_UNIQUE_RESTRICTION_SID(PRECONDITION_FAILED, "Restrictions sid must be unique"),
    MEMBER_CONFIG_UNIQUE_RESTRICTION_NAME(PRECONDITION_FAILED, "Restrictions name must be unique"),
    MEMBER_CONFIG_RESTRICTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Restriction not found"),
    MEMBER_CONFIG_PERIODICITY_CONFIGURATION_ERROR(BAD_REQUEST, "The periodicity skippedSteps configuration must be the same on the skipPeriodicityModule flag"),
    COMMISSION_FROM_RANGE_DUPLICATED(CONFLICT, "From range should be unique"),
    SURCHARGE_FROM_RANGE_ZERO_MANDANTORY(BAD_REQUEST, "At least a range with from value 0 should be informed"),
    COMMISSION_FROM_RANGE_ZERO_MANDANTORY(BAD_REQUEST, "At least a range with from value 0 should be informed"),
    SURCHARGE_TYPE_NOT_SUPPORTED(CONFLICT, "Channel type does not support surcharges"),
    COMMISSION_TYPE_NOT_SUPPORTED(CONFLICT, "Channel type does not support commissions"),
    MIN_SURCHARGE_GREATER_THAN_MAX(CONFLICT, "Min surcharge should not be greater than max"),
    MIN_COMMISSION_GREATER_THAN_MAX(CONFLICT, "Min commission should not be greater than max"),
    FIXED_OR_PERCENTAGE_MANDATORY(BAD_REQUEST, "Fixed or percentage should be informed"),
    SURCHARGE_TYPE_DUPLICATED(BAD_REQUEST, "Surcharge type duplicated"),
    WHEN_LIMIT_ENABLED_IS_MANDATORY(BAD_REQUEST, "When limit is enabled min and max values are mandatory"),
    WHEN_LIMIT_ENABLED_MIN_LOWER_THAN_MAX(CONFLICT, "When limit is enabled  min limit must not be greater than max"),
    COMMISSION_TYPE_DUPLICATED(BAD_REQUEST, "Commission type duplicated"),
    ERROR_RETRIEVING_AVET_CONFIG(INTERNAL_SERVER_ERROR, "Error retrieving avet config"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "Forbidden"),
    REQUIRED_PARAMS(BAD_REQUEST, "Required parameters"),
    USERS_LAST_MGR(HttpStatus.FORBIDDEN, "Cant delete last mgr user"),
    INVALID_USER_ID(BAD_REQUEST, "User id is mandatory and must be greater than 0"),
    INVALID_USER(CONFLICT, "Invalid user"),
    ROLES_MANDATORY(BAD_REQUEST, "Roles are mandatory and must have at least 1 element"),
    NAME_MANDATORY(BAD_REQUEST, "Name is mandatory"),
    TYPE_MANDATORY(BAD_REQUEST, "Type is mandatory"),
    STATE_MANDATORY(BAD_REQUEST, "State is mandatory"),
    NAME_IN_USE(CONFLICT, "Name is in use"),
    INVALID_NAME(BAD_REQUEST, "Name is invalid"),
    INVALID_VALIDATION_RULE(BAD_REQUEST, "Validation rule not valid for field type"),
    INVALID_HEX_COLOR(BAD_REQUEST, "Color has invalid hex value"),
    POINT_OF_SALE_NOT_FOUND(HttpStatus.NOT_FOUND, "Point of sale not found"),
    MULTI_SHOPPING_CART_NOT_ALLOWED(HttpStatus.NOT_FOUND, "Entity is not allowed to use multi shopping cart"),
    DEFAULT_LANGUAGE_CONFLICT(CONFLICT, "Default language should be one of selected languages"),
    CHANNEL_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel config not found"),
    CHANNEL_CORS_SETTINGS_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel CORS settings not found"),
    CHANNEL_DOMAIN_SETTINGS_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel domain settings not found"),
    CHANNEL_CANNOT_ADD_CURRENCY_WHEN_PROMOTION_ACTIVE(HttpStatus.CONFLICT, "Channel cannot add currency when there is an active promotion"),
    MEMBER_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Member config not found"),
    MEMBER_CONFIG_HAS_NOT_MAIN_CAPACITY(HttpStatus.PRECONDITION_FAILED, "Member config has not main capacity"),
    MEMBER_CONFIG_HAS_NOT_SUBSCRIPTION_MODE(HttpStatus.PRECONDITION_FAILED, "Member config has not subscription mode"),
    MEMBER_CONFIG_PRICES_BATCH_IS_DISABLED(HttpStatus.PRECONDITION_FAILED, "Member config prices batch is disabled"),
    MEMBER_CONFIG_IS_NOT_COMPLETED(HttpStatus.PRECONDITION_FAILED, "Member config is not completed"),
    MEMBER_DYNAMIC_CONFIG_IS_NOT_COMPLETED(HttpStatus.PRECONDITION_FAILED, "Member dynamic configuration is not completed"),
    CHANNEL_GATEWAY_IS_MANDATORY(HttpStatus.PRECONDITION_FAILED, "Channel gateway is mandatory"),
    CHANNEL_GATEWAY_WITH_SALE_REQUEST_ACTIVE(HttpStatus.PRECONDITION_FAILED, "Can't delete a gateway config with channel request active"),
    MEMBER_CONFIG_ALREADY_EXIST(HttpStatus.PRECONDITION_FAILED, "Member config already exist"),
    MEMBER_CONFIG_IS_LOCKED(HttpStatus.PRECONDITION_FAILED, "Member config is locked"),
    MEMBER_CONFIG_UNIQUE_MAIN_CAPACITY(HttpStatus.BAD_REQUEST, "Only 1 capacity can be main"),
    ENTITY_CONFIG_ERROR(HttpStatus.PRECONDITION_FAILED, "Entity config error"),
    MEMBER_CONFIG_ELEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Member config element not found"),
    CHANNEL_CONFIG_NOT_COMPLETED(HttpStatus.PRECONDITION_FAILED, "Channel config is not completed"),
    CHANNEL_BUILD_NOT_ALLOWED_NON_OB_PORTAL(HttpStatus.NOT_FOUND, "Build not allowed"),
    CHANNEL_NOT_ACTIVATED_NO_LANGUAGES(CONFLICT, "Channel cannot be activated because it has no languages"),
    CHANNEL_NOT_ACTIVATED_NO_CURRENCIES(CONFLICT, "Channel cannot be activated because it has no currencies"),
    CHANNEL_URL_IN_USE(CONFLICT, "Channel url is in use"),
    NEGATIVE_VALUE(BAD_REQUEST, "Negative values are not allowed"),
    DELIVERY_METHOD_ID_MANDATORY(BAD_REQUEST, "Delivery method id is mandatory"),
    DELIVERY_METHOD_NOT_FOUND(HttpStatus.NOT_FOUND, "Delivery method id not found"),
    DELIVERY_METHOD_COST_MANDATORY(BAD_REQUEST, "Cost is mandatory"),
    DELIVERY_METHOD_COST_NEGATIVE(BAD_REQUEST, "Cost should be equals or greater than zero."),
    DELIVERY_METHOD_STATUS_MANDATORY(BAD_REQUEST, "Status is mandatory"),
    DELIVERY_METHOD_DEFAULT_INVALID(BAD_REQUEST, "Inactive delivery method can not be set as default"),
    DELIVERY_METHOD_TOO_MANY_DEFAULTS(CONFLICT, "Only one delivery method can be set as default"),
    DELIVERY_METHOD_DEFAULT_MANDATORY(CONFLICT, "A default delivery method is mandatory"),
    CHANNEL_DELIVERY_METHODS_EMPTY(BAD_REQUEST, "This channel hasn't delivery methods"),
    INVALID_GATEWAY_SID(BAD_REQUEST, "Gateway sid cannot be blank and is mandatory"),
    INVALID_CONFIG_SID(BAD_REQUEST, "Config sid cannot be blank and is mandatory"),
    CHANNEL_GATEWAY_WALLET_RELATIONSHIP_FOUND(CONFLICT, "Gateway configuration has linked wallets (GPay or ApplePay)"),
    CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Configuration not found"),
    ONE_TRANSLATION_REQUIRED(BAD_REQUEST, "At least one translation must be specified"),
    MANDATORY_FORM_FIELDS_REQUIRED(BAD_REQUEST, "Sid require the following mandatory form fields: %s"),
    INVALID_FORM_FIELDS(BAD_REQUEST, "The following form field must be present and mandatory: %s"),
    ATTEMPTS_REQUIRED(BAD_REQUEST, "Attemps must be specified"),
    GATEWAY_NOT_FOUND(BAD_REQUEST, "Gateway configuration not found"),
    FIELD_VALUES_REQUIRED(BAD_REQUEST, "Some field values are required for this gateway"),
    GATEWAY_NOT_ALLOW_RETRIES(CONFLICT, "Gateway does not accept retries"),
    GATEWAY_OR_ENTITY_NOT_ALLOW_BENEFITS(CONFLICT, "Gateway or entity does not accept benefits"),
    GATEWAY_NOT_ALLOWED_FOR_OPERATOR(CONFLICT, "Specified gateway config cannot be set to channels of your operator"),
    GATEWAY_TOO_MANY_DEFAULTS(CONFLICT, "Only one gateway can be set as default"),
    GATEWAY_ACTIVE_MANDATORY_IF_DEFAULT(CONFLICT, "An active gateway is mandatory to be default"),
    GATEWAY_DEFAULT_MANDATORY(CONFLICT, "A default gateway is mandatory if there is an active gateway"),
    GATEWAY_NAME_TRANSLATIONS_EMPTY(BAD_REQUEST, "Gateway name translations cannot be empty"),
    PRODUCER_NOT_FROM_ENTITY(BAD_REQUEST, "Specified producer is not from your entity"),
    TICKET_TAX_ID_NOT_FOUND(BAD_REQUEST, "Ticket tax id not found"),
    CHARGES_TAX_ID_NOT_FOUND(BAD_REQUEST, "Charges tax id not found"),
    CLIENT_TAX_ID_ALREADY_IN_USE(CONFLICT, "Tax id is already in use"),
    ENTITY_TAXES_NOT_FOUND(BAD_REQUEST, "Entity taxes not found"),
    CURRENCY_NOT_FOUND(HttpStatus.NOT_FOUND, "Currency not found"),
    B2B_BALANCE_CURRENCY_NOT_FOUND(HttpStatus.NOT_FOUND, "There is no balance for the selected currency"),
    MULTI_CURRENCY_NOT_ALLOWED(BAD_REQUEST, "Multicurrency is not allowed"),
    CURRENCY_NOT_ALLOWED(BAD_REQUEST, "Currency is not allowed"),
    SEASON_TICKET_CHANNEL_EXISTS(CONFLICT, "Season ticket channel relation already exists"),
    EVENT_CHANNEL_NOT_FOUND(BAD_REQUEST, "Event channel not found"),
    EVENT_CHANNEL_HAS_SALES(CONFLICT, "Relationship event-channel cannot be deleted because it has sales"),
    EVENT_CHANNEL_EXISTS(CONFLICT, "Event channel relation already exists"),
    SEASON_TICKET_CHANNEL_NOT_FOUND(HttpStatus.NOT_FOUND, "Season ticket channel relation not found"),
    ENTITY_CHANNEL_INVALID_REL(CONFLICT, "Invalid entity-channel relationship"),
    REQUEST_NOT_PENDING(CONFLICT, "Request is not pending"),
    SESSION_CAPACITY_COUNTER(CONFLICT, "Not enough seats for counter value"),
    SESSION_PACK_INVALID_TYPE(BAD_REQUEST, "Session type is incorrect"),
    SESSION_PACK_SEATS(BAD_REQUEST, "Seat ids to modify are mandatory"),
    SESSION_PACK_WITHOUT_SESSIONS(BAD_REQUEST, "Session pack without sessions"),
    SESSION_PACK_WITHOUT_CAPACITY(BAD_REQUEST, "Not enough capacity for link/unlink operation with defined params"),
    FREE_SESSION_PACK_SEAT_CANT_BE_CHANGED(BAD_REQUEST, "The status of a free season pack seat can't be changed"),
    SEAT_STATUS_UPDATE_BLOCKED_EXTERNAL_NOT_ALLOWED(HttpStatus.FORBIDDEN, "The status of a BLOCKED_EXTERNAL seat can't be modified"),
    SEAT_PRICE_TYPE_UPDATE_AVET_NOT_ALLOWED(HttpStatus.FORBIDDEN, "The price type of an AVET session seat can't be modified"),
    INVALID_ZONE_COUNTERS_SETTING(HttpStatus.BAD_REQUEST, "Invalid parameter, zone counters cannot be informed with global zone value"),
    UPDATE_SEATS_LIMIT_EXCEED(HttpStatus.BAD_REQUEST, "Too much numbered seats to update (limit: 5000)"),
    SMART_BOOKING_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Smart Booking is not allowed for session entity"),

    USE_ALL_QUOTAS_MANDATORY(HttpStatus.BAD_REQUEST, "Use all quotas is mandatory"),
    QUOTAS_MANDATORY(HttpStatus.BAD_REQUEST, "At least one quotas must be specified when use all quotas is false"),
    SETTINGS_MANDATORY(HttpStatus.BAD_REQUEST, "Event channel settings are mandatory"),
    USE_EVENT_DATES_MANDATORY(HttpStatus.BAD_REQUEST, "Use event dates is mandatory"),
    EVENT_CHANNEL_SETTINGS_DATES_MANDATORY(HttpStatus.BAD_REQUEST, "Dates are mandatory"),
    START_GREATER_END_DATE(HttpStatus.BAD_REQUEST, "Start date is not before end date"),
    INVALID_QUOTAS(HttpStatus.BAD_REQUEST, "Quotas supplied are invalid"),
    INVALID_ACTIVITY_QUOTAS(HttpStatus.BAD_REQUEST, "Only 1 quota by venue-template allowed on activity events"),
    EVENT_GROUP_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Event group only allowed for ACTIVITY or THEME_PARK event type"),
    EVENT_TYPE_NOT_ALLOWED(CONFLICT, "Operation not allowed for current event type"),
    INVALID_GROUP_CHANGE(HttpStatus.FORBIDDEN, "Event groups cant be disabled with existing MIXED or GROUP sessions"),

    ENTITY_INTERACTIVE_VENUE_ALLOWED_VENUES_MANDATORY(HttpStatus.BAD_REQUEST, "At least one allowed venue must be specified when enabled is true"),
    FORBIDDEN_EVENT_INTERACTIVE_VENUE_UPDATE(HttpStatus.FORBIDDEN, "Entity interactive venue must be enabled to update Event interactive venue"),
    INVALID_EVENT_INTERACTIVE_VENUE_CONFIG(BAD_REQUEST, "Invalid event interactive venue config"),
    FORBIDDEN_CHANNEL_INTERACTIVE_VENUE_UPDATE(HttpStatus.FORBIDDEN, "Entity interactive venue must be enabled to update Channel interactive venue"),
    INTERACTIVE_VENUE_TYPE_NOT_FROM_ENTITY(BAD_REQUEST, "Specified venue type %s is not from your entity"),
    FORBIDDEN_VENUE_TEMPLATE_INTERACTIVE_VENUE_UPDATE(HttpStatus.FORBIDDEN, "Entity interactive venue must be enabled to update Venue Template interactive venue"),
    INTERACTIVE_VENUE_TEMPLATE_NOT_CONFIGURED_FROM_ENTITY(HttpStatus.FORBIDDEN, "Entity interactive venue must be enabled to generate Venue Template export"),
    VENUE_TEMPLATE_INTERACTIVE_VENUE_CODE_MANDATORY(HttpStatus.BAD_REQUEST, "multimedia_content_code must be specified when enabled is true"),

    ID_RATES_NOT_COHERENT(CONFLICT, "Id rates are not coherent"),
    INVALID_DESCRIPTION_LENGTH(BAD_REQUEST, "Description length is not valid"),
    SECONDARY_MARKET_NOT_ALLOWED_BY_ENTITY(HttpStatus.CONFLICT, "Secondary market not allowed by entity"),
    SECONDARY_MARKET_NOT_ALLOWED_FOR_EVENT(HttpStatus.CONFLICT, "Secondary market not allowed for event"),
    SECONDARY_MARKET_NOT_ALLOWED_FOR_ST(HttpStatus.CONFLICT, "Secondary market not allowed for season ticket"),
    EVENT_TYPE_DOES_NOT_SUPPORT_SECONDARY_MARKET(HttpStatus.CONFLICT, "Event type does not support secondary market"),
    SECONDARY_MARKET_CANT_HAVE_LIMIT(BAD_REQUEST, "Secondary Market surcharges can't have limit"),
    SEASON_TICKET_NOT_READY(CONFLICT, "Season ticket is not ready to perform this operation"),
    AVET_EVENTS_NOT_FOUND(HttpStatus.NOT_FOUND, "Avet Events not found for capacity"),
    EVENT_AVET_COMPETITION_MANDATORY(BAD_REQUEST, "Avet competition is mandatory in Avet Event"),
    EVENT_AVET_CONFIG_MANDATORY(BAD_REQUEST, "Avet config is mandatory in Avet Event"),
    EVENT_ENTITY_ID_MANDATORY(BAD_REQUEST, "Event Entity id (event_entity_id parameter) is mandatory"),
    EVENT_ENTITY_ID_INVALID(BAD_REQUEST, "Event Entity id (event_entity_id parameter) is invalid"),
    FILTER_NOT_FOUND(HttpStatus.NOT_FOUND, "Filter named %s not found"),
    SUBSCRIPTION_LIST_NOT_FOUND(HttpStatus.NOT_FOUND, "Subscription list with Id not found"),
    SUBSCRIPTION_CANNOT_BE_DEACTIVATED(CONFLICT, "Subscription list cannot be deactivated because it is in use"),
    SUBSCRIPTION_MODES_ALLOWED_CHARACTERS(BAD_REQUEST, "The subscription modes sid only allows the following characters: A-Z, 0-9, -, _, #"),
    RESTRICTIONS_ALLOWED_CHARACTERS(BAD_REQUEST, "The restrictions sid only allows the following characters: A-Z, 0-9, -, _, #"),
    RESTRICTIONS_VALUES_MUST_BE_A_POSITIVE_NUMBER(BAD_REQUEST, "Restrictions values must be a positive number"),
    RESTRICTIONS_NAME_IS_REQUIRED(BAD_REQUEST, "The restrictions name is a required field"),
    RESTRICTION_CANNOT_BE_ACTIVATED(PRECONDITION_FAILED, "The restriction cannot be activated"),
    IMAGE_INVALID_FILE(BAD_REQUEST, "Uploaded file for element %s is not an image"),
    IMAGE_INVALID_SIZE(BAD_REQUEST, "Image size %dx%d for element %s is incorrect. Expected: %dx%d"),
    IMAGE_INVALID_TYPE(BAD_REQUEST, "Uploaded image type for element %s is invalid. Valid types: %s"),
    IMAGE_INVALID_EMPTY(BAD_REQUEST, "Image for element %s can't not be empty"),
    IMAGE_INVALID_ENCODING(BAD_REQUEST, "Image for element %s must be in Base64 encoding"),
    IMAGE_INVALID_FILE_SIZE(BAD_REQUEST, "Maximum file size for element %s exceeded. Current file size is %d bytes when the maximum allowed size is %d bytes."),
    IMAGE_POSITION_REQUIRED(BAD_REQUEST, "The image type requires the position not to be null"),
    IMAGE_POSITION_INVALID(BAD_REQUEST, "The image position is not valid"),

    COMMUNICATION_ELEMENTS_TYPE(BAD_REQUEST, "Element type is mandatory"),
    COMMUNICATION_ELEMENTS_INVALID_TYPE(BAD_REQUEST, "Element type is invalid"),
    COMMUNICATION_ELEMENTS_HIERARCHY(CONFLICT, "Unsupported operation. Invitation contents should be modified through ticket contents elements"),

    ENTITY_CATEGORY_HAS_CHILDREN(BAD_REQUEST, "Entity category has child categories"),
    ENTITY_CATEGORY_HAS_BASE_CATEGORY_RELATED(BAD_REQUEST, "Entity category is related with base category"),
    ENTITY_HAS_ACTIVITY_EVENTS(HttpStatus.FORBIDDEN, "Entity activity can not be disabled with existing activity events"),

    COMPETITION_NOT_FOUND(HttpStatus.NOT_FOUND, "Competition not found"),
    MATCH_NOT_FOUND(HttpStatus.NOT_FOUND, "Match not found"),
    MATCH_ID_INVALID(BAD_REQUEST, "Invalid match id"),
    MATCH_ID_MANDATORY(BAD_REQUEST, "Match id is mandatory"),
    CAPACITY_NOT_FOUND(HttpStatus.NOT_FOUND, "Capacity not found"),
    CAPTCHA_KEY_SECRET_REQUIRED(BAD_REQUEST, "Captcha key and secret ara required"),
    COMPETITION_ID_INVALID(BAD_REQUEST, "Invalid competition id"),
    COMPETITION_ID_MANDATORY(BAD_REQUEST, "Competition id is mandatory"),
    COMPETITION_ID_ALREADY_IN_USE(BAD_REQUEST, "Competition id already in use"),
    INVALID_ID(BAD_REQUEST, "Invalid id"),

    LANGUAGE_BASE_LITERALS_NOT_FOUND(HttpStatus.NOT_FOUND, "Language base not found"),

    MEMBERS_ENTITY_NOT_ALLOWED(HttpStatus.CONFLICT, "Members are not allowed for this entity"),

    SALE_REQUESTS_NOT_FOUND(HttpStatus.NOT_FOUND, "Sale requests can not be found"),
    SALE_REQUESTS_EVENT_CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "Event category can not be found"),
    SALE_REQUESTS_GATEWAY_CONFIG_MANDATORY(HttpStatus.BAD_REQUEST, "Gateway configuration is mandatory when custom is true"),
    SALE_REQUESTS_GATEWAY_CONFIG_DEFAULT_GATEWAY_MANDATORY(HttpStatus.BAD_REQUEST, "Default gateway is mandatory"),
    SALE_REQUESTS_GATEWAY_CONFIG_DEFAULT_GATEWAY_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "Limit of default gateways exceeded"),
    SALE_REQUESTS_GATEWAY_CONFIG_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Gateways are not allowed for not customized configurations"),
    SALE_REQUESTS_GATEWAY_CONFIG_ACTIVE_GATEWAY_MANDATORY(HttpStatus.BAD_REQUEST, "At least one gateway must be active"),
    SALE_REQUESTS_GATEWAY_CONFIG_DEFAULT_GATEWAY_MUST_BE_ACTIVE(HttpStatus.BAD_REQUEST, "The default gateway must be active"),
    SALE_REQUESTS_GATEWAY_NOT_FROM_CHANNEL(HttpStatus.BAD_REQUEST, "At least one gateway does not belong to the channel or has data errors"),

    INVALID_COMM_ELEM_VALUE_LENGTH(BAD_REQUEST, "%s value size cannot be greater than %s"),
    PASSBOOK_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Passbook configuration not found"),
    INVALID_LANGUAGE_FORMAT(BAD_REQUEST, "Invalid language format, must be IETF (es-ES)"),
    LANGUAGE_NOT_IN_EVENT(BAD_REQUEST, "Language is not available for this event"),
    LANGUAGE_NOT_IN_CHANNEL(BAD_REQUEST, "Language is not available for this channel"),
    PASSBOOK_TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Passbook template not found"),

    ATTENDANCE_DATA_CONFLICT(CONFLICT, "Attendance Ticket data conflict, %s"),
    ACTIVITY_SESSION_MANDATORY(HttpStatus.BAD_REQUEST, "The session must be activity or theme park"),

    EVENT_UNSUPPORTED_TYPE(HttpStatus.BAD_REQUEST, "Unsupported event type"),
    EVENT_UNSUPPORTED_OPERATION(CONFLICT, "Unsupported event operation"),
    EVENT_INVALID_STATUS(HttpStatus.BAD_REQUEST, "Invalid event status"),
    EVENT_INVALID_TYPE(HttpStatus.BAD_REQUEST, "Invalid event type"),
    EVENT_UNSUPPORTED_CONNECTION_TYPE(HttpStatus.BAD_REQUEST, "Unsupported connection type"),
    UPDATE_EVENT_STATE_NOT_ALLOWED(CONFLICT, "Can not update the status if the event is archived"),
    ARCHIVE_EVENT_NOT_ALLOWED(CONFLICT, "Archive the event not allowed with the current status"),
    SESSION_INVALID_STATUS(HttpStatus.BAD_REQUEST, "Invalid session status"),
    SESSION_UPDATE_EXTERNAL_BARCODE_CONFLICT(CONFLICT, "Can not update external barcodes with active session"),
    UPDATE_EVENT_EXTERNAL_BARCODE_CONFIG_WITH_ACTIVE_SESSIONS(CONFLICT, "Can not update event external barcodes with active sessions"),
    UPDATE_EVENT_EXTERNAL_BARCODE_WITH_SALES(CONFLICT, "Can not update event external barcodes because the event has sales"),
    RATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Rate not found"),
    SESSION_UNSUPPORTED_OPERATION(CONFLICT, "Session unsupported operation"),
    SESSION_ALREADY_TRANSFERRED(PRECONDITION_FAILED, "Session has already been transferred"),
    EXTERNAL_AVAILABILITY_UPDATE_IN_PROGRESS(HttpStatus.CONFLICT, "An external availability update is already in progress"),
    CLUB_NOT_FOUND(HttpStatus.NOT_FOUND, "Club not found"),

    EVENT_PROMOTION_TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Event promotion template not found"),
    PROMOTION_CHANNEL_TYPE_NOT_SUPPORTED(CONFLICT, "Channel type does not support promotions"),
    EVENT_CHANNEL_NOT_REQUIRE_ATTENDANT_DATA(HttpStatus.NOT_FOUND, "The event doesn't require attendant data in this channel"),

    AVAILABILITY_ROW_IS_NOT_FROM_SESSION(HttpStatus.CONFLICT, "Provided row id doesn't belong to provided session id"),
    AVAILABILITY_NOT_NUMBERED_ZONE_IS_NOT_FROM_SESSION(HttpStatus.CONFLICT, "Provided not numbered zone id doesn't belong to provided session id"),

    EMAIL_SERVER_TYPE_MANDATORY(HttpStatus.BAD_REQUEST, "Email server type is mandatory"),
    EMAIL_SERVER_CONFIGURATION_MANDATORY(HttpStatus.BAD_REQUEST, "Configuration data is mandatory for setting up your own email server"),
    EMAIL_SERVER_SERVER_MANDATORY(HttpStatus.BAD_REQUEST, "Server is mandatory"),
    EMAIL_SERVER_PORT_MANDATORY(HttpStatus.BAD_REQUEST, "Port is mandatory"),
    EMAIL_SERVER_SECURITY_MANDATORY(HttpStatus.BAD_REQUEST, "Security type is mandatory"),

    PASSBOOK_STATE_INVALID_FOR_DELIVERY_METHOD(BAD_REQUEST, "Delivery method RECEIPT_AND_PASSBOOK requires passbook only to be activated"),
    CHANNEL_TYPE_NOT_COMPATIBLE_WITH_PASSBOOK(CONFLICT, "Channel type is not compatible with receiptTicketDisplay.passbook"),
    CHANNEL_TYPE_NOT_COMPATIBLE_WITH_NFC(CONFLICT, "Channel type is not compatible with useNFC"),
    SECONDARY_MARKET_NOT_SUPPORTED(CONFLICT, "Only V4 OB_PORTAL channels support Secondary Market"),

    CHANNEL_REDIRECTION_POLICY_ORIGIN_TYPE_NOT_NEED_VALUE(BAD_REQUEST, "Channel redirection policy with origin type does not need value"),
    CHANNEL_REDIRECTION_POLICY_CUSTOM_TYPE_MISSING_DEFAULT_VALUE(BAD_REQUEST, "Channel redirection policy with customer type needs default language value"),
    CHANNEL_REDIRECTION_POLICY_CUSTOM_TYPE_INVALID_URL(BAD_REQUEST, "Channel redirection policy with customer type invalid url"),
    INSURANCE_POLICY_NOT_FOUND(HttpStatus.NOT_FOUND, "Insurance policies not found"),
    POLICY_STATE_NOT_VALID(BAD_REQUEST, "Deleted is not a valid state for policy"),

    ENTITY_AUTH_VENDOR_NOT_ALLOWED(HttpStatus.CONFLICT, "Auth vendor for entity is not allowed"),
    AUTH_VENDOR_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, "Auth vendor type not found"),
    AUTH_VENDOR_NOT_FOUND_IN_ENTITY_VENDORS(HttpStatus.NOT_FOUND, "Auth vendor not found in entity vendors"),
    AUTH_VENDOR_ENABLED_REQUIRE_VENDOR(HttpStatus.NOT_FOUND, "At least one vendor is required if is enabled"),

    OPERATION_NOT_ALLOWED(HttpStatus.FORBIDDEN, "The requested operation is not allowed for the user"),
    PROMOTION_DISCOUNT_VALUE(BAD_REQUEST, "The promotion discount value cant be zero"),

    PRICE_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, "Price type not found"),
    PRICE_TYPE_CREATION_ERROR(CONFLICT, "Error during price type creation"),
    PRICE_TYPE_RESTRICTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Restriction not found"),
    RATE_RESTRICTIONS_NOT_FOUND(HttpStatus.NOT_FOUND, "Restriction not found"),
    INVALID_RATE_RESTRICTIONS(HttpStatus.PRECONDITION_FAILED, "Invalid rate restrictions configuration"),
    RATE_EXTERNAL_TYPE_REQUIRED(HttpStatus.BAD_REQUEST, "Rate external type is required"),
    GRAPHIC_TEMPLATE_OPERATION(HttpStatus.BAD_REQUEST, "Operation not allowed on a Graphic template"),
    INVOICE_PREFIX_ALREADY_EXIST(CONFLICT, "Invoice prefix already exist"),
    PRODUCER_SIMPLIFIED_INVOICE_FLAG(HttpStatus.BAD_REQUEST, "The producer simplified invoice flag is not activated"),
    INVOICE_PREFIX_ALLOWED_CHARACTERS(BAD_REQUEST, "The invoice prefix only allows the following characters: A-Z, 0-9, -, _, #, /"),
    INVOICE_PREFIX_CANNOT_BE_MODIFIED(HttpStatus.BAD_REQUEST, "The Event Invoice prefix cannot be changed if the Event status is not In Programming"),
    SIMPLIFIED_INVOICES_CANNOT_BE_USED(HttpStatus.BAD_REQUEST, "Only events with Producer Fiscal data can use simplified invoices"),
    PRODUCER_DOES_NOT_ALLOW_EXTERNAL_INVOICE(CONFLICT, "The producer does not allow external invoice"),
    PRODUCER_MUST_HAVE_A_DEFAULT_INVOICE_PREFIX(CONFLICT, "The producer must haven a default invoice prefix"),
    EXTERNAL_BARCODES_FILE_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "An error occurred while reading the external barcodes file."),
    EXTERNAL_BARCODES_MANDATORY_FIELDS(HttpStatus.BAD_REQUEST, "The event, the session and at least 1 barcode are mandatory"),
    ENTITY_MODULE_B2B_DISABLED(CONFLICT, "Module B2B is not enabled for the entity"),
    DATE_RANGE_EXCEEDS_THE_ALLOWED_DATE_RANGE(CONFLICT, "Date range exceeds the allowed date range (6 months)"),
    ATTENDANT_FIELDS_MUST_HAVE_ONE_MANDATORY(CONFLICT, "At least one attendant field must be mandatory"),
    SEAT_LINK_LIMIT_EXCEEDED(BAD_REQUEST, "The number of seats to modify is greater than the maximum"),

    WEBHOOK_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Webhook configuration not found"),
    OPERATOR_SCOPE_WEBHOOK_ALREADY_EXISTS(CONFLICT, "A Webhook with OPERATOR scope already exists for this operator and entity"),
    ENTITY_CONFIG_CREATE_CONFLICT(CONFLICT, "Entity configuration already exists"),
    ENTITY_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Entity has no configuration to update"),
    ENTITY_EXTERNAL_INVENTORY_PROVIDER_NOT_RELATED(HttpStatus.NOT_FOUND, "Entity is not related to external inventory provider"),
    ENTITY_EXTERNAL_CONFIG_NOT_FOUND(BAD_REQUEST, "External configuration not found for the entity provided"),
    CLIENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Client not found"),
    NO_OBJECT_UNDER_S3_PATH(INTERNAL_SERVER_ERROR, "Image not found in the expected path"),
    INVALID_EXTERNAL_BARCODE_CONFIG_VALUE(BAD_REQUEST, "invalid external barcode configuration value"),
    INACTIVE_ACCOUNT(BAD_REQUEST, "The account is not active"),
    NO_ACCOUNT(HttpStatus.NOT_FOUND, "The account doesn't exist"),
    INVALID_CLUB_CODE(BAD_REQUEST, "Club code not found or not available"),
    INVALID_ENVIRONMENT(HttpStatus.BAD_REQUEST, "The environment must be PRO in a production environment"),
    CLUB_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Club Config not found with the given club code"),
    ENTITY_ALREADY_UNLINKED(HttpStatus.PRECONDITION_FAILED, "The entity is already unlinked"),
    ENTITY_ALREADY_LINKED(HttpStatus.PRECONDITION_FAILED, "The entity is already linked"),
    USER_CANNOT_HAVE_NOTIFICATIONS(BAD_REQUEST, "Requested user cannot have this notification"),
    LOCKED_EXECUTION(CONFLICT, "There is already an ongoing execution for the given entity and capacity"),
    USER_CANNOT_UPDATE_EXTERNAL_INVOICE_NOTIFICATION(HttpStatus.FORBIDDEN, "The user must be operator to update external notification"),
    WRONG_EXTERNAL_DESCRIPTION(HttpStatus.CONFLICT, "Wrong external description"),
    ERROR_BACKEND_UPDATE_EXTERNAL_EVENTS(HttpStatus.INTERNAL_SERVER_ERROR, "ERROR Updating External Events"),
    ERROR_BACKEND_UPDATE_INTERNAL_EVENTS(HttpStatus.INTERNAL_SERVER_ERROR, "ERROR Updating Internal Events"),
    EVENT_ACCOMMODATIONS_CONFIG_NOT_PROPERLY_ENABLED(BAD_REQUEST, "Vendor and value are required in order to enable an accommodations config"),
    INVALID_SESSION_DATE_CHANGE_SEAT_CONFIG(CONFLICT, "Same Date must be in DIFFERENT sessions config"),
    ACCOMMODATIONS_CONFIG_NOT_ENABLED_BY_ENTITY(BAD_REQUEST, "Accommodations not yet enabled by entity"),
    ACCOMMODATIONS_VENDOR_NOT_ALLOWED_BY_ENTITY(BAD_REQUEST, "Event vendor not allowed by entity"),
    PARTNER_PIN_REGEX_NOT_VALID(BAD_REQUEST, "Partner Pin Regex could not be empty or null if check is set to true"),
    ERROR_OPERATOR_CURRENCIES_ARE_MANDATORY(BAD_REQUEST, "currencies are mandatory"),
    INVALID_GATEWAY_CONFIG_FOR_B2B_CHANNEL(CONFLICT, "Cash payment method cannot be configured for B2B channels"),
    INVALID_GATEWAY_CONFIG_IF_NOT_B2B_CHANNEL(CONFLICT, "Onebox Accounting payment method cannot be configured out of B2B channels"),
    ALLOW_B2B_PUBLISHING_IS_NOT_ENABLED(BAD_REQUEST,"Entity or channel doesn't allow B2B publishing"),
    ALLOW_INVITE_IS_NOT_ENABLED(BAD_REQUEST,"Entity doesn't allow invite"),
    CHANNEL_TYPE_IS_NOT_B2B(BAD_REQUEST,"Channel type is not B2B"),
    ENTITY_EXTERNAL_CONFIG_INCOMPLETE(CONFLICT, "Entity external configuration is incomplete"),
    EXTERNAL_INVENTORY_NOT_FOUND(HttpStatus.NOT_FOUND, "External inventory Not Found"),
    EXTERNAL_INVENTORY_LIST_ERROR(CONFLICT, "External inventory list error"),
    ATTRIBUTE_INVALID_VALUE(BAD_REQUEST, "Invalid attribute value"),
    ERROR_OPERATOR_WITHOUT_MULTICURRENCY(BAD_REQUEST, "Operator without multicurrency"),
    ERROR_OPERATOR_WITHOUT_MULTICURRENCY_DEFAULT(BAD_REQUEST, "Operator without multicurrency default"),
    ERROR_CURRENCY_DOESNT_EXIST(HttpStatus.NOT_FOUND, "Currency doesn't exist"),
    ERROR_CURRENCY_WITH_GATEWAY_ACTIVE(CONFLICT, "Can't delete currency with active gateway"),
    ERROR_GATEWAY_CURRENCIES_ARE_MANDATORY(BAD_REQUEST, "currencies are mandatory"),
    ERROR_GATEWAY_CURRENCY_NOT_IN_OPERATOR(CONFLICT, "Gateway currency is not allowed by the operator"),
    ERROR_GATEWAY_CURRENCY_NOT_IN_CHANNEL(CONFLICT, "Gateway currency is not allowed by the channel"),
    CANT_UPDATE_GATEWAY_CURRENCY(CONFLICT, "Gateway currencies can't be updated"),
    CANT_DELETE_GATEWAY_WITH_SALE_REQUEST(CONFLICT, "Gateway can't be deleted because there are active sales request"),
    COUNTRY_NOT_FOUND(HttpStatus.NOT_FOUND, "Country not found"),
    COUNTRY_SUBDIVISION_NOT_FOUND(HttpStatus.NOT_FOUND, "Country subdivision not found"),
    SUBDIVISION_IN_COUNTRY_NOT_FOUND(BAD_REQUEST, "Country subdivision does not exist in the country"),
    INVALID_POSTAL_CODE_COUNTRY_SUBDIVISION(HttpStatus.PRECONDITION_FAILED, "Postal code doesnt match with the country subdivision"),
    INVALID_VALUE(CONFLICT, "Invalid value"),
    INVALID_INVOICE_CONFIGURATION(BAD_REQUEST, "Invalid invoice configuration"),
    ENTITY_SECURITY_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Entity Security Configuration not found"),
    ENTITY_SECURITY_CONFIG_MISSING_AMOUNT(BAD_REQUEST, "%s amount missing"),
    ENTITY_SECURITY_CONFIG_INVALID_VALUE(BAD_REQUEST, "%s amount must be between 1 and  %s"),
    ENTITY_SECURITY_CONFIG_INVALID_EXPIRATION(BAD_REQUEST, "Expiration amount must be equal or above 1"),

    //products
    NOT_AVAILABLE_CHANNELS_FOUND(HttpStatus.NOT_FOUND, "There are no available channels for he product"),
    NOT_AVAILABLE_EVENTS_FOUND(HttpStatus.NOT_FOUND, "There are no available events for he product' channel"),
    NOT_AVAILABLE_SESSIONS_FOUND(HttpStatus.NOT_FOUND, "There are no available sessions for he product' channel"),
    PRODUCT_NOT_FOUND(HttpStatus.NOT_FOUND, "Product not found"),
    PRODUCT_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Product event not found"),
    PRODUCT_EVENT_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "Product event session not found"),
    PRODUCT_EVENT_SESSION_INVALID_SELECTION_TYPE(PRECONDITION_FAILED, "Session stock update requires RESTRICTED selection type in product - event relationship"),
    PRODUCT_EVENT_SESSION_INVALID_TYPE_OR_STOCK_TYPE( PRECONDITION_FAILED, "Session stock update requires SIMPLE product type and stock type SESSION_BOUNDED"),
    PRODUCT_EVENT_SESSION_BAD_REQUEST_STOCK_MANDATORY(BAD_REQUEST, "Stock property is mandatory when use_custom_stock is TRUE"),
    PRODUCT_EVENT_ALREADY_EXISTS(BAD_REQUEST, "Event already exists in product event relation"),
    PRODUCT_LANGUAGE_NOT_RELATED(HttpStatus.NOT_FOUND, "Language not selected in product"),
    ILLEGAL_VARIANT_AMOUNT(BAD_REQUEST, "Product simple can not have more than one variant"),
    PRODUCT_EVENT_NOT_RELATED(PRECONDITION_FAILED, "Product and event are not related"),
    B2B_PUBLISHING_SEAT_NOT_FOUND(HttpStatus.NOT_FOUND, "B2B Seat publishing not found"),
    TAX_NOT_UPDATABLE_ON_PRODUCT(BAD_REQUEST, "Tax id not updatable on active products"),
    INVALID_ENTITY_TAX(BAD_REQUEST, "Invalid tax for entity"),
    PRODUCT_STATE_NOT_VALID(BAD_REQUEST, "Deleted is not a valid state for searching products"),
    PRODUCT_EVENT_STATE_NOT_VALID(BAD_REQUEST, "Deleted is not a valid state for updating product events"),
    PRODUCT_VARIANT_NOT_FOUND(HttpStatus.NOT_FOUND, "Product variant not found"),
    PRODUCT_LANGUAGES_NOT_FOUND(HttpStatus.NOT_FOUND, "Product languages not found"),
    PRODUCT_CHANNEL_NOT_FOUND(HttpStatus.NOT_FOUND, "Product channel not found"),
    PRODUCT_CHANNELS_NOT_FOUND(HttpStatus.NOT_FOUND, "Product channels not found"),
    PRODUCT_COMMUNICATIONS_ELEMENTS_NOT_FOUND(HttpStatus.NOT_FOUND, "Product communication elements not found"),
    PRODUCT_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "Product communication elements language not found"),
    PRODUCT_VARIANT_PRICE_AND_STOCK_NOT_UPDATABLE(BAD_REQUEST, "Product variant price and stock not updatable on active products"),
    PRODUCT_EMPTY_TARGET(BAD_REQUEST, "Product with type RESTRICTED must contain a list of elements"),
    PRODUCT_ATTRIBUTE_NOT_FOUND(HttpStatus.NOT_FOUND, "Product attribute not found"),
    PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND(HttpStatus.NOT_FOUND, "Product attribute value not found"),
    PRODUCT_ATTRIBUTE_NAME_DUPLICATED(BAD_REQUEST, "Product attribute name duplicated"),
    PRODUCT_DELIVERY_POINT_NOT_FOUND(HttpStatus.NOT_FOUND, "Product delivery point not found"),
    PRODUCT_DELIVERY_POINT_RELATION_NOT_FOUND(HttpStatus.NOT_FOUND, "Product delivery point relation not found"),
    PRODUCT_DELIVERY_TYPE_REQUIRED(PRECONDITION_FAILED, "Product delivery type required"),
    PRODUCT_DELIVERY_PERIOD_REQUIRED(PRECONDITION_FAILED, "Product delivery period required"),
    PRODUCT_DELIVERY_NOT_UPDATABLE(PRECONDITION_FAILED, "Product delivery not updatable on active products"),
    PRODUCT_SESSION_BOUNDED_DELIVERY_TYPE(PRECONDITION_FAILED, "Products with session bounded stock must have session delivery type"),
    PRODUCT_CANNOT_BE_ACTIVATED(CONFLICT, "Product could not be activated"),
    PRODUCT_TAX_NOT_FOUND(HttpStatus.NOT_FOUND, "Product tax not found"),
    PRODUCT_SURCHARGE_TAX_NOT_FOUND(HttpStatus.NOT_FOUND, "Product surcharge tax not found"),
    PRODUCT_VARIANT_PRICE_REQUIRED(PRECONDITION_FAILED, "All product variants must have a price"),
    PRODUCT_EVENTS_REQUIRED(PRECONDITION_FAILED, "Product must have associated events"),
    PRODUCT_SESSIONS_REQUIRED(PRECONDITION_FAILED, "Product must have associated sessions"),
    PRODUCT_EVENT_DELIVERY_POINT_DEFAULT_REQUIRED(HttpStatus.NOT_FOUND, "One product event delivery point must be the default value"),
    PRODUCT_LANGUAGE_DEFAULT_REQUIRED(HttpStatus.NOT_FOUND, "One product language must be the default value"),
    PRODUCT_VARIANT_NOT_ENOUGH_STOCK(PRECONDITION_FAILED, "There is not enough stock"),
    PRODUCT_NAME_ALREADY_IN_USE(PRECONDITION_FAILED, "Product name is already in use"),
    PRODUCT_CHANNEL_ALREADY_EXISTS(CONFLICT, "Product channel already exists"),
    PRODUCT_CHANNEL_NOT_FROM_ENTITY(BAD_REQUEST, "Only channels from the same entity can publish a product"),
    PRODUCT_CHANNEL_INVALID_TYPE(CONFLICT, "External type channel is not allowed"),
    PRODUCT_CHANNEL_INVALID_OPTIONS(BAD_REQUEST, "At least one of the two must be true: standalone_enabled or checkout_suggestion_enabled"),
    DELIVERY_POINT_NAME_ALREADY_IN_USE(PRECONDITION_FAILED, "Delivery point name is already in use"),
    POSITION_MUST_BE_POSITIVE(BAD_REQUEST, "Position must be a positive value"),
    PRODUCT_HAS_SALES(PRECONDITION_FAILED, "Product has sales"),
    PRODUCT_INVALID_TYPE_FOR_SESSION_BOUNDED(PRECONDITION_FAILED, "Invalid Product type for session bounded stock type"),
    PRODUCT_TYPE_NOT_ALLOWED(PRECONDITION_FAILED, "Invalid product type. Only product type SIMPLE is allowed"),
    PRODUCT_STOCK_TYPE_NOT_ALLOWED(PRECONDITION_FAILED, "Invalid product stock type. Only product stock type SESSION_BOUNDED is allowed"),
    PRODUCT_MISSING_ACTIVE_VARIANT(PRECONDITION_FAILED, "Products must have at least one active variant"),

    SESSIONS_NOT_FOUND_OR_INVALID_SESSION_STATE(CONFLICT, "Sessions not found or invalid sessions state"),
    MAX_ATTRIBUTES_REACHED(BAD_REQUEST, "A product can only have two attributes as much"),
    NOT_AVET_EVENT_RESTRICTION(BAD_REQUEST, "Only Avet events can have restrictions"),
    AVET_SECTOR_RESTRICTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Restriction not found"),
    RESTRICTION_CANNOT_BE_UPDATED(BAD_REQUEST, "The restriction cannot be updated"),
    TIME_RESTRICTION_LAPSE_NOT_VALID(BAD_REQUEST, "Time restrictions lapses can only accept BEFORE and AFTER values"),
    TIME_RESTRICTION_UNIT_NOT_VALID(BAD_REQUEST, "Time restrictions units can only accept HOURS MINUTES and DAYS values"),
    DUPLICATE_AVET_SECTOR_RESTRICTION_NAME(BAD_REQUEST, "Avet sector restriction name already exists"),
    DUPLICATE_AVET_SECTOR_RESTRICTION_SID(BAD_REQUEST, "Avet sector restriction sid already exists"),
    VENUE_TEMPLATE_ID_MANDATORY(HttpStatus.CONFLICT, "Venue template id must be specified in additionalConfig"),
    VENUE_TEMPLATE_INVALID_SPACE(HttpStatus.CONFLICT, "Invalid space to assign to the venue template"),
    VENUE_TEMPLATE_SVG_GENERATION_ERROR(HttpStatus.CONFLICT, "Unable to generate svg file for the venue template"),
    VENUE_TEMPLATE_SEATS_CREATION_ERROR(HttpStatus.CONFLICT, "Returned seat ids do not match the expected ones"),
    INVENTORY_IMPORT_ERROR(HttpStatus.CONFLICT, "Error on inventory import"),
    INVENTORY_UPDATE_ERROR(HttpStatus.CONFLICT, "Error on inventory update"),
    ENTITY_INTEGRATION_CREDENTIALS_NOT_FOUND(CONFLICT, "Entity integration credentials not found"),
    EXTERNAL_SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "External Session not found"),
    EXTERNAL_VENUE_ID_ERROR(CONFLICT,"Could not resolve external venue id from inventory id"),
    EXTERNAL_VENUE_TEMPLATE_NOT_FOUND(CONFLICT, "External venue template not found for the indicated entity and venue"),
    EXTERNAL_VENUE_TEMPLATE_PROCESSING_ERROR(CONFLICT, "External venue template could not be processed from csv"),
    EVENT_WHITELABEL_UI_SETTINGS_CONFLICT(CONFLICT, "Event whitlabel ui configuration conflict" ),
    EXTERNAL_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "External event not found"),
    EXTERNAL_ST_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "External season ticket event not found"),
    EXTERNAL_PRODUCT_CONFIGURATION_NOT_FOUND(CONFLICT, "External product configuration not found"),
    EXTERNAL_RATES_NOT_FOUND(HttpStatus.NOT_FOUND, "External provider rates not found"),
    REPEATED_NAME(HttpStatus.PRECONDITION_FAILED, "Received name is used already"),
    SGA_NOT_FOUND(HttpStatus.NOT_FOUND, "Object not found in external call" ),
    USER_RATE_LIMIT_INVALID_CONFIG(HttpStatus.CONFLICT, "Config must be unlimited or not. Not both"),
    INVALID_RELEASED_SEAT_QUOTA(CONFLICT, "Invalid use of released seat quota"),
    PRODUCT_NOT_AVAILABLE(CONFLICT,"Product not available"),
    PRODUCT_YET_TO_BE_RELEASED(PRECONDITION_FAILED, "Product has not been released yet"),
    ALREADY_RELEASED_PRODUCT(PRECONDITION_FAILED, "Product has already been released"),
    INVALID_QUOTA_ID(CONFLICT, "Invalid quota"),
    DONATION_PROVIDER_NOT_ENABLED(CONFLICT, "Donation provider is not enabled"),
    INVALID_AUTH_CONFIG_AUTHENTICATION_METHODS(PRECONDITION_FAILED, "Authentication methods required"),
    INVALID_AUTH_CONFIG_AUTHENTICATORS(PRECONDITION_FAILED, "Authenticators required"),
    INVALID_AUTH_CONFIG_MULTIPLE_SYNC_METHODS(CONFLICT, "Only one sync authentication method allowed"),
    INVALID_COLLECTIVES(CONFLICT, "Invalid collectives"),
    INVALID_AUTH_CONFIG_MULTIPLE_AUTHENTICATORS(PRECONDITION_FAILED, "Only one authenticator allowed"),
    INVALID_AUTH_CONFIG_ENTITY_HAS_NOT_CUSTOMER_TYPES(PRECONDITION_FAILED, "No custom types on this entity"),
    INVALID_AUTH_CONFIG_CUSTOMER_TYPES(PRECONDITION_FAILED, "The custom type don't exists in the entity"),
    INVALID_AUTH_CONFIG_BLOCKED_CUSTOMER_TYPES(PRECONDITION_FAILED, "The blocked customer types configuration is invalid"),
    INVALID_AUTH_CONFIG_ACCOUNT(BAD_REQUEST, "Account configuration not allowed for this entity"),
    INVALID_QUEUE_ALIAS_CONFIG(BAD_REQUEST, "Alias is mandatory for active queues"),
    INVALID_QUEUE_ACCOUNT_ID_CONFIG(BAD_REQUEST, "Account id is mandatory for custom queue it accounts"),
    VENDORS_NOT_FOUND(CONFLICT, "Vendors not found"),
    INVALID_VENDORS(CONFLICT, "Invalid vendors"),
    INVALID_DONATION_API_KEY(CONFLICT, "The provided API key is not valid."),
    INVALID_DONATION_PROVIDER_ID(CONFLICT, "The donation provider ID is not valid."),
    DONATION_CONFIG_NOT_ENABLED(CONFLICT, "Donation config is not enabled"),
    INVALID_OPTION_VALUE(BAD_REQUEST, "Option value must be greater than 0"),
    INVALID_VALIDATION_RULE_FOR_FIELD_TYPE(CONFLICT, "Invalid validation rule for field type"),
    ENTITY_FORM_NOT_FOUND(HttpStatus.PRECONDITION_FAILED, "Entity form not found"),
    INVALID_ENTITY_FORM_FIELD(HttpStatus.CONFLICT, "Entity form field invalid"),
    VALIDATION_RULE_NOT_FOUND(HttpStatus.BAD_REQUEST, "Invalid validation rule for field type"),
    INVALID_FORM_TYPE(HttpStatus.BAD_REQUEST, "Invalid form name"),
    SESSION_TAG_NOT_FOUND(HttpStatus.NOT_FOUND, "Session tag not found"),
    EVENT_TAG_LANGUAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "Event tag language not found"),
    CANNOT_DISABLE_PAYMENT_METHOD_USED_FOR_BOOKING_CHECKOUT(BAD_REQUEST, "Can't disable a payment method used for booking checkout"),
    CANNOT_DELETE_PAYMENT_METHOD_ACTIVE_FOR_BOOKING_CHECKOUT(BAD_REQUEST, "Cannot disable a payment method used for booking checkout"),
	GATEWAYS_NOT_ALLOWED(PRECONDITION_FAILED, "Gateways not allowed for this channel"),
    INVALID_SECONDARY_MARKET_CONFIG(BAD_REQUEST, "Invalid secondary market configuration"),
    NULL_SECONDARY_MARKET_VALUES(BAD_REQUEST, "Secondary market configuration values cannot be null"),
    NEGATIVE_SECONDARY_MARKET_VALUES(BAD_REQUEST,"Secondary market configuration values cannot be negative"),
    INVALID_SECONDARY_MARKET_RANGE(BAD_REQUEST, "Secondary market max value cannot be less than min value or greater than 200"),
    INVALID_PRODUCT_TYPE_FOR_VALUES(BAD_REQUEST, "Only product with variants can have product attribute values"),
    PRODUCT_ATTRIBUTE_VALUE_NAME_DUPLICATED(BAD_REQUEST, "Product attribute value name duplicated"),
    PRODUCT_ATTRIBUTE_VALUE_NOT_INACTIVE_PRODUCT(BAD_REQUEST, "Product attribute value can only be created on inactive products"),
    SESSION_SECONDARY_MARKET_ENABLE_REQUIRED(BAD_REQUEST, "Enable secondary market flag is required"),
    SESSION_SECONDARY_MARKET_START_DATE_REQUIRED(BAD_REQUEST, "Secondary market start date is required"),
    SESSION_SECONDARY_MARKET_END_DATE_REQUIRED(BAD_REQUEST, "Secondary market end date is required"),
    SECONDARY_MARKET_START_DATE_AFTER_END_DATE(BAD_REQUEST, "Secondary market start date is after end date"),
    PRODUCT_VARIANT_STATE_INVALID(PRECONDITION_FAILED,"Product variant state invalid"),
    PRODUCT_VARIANT_PRODUCT_TYPE_INVALID(PRECONDITION_FAILED,"Product type must be variant"),
    PRODUCT_VARIANT_NUMBER_ATTRIBUTES_INVALID(PRECONDITION_FAILED,"Products variants attributes number invalid"),
    PRODUCT_VARIANT_MINIMUM_VALUES_INVALID(PRECONDITION_FAILED,"Products variants must have at least two values"),
    PRODUCT_VARIANT_STATUS_NOT_UPDATABLE(PRECONDITION_FAILED, "Products variant status not updatable on product with simple variant"),
    PRODUCT_VARIANT_FILTER_INVALID(BAD_REQUEST, "Product unbounded can not be filtered by stock"),
    LOYALTY_POINTS_NOT_ALLOWED(BAD_REQUEST, "Loyalty points is not allowed"),
    SUGGESTION_WITH_DIFFERENT_CURRENCY(BAD_REQUEST, "Events with different currencies cannot be linked."),
    TICKET_NUMBER_EXCLUSION_INPUT(CONFLICT, "You must inform either 'required ticket number' or 'locked ticket number', but not both"),
    WHITELABEL_PATH_MISSING(PRECONDITION_FAILED, "External whitelabel path is missing"),
    DATES_ARE_MANDATORY(BAD_REQUEST, "Dates are missing in request body"),
    INVALID_CUSTOMER_LIMITS(BAD_REQUEST, "The customer limits are not valid"),
    INVALID_CUSTOMER_TYPE(BAD_REQUEST, "Invalid customer type"),
    ORDER_NOT_FOUND(HttpStatus.NOT_FOUND, "Could not find order"),
    TICKET_NOT_FOUND(HttpStatus.NOT_FOUND, "Ticket not found"),
    RELOCATION_SEAT_IS_NUMBERED_ZONE(HttpStatus.BAD_REQUEST, "Provided seat ID is not numbered seat"),
    RELOCATION_INVALID_ORDER_STATUS_TYPE(HttpStatus.CONFLICT, "One of the seats has an order with an invalid order status type"),
    RELOCATION_INVALID_ORDER_STATUS_STATE(HttpStatus.CONFLICT, "One of the seats has an order with an invalid order status state"),
    RELOCATION_INVALID_SOURCE_SEAT_STATUS(HttpStatus.CONFLICT, "One of the source seats has an invalid status"),
    RELOCATION_INVALID_SOURCE_SEAT_WITHOUT_ORDER_CODE(HttpStatus.CONFLICT, "One of the source seats has no order code assigned"),
    RELOCATION_INVALID_DESTINATION_SEAT_WITH_ORDER_CODE(HttpStatus.CONFLICT, "One of the destination seats has an order code already assigned"),
    RELOCATION_INVALID_DESTINATION_SEAT_STATUS(HttpStatus.CONFLICT, "One of the destination seats has an invalid status"),
    RELOCATION_INVALID_SESSION_TYPE(HttpStatus.CONFLICT, "Invalid session type"),
    RELOCATION_INVALID_SESSION_STATUS(HttpStatus.CONFLICT, "Invalid session status"),
    RELOCATION_INVALID_EVENT_TYPE(HttpStatus.CONFLICT, "Invalid event type"),
    RELOCATION_SEAT_IS_SOURCE_AND_DESTINATION(HttpStatus.BAD_REQUEST, "A seat ID can't be both source and destination"),
    RELOCATION_REPEATED_SOURCE_SEAT(HttpStatus.BAD_REQUEST, "There are repeated source seat IDs"),
    RELOCATION_REPEATED_DESTINATION_SEAT(HttpStatus.BAD_REQUEST, "There are repeated destination seat IDs"),
    INVALID_DELIVERY_DATES(HttpStatus.PRECONDITION_FAILED, "Delivery start date must be earlier than delivery end date"),
    DELIVERY_DATES_REQUIRED(HttpStatus.PRECONDITION_FAILED, "Delivery dates required on products with fixed dates"),
    DYNAMIC_PRICE_ZONE_NOT_FOUND(HttpStatus.NOT_FOUND, "Dynamic price zone not found"),
    DYNAMIC_PRICE_ZONE_NO_CAPACITY(HttpStatus.CONFLICT, "Dynamic price zone exists but has no capacity available"),
    DYNAMIC_PRICE_CAPACITY_EXCEEDED(HttpStatus.CONFLICT, "Dynamic price capacity exceeded"),
    CAPACITY_DYNAMIC_PRICE_CANNOT_BE_ZERO_OR_NEGATIVE(HttpStatus.CONFLICT, "Dynamic price capacity cannot be zero or negative"),
    MISSING_DATE(BAD_REQUEST, "Date is required for this condition type"),
    MISSING_CAPACITY(BAD_REQUEST, "Capacity is required for this condition type"),
    DATE_BEFORE_CREATION(HttpStatus.CONFLICT, "Date cannot be before creation"),
    DATE_BEFORE_SALE_START(HttpStatus.CONFLICT, "Date cannot be before sale start"),
    MISSING_NAME(BAD_REQUEST, "Name is required"),
    MISSING_CONDITION_TYPE(BAD_REQUEST, "Condition type is required"),
    MISSING_ORDER(BAD_REQUEST, "Order is required"),
    MISSING_RATES(BAD_REQUEST, "Rates are required"),
    CAPACITY_LESS_THAN_PREVIOUS(HttpStatus.CONFLICT, "Capacity cannot be less than previous"),
    DATE_LESS_THAN_PREVIOUS(HttpStatus.CONFLICT, "Date cannot be less than previous"),
    DYNAMIC_PRICE_NOT_FOUND(HttpStatus.NOT_FOUND, "Dynamic price not found"),
    CANNOT_DELETE_ACTIVE_DYNAMIC_PRICE(HttpStatus.CONFLICT, "Cannot delete active dynamic price"),
    CANNOT_DELETE_PASS_DYNAMIC_PRICE(HttpStatus.CONFLICT, "Cannot delete pass dynamic price"),
    INVALID_ORDER_SEQUENCE(HttpStatus.CONFLICT, "Invalid order sequence"),
    CANNOT_UPDATE_DYNAMIC_PRICE_FOR_ACTIVE_SESSION(HttpStatus.CONFLICT, "Cannot update dynamic price for active session"),
    CANNOT_ACTIVATED_DYNAMIC_PRICE_IF_TIERED_PRICING_ACTIVE(HttpStatus.CONFLICT, "Cannot activate dynamic price if tiered pricing is active"),
    CUSTOMER_TYPE_NOT_FOUND_IN_EVENT(HttpStatus.CONFLICT, "Some customer types not found for event"),
    FEVER_ZONE_NOT_ALLOWED_BY_OPERATOR(HttpStatus.CONFLICT, "AllowFeverZone is not allowed by operator"),
    EVENT_TAX_MODE_NOT_ALLOWED(BAD_REQUEST, "Avet events must always include taxes"),
    EVENT_UPDATE_TAX_MODE_HAS_SALES(HttpStatus.CONFLICT, "Tax mode cannot be changed because the event has sales"),
    INVALID_EVENT_CHANGE_SEAT_EXPIRY_TIME_UNIT(BAD_REQUEST, "Event change seat expiry time unit not allowed"),
    FORCE_SQUARE_PICTURES_NOT_ALLOWED_FOR_INTERNAL_WHITELABEL(BAD_REQUEST, "ForceSquarePictures cannot be enabled for internal whitelabels"),
    CANNOT_ACTIVATED_DYNAMIC_PRICE_IF_GROUPS_EXIST(HttpStatus.CONFLICT, "Cannot activate dynamic price if groups exist"),
    CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_THIS_TYPE_EVENT(BAD_REQUEST, "Cannot activate dynamic price for this type of event"),
    GROUPS_INCOMPATIBLE_WITH_DYNAMIC_PRICES(BAD_REQUEST, "Groups are incompatible with dynamic prices"),
    CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_ACTIVITY_WITH_GROUPS(BAD_REQUEST, "Cannot activate dynamic price for activity event with groups"),
    SEASON_TICKET_AUTO_RENEWAL_NOT_ALLOWED(HttpStatus.CONFLICT, "Automatic renewal cannot be modified for season tickets with existing sales"),
    TAX_MODE_NOT_UPDATABLE_ON_PRODUCT(PRECONDITION_FAILED, "Tax mode not updatable on products with sales"),
    INVALID_PRODUCT_TAX_MODE(PRECONDITION_FAILED, "Invalid product tax mode"),
    INVALID_EVENT_TAX_MODE(PRECONDITION_FAILED, "Invalid event tax mode"),
    EVENT_UPDATE_TAX_MODE_INVALID_EVENT_STATUS(PRECONDITION_FAILED, "Tax mode cannot be updated when event is ready"),
    PRODUCT_UPDATE_TAX_MODE_INVALID_PRODUCT_STATUS(PRECONDITION_FAILED, "Tax mode cannot be updated when product is active"),
    DYNAMIC_PRICES_REQUIRE_V4_CHANNEL(BAD_REQUEST, "Dynamic prices require V4 channel"),
    WHITELABEL_TYPE_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "Unsupported whitelabel type"),
    EVENT_CONFIG_NOT_SUPPORTED(HttpStatus.BAD_REQUEST, "Only available for tour events or events that allow session packs"),
    ERROR_SURCHARGE_CURRENCY_NOT_IN_CONFIGURATION(CONFLICT, "Surcharge currency not found in gateway configuration"),
    ERROR_SURCHARGE_MAXVALUE_GREATER_THAN_MINVALUE(CONFLICT, "Surcharge max_value must be greater than min_value"),
    ERROR_SURCHARGE_CURRENCY_DUPLICATED(CONFLICT, "Surcharge currency must be unique"),
    INVALID_LANGUAGE_CODE(HttpStatus.BAD_REQUEST, "Invalid language code"),
    EMPTY_TRANSFER_TICKET_SESSION_LIST(BAD_REQUEST, "Empty Id session list"),
    INVALID_TRANSFER_TICKET_SESSION_LIST(HttpStatus.CONFLICT, "Invalid Id session list"),
    GATEWAY_BENEFITS_NOT_ALLOWED_BY_OPERATOR(HttpStatus.CONFLICT, "Gateway benefits not allowed by operator"),
    GATEWAY_BENEFITS_NOT_ALLOWED_BY_ENTITY(HttpStatus.CONFLICT, "Gateway benefits not allowed by entity"),
    ENTITY_COMMUNICATIONS_ELEMENTS_NOT_FOUND(HttpStatus.NOT_FOUND, "Entity communication elements not found"),
    ENTITY_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "Entity communication elements language not found"),
    PACK_SALE_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "Pack sale request not found"),
    PACK_SALE_REQUEST_ALREADY_EXISTS(CONFLICT, "Pack sale already exists"),
    CHANNEL_PACK_RELATIONSHIP_INCONSISTENT(CONFLICT, "The relationship between channel and pack is inconsistent"),
    TEMPLATE_ZONE_CODE_ALREADY_EXISTS(CONFLICT, "Template zone code already exists"),
    TEMPLATE_ZONES_INVALID_STATUS(CONFLICT, "The template zones status is invalid"),
    TEMPLATE_ZONES_NOT_FOUND(HttpStatus.NOT_FOUND, "Template zones not found"),
    QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Question not found"),
    PRODUCT_TICKET_TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Product ticket template not found"),
    PRODUCT_TICKET_MODEL_NOT_FOUND(HttpStatus.NOT_FOUND, "Product ticket model not found" ),
	PRODUCT_TICKET_TEMPLATE_NAME_ALREADY_SET(HttpStatus.CONFLICT, "Product ticket template name already set"),
    SESSION_LIMIT_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Session limit not allowed"),
    PRODUCT_TICKET_LANGUAGE_LITERALS_NOT_FOUND(HttpStatus.NOT_FOUND, "Product ticket language literals not found"),
    PRODUCT_TICKET_DEFAULT_LITERALS_NOT_FOUND(HttpStatus.NOT_FOUND, "Product ticket literals not found"),
    ACCESS_CONTROL_REQUIRES_END_DATE(BAD_REQUEST, "Access control requires end date to create a session"),
    ACCESS_CONTROL_REQUIRES_DATES(BAD_REQUEST, "Access control requires start date and end date to create a session"),
    ACCESS_CONTROL_REQUIRES_CUSTOM_CATEGORY(BAD_REQUEST, "Access control requires custom category"),;

    private final HttpStatus httpStatus;
    private final String message;
    private final boolean forwardMessage;

    ApiMgmtErrorCode(HttpStatus httpStatus, String message, boolean forwardMessage) {
        this.httpStatus = httpStatus;
        this.message = message;
        this.forwardMessage = forwardMessage;
    }

    ApiMgmtErrorCode(HttpStatus httpStatus, String message) {
        this.httpStatus = httpStatus;
        this.message = message;
        this.forwardMessage = false;
    }

    @Override
    public HttpStatus getHttpStatus() {
        return this.httpStatus;
    }

    @Override
    public String getMessage() {
        return this.message;
    }

    @Override
    public String getErrorCode() {
        return this.name();
    }

    @Override
    public boolean forwardMessage() {
        return forwardMessage;
    }

    @Override
    public String formatMessage(Object... args) {
        return String.format(getMessage(), args);
    }

    public static ErrorCode getByCode(String code) {
        return Stream.of(values())
                .filter(errorCode -> errorCode.getErrorCode().equals(code))
                .findFirst()
                .orElse(null);
    }
}
