package es.onebox.mgmt.exception;

import es.onebox.core.exception.ErrorCode;
import org.springframework.http.HttpStatus;

import java.util.stream.Stream;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.CONFLICT;
import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.http.HttpStatus.PRECONDITION_FAILED;

public enum ApiMgmtChannelsErrorCode implements FormattableErrorCode {

    NOT_FOUND(HttpStatus.NOT_FOUND, "Url not found"),
    APPLICATION_UNSUPPORTED(BAD_REQUEST, "Unsupported application"),
    CHANNEL_ID_INVALID(BAD_REQUEST, "Channel id is invalid"),
    CHANNEL_NAME_MANDATORY(BAD_REQUEST, "Name is mandatory"),
    CHANNEL_NAME_INVALID(BAD_REQUEST, "Name is invalid"),
    CHANNEL_DOMAIN_INTERNAL(BAD_REQUEST, "Domain cannot be changed in an internal whitelabel"),
    CHANNEL_WHITELABEL_PATH_INTERNAL(BAD_REQUEST, "Whitelabel path cannot be changed in an internal whitelabel"),
    CHANNEL_NAME_INVALID_SIZE(BAD_REQUEST, "Channel name must be 200 characters or less."),
    CHANNEL_URL_INVALID_SIZE(BAD_REQUEST, "Channel url must be 100 characters or less."),
    CHANNEL_TYPE_MANDATORY(BAD_REQUEST, "Type is mandatory"),
    CHANNEL_SUBTYPE_INVALID(BAD_REQUEST, "Invalid channel subtype"),
    CHANNEL_ENTITY_ID_MANDATORY(BAD_REQUEST, "Entity id is mandatory"),
    CHANNEL_ENTITY_ID_INVALID(BAD_REQUEST, "Entity id is invalid"),
    CHANNEL_STATUS_INVALID(BAD_REQUEST, "Channel status is invalid"),
    CHANNEL_BUILD_INVALID(BAD_REQUEST, "Channel build is invalid"),
    CHANNEL_URL_INVALID(BAD_REQUEST, "Channel url is invalid. Only letters, numbers, '_', '-' and '.' are accepted."),
    CHANNEL_UNSUPPORTED_TYPE(BAD_REQUEST, "Unsupported channel type"),
    CHANNEL_UNSUPPORTED_LANGUAGE(BAD_REQUEST, "Unsupported channel language"),
    CHANNEL_UNSUPPORTED_OPERATION(HttpStatus.METHOD_NOT_ALLOWED, "Unsupported channel operation for this channel type"),
    CHANNEL_UNSUPPORTED_BUILD(BAD_REQUEST, "Unsupported channel build for channel type"),
    CHANNEL_INVALID_FORM_UPDATE(BAD_REQUEST, "Fields cant not be updated"),
    CHANNEL_UPDATE_INVALID_PARAM(BAD_REQUEST, "%s"),
    CHANNEL_NAME_IN_USE(CONFLICT, "Name is in use"),
    CHANNEL_ACTIVE_LANGUAGE_MANDATORY(CONFLICT, "An activated channel must have at least one language selected"),
    CHANNEL_MEMBERS_EXISTS_FOR_ENTITY(CONFLICT, "A channel of type 'MEMBERS' already exists in the entity"),
    MEMBER_CONFIG_SUBSCRIPTION_MODE_SID_EXISTS(CONFLICT, "A subscription mode id already exists in the configuration"),
    MEMBER_CONFIG_RESTRICTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Restriction not found"),
    CHANNEL_URL_MANDATORY_FOR_TYPE_PORTAL(BAD_REQUEST, "Channel url is mandatory when creating channel of type OB_PORTAL"),
    CHANNEL_VALIDATION_RULE_INVALID(BAD_REQUEST, "Validation rule not allowed for this type of field"),
    CHANNEL_VALIDATION_RULE_REPEATED(BAD_REQUEST, "Validation rule repeated"),
    SUPPLIED_COLLECTIVE_NOT_FOUND(BAD_REQUEST, "No collective with supplied collective id"),
    COLLECTIVE_MANDATORY(BAD_REQUEST, "Collective id is mandatory when creating channel of type SUBSCRIBERS"),
    CHANNEL_WEB_BOXOFFICE_ONLY(CONFLICT, "This feature is available only for web boxoffice channels only"),
    CHANNEL_BOOKING_CHECKOUT_DOMAIN_MANDATORY(BAD_REQUEST, "The booking checkout domain is mandatory if activating booking checkout"),
    CHANNEL_BOOKING_CHECKOUT_DOMAIN_MALFORMED(BAD_REQUEST, "The booking checkout domain is malformed"),
    CHANNEL_BOOKING_CHECKOUT_INACTIVE_PAYMENT_METHOD(CONFLICT, "At least one of the provided booking checkout payment method is inactive"),
    CHANNEL_BOOKING_CHECKOUT_PAYMENT_METHOD_DOES_NOT_MATCH(CONFLICT, "At least one of the provided booking checkout payment methods does not match"),
    CHANNEL_BOOKING_CHECKOUT_PAYMENT_METHOD_NOT_AVAILABLE(CONFLICT, "Payment methods ONEBOXACCOUNTING and CASH are not allowed for booking checkout"),
    CHANNEL_BOOKING_CHECKOUT_PAYMENT_METHOD_MUST_BE_UNIQUE(CONFLICT, "Payment methods must be unique"),
    CHANNEL_BOOKING_CHECKOUT_NOT_ALLOWED_FOR_CHANNEL_TYPE(BAD_REQUEST, "Booking checkout settings are only allowed on OB_PORTAL channels"),
    CHANNEL_BOOKING_CHECKOUT_DIFFERENT_ENTITY(BAD_REQUEST, "The booking checkout channel must belong to the same entity as the main channel"),
    PASSBOOK_STATE_INVALID_FOR_DELIVERY_METHOD(CONFLICT, "Delivery method RECEIPT_AND_PASSBOOK requires passbook only to be activated"),
    DELIVERY_METHODS_NOT_COMPATIBLE(HttpStatus.METHOD_NOT_ALLOWED, "Delivery methods are not compatible with channel type"),
    EMAIL_CONTENT_NOT_COMPATIBLE_WITH_CHANNEL(BAD_REQUEST, "Requested email content is not compatible with channel type"),
    CHANNEL_INVALID_TICKET_LIMIT(BAD_REQUEST, "Specified ticket limit is not compatible with this channel type"),
    CHANNEL_ADDITIONAL_AGREEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel additional agreement not found"),
    MEMBER_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Channels member config not found"),
    MEMBER_RESTRICTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Member restriction not found"),
    CLUB_CONFIG_NOT_FOUND(HttpStatus.NOT_FOUND, "Channels club config not found"),
    MEMBER_CONFIG_SUBSCRIPTION_MODE_NOT_FOUND(HttpStatus.NOT_FOUND, "Subscription mode not found"),
    MEMBER_CONFIG_PROPERTY_NOT_FOUND(HttpStatus.NOT_FOUND, "Channels member config property not found"),
    MEMBER_CONFIG_CAPACITY_NOT_FOUND(HttpStatus.PRECONDITION_FAILED, "Member capacity must be selected"),
    MEMBER_CONFIG_VENUE_PROPERTY_NOT_FOUND(HttpStatus.NOT_FOUND, "Channels member config venueId property not found"),
    MEMBER_ORDER_TYPE_INVALID(BAD_REQUEST, "Invalid member order type"),
    CHANNEL_FORM_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel Form not found"),
    CHANNEL_AGREEMENT_POSITION_NOT_CORRELATIVE(HttpStatus.BAD_REQUEST, "Channel additional agreement position must be correlative"),
    CHANNEL_AGREEMENT_INVALID_STATE(CONFLICT, "Channel agreement cannot be mandatory and disabled"),
    CHANNEL_FAQ_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel FAQ item not found"),
    INVITATIONS_NOT_ENABLED_BY_ENTITY(CONFLICT, "Entity does not have invitations enabled"),
    B2B_MODULE_NOT_ALLOWED_BY_ENTITY(CONFLICT, "Entity does not have b2b module allowed"),
    B2B_MODULE_NOT_ALLOWED_BY_CHANNEL(CONFLICT, "Channel type does not allow b2b module"),
    AUTOMATIC_SEAT_SELECTION_NOT_ALLOWED_IN_CHANNEL(CONFLICT, "Automatic seat selection not allowed by channel type"),
    USER_REGISTRATION_POLICY_NOT_ALLOWED_IN_CHANNEL(CONFLICT, "User registration policy not allowed by channel type"),
    COMMERCIAL_CONSENT_NOT_COMPATIBLE_WITH_CHANNEL(CONFLICT, "Channel type not compatible with commercial consent"),
    EMAIL_TEMPLATE_TYPE_NOT_MAPPED(HttpStatus.NOT_FOUND, "Email template type mapped"),
    EXTERNAL_TOOLS_TEMPLATE_DO_NOT_EXIST(CONFLICT, "External tools document template do not exist"),
    EXTERNAL_TOOLS_TEMPLATE_MALFORMED(CONFLICT, "External tools document template malformed"),
    GTM_CONTAINER_ID_MISSING(BAD_REQUEST, "GTM Container Id is required"),
    INVALID_ADDITIONAL_CONFIGURATION_FIELD(BAD_REQUEST, "additional config contains an invalid config for the tool"),
    EXTERNAL_TOOL_CANNOT_BE_RESET(BAD_REQUEST, "The external tool cannot be reset"),
    INVALID_EXTERNAL_TOOL_CONFIG(CONFLICT, "external config is not valid"),
    VOICEFLOW_CODE_MISSING(CONFLICT, "Voiceflow code is missing"),
    GTM_CONFIG_JSON_MALFORMED(BAD_REQUEST, "GTM config JSON malformed"),
    ADOBE_DTM_CONFIG_JSON_MALFORMED(BAD_REQUEST, "Adobe DTM config JSON malformed"),
    GTM_CONTAINER_ID_MALFORMED(BAD_REQUEST, "gtm container_id malformed"),
    GTM_IS_NOT_ENABLED(CONFLICT, "GTM is not enabled"),
    NOT_PROFILED_TEXT_BLOCK(CONFLICT, "Text block is not profiled"),
    PROFILED_TEXT_BLOCK(CONFLICT, "Text block is profiled"),
    INVALID_LANGUAGE_FOR_TEXT_BLOCK(CONFLICT, "Invalid language for text block"),
    TEXT_BLOCK_NOT_FOUND(CONFLICT, "Text block not found"),
    TICKET_CONTENT_TO_DELETE_NOT_FOUND(HttpStatus.NOT_FOUND, "Ticket content to delete not found"),
    ENTITY_IS_NOT_AVET(CONFLICT, "Entity must have AVET active to create channel type MEMBERS_AVET"),
    VOUCHER_GROUP_NOT_FOUND(CONFLICT, "Voucher group not found"),
    VOUCHER_NOT_FOUND(CONFLICT, "Voucher not found"),
    VOUCHER_CREATE_INVALID_TYPE(BAD_REQUEST, "Voucher does not support creation for this voucher-group type"),
    VOUCHER_DELETE_ALREADY_USED(CONFLICT, "Voucher cant be deleted because it has been already used"),
    VOUCHER_DELETE_INVALID_TYPE(CONFLICT, "Voucher of current voucher-group type cant be deleted"),
    COLLECTIVE_ID_REQUIRED_IN_SUBSCRIBERS_CHANNEL(BAD_REQUEST, "Collective Id is required to create a subscribers type channel"),
    CONNECTOR_NOT_FOUND(HttpStatus.NOT_FOUND, "Integration connector not found for entity"),
    CHANNEL_COLLECTIVE_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel Collective not found"),
    CHANNEL_OR_COLLECTIVE_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel or Collective not found"),
    COLLECTIVE_NOT_COMPATIBLE_WITH_PORTAL_SUBSCRIBERS(CONFLICT, "Collective must be external and user password to be compatible with channel type portal subcribers"),
    PURCHASE_CONTENT_TO_DELETE_NOT_FOUND(HttpStatus.NOT_FOUND, "Purchase content to delete not found"),
    PURCHASE_TEXT_CONTENT_NOT_DELETABLE(BAD_REQUEST, "Purchase text content is not deletable"),
    VOUCHER_IS_NOT_GIFT_CARD(CONFLICT, "Voucher is not gift card type"),
    CHANNEL_IDS_IS_REQUIRED(BAD_REQUEST, "With Channel Scope RESTRICTED channel id list is mandatory"),
    CHANNEL_IDS_MUST_BE_NULL(BAD_REQUEST, "With Channel Scope ALL channel id list must be null"),
    VOUCHER_GROUP_NAME_IN_USE(CONFLICT, "Another voucher group exists with the same name"),
    VOUCHER_GROUP_INVALID_STATUS_UPDATE(BAD_REQUEST, "Voucher group cannot be activated without mandatory relations"),
    INVALID_USAGE_LIMIT(BAD_REQUEST, "Usage limit must be positive and greater or equal than the number of uses"),
    INVALID_EXPIRATION_DATE(BAD_REQUEST, "Expiration date on update must be after now"),
    EVENT_NOT_FOUND_IN_CHANNEL_EVENTS(HttpStatus.NOT_FOUND, "Event not found in channel events"),
    UPDATED_EVENT_NOT_FOUND_IN_CHANNEL_EVENTS(HttpStatus.NOT_FOUND, "Updated event not found in channel events"),
    UPDATED_EVENT_MISMATCH(BAD_REQUEST, "Sorted event must be visible"),
    CHANNEL_EVENT_CURRENCY_NOT_MATCH(HttpStatus.CONFLICT, "The currency between channel and event not match"),
    CHANNEL_CANNOT_REMOVE_CURRENCY_WITH_EVENT_SALES_REQUEST(CONFLICT, "Channel cannot remove currency with event sale request"),
    TICKET_PASSBOOK_CONTENT_REQUIRE_PASSBOOK_ENABLED(CONFLICT, "Ticket passbook content requires passbook to be activated"),
    TICKET_PDF_PASSBOOK_PRINTER_CONTENT_CLONE_ERROR(INTERNAL_SERVER_ERROR, "Ticket PDF, passbook and printer contents clone error"),
    TICKET_PDF_PASSBOOK_CONTENT_CLONE_ERROR(INTERNAL_SERVER_ERROR, "Ticket PDF and passbook contents clone error"),
    TICKET_PDF_PRINTER_CONTENT_CLONE_ERROR(INTERNAL_SERVER_ERROR, "Ticket PDF and printer contents clone error"),
    TICKET_PASSBOOK_PRINTER_CONTENT_CLONE_ERROR(INTERNAL_SERVER_ERROR, "Ticket passbook and printer contents clone error"),
    TICKET_PDF_CONTENT_CLONE_ERROR(INTERNAL_SERVER_ERROR, "Ticket PDF contents clone error"),
    TICKET_PASSBOOK_CONTENT_CLONE_ERROR(INTERNAL_SERVER_ERROR, "Ticket passbook contents clone error"),
    TICKET_PRINTER_CONTENT_CLONE_ERROR(INTERNAL_SERVER_ERROR, "Ticket printer contents clone error"),
    TEXTS_BLOCKS_TO_CLONE_NOT_FOUND(HttpStatus.NOT_FOUND, "Texts blocks to clone not found"),
    TEXTS_TO_CLONE_NOT_FOUND(HttpStatus.NOT_FOUND, "Portal texts to clone not found"),
    PURCHASE_CONTENT_EMAIL_TO_CLONE_NOT_FOUND(HttpStatus.NOT_FOUND, "Purchase content email to clone not found"),
    CHANNELS_TYPE_MISMATCH(CONFLICT, "The source channel type must be the same as target channel type"),
    GIFT_CARD_MUST_BE_NULL_IF_NOT_ENABLED(BAD_REQUEST, "A gift card id cannot be specified if gift card is not enabled in the channel"),
    LOYALTY_POINTS_MUST_BE_ENABLED(BAD_REQUEST, "Purchases with loyalty points are permitted only when the entity has enabled loyalty points"),
    GIFT_CARD_CURRENCY_NOT_MATCH(CONFLICT, "The gift card currency is different than request currency"),
    VOUCHER_GROUP_MUST_BE_TYPE_GIFT_CARD(CONFLICT, "Voucher group must be type gift card to be saleable in a channel"),
    FROM_VALUE_MUST_BE_LOWER_THAN_TO_VALUE(BAD_REQUEST, "From value must be lower than to value"),
    BULK_UPDATE_NO_COMPATIBLE_WITH_GIFT_CARD(CONFLICT, "Gift card vouchers cannot be updated in bulk"),
    NOT_ALLOW_UPDATE_DATA_PROTECTION(CONFLICT, "This channel cannot update data protection fields. only available for Box Office"),
    NOT_ALLOW_UPDATE_DATA_PROTECTION_FIELDS(CONFLICT, "Cannot update data protection fields, channel's entity should have active this flag"),
    DATA_PROTECTION_FORM_NOT_AVAILABLE(CONFLICT, "Data protection form is available only for BoxOffice channels"),
    FORM_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, "Form type not found in available forms for this channel"),
    VOUCHER_EXPIRATION_INCONSISTENT_VALUES(BAD_REQUEST, "A date cannot be set if expiration is disabled"),
    VOUCHER_GROUP_EXPIRATION_DATE_AFTER_NOW(BAD_REQUEST, "The expiration date cannot be before the current date"),
    VOUCHER_GROUP_EXPIRATION_DATE_INCONSISTENT(BAD_REQUEST, "Voucher group expiration date request is not correct"),
    OPERATION_NOT_ALLOWED_FOR_USER(CONFLICT, "The requested operation is not available for the user role"),
    VOUCHER_GROUP_DELETE_HAS_USED_CODES(CONFLICT, "Voucher group cannot be deleted because already has used codes"),
    VOUCHER_GROUP_CURRENCIES_MUST_BE_CHANNEL(CONFLICT, "Voucher group currencies must be the same that channel currencies"),
    GIFT_CARD_CURRENCIES_CANNOT_BE_REPEATED(CONFLICT, "GifCard currencies cannot be repeated"),
    CHANNEL_PROMOTION_NOT_FOUND(CONFLICT, "Channel promotion not found"),
    CHANNEL_LINKED_CUSTOMERS_NOT_ALLOWED_FOR_CHANNEL_TYPE(BAD_REQUEST, "allow_linked_customers is only allowed in WEB channels"),
    CHANNEL_LINKED_CUSTOMERS_NOT_ALLOWED_IN_ENTITY(BAD_REQUEST, "allow_linked_customers not allowed as the channel entity doesn't allow members"),
    VOUCHER_GROUP_VALIDATION_TYPE_INVALID(BAD_REQUEST, "The combination voucher group type and validation is not valid"),
    VOUCHER_AVET_REQUIRES_AVET_ENTITY(CONFLICT, "Voucher group with validation method AVET required that the entity has AVET activated"),
    VOUCHER_EXTERNAL_CANNOT_MANUAL_UPDATE_BALANCE(CONFLICT, "External vouchers cannot manual update the balance"),
    EMAIL_REQUIRED(BAD_REQUEST, "Email required"),
    VOUCHER_TRANSACTION_REFUND_NOT_FOUND(CONFLICT, "Voucher type Refund without REFUND_TO_VOUCHER transaction"),
    ONLY_ONE_AVET_VOUCHER_PER_CHANNEL(CONFLICT, "Only one voucher group with validation method AVET allowed per channel"),
    SALE_REQUEST_AGREEMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Catalog sale request additional agreement not found"),
    SALE_REQUEST_AGREEMENT_INVALID_STATE(CONFLICT, "Catalog sale request agreement cannot be mandatory and disabled"),
    USERS_LIMIT_EXCEEDED(HttpStatus.FORBIDDEN, "Limit of users for entity exceeded"),
    DIGITAL_SEASON_TICKET_TEMPLATE_ON_ENTITY_NOT_ALLOWED(CONFLICT, "allow_digital_season_ticket is required in entity to set channel passbook template"),
    PASSBOOK_TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Passbook template not found"),
    PASSBOOK_TEMPLATE_TYPE_ORDER(CONFLICT, "Passbook template must be of type MEMBER_ORDER"),
    ERROR_MASTER_LITERALS_DOC_NOT_FOUND(HttpStatus.NOT_FOUND, "Master literals document not found"),
    INVALID_CHANNEL_TYPE_VIRTUAL_QUEUE_CONFIG(CONFLICT, "Queue configuration only available for channels type PORTAL_SUBSCRIBERS (with portal build STH) and AVET"),
    INVALID_CHANNEL_TYPE_EVENT_SALE_RESTRICTIONS(CONFLICT, "Event sale restriction only available for OB_PORTAL channel type"),
    META_PIXEL_ID_MISSING(BAD_REQUEST, "Meta Pixel Id is required"),
    META_PIXEL_ID_MALFORMED(BAD_REQUEST, "Meta pixel Id malformed"),
    SHARING_SETTINGS_NOT_ALLOWED_FOR_CHANNEL_TYPE(BAD_REQUEST, "Sharing settings are only allowed on b2b channels"),
    ENABLED_B2B_EXTERNAL_DOWNLOAD_WITHOUT_TARGET_CHANNEL(BAD_REQUEST, "Cannot enable a b2b external download url without a target channel"),
    B2B_EXTERNAL_DOWNLOAD_URL_ONLY_ALLOWED_FOR_B2B_CHANNELS(BAD_REQUEST, "B2B external download url is only allowed for B2B channels"),
    TARGET_CHANNEL_INVALID(BAD_REQUEST, "Target channel invalid"),
    TARGET_CHANNEL_TYPE_NOT_SUITABLE_FOR_EXTERNAL_DOWNLOAD_URL(BAD_REQUEST, "The requested channel type isn't a suitable external download url"),
    B2B_PUBLISHING_ONLY_ALLOWED_FOR_B2B_CHANNELS(BAD_REQUEST, "Only B2B channels with B2B module may use Seat Publishing feature"),
    B2B_PUBLISHING_NOT_ALLOWED_BY_ENTITY(BAD_REQUEST, "This channel's entity does not allow B2B Publishing"),
    B2B_EVENT_CATEGORY_FILTER_ONLY_ALLOWED_FOR_B2B_CHANNELS(BAD_REQUEST, "Only B2B channels can use event category filter feature"),
    INVITATIONS_SELECTION_MODE_REQUIRED(BAD_REQUEST, "Invitations selection mode is required"),
    CHANNEL_SUGGESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Suggested source or target item not found for this channel"),
    CHANNEL_SUGGESTION_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND, "Channel suggestion type not found"),
    EVENT_SUGGESTION_DUPLICATED(BAD_REQUEST, "Duplicated event suggestion"),
    SESSION_SUGGESTION_DUPLICATED(BAD_REQUEST, "Duplicated session suggestion"),
    UNSUPPORTED_SUGGESTION_TYPE(HttpStatus.METHOD_NOT_ALLOWED, "Unsupported suggestion type"),
    LIMIT_SUGGESTED_ITEMS_MAX(CONFLICT, "Limit of 10 suggested items can't be surpassed"),
    SESSION_NOT_FOUND_IN_CHANNEL_EVENTS(HttpStatus.NOT_FOUND, "Session not found in channel events"),
    CHANNEL_SUGGESTION_SELF_REFERENCED(BAD_REQUEST, "Channel suggestion source cannot suggest itself"),
    SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "Session not found"),
    EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Event not found"),
    EVENT_OR_SESSION_NOT_FOUND_IN_CHANNEL(HttpStatus.NOT_FOUND, "Event or session not found in channel "),
    INVALID_SUPPORT_EMAIL(CONFLICT, "Missing support email address"),
    PROMOTION_LOCATION_REQUIRED(CONFLICT, "Promotion location requires at least one value"),
    UNSUPPORTED_CUSTOM_RESOURCES_CHANNEL_TYPE(HttpStatus.METHOD_NOT_ALLOWED, "Unsupported channel type for custom resources. Only PORTAL subtypes are supported"),
    CUSTOM_RESOURCES_REQUEST_REPEATED_ELEMENTS(BAD_REQUEST, "The channel custom resources request contains repeated language and type combinations"),
    PACK_NOT_FOUND(HttpStatus.NOT_FOUND, "Pack not found"),
    INVALID_PACK_CONFIG(CONFLICT, "Pack does not support this type of configuration"),
    PACK_RATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Pack rate not found"),
    PACK_CANNOT_BE_ENABLED_EVENT_HAS_NO_PUBLISHED_SESSIONS(CONFLICT, "Pack cannot be enabled. Event %s has no published sessions", true),
    PACK_ITEM_MUST_HAVE_A_CHANNEL_CURRENCY(CONFLICT, "Pack item must have a channel currency"),
    PACK_ITEMS_MUST_HAVE_SAME_CURRENCY(CONFLICT, "Pack items must have the same currency"),
    PACK_CANNOT_BE_ENABLED_PRODUCT_IS_NOT_ACTIVE(CONFLICT, "Pack cannot be enabled. Product %s is not active", true),
    PACK_CANNOT_BE_ENABLED_PRODUCT_WITHOUT_STOCK(CONFLICT, "Pack cannot be enabled. Product %s without stock", true),
    PACK_CANNOT_BE_ENABLED_PRODUCT_IS_NOT_RELATED(CONFLICT, "Pack cannot be enabled. Product %s is not related with main item", true),
    PACK_STATUS_INVALID(CONFLICT, "Invalid pack status for update"),
    PACK_HAS_SALES(CONFLICT, "Pack cannot be deleted because it has sales"),
    PACK_ITEM_SUBSET_NOT_FOUND(HttpStatus.NOT_FOUND, "Pack item subsets not found"),
    PACK_ITEM_INVALID_FOR_SUBSETS(CONFLICT, "Pack item invalid for subitems. Check item type and if it's principal"),
    INVALID_CHANNEL_PACK_DATES_REQUIRED(BAD_REQUEST, "Invalid pack config. StartDate and endDate required"),
    INVALID_CHANNEL_PACK_DATES_END_BEFORE_START(BAD_REQUEST, "Invalid dates for pack. End before after"),
    CHANNEL_PACK_EVENT_ITEM_INVALID_STATUS(CONFLICT, "Pack event item has an invalid status"),
    CHANNEL_PACK_SESSION_ITEM_INVALID_STATUS(CONFLICT, "Pack session item has an invalid status"),
    CHANNEL_PACK_CANNOT_BE_ACTIVATED(CONFLICT, "Pack can't be activated. It doesn't meet the requirements"),
    CHANNEL_PACK_MAIN_ITEM_CANNOT_BE_DELETED(CONFLICT, "Main pack item can't be deleted"),
    CHANNEL_PACK_MAIN_ITEM_MANDATORY(BAD_REQUEST, "Invalid pack config. Main item is mandatory for AUTOMATIC packs"),
    CHANNEL_PACK_MAIN_ITEM_ITEM_ID_CANNOT_BE_NULL(BAD_REQUEST, "Main item price_type_id can't be null"),
    CHANNEL_PACK_MAIN_ITEM_TYPE_CANNOT_BE_NULL(BAD_REQUEST, "Main item type can't be null"),
    CHANNEL_PACK_MAIN_ITEM_VENUE_TEMPLATE_ID_CANNOT_BE_NULL(BAD_REQUEST, "Main item venue_template_id can't be null"),
    CHANNEL_PACK_MAIN_ITEM_TYPE_CANNOT_BE_PRODUCT(CONFLICT, "Main item type can't be product type"),
    CHANNEL_PACK_MAIN_ITEM_SESSION_CANNOT_HAVE_SUB_ITEMS(BAD_REQUEST, "Main item session can't have sub items"),
    CHANNEL_PACK_MAIN_ITEM_SESSION_CANNOT_HAVE_VENUE_TEMPLATE_ID(BAD_REQUEST, "Main item session can't have venue template id"),
    CHANNEL_PACK_ITEMS_ALREADY_IN_PACK(CONFLICT, "Invalid pack item. Item already exists in pack"),
    CHANNEL_PACK_ITEM_PRICE_TYPE_ID_CANNOT_BE_NULL(BAD_REQUEST, "price_type_id can't be null"),
    CHANNEL_PACK_ITEM_PRICE_TYPE_ID_OR_MAPPING(BAD_REQUEST, "price_type_id or price_type_mapping can't be defined at same time"),
    CHANNEL_PACK_ITEM_VARIANT_ID_CANNOT_BE_NULL(BAD_REQUEST, "variant_id can't be null"),
    CHANNEL_PACK_ITEM_DELIVERY_POINT_ID_CANNOT_BE_NULL(BAD_REQUEST, "delivery_point_id can't be null"),
    CHANNEL_PACK_ITEM_SHARED_BARCODE_CANNOT_BE_NULL(BAD_REQUEST, "shared_barcode can't be null"),
    CHANNEL_PACK_ITEM_SIMPLE_PRODUCT_CANNOT_HAVE_VARIANTS(CONFLICT, "Product item is simple and can't have variants"),
    CHANNEL_PACK_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "Item not found in pack"),
    CHANNEL_PACK_ITEM_MAIN_ITEM_CANNOT_HAVE_PRICE_TYPE_ID(CONFLICT, "Pack main item can't have price_type_id"),
    CHANNEL_PACK_ITEM_WITH_MAIN_TEMPLATE_CANNOT_HAVE_PRICE_TYPE_ID(CONFLICT, "Pack item with main template can't have price_type_id"),
    CHANNEL_PACK_ITEM_FROM_MANUAL_PACK_CANNOT_HAVE_PRICE_TYPE_ID(CONFLICT, "Pack item from manual pack can't have price_type_id"),
    CHANNEL_PACK_ITEM_FROM_MANUAL_PACK_CANNOT_HAVE_VARIANT_ID(CONFLICT, "Pack item from manual pack can't have variant_id"),
    CHANNEL_PACK_ITEM_FROM_MANUAL_PACK_CANNOT_HAVE_SHARED_BARCODE(CONFLICT, "Pack item from manual pack can't have shared_barcode"),
    CHANNEL_PACK_ITEM_FROM_MANUAL_PACK_CANNOT_HAVE_DELIVERY_POINT_ID(CONFLICT, "Pack item from manual pack can't have delivery_point_id"),
    CHANNEL_PACK_ITEM_FROM_MANUAL_PACK_CANNOT_BE_UPDATED(CONFLICT, "Pack item from manual pack can't be updated"),
    CHANNEL_PACK_ITEM_CANNOT_BE_EVENT_TYPE(CONFLICT, "Only pack main item can be event type"),
    CHANNEL_PACK_ITEM_EVENT_CANNOT_BE_UPDATED(CONFLICT, "Pack event item can't be updated"),
    CHANNEL_PACK_URLS_NOT_AVAILABLE(CONFLICT, "Pack urls are only available for v4 channels"),
    INVALID_TAXES_DISPLAY_CONFIG(HttpStatus.CONFLICT, "Invalid taxes configuration"),
    INVALID_PRICES_DISPLAY_CONFIG(HttpStatus.CONFLICT, "Invalid price configuration"),
    FILENAME_NOT_FOUND(HttpStatus.NOT_FOUND, "No file with the provided filename was found"),
    FILENAME_ALREADY_EXISTS(CONFLICT, "The provided filename already exists in this channel"),
    INVALID_FILENAME(BAD_REQUEST, "The provided filename contains invalid characters or is invalid"),
    CUSTOM_RESOURCE_ASSETS_REQUEST_REPEATED_FILENAMES(BAD_REQUEST, "The request contains repeated filenames"),
    REPEATED_CAROUSEL_EVENT(BAD_REQUEST, "The carousel events can't be repeated"),
    REPEATED_CAROUSEL_POSITION(BAD_REQUEST, "The carousel positions can't be repeated"),
    INVALID_CAROUSEL_POSITION(BAD_REQUEST, "The carousel position must be between 0 and %s", true),
    INVALID_CAROUSEL_SIZE(BAD_REQUEST, "There can only be a maximum of %s events in the carousel", true),
    INVALID_CAROUSEL_VISIBILITY(BAD_REQUEST, "The carousel event must be visible in catalog"),
    DONATION_PROVIDER_NOT_ENABLED(HttpStatus.CONFLICT, "Donation provider is not enabled"),
    EVENT_MUST_BE_VISIBLE_TO_EXTEND(CONFLICT, "The event: %s must be visible in catalog in order to extend", true),
    EVENT_MUST_BELONG_CUSTOMIZED_ORDER(CONFLICT, "The event: %s must belong to customized order", true),
    INVALID_OPTION_VALUE(BAD_REQUEST, "Option value must be greater than 0"),
    REQUIRED_OPTION_VALUE(BAD_REQUEST, "Option value cannot be null when the configuration type is custom."),
    CHANNEL_ALREADY_MIGRATED(CONFLICT, "Channel is already migrated to v4"),
    CHANNEL_CONTAINS_NOT_VALIDATED_STRIPE_GATEWAY(CONFLICT, "Channel contains a not validated stripe gateway"),
    ERROR_PROCESSING_CHANEL_FORMS_JSONS(CONFLICT, "Error processing JSON files to obtain channel forms"),
    CURRENCY_MUST_BE_UNIQUE(CONFLICT, "Currency must be unique"),
    ALLOW_UNPAID_TERM_INVALID_OPERATION(BAD_REQUEST, "Member operation cannot allow unpaid terms"),
    CHANNEL_TYPE_NOT_ABLE_TO_MIGRATE(CONFLICT, "Channel cannot be migrated, is not OB Portal"),
    V2_RECEIPT_TEMPLATE_NOT_COMPATIBLE(CONFLICT, "The channel must migrate to v4 to use the v2 receipt template"),
    RECEIPT_TEMPLATE_NOT_FOUND(HttpStatus.NOT_FOUND, "Receipt template not found"),
    CHANNEL_RECEIPT_TICKET_DISPLAY_EMPTY(BAD_REQUEST, "There must be at least one receipt ticket display selected"),
    CHANNEL_RECEIPT_SETTINGS_NOT_COMPATIBLE_WITH_DELIVERY_METHOD(BAD_REQUEST, "Receipt Ticket Display settings are only valid with PRINT_AT_HOME delivery method"),
    CHANNEL_RECEIPT_TICKET_DISPLAY_NOT_COMPATIBLE_WITH_EMAIL_MODE(BAD_REQUEST, "Receipt Ticket Display settings are only valid with UNIFIED_TICKET_AND_RECEIPT and RECEIPT_AND_PASSBOOK emailModes"),
    MODULE_INVALID_TEXT_BLOCK_ID(BAD_REQUEST, "Thank you page modules must have a valid text block id"),
    EMAIL_CONFLICT(CONFLICT, "There are more than 1 item for filter by email"),
    EVENT_CURRENCY_NOT_MATCH(CONFLICT, "The currency between event and channel not match"),
    DEPTH_EXCEEDED_MAX_LEVELS(BAD_REQUEST, "The maximum depth levels has been exceeded"),
    CHANNEL_HAS_SALES(CONFLICT, "Channel cannot be deleted because it has sales"),
    CHANNEL_TAX_DISPLAY_MODE_MISSING(BAD_REQUEST, "Tax display mode is mandatory && Price display mode is mandatory"),
    INVALID_CHANNEL_PRICE_DISPLAY(BAD_REQUEST, "Incompatible price display configuration"),
    PACK_ITEM_PRICE_TYPES_BAD_REQUEST(BAD_REQUEST, "Some of the provided properties are invalid or do not exist."),
    PACK_ITEM_PRICE_TYPES_NOT_FOUND(HttpStatus.NOT_FOUND, "Price types visibility for this Pack Item have not been set yet."),
    CHANNEL_PRODUCT_ALREADY_EXISTS(CONFLICT, "The relationship between channel and product already exists"),
    CHANNEL_PRODUCT_CURRENCY_NOT_MATCH(CONFLICT, "The currency between channel and product does not match"),
    PRODUCT_SALE_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "Product sale request not found"),
    PRESELECTED_ITEMS_EXCEEDS_CHANNEL_LIMIT(CONFLICT, "Preselected items exceed the maximum allowed tickets for the channel"),
    PACK_SALE_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "Pack sale request not found"),
    CHANNEL_PACK_RELATIONSHIP_INCONSISTENT(CONFLICT, "The relationship between channel and pack is inconsistent"),
    PACK_SALE_REQUEST_ALREADY_EXISTS(CONFLICT, "Pack sale already exists"),
    INVALID_CHANNEL_SURCHARGE_TAX(CONFLICT, "Invalid channel surcharge tax"),
    INVALID_CHANNEL_SURCHARGE_TAX_ORIGIN(CONFLICT, "At least one surcharge tax is required for channel origin"),
    INVALID_SALE_REQUEST_SURCHARGE_TAX(CONFLICT, "Invalid sale request surcharge tax"),
    INVALID_SALE_REQUEST_SURCHARGE_TAX_ORIGIN(HttpStatus.CONFLICT, "At least one surcharge tax is required for sale request origin"),
    INVALID_DOMAIN_CONFIG_PARAMETERS(HttpStatus.BAD_REQUEST, "Invalid domain parameters"),
    VENDOR_PROPERTY_REQUIRED(BAD_REQUEST, "Vendor required property is required"),
    DELIVERY_METHOD_TAXES_REQUIRED(HttpStatus.BAD_REQUEST, "At least one tax is required for delivery methods with cost"),
	INVALID_CHANNEL_DELIVERY_METHOD_TAX(HttpStatus.BAD_REQUEST, "Invalid channel delivery method tax");

    private final HttpStatus httpStatus;
    private final String message;
    private final boolean forwardMessage;

    ApiMgmtChannelsErrorCode(HttpStatus httpStatus, String message) {
        this.httpStatus = httpStatus;
        this.message = message;
        this.forwardMessage = false;
    }

    ApiMgmtChannelsErrorCode(HttpStatus httpStatus, String message, boolean forwardMessage) {
        this.httpStatus = httpStatus;
        this.message = message;
        this.forwardMessage = forwardMessage;
    }

    @Override
    public boolean forwardMessage() {
        return forwardMessage;
    }

    @Override
    public HttpStatus getHttpStatus() {
        return this.httpStatus;
    }

    @Override
    public String getMessage() {
        return this.message;
    }

    @Override
    public String getErrorCode() {
        return this.name();
    }

    @Override
    public String formatMessage(Object... args) {
        return String.format(getMessage(), args);
    }

    public static ErrorCode getByCode(String code) {
        return Stream.of(values())
                .filter(errorCode -> errorCode.getErrorCode().equals(code))
                .findFirst()
                .orElse(null);
    }
}
