package es.onebox.fcb.tickets;

import es.onebox.common.datasources.ms.order.dto.OrderDTO;
import es.onebox.common.datasources.ms.order.dto.OrderDateDTO;
import es.onebox.common.datasources.ms.order.dto.OrderStatusDTO;
import es.onebox.common.datasources.ms.order.enums.OrderType;
import es.onebox.fcb.dao.OrderCodeCouchDao;
import es.onebox.fcb.dao.OrderCodeCounterCouchDao;
import es.onebox.fcb.domain.OrderCode;
import es.onebox.fcb.tickets.dto.OperationIdRequest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

import java.time.ZoneId;
import java.time.ZonedDateTime;

import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.times;

public class OperationCodeServiceTest {

    @InjectMocks
    private OperationCodeService operationCodeService;

    @Mock
    private OrderCodeCouchDao orderCodeCouchDao;

    @Mock
    private OrderCodeCounterCouchDao orderCodeCounterCouchDao;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void validateSeason() {
        checkYear("25", 2024, 12, 10);
        checkYear("24", 2023, 7, 1);
        checkYear("23", 2023, 6, 30);
    }

    @Test
    public void validateGeneratedId() {
        OrderDTO orderDTO = getOrderWithDate(25, 3, 10, 0, 0, 0);
        orderDTO.setCode("123");
        orderDTO.setStatus(new OrderStatusDTO());
        orderDTO.getStatus().setType(OrderType.PURCHASE);

        OrderCode code = new OrderCode();
        code.setCode("123");
        code.setExternalCode("123456789");
        Mockito.when(orderCodeCouchDao.get(Mockito.anyString())).thenReturn(code);

        String idOperation = operationCodeService.getOrGenerateOperationId(getRequest(orderDTO));
        Assertions.assertEquals(code.getExternalCode(), idOperation, "Failed to check code");
        Mockito.verify(orderCodeCounterCouchDao, times(0)).autoIncrementCounter(Mockito.anyString());
    }

    @Test
    public void validateAutogeneratedId() {
        OrderDTO orderDTO = getOrderWithDate(25, 3, 10, 0, 0, 0);
        orderDTO.setCode("1234");
        orderDTO.setStatus(new OrderStatusDTO());
        orderDTO.getStatus().setType(OrderType.PURCHASE);

        OrderCode code = new OrderCode();
        code.setCode("123");
        code.setExternalCode("123456789");
        Mockito.when(orderCodeCouchDao.get(Mockito.eq("123"))).thenReturn(code);
        doReturn(432312L).when(orderCodeCounterCouchDao).autoIncrementCounter(ArgumentMatchers.anyString());

        String idOperation = operationCodeService.getOrGenerateOperationId(getRequest(orderDTO));

        Assertions.assertNotEquals(code.getExternalCode(), idOperation, "Failed to check code");
        Assertions.assertEquals("250000698B8V", idOperation, "Failed to check code");
        Mockito.verify(orderCodeCounterCouchDao, times(1)).autoIncrementCounter(Mockito.anyString());
    }

    @Test
    public void validateCodeSell() {
        OrderDTO orderDTO = getOrderWithDate(25, 3, 10, 0, 0, 0);
        orderDTO.setStatus(new OrderStatusDTO());
        orderDTO.getStatus().setType(OrderType.PURCHASE);

        doReturn(432312L).when(orderCodeCounterCouchDao).autoIncrementCounter(ArgumentMatchers.anyString());

        String idOperation = operationCodeService.getOrGenerateOperationId(getRequest(orderDTO));
        Assertions.assertEquals("250000698B8V", idOperation, "Failed to check code");
    }

    @Test
    public void validateCodeRefund() {
        OrderDTO orderDTO = getOrderWithDate(25, 3, 10, 0, 0, 0);
        orderDTO.setStatus(new OrderStatusDTO());
        orderDTO.getStatus().setType(OrderType.REFUND);

        doReturn(1L).when(orderCodeCounterCouchDao).autoIncrementCounter(ArgumentMatchers.anyString());

        String idOperation = operationCodeService.getOrGenerateOperationId(getRequest(orderDTO));
        Assertions.assertEquals("25000000001W", idOperation, "Failed to check code");
    }

    @Test
    public void validateRefundCode() {
        OrderDTO orderDTO = getOrderWithDate(25, 3, 10, 0, 0, 0);
        orderDTO.setStatus(new OrderStatusDTO());
        orderDTO.getStatus().setType(OrderType.PURCHASE);

        doReturn(1L).when(orderCodeCounterCouchDao).autoIncrementCounter(ArgumentMatchers.anyString());
        String operationId = operationCodeService.getOrGenerateOperationId(getRequest(orderDTO));
        Assertions.assertEquals("25000000001V", operationId, "Failed to check code");

        Mockito.when(orderCodeCouchDao.get(Mockito.eq(orderDTO.getCode()))).thenReturn(new OrderCode(operationId));

        String refundOperationId = operationCodeService.getRefundOperationId(orderDTO.getCode());
        Assertions.assertEquals("25000000001W", refundOperationId, "Failed to check code");
    }

    private void checkYear(String checkYear, int year, int month, int day) {
        doReturn(0L).when(orderCodeCounterCouchDao).autoIncrementCounter(ArgumentMatchers.anyString());

        OrderDTO orderDTO = getOrderWithDate(year, month, day, 0, 0, 0);
        orderDTO.setStatus(new OrderStatusDTO());
        orderDTO.getStatus().setType(OrderType.PURCHASE);

        String idOperation = operationCodeService.getOrGenerateOperationId(getRequest(orderDTO));
        Assertions.assertEquals(checkYear, idOperation.substring(0, 2), "Failed to check year: " + checkYear + " - date: " + orderDTO.getDate().getPurchased());
    }

    private static OrderDTO getOrderWithDate(int year, int month, int day, int hour, int minute, int second) {
        OrderDTO orderDTO = new OrderDTO();
        orderDTO.setDate(new OrderDateDTO());
        orderDTO.getDate().setTimeZone("Europe/Berlin");
        orderDTO.getDate().setPurchased(ZonedDateTime.of(year, month, day, hour, minute, second, 0, ZoneId.of("Europe/Berlin")));
        return orderDTO;
    }


    private OperationIdRequest getRequest(OrderDTO orderDTO) {
        OperationIdRequest request = new OperationIdRequest();
        request.setCode(orderDTO.getCode());
        request.setPurchaseDate(orderDTO.getDate().getPurchased());
        request.setOrderType(orderDTO.getStatus().getType().name());
        request.setTimeZone(orderDTO.getDate().getTimeZone());
        return request;
    }
}
