export enum SessionsFilterFields {
    name = 'name',
    status = 'status',
    type = 'type',
    startDate = 'start_date',
    entityId = 'entity_id',
    capacity = 'capacity',
    archived = 'archived',
    statusFlags = 'status.flags',
    generationStatus = 'generation_status',
    publicationCancelledReason = 'publication_cancelled_reason',
    releaseEnabled = 'release_enabled',
    venueTemplateId = 'venue_template.id',
    venueTemplateName = 'venue_template.name',
    venueTplVenueId = 'venue_template.venue.id',
    venueTplVenueName = 'venue_template.venue.name',
    venueTplType = 'venue_template.type',
    settingsSmartbookingStatus = 'settings.smart_booking.status',
    settingsSmartbookingRelatedSession = 'settings.smart_booking.related_session',
    id = 'id'
}
