get:
  x-internal: true
  summary: Search producers
  description: Search producers
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Producers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: query
      name: entity_id
      description: The entity of the producer
      schema:
        type: integer
    - in: query
      name: entity_admin_id
      description: The entity admin of the producer entity
      schema:
        type: integer
      x-internal: true
    - in: query
      name: status
      description: The status of the producer
      style: form
      schema:
        type: array
        items:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
    - in: query
      name: q
      description: Free search for producers by name
      schema:
        type: string
    - in: query
      name: fields
      description: Response will contain only the id and the selected fields
      style: form
      schema:
        type: array
        items:
          type: string
          enum:
            - name
            - status
    - in: query
      name: sort
      description: Sorting of enum fields with format field:[asc|desc]. For example 'name:desc'
      schema:
        type: string
        enum:
          - name
          - status
    - in: query
      name: limit
      schema:
        type: integer
      description: Limit (default 50, max 1000)
    - in: query
      name: offset
      schema:
        type: integer
      description: Offset (default 0)
  responses:
    '200':
      description: Get list of producers
      content:
        application/json:
          schema:
            $ref: ../../models/entities/producers.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
post:
  x-internal: true
  summary: New producer
  description: Creates new producer
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - Producers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - name
            - nif
            - social_reason
          properties:
            name:
              type: string
            nif:
              type: string
            social_reason:
              type: string
            entity_id:
              type: integer
              format: int64
              description: Entity ID (Only required for user ``ROLE_OPR_MGR``)
  responses:
    '201':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            required:
              - id
            properties:
              id:
                type: integer
                format: int64
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '401':
      description: Invalid token
      content:
        application/json:
          schema:
            $ref: '../../models/common/error-auth.yml'
    '403':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
