get:
  x-internal: true
  summary: Search producer invoice prefixes
  description: Search producer invoice prefixes
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS']
  tags:
    - Producers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: producerId
      description: The producer ID
      schema:
        type: integer
      required: true
    - in: query
      name: limit
      schema:
        type: integer
      description: Limit (default 50, max 1000)
    - in: query
      name: offset
      schema:
        type: integer
      description: Offset (default 0)
  responses:
    '200':
      description: Get list of producer invoice prefixes
      content:
        application/json:
          schema:
            $ref: ../../models/entities/invoice-prefixes.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml

post:
  x-internal: true
  summary: New producer invoice prefix
  description: Creates a new producer invoice prefix
  security:
    - OAuth2: ['ROLE_EVN_MGR', 'ROLE_OPR_MGR']
  tags:
    - Producers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: producerId
      description: The producer ID
      schema:
        type: integer
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - prefix
          properties:
            prefix:
              type: string
              description: The invoice prefix
  responses:
    '201':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            required:
              - id
            properties:
              id:
                type: integer
                format: int64
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '401':
      description: Invalid token
      content:
        application/json:
          schema:
            $ref: '../../models/common/error-auth.yml'
    '403':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '409':
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '../../models/common/error.yml'