get:
  x-internal: true
  summary: Get producer invoice provider options
  description: Get producer invoice provider options
  security:
    - OAuth2: ['ROLE_ENT_MGR', 'ROLE_ENT_ANS', 'ROLE_OPR_MGR', 'ROLE_OPR_ANS', 'ROLE_EVN_MGR']
  tags:
    - Producers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: producerId
      description: The producer ID
      schema:
        type: integer
      required: true
  responses:
    '200':
      description: Get producer invoice provider info
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
              enum:
                - TBAI
                - ONEBOX
                - FEVER
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
post:
  x-internal: true
  summary: Request the use of an invoice provider
  description: Request the use of an invoice provider
  security:
    - OAuth2: ['ROLE_ENT_MGR', 'ROLE_OPR_MGR', 'ROLE_EVN_MGR']
  tags:
    - Producers
  parameters:
    - in: header
      name: Authorization
      description: Bearer Token
      schema:
        type: string
      required: true
    - in: path
      name: producerId
      description: The producer ID
      schema:
        type: integer
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - provider
          properties:
            provider:
              type: string
              enum:
                - ONEBOX
                - TBAI
                - FEVER
  responses:
    '201':
      description: The request status
      content:
        application/json:
          schema:
            $ref: ../../models/entities/invoice-provider-info.yml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../models/common/error-auth.yml
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: ../../models/common/error.yml
