export type SeasonChannelReleaseStatus = 'PENDING_RELATIONSHIP' | 'PLANNED' | 'IN_PROGRAMMING'
    | 'RELEASE_PENDING' | 'RELEASED' | 'RELEASE_CANCELLED' | 'RELEASE_FINISHED' | 'CANCELLED' | 'NOT_ACCOMPLISHED' | 'REJECTED';
