//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.purchase.order;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refund" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="purchase" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="print" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="modifyGroupAttendance" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refund",
    "purchase",
    "print",
    "modifyGroupAttendance"
})
@XmlRootElement(name = "operationsAllowed")
public class OperationsAllowed
    implements Serializable
{

    @XmlElement(defaultValue = "true")
    protected boolean refund;
    @XmlElement(defaultValue = "true")
    protected boolean purchase;
    @XmlElement(defaultValue = "true")
    protected boolean print;
    @XmlElement(defaultValue = "false")
    protected boolean modifyGroupAttendance;

    /**
     * Gets the value of the refund property.
     * 
     */
    public boolean isRefund() {
        return refund;
    }

    /**
     * Sets the value of the refund property.
     * 
     */
    public void setRefund(boolean value) {
        this.refund = value;
    }

    /**
     * Gets the value of the purchase property.
     * 
     */
    public boolean isPurchase() {
        return purchase;
    }

    /**
     * Sets the value of the purchase property.
     * 
     */
    public void setPurchase(boolean value) {
        this.purchase = value;
    }

    /**
     * Gets the value of the print property.
     * 
     */
    public boolean isPrint() {
        return print;
    }

    /**
     * Sets the value of the print property.
     * 
     */
    public void setPrint(boolean value) {
        this.print = value;
    }

    /**
     * Gets the value of the modifyGroupAttendance property.
     * 
     */
    public boolean isModifyGroupAttendance() {
        return modifyGroupAttendance;
    }

    /**
     * Sets the value of the modifyGroupAttendance property.
     * 
     */
    public void setModifyGroupAttendance(boolean value) {
        this.modifyGroupAttendance = value;
    }

}
