//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.purchase.order;

import es.onebox.common.datasources.rest.dto.ns.amount.PriceBreakdown;
import es.onebox.common.datasources.rest.dto.ns.channel.Channel;
import es.onebox.common.datasources.rest.dto.ns.customer.CustomerType;
import es.onebox.common.datasources.rest.dto.ns.customer.VisitorGroup;
import es.onebox.common.datasources.rest.dto.ns.platformclient.PlatformClientType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="client" type="{http://www.oneboxtm.es/ns/customer}customerType"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/purchase/order}operationsOrderAllowed" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/purchase/order}order-item" maxOccurs="unbounded"/>
 *         &lt;element name="delivery-method" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/purchase/order}insurance"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/amount}price-breakdown" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/purchase/order}payments" minOccurs="0"/>
 *         &lt;element name="toBePaid" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="pending" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="suspectFraud" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/channel}channel"/>
 *         &lt;element name="orderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="requestedPaymentReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="additionalChannelCommissions" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/customer}visitorGroup" maxOccurs="unbounded"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="externalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/purchase/order}invoiceData"/>
 *         &lt;element name="platformClient" type="{http://www.oneboxtm.es/ns/platformClient}platformClientType"/>
 *         &lt;element name="includeAllSeasonSessionTickets" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="currency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orderCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://www.oneboxtm.es/ns/purchase/order}orderStatus" />
 *       &lt;attribute name="type" use="required" type="{http://www.oneboxtm.es/ns/purchase/order}orderType" />
 *       &lt;attribute name="preOrderTimeLeft" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "client",
    "operationsOrderAllowed",
    "orderItem",
    "deliveryMethod",
    "insurance",
    "priceBreakdown",
    "payments",
    "toBePaid",
    "pending",
    "suspectFraud",
    "channel",
    "orderDate",
    "requestedPaymentReference",
    "additionalChannelCommissions",
    "visitorGroup",
    "notes",
    "externalCode",
    "invoiceData",
    "platformClient",
    "includeAllSeasonSessionTickets"
})
@XmlRootElement(name = "order-details")
public class OrderDetails
    implements Serializable
{

    @XmlElement(required = true)
    protected CustomerType client;
    protected OperationsOrderAllowed operationsOrderAllowed;
    @XmlElement(name = "order-item", required = true)
    protected List<OrderItem> orderItem;
    @XmlElement(name = "delivery-method")
    protected BigInteger deliveryMethod;
    @XmlElement(required = true)
    protected Insurance insurance;
    @XmlElement(name = "price-breakdown", namespace = "http://www.oneboxtm.es/ns/amount")
    protected PriceBreakdown priceBreakdown;
    protected Payments payments;
    @XmlElement(required = true)
    protected BigDecimal toBePaid;
    @XmlElement(required = true)
    protected BigDecimal pending;
    protected boolean suspectFraud;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/channel", required = true)
    protected Channel channel;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar orderDate;
    protected String requestedPaymentReference;
    protected BigDecimal additionalChannelCommissions;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/customer", required = true)
    protected List<VisitorGroup> visitorGroup;
    @XmlElement(required = true)
    protected String notes;
    @XmlElement(required = true)
    protected String externalCode;
    @XmlElement(required = true)
    protected InvoiceData invoiceData;
    @XmlElement(required = true)
    protected PlatformClientType platformClient;
    protected boolean includeAllSeasonSessionTickets;
    @XmlAttribute(name = "currency", required = true)
    protected String currency;
    @XmlAttribute(name = "orderCode", required = true)
    protected String orderCode;
    @XmlAttribute(name = "status", required = true)
    protected OrderStatus status;
    @XmlAttribute(name = "type", required = true)
    protected OrderType type;
    @XmlAttribute(name = "preOrderTimeLeft")
    protected Integer preOrderTimeLeft;

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     */
    public void setClient(CustomerType value) {
        this.client = value;
    }

    /**
     * Gets the value of the operationsOrderAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsOrderAllowed }
     *     
     */
    public OperationsOrderAllowed getOperationsOrderAllowed() {
        return operationsOrderAllowed;
    }

    /**
     * Sets the value of the operationsOrderAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsOrderAllowed }
     *     
     */
    public void setOperationsOrderAllowed(OperationsOrderAllowed value) {
        this.operationsOrderAllowed = value;
    }

    /**
     * Gets the value of the orderItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItem }
     * 
     * 
     */
    public List<OrderItem> getOrderItem() {
        if (orderItem == null) {
            orderItem = new ArrayList<OrderItem>();
        }
        return this.orderItem;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDeliveryMethod(BigInteger value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the insurance property.
     * 
     * @return
     *     possible object is
     *     {@link Insurance }
     *     
     */
    public Insurance getInsurance() {
        return insurance;
    }

    /**
     * Sets the value of the insurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Insurance }
     *     
     */
    public void setInsurance(Insurance value) {
        this.insurance = value;
    }

    /**
     * Gets the value of the priceBreakdown property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBreakdown }
     *     
     */
    public PriceBreakdown getPriceBreakdown() {
        return priceBreakdown;
    }

    /**
     * Sets the value of the priceBreakdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBreakdown }
     *     
     */
    public void setPriceBreakdown(PriceBreakdown value) {
        this.priceBreakdown = value;
    }

    /**
     * Gets the value of the payments property.
     * 
     * @return
     *     possible object is
     *     {@link Payments }
     *     
     */
    public Payments getPayments() {
        return payments;
    }

    /**
     * Sets the value of the payments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payments }
     *     
     */
    public void setPayments(Payments value) {
        this.payments = value;
    }

    /**
     * Gets the value of the toBePaid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getToBePaid() {
        return toBePaid;
    }

    /**
     * Sets the value of the toBePaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setToBePaid(BigDecimal value) {
        this.toBePaid = value;
    }

    /**
     * Gets the value of the pending property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPending() {
        return pending;
    }

    /**
     * Sets the value of the pending property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPending(BigDecimal value) {
        this.pending = value;
    }

    /**
     * Gets the value of the suspectFraud property.
     * 
     */
    public boolean isSuspectFraud() {
        return suspectFraud;
    }

    /**
     * Sets the value of the suspectFraud property.
     * 
     */
    public void setSuspectFraud(boolean value) {
        this.suspectFraud = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link Channel }
     *     
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channel }
     *     
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDate(XMLGregorianCalendar value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the requestedPaymentReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedPaymentReference() {
        return requestedPaymentReference;
    }

    /**
     * Sets the value of the requestedPaymentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedPaymentReference(String value) {
        this.requestedPaymentReference = value;
    }

    /**
     * Gets the value of the additionalChannelCommissions property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAdditionalChannelCommissions() {
        return additionalChannelCommissions;
    }

    /**
     * Sets the value of the additionalChannelCommissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAdditionalChannelCommissions(BigDecimal value) {
        this.additionalChannelCommissions = value;
    }

    /**
     * Gets the value of the visitorGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitorGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitorGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VisitorGroup }
     * 
     * 
     */
    public List<VisitorGroup> getVisitorGroup() {
        if (visitorGroup == null) {
            visitorGroup = new ArrayList<VisitorGroup>();
        }
        return this.visitorGroup;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the externalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalCode() {
        return externalCode;
    }

    /**
     * Sets the value of the externalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalCode(String value) {
        this.externalCode = value;
    }

    /**
     * Gets the value of the invoiceData property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceData }
     *     
     */
    public InvoiceData getInvoiceData() {
        return invoiceData;
    }

    /**
     * Sets the value of the invoiceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceData }
     *     
     */
    public void setInvoiceData(InvoiceData value) {
        this.invoiceData = value;
    }

    /**
     * Gets the value of the platformClient property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformClientType }
     *     
     */
    public PlatformClientType getPlatformClient() {
        return platformClient;
    }

    /**
     * Sets the value of the platformClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformClientType }
     *     
     */
    public void setPlatformClient(PlatformClientType value) {
        this.platformClient = value;
    }

    /**
     * Gets the value of the includeAllSeasonSessionTickets property.
     * 
     */
    public boolean isIncludeAllSeasonSessionTickets() {
        return includeAllSeasonSessionTickets;
    }

    /**
     * Sets the value of the includeAllSeasonSessionTickets property.
     * 
     */
    public void setIncludeAllSeasonSessionTickets(boolean value) {
        this.includeAllSeasonSessionTickets = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the orderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * Sets the value of the orderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderCode(String value) {
        this.orderCode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link OrderStatus }
     *     
     */
    public OrderStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStatus }
     *     
     */
    public void setStatus(OrderStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link OrderType }
     *     
     */
    public OrderType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderType }
     *     
     */
    public void setType(OrderType value) {
        this.type = value;
    }

    /**
     * Gets the value of the preOrderTimeLeft property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPreOrderTimeLeft() {
        return preOrderTimeLeft;
    }

    /**
     * Sets the value of the preOrderTimeLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPreOrderTimeLeft(Integer value) {
        this.preOrderTimeLeft = value;
    }

    /**
     * Sets the value of the orderItem property.
     * 
     * @param orderItem
     *     allowed object is
     *     {@link OrderItem }
     *     
     */
    public void setOrderItem(List<OrderItem> orderItem) {
        this.orderItem = orderItem;
    }

    /**
     * Sets the value of the visitorGroup property.
     * 
     * @param visitorGroup
     *     allowed object is
     *     {@link VisitorGroup }
     *     
     */
    public void setVisitorGroup(List<VisitorGroup> visitorGroup) {
        this.visitorGroup = visitorGroup;
    }

}
