//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.purchase.order;

import es.onebox.common.datasources.rest.dto.ns.search.AdvancedSearchType;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oneboxtm.es/ns/search}advancedSearchType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/purchase/order}orders-summary"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ordersSummary"
})
@XmlRootElement(name = "orderAdvancedSearch")
public class OrderAdvancedSearch
    extends AdvancedSearchType
    implements Serializable
{

    @XmlElement(name = "orders-summary", required = true)
    protected OrdersSummary ordersSummary;

    /**
     * Gets the value of the ordersSummary property.
     * 
     * @return
     *     possible object is
     *     {@link OrdersSummary }
     *     
     */
    public OrdersSummary getOrdersSummary() {
        return ordersSummary;
    }

    /**
     * Sets the value of the ordersSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrdersSummary }
     *     
     */
    public void setOrdersSummary(OrdersSummary value) {
        this.ordersSummary = value;
    }

}
