export interface GetOrdersWithFieldsRequestBody {
    fields: GetOrdersFields[];
}

export enum GetOrdersFields {
    code = 'code',
    type = 'type',
    date = 'date',
    lastModified = 'last_modified',
    channelId = 'channel.id',
    channelName = 'channel.name',
    clientType = 'client_type',
    buyerDataName = 'buyer_data.name',
    buyerDataSurname = 'buyer_data.surname',
    buyerDataEmail = 'buyer_data.email',
    buyerDataPhone = 'buyer_data.phone',
    buyerDataInternationalPhonePrefix = 'buyer_data.international_phone.prefix',
    buyerDataInternationalPhoneNumber = 'buyer_data.international_phone.number',
    delivery = 'delivery',
    priceCurrency = 'price.currency',
    priceDonation = 'price.donation',
    priceBase = 'price.base',
    priceFinal = 'price.final',
    priceSalesAutomatic = 'price.sales.automatic',
    priceSalesDiscount = 'price.sales.discount',
    priceSalesPromotion = 'price.sales.promotion',
    priceSalesOrderAutomatic = 'price.sales.order_automatic',
    priceSalesOrderCollective = 'price.sales.order_collective',
    priceDelivery = 'price.delivery',
    priceGateway = 'price.gateway',
    priceInsurance = 'price.insurance',
    priceB2bConditions = 'price.b2b.conditions',
    priceB2bCommission = 'price.b2b.commission',
    priceChargesPromoter = 'price.charges.promoter',
    priceChargesChannel = 'price.charges.channel',
    priceChargesSecondaryMarketChannel = 'price.charges.secondary_market_channel',
    priceChargesSecondaryMarketPromoter = 'price.charges.secondary_market_promoter',
    priceChargesReallocation = 'price.charges.reallocation',
    priceChargesTicketReallocation = 'price.charges.ticket_reallocation',
    priceReallocationRefund = 'price.reallocation_refund',
    priceChannelCommission = 'price.channel_commission',
    itemsCount = 'items_count',
    ticketsCount = 'tickets_count',
    productsCount = 'products_count',
    itemsId = 'items.id',
    itemsType = 'items.type',
    itemsState = 'items.state',
    itemsTicketType = 'items.ticket.type',
    itemsTicketAllocationType = 'items.ticket.allocation.type',
    itemsTicketAllocationEventId = 'items.ticket.allocation.event.id',
    itemsTicketAllocationEventName = 'items.ticket.allocation.event.name',
    itemsTicketAllocationEventType = 'items.ticket.allocation.event.type',
    itemsTicketAllocationSessionId = 'items.ticket.allocation.session.id',
    itemsTicketAllocationSessionName = 'items.ticket.allocation.session.name',
    itemsTicketAllocationSessionDateStart = 'items.ticket.allocation.session.date.start',
    itemsTicketAllocationVenueId = 'items.ticket.allocation.venue.id',
    itemsTicketAllocationVenueName = 'items.ticket.allocation.venue.name'
}
