additionalProperties: false
type: object
properties:
  address:
    type: string
  city:
    type: string
  postal_code:
    type: string
  country:
    type: object
    properties:
      code:
        type: string
        description: ISO 3166 codes
      name:
        type: string
  country_subdivision:
    type: object
    properties:
      code:
        type: string
        description: ISO 3166 codes
      name:
        type: string
  email:
    type: string
  phone:
    type: string
  name:
    type: string
