additionalProperties: false
type: object
required:
  - id
  - name
  - status
  - nif
  - entity
  - default
  - social_reason
  - use_simplified_invoice
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  nif:
    type: string
  social_reason:
    type: string
  status:
    $ref: 'producer-status.yml'
  default:
    type: boolean
  entity:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  contact:
    $ref: 'producer-contact.yml'
  use_simplified_invoice:
    type: boolean
