//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.shopping.cart;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.onebox.stubhub.datasources.rest.dto.ns.shopping.cart package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.onebox.stubhub.datasources.rest.dto.ns.shopping.cart
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Insurance }
     * 
     */
    public Insurance createInsurance() {
        return new Insurance();
    }

    /**
     * Create an instance of {@link GiftTicketCodeApplicableGroup }
     * 
     */
    public GiftTicketCodeApplicableGroup createGiftTicketCodeApplicableGroup() {
        return new GiftTicketCodeApplicableGroup();
    }

    /**
     * Create an instance of {@link UserApplicableGroup }
     * 
     */
    public UserApplicableGroup createUserApplicableGroup() {
        return new UserApplicableGroup();
    }

    /**
     * Create an instance of {@link ExternalProperties }
     * 
     */
    public ExternalProperties createExternalProperties() {
        return new ExternalProperties();
    }

    /**
     * Create an instance of {@link ShoppingCartItem }
     * 
     */
    public ShoppingCartItem createShoppingCartItem() {
        return new ShoppingCartItem();
    }

    /**
     * Create an instance of {@link TicketDataType }
     * 
     */
    public TicketDataType createTicketDataType() {
        return new TicketDataType();
    }

    /**
     * Create an instance of {@link ProductDataType }
     * 
     */
    public ProductDataType createProductDataType() {
        return new ProductDataType();
    }

    /**
     * Create an instance of {@link OperationsAllowed }
     * 
     */
    public OperationsAllowed createOperationsAllowed() {
        return new OperationsAllowed();
    }

    /**
     * Create an instance of {@link Attendant }
     * 
     */
    public Attendant createAttendant() {
        return new Attendant();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link ShoppingCartAvailableSales }
     * 
     */
    public ShoppingCartAvailableSales createShoppingCartAvailableSales() {
        return new ShoppingCartAvailableSales();
    }

    /**
     * Create an instance of {@link ShoppingCartItemSales }
     * 
     */
    public ShoppingCartItemSales createShoppingCartItemSales() {
        return new ShoppingCartItemSales();
    }

    /**
     * Create an instance of {@link AvailableEntitiesAttributes }
     * 
     */
    public AvailableEntitiesAttributes createAvailableEntitiesAttributes() {
        return new AvailableEntitiesAttributes();
    }

    /**
     * Create an instance of {@link EntityAttributes }
     * 
     */
    public EntityAttributes createEntityAttributes() {
        return new EntityAttributes();
    }

    /**
     * Create an instance of {@link PromotionalCodeApplicableGroup }
     * 
     */
    public PromotionalCodeApplicableGroup createPromotionalCodeApplicableGroup() {
        return new PromotionalCodeApplicableGroup();
    }

    /**
     * Create an instance of {@link ShoppingCart }
     * 
     */
    public ShoppingCart createShoppingCart() {
        return new ShoppingCart();
    }

    /**
     * Create an instance of {@link AvailableInsurances }
     * 
     */
    public AvailableInsurances createAvailableInsurances() {
        return new AvailableInsurances();
    }

}
