//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.shopping.cart;

import es.onebox.common.datasources.rest.dto.ns.amount.PriceBreakdown;
import es.onebox.common.datasources.rest.dto.ns.platformclient.ClientConditionsType;
import es.onebox.common.datasources.rest.dto.ns.sales.AutomaticPromotion;
import es.onebox.common.datasources.rest.dto.ns.sales.Discount;
import es.onebox.common.datasources.rest.dto.ns.sales.Promotion;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ticket-data" type="{http://www.oneboxtm.es/ns/shopping/cart}ticketDataType"/>
 *           &lt;element name="product-data" type="{http://www.oneboxtm.es/ns/shopping/cart}productDataType"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/sales}automatic-promotion" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/sales}promotion" minOccurs="0"/>
 *         &lt;element name="promotionActivator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/sales}discount" minOccurs="0"/>
 *         &lt;element name="discountActivator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/amount}price-breakdown" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/shopping/cart}operationsAllowed" minOccurs="0"/>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/shopping/cart}attendant" minOccurs="0"/>
 *         &lt;element name="itemWarning" type="{http://www.oneboxtm.es/ns/shopping/cart}itemWarnings" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modifyingBookingOrderCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientConditions" type="{http://www.oneboxtm.es/ns/platformClient}clientConditionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="type" type="{http://www.oneboxtm.es/ns/shopping/cart}itemType" default="TICKET" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ticketData",
    "productData",
    "automaticPromotion",
    "promotion",
    "promotionActivator",
    "productId",
    "discount",
    "discountActivator",
    "priceBreakdown",
    "operationsAllowed",
    "attendant",
    "itemWarning",
    "modifyingBookingOrderCode",
    "clientConditions"
})
@XmlRootElement(name = "shopping-cart-item")
public class ShoppingCartItem
    implements Serializable
{

    @XmlElement(name = "ticket-data")
    protected TicketDataType ticketData;
    @XmlElement(name = "product-data")
    protected ProductDataType productData;
    @XmlElement(name = "automatic-promotion", namespace = "http://www.oneboxtm.es/ns/sales")
    protected AutomaticPromotion automaticPromotion;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/sales")
    protected Promotion promotion;
    protected String promotionActivator;
    protected BigInteger productId;
    @XmlElement(namespace = "http://www.oneboxtm.es/ns/sales")
    protected Discount discount;
    protected String discountActivator;
    @XmlElement(name = "price-breakdown", namespace = "http://www.oneboxtm.es/ns/amount")
    protected PriceBreakdown priceBreakdown;
    protected OperationsAllowed operationsAllowed;
    protected Attendant attendant;
    protected List<ItemWarnings> itemWarning;
    protected String modifyingBookingOrderCode;
    protected ClientConditionsType clientConditions;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "type")
    protected ItemType type;

    /**
     * Gets the value of the ticketData property.
     * 
     * @return
     *     possible object is
     *     {@link TicketDataType }
     *     
     */
    public TicketDataType getTicketData() {
        return ticketData;
    }

    /**
     * Sets the value of the ticketData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketDataType }
     *     
     */
    public void setTicketData(TicketDataType value) {
        this.ticketData = value;
    }

    /**
     * Gets the value of the productData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDataType }
     *     
     */
    public ProductDataType getProductData() {
        return productData;
    }

    /**
     * Sets the value of the productData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDataType }
     *     
     */
    public void setProductData(ProductDataType value) {
        this.productData = value;
    }

    /**
     * Gets the value of the automaticPromotion property.
     * 
     * @return
     *     possible object is
     *     {@link AutomaticPromotion }
     *     
     */
    public AutomaticPromotion getAutomaticPromotion() {
        return automaticPromotion;
    }

    /**
     * Sets the value of the automaticPromotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutomaticPromotion }
     *     
     */
    public void setAutomaticPromotion(AutomaticPromotion value) {
        this.automaticPromotion = value;
    }

    /**
     * Gets the value of the promotion property.
     * 
     * @return
     *     possible object is
     *     {@link Promotion }
     *     
     */
    public Promotion getPromotion() {
        return promotion;
    }

    /**
     * Sets the value of the promotion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Promotion }
     *     
     */
    public void setPromotion(Promotion value) {
        this.promotion = value;
    }

    /**
     * Gets the value of the promotionActivator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionActivator() {
        return promotionActivator;
    }

    /**
     * Sets the value of the promotionActivator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionActivator(String value) {
        this.promotionActivator = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductId(BigInteger value) {
        this.productId = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link Discount }
     *     
     */
    public Discount getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discount }
     *     
     */
    public void setDiscount(Discount value) {
        this.discount = value;
    }

    /**
     * Gets the value of the discountActivator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountActivator() {
        return discountActivator;
    }

    /**
     * Sets the value of the discountActivator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountActivator(String value) {
        this.discountActivator = value;
    }

    /**
     * Gets the value of the priceBreakdown property.
     * 
     * @return
     *     possible object is
     *     {@link PriceBreakdown }
     *     
     */
    public PriceBreakdown getPriceBreakdown() {
        return priceBreakdown;
    }

    /**
     * Sets the value of the priceBreakdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceBreakdown }
     *     
     */
    public void setPriceBreakdown(PriceBreakdown value) {
        this.priceBreakdown = value;
    }

    /**
     * Gets the value of the operationsAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsAllowed }
     *     
     */
    public OperationsAllowed getOperationsAllowed() {
        return operationsAllowed;
    }

    /**
     * Sets the value of the operationsAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsAllowed }
     *     
     */
    public void setOperationsAllowed(OperationsAllowed value) {
        this.operationsAllowed = value;
    }

    /**
     * Gets the value of the attendant property.
     * 
     * @return
     *     possible object is
     *     {@link Attendant }
     *     
     */
    public Attendant getAttendant() {
        return attendant;
    }

    /**
     * Sets the value of the attendant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attendant }
     *     
     */
    public void setAttendant(Attendant value) {
        this.attendant = value;
    }

    /**
     * Gets the value of the itemWarning property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemWarning property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemWarning().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemWarnings }
     * 
     * 
     */
    public List<ItemWarnings> getItemWarning() {
        if (itemWarning == null) {
            itemWarning = new ArrayList<ItemWarnings>();
        }
        return this.itemWarning;
    }

    /**
     * Gets the value of the modifyingBookingOrderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyingBookingOrderCode() {
        return modifyingBookingOrderCode;
    }

    /**
     * Sets the value of the modifyingBookingOrderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyingBookingOrderCode(String value) {
        this.modifyingBookingOrderCode = value;
    }

    /**
     * Gets the value of the clientConditions property.
     * 
     * @return
     *     possible object is
     *     {@link ClientConditionsType }
     *     
     */
    public ClientConditionsType getClientConditions() {
        return clientConditions;
    }

    /**
     * Sets the value of the clientConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientConditionsType }
     *     
     */
    public void setClientConditions(ClientConditionsType value) {
        this.clientConditions = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ItemType }
     *     
     */
    public ItemType getType() {
        if (type == null) {
            return ItemType.TICKET;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemType }
     *     
     */
    public void setType(ItemType value) {
        this.type = value;
    }

    /**
     * Sets the value of the itemWarning property.
     * 
     * @param itemWarning
     *     allowed object is
     *     {@link ItemWarnings }
     *     
     */
    public void setItemWarning(List<ItemWarnings> itemWarning) {
        this.itemWarning = itemWarning;
    }

}
