//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.shopping.cart;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/shopping/cart}shopping-cart-item-sales" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="token" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timeLeft" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shoppingCartItemSales"
})
@XmlRootElement(name = "shopping-cart-available-sales")
public class ShoppingCartAvailableSales
    implements Serializable
{

    @XmlElement(name = "shopping-cart-item-sales", required = true)
    protected List<ShoppingCartItemSales> shoppingCartItemSales;
    @XmlAttribute(name = "token", required = true)
    protected String token;
    @XmlAttribute(name = "currency", required = true)
    protected String currency;
    @XmlAttribute(name = "timeLeft", required = true)
    protected int timeLeft;

    /**
     * Gets the value of the shoppingCartItemSales property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shoppingCartItemSales property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShoppingCartItemSales().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShoppingCartItemSales }
     * 
     * 
     */
    public List<ShoppingCartItemSales> getShoppingCartItemSales() {
        if (shoppingCartItemSales == null) {
            shoppingCartItemSales = new ArrayList<ShoppingCartItemSales>();
        }
        return this.shoppingCartItemSales;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the timeLeft property.
     * 
     */
    public int getTimeLeft() {
        return timeLeft;
    }

    /**
     * Sets the value of the timeLeft property.
     * 
     */
    public void setTimeLeft(int value) {
        this.timeLeft = value;
    }

    /**
     * Sets the value of the shoppingCartItemSales property.
     * 
     * @param shoppingCartItemSales
     *     allowed object is
     *     {@link ShoppingCartItemSales }
     *     
     */
    public void setShoppingCartItemSales(List<ShoppingCartItemSales> shoppingCartItemSales) {
        this.shoppingCartItemSales = shoppingCartItemSales;
    }

}
