//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 12:32:19 PM CEST 
//


package es.onebox.common.datasources.rest.dto.ns.shopping.cart;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oneboxtm.es/ns/shopping/cart}externalProperties" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idGroup" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "externalProperties"
})
@XmlRootElement(name = "userApplicableGroup")
public class UserApplicableGroup
    implements Serializable
{

    protected ExternalProperties externalProperties;
    @XmlAttribute(name = "idGroup")
    protected Integer idGroup;
    @XmlAttribute(name = "username")
    protected String username;

    /**
     * Gets the value of the externalProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalProperties }
     *     
     */
    public ExternalProperties getExternalProperties() {
        return externalProperties;
    }

    /**
     * Sets the value of the externalProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalProperties }
     *     
     */
    public void setExternalProperties(ExternalProperties value) {
        this.externalProperties = value;
    }

    /**
     * Gets the value of the idGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdGroup() {
        return idGroup;
    }

    /**
     * Sets the value of the idGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdGroup(Integer value) {
        this.idGroup = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

}
