package es.onebox.event.exception;

import es.onebox.core.exception.ErrorCode;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.CONFLICT;
import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.http.HttpStatus.NOT_FOUND;
import static org.springframework.http.HttpStatus.PRECONDITION_FAILED;

public enum MsEventErrorCode implements ErrorCode {
    GENERIC_ERROR("GENERIC_ERROR", HttpStatus.INTERNAL_SERVER_ERROR, "Something went really wrong"),
    COMMUNICATION_ELEMENT_BULK_UPDATE_LOCKED("COMMUNICATION_ELEMENT_BULK_UPDATE_LOCKED", INTERNAL_SERVER_ERROR, "Communication elements bulk update is locked."),
    INVALID_NAME_FORMAT("ME0009", HttpStatus.PRECONDITION_FAILED, "Item name has invalid length or reserved characters"),
    EVENT_NOT_FOUND("ME0001", HttpStatus.NOT_FOUND, "Event not found"),
    SESSION_NOT_FOUND("SESSION_NOT_FOUND", HttpStatus.NOT_FOUND, "Session not found"),
    EVENT_CHANNEL_HAS_SALES("ME0002", HttpStatus.CONFLICT, "Relationship event-channel cannot be deleted because it has sales"),
    DEFAULT_PROMOTER_NOT_AVAILABLE("ME0003", HttpStatus.PRECONDITION_FAILED, "Defined entity doesn't has default promoter"),
    CHANNEL_EVENT_NOT_FOUND("ME0004", HttpStatus.NOT_FOUND, "Channel event not found"),
    CHANNEL_SESSION_NOT_FOUND("ME0005", HttpStatus.NOT_FOUND, "Channel session not found"),
    LANGUAGE_NOT_AVAILABLE("ME0006", HttpStatus.PRECONDITION_FAILED, "Received language codes are not available in the platform"),
    REPEATED_NAME("ME0007", HttpStatus.PRECONDITION_FAILED, "Received name is used already"),
    EVENT_NOT_REMOVABLE("ME0008", HttpStatus.FORBIDDEN, "Event cannot be removed"),
    INVALID_NAME_CONFLICT("ME0010", HttpStatus.CONFLICT, "Name already exists for entity"),
    EVENT_INVALID_DEFAULT_LANGUAGE("ME0011", HttpStatus.PRECONDITION_FAILED, "Event language must define 1 by default"),
    EVENT_INVALID_STATUS_GENERATION("ME0012", HttpStatus.FORBIDDEN, "Event cant change status with pending seat generations"),
    EVENT_INVALID_STATUS_FINISH("ME0013", HttpStatus.FORBIDDEN, "Event cant change status with already alive sessions"),
    INVALID_VENUE_TEMPLATE("ME0015", HttpStatus.PRECONDITION_FAILED, "Invalid venueTemplateId for event"),
    EVENT_ID_MANDATORY("ME0014", BAD_REQUEST, "Event id is mandatory"),
    TEMPLATE_ID_MANDATORY("ME0087", BAD_REQUEST, "Session id is mandatory"),
    NO_PRICES_FOUND("ME0016", HttpStatus.NOT_FOUND, "No prices found for this template id"),
    INVALID_PRICE_TYPE("ME0017", BAD_REQUEST, "Invalid price type"),
    TEMPLATE_ID_NOT_FROM_EVENT("ME0018", BAD_REQUEST, "Venue template not from event"),
    SEASON_LOCK("ME0020", HttpStatus.PRECONDITION_FAILED, "Season session lock"),
    INVALID_EVENT_STATUS("ME0021", HttpStatus.PRECONDITION_FAILED, "Invalid event status"),
    EVENT_CHANNEL_NOT_FOUND("ME0028", HttpStatus.NOT_FOUND, "Event channel not found"),
    EVENT_CHANNEL_EXISTS("ME0029", HttpStatus.CONFLICT, "Event channel relation already exists"),
    CHANNEL_NOT_FOUND("ME0030", HttpStatus.NOT_FOUND, "Channel not found"),
    CHANNEL_ID_MANDATORY("ME0031", BAD_REQUEST, "Channel id is mandatory"),
    CHANNEL_AGENCY_ID_MANDATORY("CHANNEL_AGENCY_ID_MANDATORY", BAD_REQUEST, "Channel agency id is mandatory"),
    INCONSISTENT_DATES("ME0033", HttpStatus.CONFLICT, "The introduced date(s) are not coherent"),
    INCONSISTENT_PUBLISHED_ONSALE_STATE("ME0034", HttpStatus.CONFLICT, "Sales cannot be enabled while the season ticket is not published"),
    FIELD_NOT_UPGRADEABLE("ME0035", HttpStatus.CONFLICT, "One of the fields cannot be updated"),
    REQUEST_NOT_PENDING("ME0036", HttpStatus.CONFLICT, "Request is not pending"),
    USE_ALL_SALE_GROUPS_MANDATORY("ME0037", BAD_REQUEST, "Use all sale groups is mandatory"),
    SALE_GROUPS_MANDATORY("ME0038", BAD_REQUEST, "At least one sale group must be specified when use all sale groups is false"),
    SETTINGS_MANDATORY("ME0039", BAD_REQUEST, "Event channel settings are mandatory"),
    USE_EVENT_DATES_MANDATORY("ME0040", BAD_REQUEST, "Use event dates is mandatory"),
    EVENT_CHANNEL_SETTINGS_DATES_MANDATORY("ME0041", BAD_REQUEST, "Dates are mandatory"),
    START_GREATER_END_DATE("ME0042", BAD_REQUEST, "Start date is not before end date"),
    INVALID_SALE_GROUPS("ME0043", BAD_REQUEST, "Sale groups supplied are invalid"),
    INVALID_DESCRIPTION_LENGTH("ME0045", BAD_REQUEST, "Description length is not valid"),
    SECONDARY_MARKET_NOT_ALLOWED_FOR_EVENT("ME0046", CONFLICT, "Secondary market not allowed by event"),
    SECONDARY_MARKET_NOT_ALLOWED_BY_ENTITY("SECONDARY_MARKET_NOT_ALLOWED_BY_ENTITY", HttpStatus.CONFLICT, "Secondary market not allowed by entity"),
    SECONDARY_MARKET_NOT_SUPPORTED("SECONDARY_MARKET_NOT_SUPPORTED", HttpStatus.CONFLICT, "Only V4 OB_PORTAL channels support Secondary Market"),
    EVENT_TYPE_DOES_NOT_SUPPORT_SECONDARY_MARKET("EVENT_TYPE_DOES_NOT_SUPPORT_SECONDARY_MARKET", CONFLICT, "Event type does not support secondary market"),
    TYPE_MANDATORY("ME0049", BAD_REQUEST, "Type is mandatory"),
    SURCHARGE_TYPE_DUPLICATED("ME0050", BAD_REQUEST, "Duplicated surcharge type"),
    SURCHARGE_TYPE_NOT_SUPPORTED("ME0051", CONFLICT, "Surcharge type not supported for this channel type"),
    AT_LEAST_ONE_RANGE("ME0052", BAD_REQUEST, "At least one range should be informed"),
    SURCHARGE_FROM_RANGE_MANDATORY("ME0053", BAD_REQUEST, "From range is mandatory"),
    FIXED_OR_PERCENTAGE_MANDATORY("ME0054", BAD_REQUEST, "Fixed or percentage should be informed"),
    SURCHARGE_DUPLICATED_FROM_RANGE("ME0055", BAD_REQUEST, "From range should be unique"),
    FROM_RANGE_ZERO_MANDATORY("ME0056", BAD_REQUEST, "At least a range with from value 0 should be informed"),
    MIN_SURCHARGE_GREATER_THAN_MAX("ME0057", BAD_REQUEST, "Min surcharge should not  be greater than max surcharge."),
    SECONDARY_MARKET_CANT_HAVE_LIMIT("SECONDARY_MARKET_CANT_HAVE_LIMIT", BAD_REQUEST, "Secondary Market surcharges can't have limit"),
    WHEN_LIMIT_ENABLED_IS_MANDATORY("ME0075", BAD_REQUEST, "When limit is enabled min and max values are mandatory."),
    WHEN_LIMIT_ENABLED_MIN_LOWER_THAN_MAX("ME0076", BAD_REQUEST, "When limit is enabled  min limit must not be greater than max."),
    EVENT_AVET_CONFIG_MANDATORY("ME0079", HttpStatus.BAD_REQUEST, "Avet config is mandatory in Avet Event"),
    EVENT_AVET_COMPETITION_MANDATORY("ME0080", HttpStatus.BAD_REQUEST, "Avet competition is mandatory in Avet Event"),
    TOUR_NOT_FOUND("ME0081", HttpStatus.NOT_FOUND, "Tour not found"),
    INVALID_TAX("ME0082", BAD_REQUEST, "Invalid tax for session"),
    PAGINATION_LIMIT_EXCEEDED("ME0083", CONFLICT, "Pagination limit exceeded"),
    TICKET_TEMPLATE_NOT_FOUND("ME0086", HttpStatus.NOT_FOUND, "Ticket template not found"),
    TICKET_TEMPLATE_LITERAL_NOT_FOUND("ME0094", HttpStatus.NOT_FOUND, "Ticket template literal not found"),
    TICKET_TEMPLATE_MODEL_NOT_FOUND("ME0087", HttpStatus.NOT_FOUND, "Ticket template model not found"),
    TICKET_TEMPLATE_NOT_REMOVABLE("ME0088", HttpStatus.FORBIDDEN, "Default ticket template not removable"),
    TICKET_TEMPLATE_INVALID_DEFAULT_LANGUAGE("ME0089", HttpStatus.PRECONDITION_FAILED, "Ticket template language config not valid"),
    TICKET_TEMPLATE_FORMAT_NOT_AVAILABLE("TICKET_TEMPLATE_FORMAT_NOT_AVAILABLE", HttpStatus.PRECONDITION_FAILED, "Ticket template format not available"),
    COMMUNICATION_ELEMENT_UPDATE_REQUIRED("ME0090", BAD_REQUEST, "Value or image must be informed"),
    EVENT_ALREADY_HAS_SESSION_PACKS("ME0098", HttpStatus.FORBIDDEN, "Event pack type cant be changed with existing session packs"),
    PASSBOOK_TEMPLATE_NOT_FOUND("ME0101", NOT_FOUND, "Passbook template not found"),
    INVALID_STRING_LENGTH("ME102", BAD_REQUEST, "String length exceeds maximum permitted"),
    ATTRIBUTE_INVALID_VALUE("ATTRIBUTE_INVALID_VALUE", BAD_REQUEST, "Invalid attribute value"),
    ATTRIBUTE_INVALID_ID("ATTRIBUTE_INVALID_ID", BAD_REQUEST, "Invalid attribute id"),
    INVALID_ACTIVITY_SALE_GROUPS("INVALID_ACTIVITY_SALE_GROUPS", BAD_REQUEST, "Only 1 quota by venue-template allowed on activity events"),
    EVENT_GROUP_NOT_ALLOWED("EVENT_GROUP_NOT_ALLOWED", BAD_REQUEST, "Event group only allowed for ACTIVITY or THEME_PARK event type"),
    EVENT_INVALID_GROUP_DISABLE("EVENT_INVALID_GROUP_CHANGE", HttpStatus.FORBIDDEN, "Event groups cant be disabled with existing MIXED or GROUP sessions"),
    ATTENDANT_CONFIG_AUTOFILL_NOT_ALLOWED("ATTENDANT_CONFIG_AUTOFILL_NOT_ALLOWED", BAD_REQUEST, "Attendants config autofill is compatible only with AVET Events."),
    EVENT_ID_INVALID("EVENT_ID_INVALID",BAD_REQUEST, "Event Id should not be not null and greater than 0"),
    UPDATE_EVENT_EXTERNAL_BARCODE_CONFIG_WITH_ACTIVE_SESSIONS("ME0121", CONFLICT, "Can not update event external barcodes with active sessions"),
    UPDATE_EVENT_EXTERNAL_BARCODE_WITH_SALES("ME0122", CONFLICT, "Can not update event external barcodes because the event has sales"),
    UPDATE_SESSION_EXTERNAL_BARCODE_WITH_SALES("ME0123", CONFLICT, "Can not update session external barcodes because the session has sales"),
    PRICE_TYPE_NOT_FOUND("PRICE_TYPE_NOT_FOUND",NOT_FOUND, "Price type not found"),
    PRICE_TYPE_RESTRICTION_NOT_FOUND("PRICE_TYPE_RESTRICTION_NOT_FOUND", NOT_FOUND, "Restriction not found"),
    RATE_RESTRICTIONS_NOT_FOUND("RATE_RESTRICTIONS_NOT_FOUND", NOT_FOUND, "Restriction not found"),
    OPERATION_NOT_ALLOWED_ON_GRAPHIC_TEMPLATE("OPERATION_NOT_ALLOWED_ON_GRAPHIC_TEMPLATE", BAD_REQUEST, "This operation is not allowed on a Graphic Template"),
    INVOICE_PREFIX_CANNOT_BE_MODIFIED("INVOICE_PREFIX_CANNOT_BE_MODIFIED", HttpStatus.BAD_REQUEST, "The Event Invoice prefix cannot be changed if the Event status is not In Programming"),
    PRODUCER_SIMPLIFIED_INVOICE_FLAG("PRODUCER_SIMPLIFIED_INVOICE_FLAG", HttpStatus.BAD_REQUEST, "The producer simplified invoice flag is not activated"),
    SIMPLIFIED_INVOICES_CANNOT_BE_USED("SIMPLIFIED_INVOICES_CANNOT_BE_USED", BAD_REQUEST, "Only events with Producer Fiscal data can use simplified invoices"),
    EXTERNAL_EVENT_NOT_FOUND("ME0124", NOT_FOUND, "External Event not found"),
    EVENT_IS_NOT_AVET("ME0126", CONFLICT, "Event is not AVET"),
    PROMOTION_NOT_FOUND("PROMOTION_NOT_FOUND", NOT_FOUND, "Promotion not found"),
    REPEATED_EXTERNAL_DESCRIPTION("ME0127", CONFLICT, "In event external description cannot be repeated"),
    NO_OBJECT_UNDER_S3_PATH("NO_OBJECT_UNDER_S3_PATH", HttpStatus.INTERNAL_SERVER_ERROR, "Object not found in the expected path"),
    BAD_REQUEST_PARAMETER("BAD_REQUEST_PARAMETER", HttpStatus.BAD_REQUEST, "Some parameters are incorrect or invalid"),
    EXTERNAL_DESCRIPTION_NOT_FOUND("ME0128", CONFLICT, "This external description does not exists in AVET"),
    WRONG_EXTERNAL_DESCRIPTION("ME0129", CONFLICT, "Wrong external description"),
    PRICE_LIST_VOID_IN_AVET("ME0131", CONFLICT, "Does not exist avet prices in AVET"),
    COMPETITION_NOT_FOUND("ME0132", NOT_FOUND, "Competition not found"),
    EXPORT_UPLOAD_EXCEPTION("EXPORT_UPLOAD_EXCEPTION", HttpStatus.NOT_FOUND, "Error uploading report to S3"),
    EXPORT_WITH_TOO_MANY_RECORDS("EXPORT_WITH_TOO_MANY_RECORDS", HttpStatus.CONFLICT, "Export records limit (%d) reached"),
    S3_FILE_NOT_UPLOADED("S3_FILE_NOT_UPLOADED", HttpStatus.INTERNAL_SERVER_ERROR, "S3 file status: %s"),
    AMQP_PUSH_EXCEPTION("AMQP_REPORT_PUSH_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR, "Unable to send message to the queue"),
    EXPORT_STATUS_NOT_FOUND("EXPORT_STATUS_NOT_FOUND", NOT_FOUND, "Export status not found for provided ID"),
    EVENT_ACCOMMODATIONS_CONFIG_NOT_PROPERLY_ENABLED("EVENT_ACCOMMODATIONS_CONFIG_NOT_PROPERLY_ENABLED", BAD_REQUEST, "Enabling accommodations config requires a vendor & value"),
    ACCOMMODATIONS_CONFIG_NOT_ENABLED_BY_ENTITY("ACCOMMODATIONS_CONFIG_NOT_ENABLED_BY_ENTITY", BAD_REQUEST, "Accommodations not yet enabled by entity"),
    ACCOMMODATIONS_VENDOR_NOT_ALLOWED_BY_ENTITY("ACCOMMODATIONS_VENDOR_NOT_ALLOWED_BY_ENTITY", BAD_REQUEST, "Event vendor not allowed by entity"),
    CONFIG_NOT_FOUND("CONFIG_NOT_FOUND", NOT_FOUND, "Configuration not found "),
    PRODUCER_NOT_FOUND("PRODUCER_NOT_FOUND", NOT_FOUND, "Producer not found "),
    ENTITY_NOT_FOUND("ENTITY_NOT_FOUND", NOT_FOUND, "Entity not found"),
    COUNTRY_NOT_FOUND("COUNTRY_NOT_FOUND", NOT_FOUND,"Country not found"),
    COUNTRY_SUBDIVISION_NOT_FOUND("COUNTRY_SUBDIVISION_NOT_FOUND", NOT_FOUND,"Country subdivision not found"),
    INVALID_POSTAL_CODE_COUNTRY_SUBDIVISION("INVALID_POSTAL_CODE", HttpStatus.PRECONDITION_FAILED, "Postal code doesnt match with the country subdivision"),
    PRODUCT_DELIVERY_POINT_NOT_FOUND("PRODUCT_DELIVERY_POINT_NOT_FOUND", NOT_FOUND, "Product delivery point not found "),
    PRODUCT_DELIVERY_POINT_RELATION_NOT_FOUND("PRODUCT_DELIVERY_POINT_RELATION_NOT_FOUND", NOT_FOUND, "Product delivery point relation not found "),
    PRODUCT_LANGUAGES_NOT_FOUND("PRODUCT_LANGUAGES_NOT_FOUND", NOT_FOUND, "Product languages not found "),
    PRODUCT_IMAGE_TYPE_NOT_FOUND("PRODUCT_IMAGE_TYPE_NOT_FOUND", NOT_FOUND, "Ticket content image type not found"),
    TICKET_CONTENT_LANGUAGE_NOT_MATCH("TICKET_CONTENT_LANGUAGE_NOT_MATCH", NOT_FOUND, "Ticket content languages is different to product"),
    TEXT_VALUE_EXCEEDS_MAX_LENGTH("TEXT_VALUE_EXCEEDS_MAX_LENGTH", BAD_REQUEST, "The text exceeds the maximum number of characters allowed"),
    PRODUCT_CHANNEL_NOT_FOUND("PRODUCT_CHANNEL_NOT_FOUND", NOT_FOUND, "Product channel not found"),
    PRODUCT_CHANNELS_NOT_FOUND("PRODUCT_CHANNELS_NOT_FOUND", NOT_FOUND, "Product channels not found"),
    PRODUCT_CHANNEL_ALREADY_EXISTS("PRODUCT_CHANNEL_ALREADY_EXISTS", CONFLICT, "Product channel already exists"),
    PRODUCT_CHANNEL_NOT_FROM_ENTITY("PRODUCT_CHANNEL_NOT_FOUND", BAD_REQUEST, "Only channels from the same entity can publish a product"),
    PRODUCT_CHANNEL_INVALID_TYPE("PRODUCT_CHANNEL_INVALID_TYPE", CONFLICT, "External type channel is not allowed"),
    PRODUCT_EVENT_NOT_FOUND("PRODUCT_EVENT_NOT_FOUND", NOT_FOUND, "Product event not found"),
    PRODUCT_EVENT_SESSION_NOT_FOUND("PRODUCT_EVENT_SESSION_NOT_FOUND", NOT_FOUND, "Product event session not found"),
    PRODUCT_EVENT_SESSION_BAD_REQUEST_STOCK_MANDATORY("PRODUCT_EVENT_SESSION_BAD_REQUEST_STOCK_MANDATORY", BAD_REQUEST, "Stock property is mandatory when useCustomStock is TRUE"),
    PRODUCT_EVENT_SESSION_BAD_REQUEST_PRICE_MANDATORY("PRODUCT_EVENT_SESSION_BAD_REQUEST_PRICE_MANDATORY", BAD_REQUEST, "Price property is mandatory when useCustomPrice is TRUE"),
    PRODUCT_EVENT_SESSION_INVALID_SELECTION_TYPE("PRODUCT_EVENT_SESSION_INVALID_SELECTION_TYPE", PRECONDITION_FAILED, "Session stock update requires RESTRICTED selection type in product - event relationship"),
    PRODUCT_EVENT_SESSION_INVALID_TYPE_OR_STOCK_TYPE("PRODUCT_EVENT_SESSION_INVALID_TYPE_OR_STOCK_TYPE", PRECONDITION_FAILED, "Session stock update requires SIMPLE product type and stock type SESSION_BOUNDED"),
    PRODUCT_EVENT_ALREADY_EXISTS("PRODUCT_EVENT_ALREADY_EXISTS", BAD_REQUEST, "Event already exists in product event relation"),
    PRODUCT_EVENT_STATE_NOT_VALID("PRODUCT_EVENT_STATE_NOT_VALID", BAD_REQUEST, "Deleted is not a valid state for updating product events"),
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND", NOT_FOUND, "Product not found "),
    PRODUCT_CANNOT_BE_ACTIVATED("PRODUCT_CANNOT_BE_ACTIVATED", PRECONDITION_FAILED, "Product cannot be activated "),
    PRODUCT_LANGUAGE_DEFAULT_REQUIRED("PRODUCT_LANGUAGE_DEFAULT_REQUIRED", NOT_FOUND, "One product language must be the default value"),
    PRODUCT_EVENT_DELIVERY_POINT_DEFAULT_REQUIRED("PRODUCT_EVENT_DELIVERY_POINT_DEFAULT_REQUIRED", NOT_FOUND, "One product event delivery point must be the default value"),
    PRODUCT_SESSION_DELIVERY_POINT_DEFAULT_REQUIRED("PRODUCT_SESSION_DELIVERY_POINT_DEFAULT_REQUIRED", NOT_FOUND, "One product session delivery point must be the default value"),
    PRODUCT_EVENT_NOT_RELATED("PRODUCT_EVENT_NOT_RELATED", NOT_FOUND, "There is no relation between the product and the event"),
    PRODUCT_VARIANT_NOT_ENOUGH_STOCK("PRODUCT_VARIANT_NOT_ENOUGH_STOCK", PRECONDITION_FAILED, "There is not enough stock"),
    PRODUCT_SESSION_NOT_RELATED("PRODUCT_SESSION_NOT_RELATED", NOT_FOUND, "There is no relation between the product and the session"),
    PRODUCT_HAS_SALES("PRODUCT_HAS_SALES", PRECONDITION_FAILED, "Product has sales"),
    PRODUCT_SURCHARGE_TYPE_NOT_SUPPORTED("PRODUCT_SURCHARGE_TYPE_NOT_SUPPORTED", CONFLICT, "Surcharge type not supported"),
    INVALID_ENTITY_TAX("INVALID_ENTITY_TAX", BAD_REQUEST, "Invalid tax for entity"),
    INVALID_ENTITY_SURCHARGE_TAX("INVALID_ENTITY_SURCHARGE_TAX", BAD_REQUEST, "Invalid surcharge tax for entity"),
    TAX_NOT_UPDATABLE_ON_PRODUCT("TAX_NOT_UPDATABLE_ON_PRODUCT", BAD_REQUEST, "Tax id not updatable on active products"),
    CURRENCY_NOT_UPDATABLE_ON_PRODUCT("CURRENCY_NOT_UPDATABLE_ON_PRODUCT", PRECONDITION_FAILED, "Currency not updatable on active products"),
    TAX_MODE_NOT_UPDATABLE_ON_PRODUCT("TAX_MODE_NOT_UPDATABLE_ON_PRODUCT", PRECONDITION_FAILED, "Tax mode not updatable on products with sales"),
    ILLEGAL_VARIANT_AMOUNT("ILLEGAL_VARIANT_AMOUNT", BAD_REQUEST, "Product simple can not have more than one variant"),
    POSITION_MUST_BE_POSITIVE("POSITION_MUST_BE_POSITIVE", BAD_REQUEST, "Position must be a positive number"),
    PRODUCT_LANGUAGE_NOT_RELATED("PRODUCT_LANGUAGE_NOT_RELATED", HttpStatus.NOT_FOUND, "Product and language are not related"),
    PRODUCT_COMMUNICATIONS_ELEMENTS_NOT_FOUND("PRODUCT_COMMUNICATIONS_ELEMENTS_NOT_FOUND", HttpStatus.NOT_FOUND, "Product communication elements not found"),
    PRODUCT_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND("PRODUCT_COMMUNICATIONS_ELEMENTS_LANGUAGE_NOT_FOUND", HttpStatus.NOT_FOUND, "Product communication elements language not found"),
    PRODUCT_VARIANT_PRICE_AND_STOCK_NOT_UPDATABLE("PRODUCT_VARIANT_PRICE_AND_STOCK_NOT_UPDATABLE", BAD_REQUEST, "Product variant price and stock not updatable on active products"),
    PRODUCT_VARIANT_STATUS_NOT_UPDATABLE("PRODUCT_VARIANT_STATUS_NOT_UPDATABLE", CONFLICT, "Products variant status not updatable on product with simple variant"),
    PRODUCT_VARIANT_NOT_FOUND("PRODUCT_VARIANT_NOT_FOUND", NOT_FOUND, "Product variant not found"),
    PRODUCT_VARIANT_STATE_INVALID("PRODUCT_VARIANT_STATE_INVALID", PRECONDITION_FAILED, "Product variant state invalid"),
    PRODUCT_VARIANT_PRODUCT_TYPE_INVALID("PRODUCT_VARIANT_PRODUCT_TYPE_INVALID", PRECONDITION_FAILED, "Product type must be variant"),
    PRODUCT_VARIANT_FILTER_INVALID("PRODUCT_VARIANT_FILTER_INVALID", BAD_REQUEST, "Product unbounded can not be filtered by stock"),
    PRODUCT_VARIANT_NUMBER_ATTRIBUTES_INVALID("PRODUCT_VARIANT_NUMBER_ATTRIBUTES_INVALID", PRECONDITION_FAILED, "Products variants attributes number invalid"),
    PRODUCT_VARIANT_MINIMUM_VALUES_INVALID("PRODUCT_VARIANT_MINIMUM_VALUES_INVALID", PRECONDITION_FAILED, "Products variants must have at least two values"),
    PRODUCT_MISSING_ACTIVE_VARIANT("PRODUCT_MISSING_ACTIVE_VARIANT", PRECONDITION_FAILED, "Products must have at least one active variant"),
    PRODUCT_ATTRIBUTE_NOT_FOUND("PRODUCT_ATTRIBUTE_NOT_FOUND", NOT_FOUND, "Product attribute not found"),
    PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND("PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND", NOT_FOUND, "Product attribute value not found"),
    PRODUCT_ATTRIBUTE_NAME_DUPLICATED("PRODUCT_ATTRIBUTE_NAME_DUPLICATED", BAD_REQUEST, "Product attribute name duplicated"),
    PRODUCT_ATTRIBUTE_VALUE_NAME_DUPLICATED("PRODUCT_ATTRIBUTE_VALUE_NAME_DUPLICATED", CONFLICT, "Product attribute value name duplicated"),
    PRODUCT_TAX_NOT_FOUND("PRODUCT_TAX_NOT_FOUND", NOT_FOUND, "Product tax not found"),
    PRODUCT_SURCHARGE_TAX_NOT_FOUND("PRODUCT_SURCHARGE_TAX_NOT_FOUND", NOT_FOUND, "Product surcharge tax not found"),
    PRODUCT_DELIVERY_TYPE_REQUIRED("PRODUCT_DELIVERY_TYPE_REQUIRED", PRECONDITION_FAILED, "Product delivery type required"),
    PRODUCT_DELIVERY_PERIOD_REQUIRED("PRODUCT_DELIVERY_PERIOD_REQUIRED", PRECONDITION_FAILED, "Product delivery period required"),
    PRODUCT_DELIVERY_NOT_UPDATABLE("PRODUCT_DELIVERY_NOT_UPDATABLE", PRECONDITION_FAILED, "Product delivery not updatable on active products"),
    PRODUCT_VARIANT_PRICE_REQUIRED("PRODUCT_VARIANT_PRICE_REQUIRED", PRECONDITION_FAILED, "All product variants must have a price"),
    PRODUCT_EVENTS_REQUIRED("PRODUCT_EVENTS_REQUIRED", PRECONDITION_FAILED, "Product must have associated events"),
    PRODUCT_SESSIONS_REQUIRED("PRODUCT_SESSIONS_REQUIRED", PRECONDITION_FAILED, "Product must have associated sessions"),
    PRODUCT_NAME_ALREADY_IN_USE("PRODUCT_NAME_ALREADY_IN_USE", PRECONDITION_FAILED, "Product name already in use"),
    PRODUCT_INVALID_TYPE_FOR_SESSION_BOUNDED("PRODUCT_INVALID_TYPE_FOR_SESSION_BOUNDED", PRECONDITION_FAILED, "Invalid product type for SESSION_BOUNDED stock type"),
    PRODUCT_TYPE_NOT_ALLOWED("PRODUCT_TYPE_NOT_ALLOWED", PRECONDITION_FAILED, "Invalid product type. Only product type SIMPLE is allowed"),
    PRODUCT_STOCK_TYPE_NOT_ALLOWED("PRODUCT_TYPE_NOT_ALLOWED", PRECONDITION_FAILED, "Invalid product stock type. Only product stock type SESSION_BOUNDED is allowed"),
    DELIVERY_POINT_NAME_ALREADY_IN_USE("DELIVERY_POINT_NAME_ALREADY_IN_USE", PRECONDITION_FAILED, "Delivery Point name already in use"),
    MAX_ATTRIBUTES_REACHED("MAX_ATTRIBUTES_REACHED", BAD_REQUEST, "A product can only have two attributes as much"),
    MAX_ATTRIBUTE_VALUES_BY_PRODUCT_REACHED("MAX_ATTRIBUTE_VALUES_REACHED", CONFLICT, "It can only have 25 values grouped by product and attribute as much"),
    SESSIONS_NOT_FOUND_OR_INVALID_SESSION_STATE("SESSIONS_NOT_FOUND_OR_INVALID_SESSION_STATE", CONFLICT, "Sessions not found or invalid sessions state"),
    EVENTS_NOT_FOUND_OR_INVALID_EVENT_STATE("EVENTS_NOT_FOUND_OR_INVALID_EVENT_STATE", CONFLICT, "Events not found or invalid events state"),
    EVENT_SESSION_CONFLICT("EVENT_SESSION_CONFLICT",HttpStatus.CONFLICT, "Invalid session id for filtered events"),
    EVENT_TYPE_SUPRA_UI_CONFIGURATION_CONFLICT("EVENT_TYPE_SUPRA_UI_CONFIGURATION_CONFLICT", CONFLICT, "Event configured as supra is not compatible with the selected whitelabel ui configurations"),
    EVENT_WHITELABEL_UI_SETTINGS_CONFLICT("EVENT_WHITELABEL_UI_SETTINGS_CONFLICT", CONFLICT, "Event whitlabel ui configuration conflict"),
    EVENT_CHANNEL_CURRENCY_NOT_MATCH("EVENT_CHANNEL_CURRENCY_NOT_MATCH", CONFLICT, "Event currency not match with channel currencies"),
    NOT_AVET_EVENT("NOT_AVET_EVENT_RESTRICTION", BAD_REQUEST, "Only Avet events can have restrictions"),
    AVET_SECTOR_RESTRICTION_NOT_FOUND("AVET_SECTOR_RESTRICTION_NOT_FOUND", NOT_FOUND, "The restriction could not be found"),
    DUPLICATE_AVET_SECTOR_RESTRICTION_NAME("DUPLICATE_AVET_SECTOR_RESTRICTION_NAME", BAD_REQUEST, "Avet sector restriction name already exists"),
    DUPLICATE_AVET_SECTOR_RESTRICTION_SID("DUPLICATE_AVET_SECTOR_RESTRICTION_SID", BAD_REQUEST, "Avet sector restriction sid already exists"),
    EVENT_SESSION_SB_TOO_MANY_VENUE_TEMPLATES("EVENT_SESSION_SB_TOO_MANY_VENUE_TEMPLATES", CONFLICT, "Too many ACTIVITY venue templates to create Smart bBooking session"),
    EVENT_SESSION_MAPPING_NOT_FOUND("EVENT_SESSION_MAPPING_NOT_FOUND", CONFLICT, "There is not a mapping for session"),
    EVENT_MAPPING_NOT_FOUND("EVENT_MAPPING_NOT_FOUND", CONFLICT, "There is no mapping for event"),
    SESSION_PRESALE_NOT_FOUND("SESSION_PRESALE_NOT_FOUND", HttpStatus.NOT_FOUND, "Session presale not found"),
    INVALID_SESSION_PRESALE_DATES_REQUIRED("INVALID_SESSION_PRESALE_DATES_REQUIRED", HttpStatus.BAD_REQUEST, "Session presale update request missing dates"),
    INVALID_SESSION_PRESALE_DATES_END_BEFORE_START("INVALID_SESSION_PRESALE_DATES_END_BEFORE_START", HttpStatus.BAD_REQUEST, "Session presale update request invalid dates"),
    INVALID_SESSION_PRESALE_CREATE_REQUEST("INVALID_SESSION_PRESALE_CREATE_REQUEST", HttpStatus.BAD_REQUEST, "Invalid session presale create request"),
    INVALID_SESSION_PRESALE_UPDATE_REQUEST("INVALID_SESSION_PRESALE_UPDATE_REQUEST", HttpStatus.BAD_REQUEST, "Invalid session presale update request"),
    EVENT_TAG_LANGUAGE_NOT_FOUND("EVENT_TAG_LANGUAGE_NOT_FOUND", NOT_FOUND,"Event tag language not found"),
    INVALID_SECONDARY_MARKET_CONFIG("INVALID_SECONDARY_MARKET_CONFIG", BAD_REQUEST, "Invalid secondary market configuration"),
    NULL_SECONDARY_MARKET_VALUES("NULL_SECONDARY_MARKET_VALUES", BAD_REQUEST, "Secondary market configuration values cannot be null"),
    NEGATIVE_SECONDARY_MARKET_VALUES("NEGATIVE_SECONDARY_MARKET_VALUES", BAD_REQUEST, "Secondary market configuration values cannot be negative"),
    INVALID_SECONDARY_MARKET_RANGE("INVALID_SECONDARY_MARKET_RANGE", BAD_REQUEST, "Secondary market max value cannot be less than min value or greater than 200"),
    INVALID_CUSTOMER_TYPE("INVALID_CUSTOMER_TYPE", BAD_REQUEST, "The customer type dont exists in the entity"),
    INVALID_CUSTOMER_LIMITS("INVALID_CUSTOMER_LIMITS", BAD_REQUEST, "The customer limits are not valid"),
    INVALID_DELIVERY_DATES("INVALID_DELIVERY_DATES", PRECONDITION_FAILED, "Delivery start date must be earlier than delivery end date"),
    DELIVERY_DATES_REQUIRED("DELIVERY_DATES_REQUIRED", PRECONDITION_FAILED, "Delivery dates required on products with fixed dates"),
    DYNAMIC_PRICE_ZONE_NOT_FOUND("DYNAMIC_PRICE_ZONE_NOT_FOUND", NOT_FOUND, "Dynamic price zone not found"),
    PRICE_OCCUPATION_NOT_FOUND("PRICE_OCCUPATION_NOT_FOUND", NOT_FOUND, "price zone ocupation not found"),
    DYNAMIC_PRICE_CONFIG_NOT_FOUND("DYNAMIC_PRICE_CONFIG_NOT_FOUND", NOT_FOUND, "Dynamic prices config not found"),
    MISSING_DATE("MISSING_DATE", BAD_REQUEST, "Date is required for this condition type"),
    MISSING_CAPACITY("MISSING_CAPACITY", BAD_REQUEST, "Capacity is required for this condition type"),
    DATE_BEFORE_CREATION("DATE_BEFORE_CREATION", BAD_REQUEST, "Date cannot be before creation"),
    DATE_BEFORE_SALE_START("DATE_BEFORE_SALE_START", BAD_REQUEST, "Date cannot be before sale start"),
    MISSING_NAME("MISSING_NAME", BAD_REQUEST, "Name is required"),
    MISSING_CONDITION_TYPE("MISSING_CONDITION_TYPE", BAD_REQUEST, "Condition type is required"),
    MISSING_ORDER("MISSING_ORDER", BAD_REQUEST, "Order is required"),
    MISSING_RATES("MISSING_RATES", BAD_REQUEST, "Rates are required"),
    CAPACITY_LESS_THAN_PREVIOUS("CAPACITY_LESS_THAN_PREVIOUS", CONFLICT, "Capacity cannot be less than previous"),
    DATE_LESS_THAN_PREVIOUS("DATE_LESS_THAN_PREVIOUS", CONFLICT, "Date cannot be less than previous"),
    CHANNEL_SESSION_PRICES_NOT_FOUND("CHANNEL_SESSION_PRICES_NOT_FOUND", NOT_FOUND, "Channel session prices not found"),
    CHANNEL_PACK_PRICES_NOT_FOUND("CHANNEL_PACK_PRICES_NOT_FOUND", NOT_FOUND, "Channel pack prices not found"),
    DYNAMIC_PRICE_NOT_FOUND("DYNAMIC_PRICE_NOT_FOUND", NOT_FOUND, "Dynamic price not found"),
    CANNOT_DELETE_ACTIVE_DYNAMIC_PRICE("CANNOT_DELETE_ACTIVE_DYNAMIC_PRICE", BAD_REQUEST, "Cannot delete active dynamic price"),
    CANNOT_DELETE_PASS_DYNAMIC_PRICE("CANNOT_DELETE_PASS_DYNAMIC_PRICE", BAD_REQUEST, "Cannot delete pass dynamic price"),
    INVALID_ORDER_SEQUENCE("INVALID_ORDER_SEQUENCE", BAD_REQUEST, "Invalid order sequence"),
    CANNOT_UPDATE_DYNAMIC_PRICE_FOR_ACTIVE_SESSION("CANNOT_UPDATE_DYNAMIC_PRICE_FOR_ACTIVE_SESSION", BAD_REQUEST, "Cannot update dynamic price for active session"),
    CANNOT_ACTIVATED_DYNAMIC_PRICE_IF_TIERED_PRICING_ACTIVE("CANNOT_ACTIVATED_DYNAMIC_PRICE_IF_TIERED_PRICING_ACTIVE", BAD_REQUEST, "Cannot activate dynamic price if tiered pricing is active"),
    CUSTOMER_TYPE_NOT_FOUND_IN_EVENT("CUSTOMER_TYPE_NOT_FOUND_IN_EVENT", CONFLICT, "Some customer types not found for event"),
    INVALID_EVENT_CHANGE_SEAT_EXPIRY_TIME_UNIT("INVALID_EVENT_CHANGE_SEAT_EXPIRY_TIME_UNIT", BAD_REQUEST, "Event change seat expiry time unit not allowed"),
    CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_THIS_TYPE_EVENT("CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_THIS_TYPE_EVENT", BAD_REQUEST, "Cannot activate dynamic price for this type of event"),
    CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_ACTIVITY_WITH_GROUPS("CANNOT_ACTIVATED_DYNAMIC_PRICE_FOR_ACTIVITY_WITH_GROUPS", BAD_REQUEST, "Cannot activate dynamic price for activity event with groups"),
    EVENT_UPDATE_TAX_MODE_HAS_SALES("EVENT_UPDATE_TAX_MODE_HAS_SALES", CONFLICT, "Tax mode cannot be changed because the event has sales"),
    PRODUCT_UPDATE_TAX_MODE_INVALID_PRODUCT_STATUS("PRODUCT_UPDATE_TAX_MODE_INVALID_PRODUCT_STATUS", PRECONDITION_FAILED, "Tax mode cannot be updated when product is active"),
    EVENT_TAX_MODE_NOT_ALLOWED("EVENT_TAX_MODE_NOT_ALLOWED", CONFLICT, "Avet events must always include taxes"),
    INVALID_PRODUCT_TAX_MODE("INVALID_PRODUCT_TAX_MODE", PRECONDITION_FAILED, "Invalid product tax mode"),
    INVALID_EVENT_TAX_MODE("INVALID_EVENT_TAX_MODE", PRECONDITION_FAILED, "Invalid event tax mode"),
    EVENT_UPDATE_TAX_MODE_INVALID_EVENT_STATUS("EVENT_UPDATE_TAX_MODE_INVALID_EVENT_STATUS", PRECONDITION_FAILED, "Tax mode cannot be updated when event is ready"),
    DYNAMIC_PRICES_REQUIRE_V4_CHANNEL("DYNAMIC_PRICES_REQUIRE_V4_CHANNEL", BAD_REQUEST, "Dynamic prices require V4 channel"),
    INVALID_LANGUAGE_CODE("INVALID_LANGUAGE_CODE", BAD_REQUEST, "Invalid language code"),
    EMPTY_TRANSFER_TICKET_SESSION_LIST("EMPTY_TRANSFER_TICKET_SESSION_LIST", BAD_REQUEST, "Empty Id session list"),
    INVALID_TRANSFER_TICKET_SESSION_LIST("INVALID_TRANSFER_TICKET_SESSION_LIST", HttpStatus.CONFLICT, "Invalid Id session list"),
    MASTER_FORM_NOT_FOUND("MASTER_FORM_NOT_FOUND", NOT_FOUND, "Master form not found"),
    INVALID_VALIDATION_RULE_FOR_FIELD_TYPE("INVALID_VALIDATION_RULE_FOR_FIELD_TYPE", BAD_REQUEST, "Invalid validation rule for field type"),
    QUESTION_ID_ALREADY_EXISTS("QUESTION_ID_ALREADY_EXISTS", HttpStatus.CONFLICT, "Question IDs must be different"),
    QUESTION_NOT_FOUND("QUESTION_NOT_FOUND",NOT_FOUND, "Question not found"),
    INVALID_SESSION_DATE_CHANGE_SEAT_CONFIG("INVALID_SESSION_DATE_CHANGE_SEAT_CONFIG", CONFLICT, "Same Date must be in DIFFERENT sessions config"),
    PRODUCT_TICKET_DEFAULT_LITERALS_NOT_FOUND("PRODUCT_TICKET_DEFAULT_LITERALS_NOT_FOUND",NOT_FOUND, "Product ticket literals not found"),
    PRODUCT_TICKET_LITERALS_LANGUAGE_NOT_FOUND("PRODUCT_TICKET_LANGUAGE_LITERALS_NOT_FOUND",NOT_FOUND, "Product ticket literals language not found"),
    PRODUCT_TICKET_TEMPLATE_NOT_FOUND("PRODUCT_TICKET_TEMPLATE_NOT_FOUND", NOT_FOUND, "Product ticket template not found"),
    PRODUCT_TICKET_TEMPLATE_LANGUAGES_NOT_FOUND("PRODUCT_TICKET_TEMPLATE_LANGUAGES_NOT_FOUND", NOT_FOUND, "Product ticket template languages not found"),
    PRODUCT_TICKET_MODEL_NOT_FOUND("PRODUCT_TICKET_MODEL_NOT_FOUND", NOT_FOUND , "Product ticket model not found" ),
    PRODUCT_TICKET_TEMPLATE_NAME_ALREADY_SET("PRODUCT_TICKET_TEMPLATE_NAME_ALREADY_SET", CONFLICT, "Product ticket template name already set"),
    PRODUCT_TICKET_TEMPLATE_INVALID_DEFAULT_LANGUAGE("ME0089", HttpStatus.PRECONDITION_FAILED, "Product ticket template language config not valid"),;

    private final String errorCode;
    private final HttpStatus httpStatus;
    private final String message;

    MsEventErrorCode(String errorCode, HttpStatus httpStatus, String message) {
        this.httpStatus = httpStatus;
        this.message = message;
        this.errorCode = errorCode;
    }

    @Override
    public HttpStatus getHttpStatus() {
        return this.httpStatus;
    }

    @Override
    public String getMessage() {
        return this.message;
    }

    @Override
    public String getErrorCode() {
        return this.errorCode;
    }
}
